/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.venta;

import GUI.Views.AbstractView;
import GUI.Views.util.VentaCellRender;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NonUniqueResultException;
import javax.swing.JOptionPane;
import restManager.algoritmo.Y;
import restManager.backup.BackUp;
import restManager.controller.AbstractDialogController;
import restManager.controller.Licence.Licence;
import restManager.controller.Licence.LicenceController;
import restManager.controller.configuracion.ConfiguracionController;
import restManager.controller.venta.VentaDetailController;
import restManager.controller.venta.VentaListController;
import restManager.exceptions.DevelopingOperationException;
import restManager.exceptions.NoSelectedException;
import restManager.exceptions.UnauthorizedAccessException;
import restManager.exceptions.ValidatingException;
import restManager.persistencia.Control.VentaDAO1;
import restManager.persistencia.Seccion;
import restManager.persistencia.Venta;
import restManager.persistencia.models.VentaDAO;
import restManager.resources.R;
import restManager.util.RestManagerAbstractTableCellModel;
import restManager.util.RestManagerComboBoxModel;
import restManager.util.utils;

/**
 *
 * @author Jorge
 */
public class VentaCalendarView extends AbstractView {

    private RestManagerAbstractTableCellModel<Venta> model;
    Calendar cal = new GregorianCalendar();
    int monthOffset = 0;

    /**
     * Creates new form VentasCalendarFragmentView
     *
     * @param controller
     */
    public VentaCalendarView(AbstractDialogController controller) {
        super(DialogType.FULL_SCREEN, controller);
        initComponents();
        fetchComponentData();
    }

    public VentaCalendarView(AbstractDialogController<Venta> controller, AbstractView parentComponent) {
        super(DialogType.FULL_SCREEN, controller, parentComponent);
        initComponents();
        fetchComponentData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelCalendario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalendar = new javax.swing.JTable();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelControles = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jPanelSeleccion = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanelEstadisticas = new javax.swing.JPanel();
        jPanelVentas = new javax.swing.JPanel();
        jLabelTotalVendido = new javax.swing.JLabel();
        jLabelPromedioVendido = new javax.swing.JLabel();
        jLabelHoraPico = new javax.swing.JLabel();
        jPanelGastos = new javax.swing.JPanel();
        jLabelInsumo = new javax.swing.JLabel();
        jLabelTrabajadores = new javax.swing.JLabel();
        jLabelOtros = new javax.swing.JLabel();
        jPanelResumen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserDel = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserAl = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanelDetalles.setLayout(new javax.swing.OverlayLayout(jPanelDetalles));

        jPanelCalendario.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCalendario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelCalendario.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        jTableCalendar.setBackground(new java.awt.Color(204, 204, 204));
        jTableCalendar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTableCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCalendar.setColumnSelectionAllowed(true);
        jTableCalendar.setOpaque(false);
        jTableCalendar.setRowHeight(80);
        jTableCalendar.setRowMargin(2);
        jTableCalendar.setShowGrid(false);
        jTableCalendar.setTableHeader(null);
        jTableCalendar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableCalendarFocusLost(evt);
            }
        });
        jTableCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCalendarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCalendar);

        jPanelCalendario.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanelHeader.setLayout(new java.awt.GridLayout(1, 7));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lunes");
        jPanelHeader.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Martes");
        jPanelHeader.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Miercoles");
        jPanelHeader.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jueves");
        jPanelHeader.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Viernes");
        jPanelHeader.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sabado");
        jPanelHeader.add(jLabel7);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Domingo");
        jPanelHeader.add(jLabel1);

        jPanelCalendario.add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        jPanelDetalles.add(jPanelCalendario);

        getContentPane().add(jPanelDetalles, java.awt.BorderLayout.CENTER);

        jPanelControles.setBackground(new java.awt.Color(204, 204, 204));
        jPanelControles.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonEliminar.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelControles.add(jButtonEliminar);

        jButtonEditar.setText(bundle.getString("label_editar")); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanelControles.add(jButtonEditar);

        jButtonY.setText("Y");
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });
        jPanelControles.add(jButtonY);

        getContentPane().add(jPanelControles, java.awt.BorderLayout.PAGE_END);

        jPanelSeleccion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/logout40.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelSeleccion.add(jButton1, java.awt.BorderLayout.LINE_START);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel9.setText("Año");
        jPanel3.add(jLabel9);

        jYearChooser1.setOpaque(false);
        jYearChooser1.setPreferredSize(new java.awt.Dimension(80, 35));
        jYearChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jYearChooser1PropertyChange(evt);
            }
        });
        jPanel3.add(jYearChooser1);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel8.setText("Mes");
        jPanel3.add(jLabel8);

        jMonthChooser1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMonthChooser1.setMinimumSize(new java.awt.Dimension(176, 40));
        jMonthChooser1.setOpaque(false);
        jMonthChooser1.setPreferredSize(new java.awt.Dimension(176, 40));
        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });
        jPanel3.add(jMonthChooser1);

        jPanelSeleccion.add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanelSeleccion, java.awt.BorderLayout.PAGE_START);

        jPanelEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadisticas Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelEstadisticas.setLayout(new java.awt.GridLayout(3, 0));

        jPanelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelVentas.setLayout(new java.awt.GridLayout(3, 0));

        jLabelTotalVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTotalVendido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pulgar-arriba.png"))); // NOI18N
        jLabelTotalVendido.setText("XXXXXX.XX < >");
        jLabelTotalVendido.setToolTipText("Total");
        jLabelTotalVendido.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanelVentas.add(jLabelTotalVendido);

        jLabelPromedioVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPromedioVendido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPromedioVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/promedio.png"))); // NOI18N
        jLabelPromedioVendido.setText("XXXXXX.XX < >");
        jLabelPromedioVendido.setToolTipText("Promedio");
        jLabelPromedioVendido.setBorder(javax.swing.BorderFactory.createTitledBorder("Promedio"));
        jPanelVentas.add(jLabelPromedioVendido);

        jLabelHoraPico.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelHoraPico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoraPico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/hora_pico.png"))); // NOI18N
        jLabelHoraPico.setText("XX PM/AM");
        jLabelHoraPico.setToolTipText("Hora Pico");
        jLabelHoraPico.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora Pico"));
        jPanelVentas.add(jLabelHoraPico);

        jPanelEstadisticas.add(jPanelVentas);

        jPanelGastos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gastos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelGastos.setLayout(new java.awt.GridLayout(3, 0));

        jLabelInsumo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelInsumo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInsumo.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelInsumo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 3, true), "Insumo"));
        jPanelGastos.add(jLabelInsumo);

        jLabelTrabajadores.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTrabajadores.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 3, true), "Trabajadores"));
        jPanelGastos.add(jLabelTrabajadores);

        jLabelOtros.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelOtros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelOtros.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelOtros.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true), "Otros"));
        jPanelGastos.add(jLabelOtros);

        jPanelEstadisticas.add(jPanelGastos);

        jPanelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen Detallado", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelResumen.setLayout(new javax.swing.BoxLayout(jPanelResumen, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel10.setText("Del");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);

        jDateChooserDel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDelPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooserDel);

        jPanelResumen.add(jPanel1);

        jLabel11.setText("Al");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jPanel2.add(jDateChooserAl);

        jPanelResumen.add(jPanel2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/detalles.png"))); // NOI18N
        jButton3.setToolTipText("Vista Detallada");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelResumen.add(jButton3);

        jPanelEstadisticas.add(jPanelResumen);

        getContentPane().add(jPanelEstadisticas, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jYearChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jYearChooser1PropertyChange
        if (evt.getPropertyName().equals("year")) {
            updateView();
        }
    }//GEN-LAST:event_jYearChooser1PropertyChange

    private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooser1PropertyChange
        if (evt.getPropertyName().equals("month")) {
            updateView();
        }
    }//GEN-LAST:event_jMonthChooser1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        createDetailResumenView();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableCalendarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableCalendarFocusLost

    }//GEN-LAST:event_jTableCalendarFocusLost

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        editSelected();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCalendarMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == 1) {
            editSelected();
        }

    }//GEN-LAST:event_jTableCalendarMouseClicked

    private void jDateChooserDelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDelPropertyChange
        if (evt.getPropertyName().equals("date")) {
            jDateChooserAl.setDate((Date) evt.getNewValue());
        }
//        jDateChooserAl.setDate((Date) evt.getNewValue());
    }//GEN-LAST:event_jDateChooserDelPropertyChange

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        deleteSelected();// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        if (!R.PERIRSTENCE_UNIT_NAME.equals(R.RESOURCE_BUNDLE.getString("unidad_persistencia_remota"))) {
            throw new UnauthorizedAccessException(this, "Esta operacion solo se puede ejecutar conectado al servidor remoto");
        }
        Y alg = new Y(model.getValueAt(jTableCalendar.getSelectedRow(), jTableCalendar.getSelectedColumn()), getController());
        Venta old = alg.getVentaReal();
        Venta newVenta = new Venta();
        if (new BackUp().ExisteVentaEnLocal(old)) {
            throw new ValidatingException("Primero debe realizar una copia de seguridad del dia seleccionado en su ordenador");
        }
        try {
            getController().destroy(VentaDAO.getInstance().find(old.getFecha()), true);
            newVenta.setAsistenciaPersonalList(new ArrayList<>());
            newVenta.setFecha(old.getFecha());
            newVenta.setOrdenList(alg.ejecutarAlgoritmo());
            newVenta.setGastoVentaList(new ArrayList<>());
            newVenta.setVentagastosPagotrabajadores(VentaDAO1.getValorTotalPagoTrabajadores(newVenta));
            newVenta.setVentagastosGastos((float) 0.0);
            newVenta.setVentaTotal((double) VentaDAO1.getValorTotalVentas(newVenta));
            VentaDAO.getInstance().startTransaction();
            VentaDAO.getInstance().create(newVenta);
            VentaDAO.getInstance().commitTransaction();
        } catch (Exception e) {
            VentaDAO.getInstance().startTransaction();
            VentaDAO.getInstance().create(old);
            VentaDAO.getInstance().commitTransaction();
            JOptionPane.showMessageDialog(this, "La operacion no se ha podido completar correctamente. Contacte con soporte");

        }
        if (VentaDAO.getInstance().find(old.getFecha()) == null) {
            VentaDAO.getInstance().startTransaction();
            VentaDAO.getInstance().create(old);
            VentaDAO.getInstance().commitTransaction();
            JOptionPane.showMessageDialog(this, "La operacion no se ha podido completar correctamente. Contacte con soporte");
        }

    }//GEN-LAST:event_jButtonYActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonY;
    private com.toedter.calendar.JDateChooser jDateChooserAl;
    private com.toedter.calendar.JDateChooser jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHoraPico;
    private javax.swing.JLabel jLabelInsumo;
    private javax.swing.JLabel jLabelOtros;
    private javax.swing.JLabel jLabelPromedioVendido;
    private javax.swing.JLabel jLabelTotalVendido;
    private javax.swing.JLabel jLabelTrabajadores;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCalendario;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResumen;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCalendar;
    private javax.swing.JTree jTree1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
        updateCalendar();
        jScrollPane1.getViewport().setOpaque(false);

        int month = jMonthChooser1.getMonth();
        int year = jYearChooser1.getYear();
        jDateChooserDel.setCalendar(cal);
        model = new RestManagerAbstractTableCellModel<Venta>(findVentas(month, year), jTableCalendar) {
            @Override
            public int getColumnCount() {
                return 7;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return Venta.class;
            }

            @Override
            public Venta getValueAt(int rowIndex, int columnIndex) {
                int linearPos = rowIndex * getColumnCount() + columnIndex;
                if (linearPos >= monthOffset) {
                    for (Venta x : getItems()) {
                        if ((x.getFecha().getDate() - 1) == (linearPos - monthOffset)) {
                            return x;
                        }
                    }
                }
                return null;
            }

            @Override
            public int getRowCount() {
                return 6;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Lunes";
                    case 1:
                        return "Martes";
                    case 2:
                        return "Miercoles";
                    case 3:
                        return "Jueves";
                    case 4:
                        return "Viernes";
                    case 5:
                        return "Sabado";
                    case 6:
                        return "Domingo";
                    default:
                        return null;
                }
            }
        };
        jTableCalendar.setModel(model);
        updatePanelEstaidisticas(model.getItems());
        jTableCalendar.setDefaultRenderer(Venta.class, new VentaCellRender());
    }

    public List<Venta> findVentas(int month, int year) {
        return getController().findVentas(month, year);
    }

    @Override
    public VentaListController getController() {
        return (VentaListController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }

    public void updateCalendar() {
        cal.set(Calendar.DAY_OF_MONTH, 1);
        cal.set(Calendar.YEAR, jYearChooser1.getYear());
        cal.set(Calendar.MONTH, jMonthChooser1.getMonth());
        monthOffset = cal.get(Calendar.DAY_OF_WEEK) - 2;
        if (monthOffset == -1) {
            monthOffset = 6;
        }

    }

    public List<Venta> getSelectedVentas() {
        return model.getSelectedItems();
    }

    public void updatePanelEstaidisticas(List<Venta> ventas) {
        double suma = 0;
        double gInsumos = 0;
        double gGastos = 0;
        double gTrabajadores = 0;
        int cantidad = 0;
        for (Venta x : ventas) {
            if (x.getVentaTotal() != null) {
                suma += x.getVentaTotal();
                if (x.getVentagastosEninsumos() != null) {
                    gInsumos += x.getVentagastosEninsumos();
                }
                if (x.getVentagastosGastos() != null) {
                    gGastos += x.getVentagastosGastos();
                }
                if (x.getVentagastosPagotrabajadores() != null) {
                    gTrabajadores += x.getVentagastosPagotrabajadores();
                }
                cantidad++;
            }
        }
        double promedio = suma / cantidad;

        jLabelTotalVendido.setText(utils.setDosLugaresDecimales((float) suma));
        jLabelPromedioVendido.setText(utils.setDosLugaresDecimales((float) promedio));
        jLabelInsumo.setText(utils.setDosLugaresDecimales((float) gInsumos));
        jLabelTrabajadores.setText(utils.setDosLugaresDecimales((float) (gTrabajadores)));
        jLabelOtros.setText(utils.setDosLugaresDecimales((float) gGastos));
        int hora_pico_promedio = VentaDAO1.getModalPickHour(ventas);
        jLabelHoraPico.setText(hora_pico_promedio > 12 ? (hora_pico_promedio - 12) + " PM" : hora_pico_promedio + " AM");
    }

    private void editSelected() {
        VentaDetailController controller = new VentaDetailController(model.getValueAt(jTableCalendar.getSelectedRow(), jTableCalendar.getSelectedColumn()), this);
    }

    private void createDetailResumenView() {
        if (jDateChooserAl.getDate() == null || jDateChooserDel.getDate() == null) {
            throw new NoSelectedException(jPanelResumen);
        }
        if (jDateChooserAl.getDate().compareTo(jDateChooserDel.getDate()) < 0) {
            throw new ValidatingException(jPanelResumen);
        }
        getController().createDetailResumenView(jDateChooserDel.getDate(), jDateChooserAl.getDate());
    }

    private void deleteSelected() {
        if (jTableCalendar.getSelectedColumnCount() > 1 || jTableCalendar.getSelectedRowCount() > 1) {
            for (int selectedColumn : jTableCalendar.getSelectedColumns()) {
                for (int selectedRow : jTableCalendar.getSelectedRows()) {
                    Venta v = model.getValueAt(selectedRow, selectedColumn);
                    if (v != null) {
                        getController().destroy(model.getValueAt(selectedRow, selectedColumn));
                    }
                }
            }
        } else {
            getController().destroy(model.getValueAt(jTableCalendar.getSelectedRow(), jTableCalendar.getSelectedColumn()));
        }
    }

    @Override
    public void fetchComponentData() {
        LicenceController controller = new LicenceController(Licence.TipoLicencia.SECUNDARIA);
        jButtonY.setVisible(controller.getLicence().LICENCIA_ACTIVA && controller.getLicence().LICENCIA_VALIDA);
    }

}
