/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.venta;

import GUI.Views.AbstractView;
import com.jidesoft.utils.DateUtils;
import java.awt.Color;
import java.awt.Frame;
import restManager.controller.AbstractDialogController;
import restManager.exceptions.DevelopingOperationException;

/**
 *
 * @author Jorge
 */
public class VentaArchivadaCalendarView extends AbstractView {

    public VentaArchivadaCalendarView(AbstractDialogController controller, Frame owner, boolean modal) {
        super(DialogType.NORMAL, controller, owner, modal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        substanceDatePickerUI1 = new org.pushingpixels.substance.swingx.SubstanceDatePickerUI();
        jPanelRoot = new javax.swing.JPanel();
        paintPanel1 = new com.jidesoft.swing.PaintPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jPanelOptions = new javax.swing.JPanel();
        jButtonArchivarDias = new javax.swing.JButton();
        jButtonCierreVentas = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelRoot.setLayout(new java.awt.BorderLayout());

        com.jidesoft.swing.JideBorderLayout jideBorderLayout1 = new com.jidesoft.swing.JideBorderLayout();
        jideBorderLayout1.setVgap(10);
        jideBorderLayout1.setHgap(10);
        paintPanel1.setLayout(jideBorderLayout1);
        paintPanel1.add(jCalendar1);

        jPanelRoot.add(paintPanel1, java.awt.BorderLayout.CENTER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jXLabel1.setText(bundle.getString("label_dias_archivados")); // NOI18N
        jXLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jPanel2.add(jXLabel1);

        jPanelRoot.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanelOptions.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        jButtonArchivarDias.setText(bundle.getString("label_archivar_dias")); // NOI18N
        jPanelOptions.add(jButtonArchivarDias);

        jButtonCierreVentas.setText(bundle.getString("label_cierre_ventas")); // NOI18N
        jPanelOptions.add(jButtonCierreVentas);

        jButtonEliminar.setText(bundle.getString("label_eliminar")); // NOI18N
        jPanelOptions.add(jButtonEliminar);

        jButtonSalir.setText(bundle.getString("label_salir")); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelOptions.add(jButtonSalir);

        jPanelRoot.add(jPanelOptions, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanelRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    @Override
    public void updateView() {
        throw new DevelopingOperationException(); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivarDias;
    private javax.swing.JButton jButtonCierreVentas;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonSalir;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelRoot;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private com.jidesoft.swing.PaintPanel paintPanel1;
    private org.pushingpixels.substance.swingx.SubstanceDatePickerUI substanceDatePickerUI1;
    // End of variables declaration//GEN-END:variables
}
