/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.venta;

import GUI.Views.AbstractView;
import GUI.Views.util.VentaCellRender;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import restManager.controller.AbstractDialogController;
import restManager.controller.venta.VentaDetailController;
import restManager.controller.venta.VentaListController;
import restManager.exceptions.NoSelectedException;
import restManager.exceptions.ValidatingException;
import restManager.persistencia.Control.VentaDAO1;
import restManager.persistencia.Venta;
import restManager.util.RestManagerAbstractTableCellModel;
import restManager.util.comun;

/**
 *
 * @author Jorge
 */
public class VentaCalendarView extends AbstractView {

    private RestManagerAbstractTableCellModel<Venta> model;
    Calendar cal = new GregorianCalendar();
    int monthOffset = 0;

    /**
     * Creates new form VentasCalendarFragmentView
     *
     * @param controller
     */
    public VentaCalendarView(AbstractDialogController controller) {
        super(DialogType.FULL_SCREEN, controller);
        initComponents();
        init();
    }

    public VentaCalendarView(AbstractDialogController<Venta> controller, AbstractView parentComponent) {
        super(DialogType.FULL_SCREEN, controller, parentComponent);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelCalendario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalendar = new javax.swing.JTable();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelControles = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelSeleccion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanelEstadisticas = new javax.swing.JPanel();
        jPanelVentas = new javax.swing.JPanel();
        jLabelTotalVendido = new javax.swing.JLabel();
        jLabelPromedioVendido = new javax.swing.JLabel();
        jLabelHoraPico = new javax.swing.JLabel();
        jPanelGastos = new javax.swing.JPanel();
        jPanelResumen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserDel = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserAl = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanelDetalles.setLayout(new javax.swing.OverlayLayout(jPanelDetalles));

        jPanelCalendario.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCalendario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelCalendario.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        jTableCalendar.setBackground(new java.awt.Color(204, 204, 204));
        jTableCalendar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTableCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCalendar.setColumnSelectionAllowed(true);
        jTableCalendar.setOpaque(false);
        jTableCalendar.setRowHeight(80);
        jTableCalendar.setRowMargin(2);
        jTableCalendar.setShowGrid(false);
        jTableCalendar.setTableHeader(null);
        jTableCalendar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableCalendarFocusLost(evt);
            }
        });
        jTableCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCalendarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCalendar);

        jPanelCalendario.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanelHeader.setLayout(new java.awt.GridLayout(1, 7));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lunes");
        jPanelHeader.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Martes");
        jPanelHeader.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Miercoles");
        jPanelHeader.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jueves");
        jPanelHeader.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Viernes");
        jPanelHeader.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sabado");
        jPanelHeader.add(jLabel7);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Domingo");
        jPanelHeader.add(jLabel1);

        jPanelCalendario.add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        jPanelDetalles.add(jPanelCalendario);

        getContentPane().add(jPanelDetalles, java.awt.BorderLayout.CENTER);

        jPanelControles.setBackground(new java.awt.Color(204, 204, 204));
        jPanelControles.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButton1.setText(bundle.getString("label_salir")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelControles.add(jButton1);

        jButton2.setText(bundle.getString("label_editar")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelControles.add(jButton2);

        getContentPane().add(jPanelControles, java.awt.BorderLayout.PAGE_END);

        jPanelSeleccion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel9.setText("Año");
        jPanelSeleccion.add(jLabel9);

        jYearChooser1.setOpaque(false);
        jYearChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jYearChooser1PropertyChange(evt);
            }
        });
        jPanelSeleccion.add(jYearChooser1);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel8.setText("Mes");
        jPanelSeleccion.add(jLabel8);

        jMonthChooser1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jMonthChooser1.setOpaque(false);
        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });
        jPanelSeleccion.add(jMonthChooser1);

        getContentPane().add(jPanelSeleccion, java.awt.BorderLayout.PAGE_START);

        jPanelEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadisticas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 18))); // NOI18N
        jPanelEstadisticas.setLayout(new java.awt.GridLayout(3, 0));

        jPanelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder("Ventas"));
        jPanelVentas.setLayout(new java.awt.GridLayout(3, 0));

        jLabelTotalVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTotalVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pulgar-arriba.png"))); // NOI18N
        jLabelTotalVendido.setText("26000 CUC");
        jLabelTotalVendido.setToolTipText("Total");
        jPanelVentas.add(jLabelTotalVendido);

        jLabelPromedioVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPromedioVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/promedio.png"))); // NOI18N
        jLabelPromedioVendido.setText("3000 CUC");
        jLabelPromedioVendido.setToolTipText("Promedio");
        jPanelVentas.add(jLabelPromedioVendido);

        jLabelHoraPico.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelHoraPico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/hora_pico.png"))); // NOI18N
        jLabelHoraPico.setText("4 PM");
        jLabelHoraPico.setToolTipText("Hora Pico");
        jPanelVentas.add(jLabelHoraPico);

        jPanelEstadisticas.add(jPanelVentas);

        jPanelGastos.setBorder(javax.swing.BorderFactory.createTitledBorder("Gastos"));
        jPanelEstadisticas.add(jPanelGastos);

        jPanelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen Detallado"));
        jPanelResumen.setLayout(new javax.swing.BoxLayout(jPanelResumen, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel10.setText("Del");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);

        jDateChooserDel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDelPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooserDel);

        jPanelResumen.add(jPanel1);

        jLabel11.setText("Al");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jPanel2.add(jDateChooserAl);

        jPanelResumen.add(jPanel2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/detalles.png"))); // NOI18N
        jButton3.setToolTipText("Vista Detallada");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelResumen.add(jButton3);

        jPanelEstadisticas.add(jPanelResumen);

        getContentPane().add(jPanelEstadisticas, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jYearChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jYearChooser1PropertyChange
        if (evt.getPropertyName().equals("year")) {
            init();
        }
    }//GEN-LAST:event_jYearChooser1PropertyChange

    private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooser1PropertyChange
        if (evt.getPropertyName().equals("month")) {
            init();
        }
    }//GEN-LAST:event_jMonthChooser1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        createDetailResumenView();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableCalendarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableCalendarFocusLost

    }//GEN-LAST:event_jTableCalendarFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        editSelected();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCalendarMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == 1) {
            editSelected();
        }

    }//GEN-LAST:event_jTableCalendarMouseClicked

    private void jDateChooserDelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDelPropertyChange
        if (evt.getPropertyName().equals("date")) {
            jDateChooserAl.setDate((Date) evt.getNewValue());
        }
//        jDateChooserAl.setDate((Date) evt.getNewValue());
    }//GEN-LAST:event_jDateChooserDelPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserAl;
    private com.toedter.calendar.JDateChooser jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHoraPico;
    private javax.swing.JLabel jLabelPromedioVendido;
    private javax.swing.JLabel jLabelTotalVendido;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCalendario;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResumen;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCalendar;
    private javax.swing.JTree jTree1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
//    Venta root = new Venta();
//    root.setOrdenList(new ArrayList<Orden>());
//        RestManagerVentaTreeNode rootNode = new RestManagerVentaTreeNode(root);
//        for (Venta x : getController().getItems()) {
//            rootNode.insert(x);
//        }
//        jTree1 = new JTree(rootNode);

    }

    public void init() {
        updateCalendar();
        jScrollPane1.getViewport().setOpaque(false);

        int month = jMonthChooser1.getMonth();
        int year = jYearChooser1.getYear();
        model = new RestManagerAbstractTableCellModel<Venta>(findVentas(month, year), jTableCalendar) {
            @Override
            public int getColumnCount() {
                return 7;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return Venta.class;
            }

            @Override
            public Venta getValueAt(int rowIndex, int columnIndex) {
                int linearPos = rowIndex * getColumnCount() + columnIndex;
                if (linearPos >= monthOffset) {
                    for (Venta x : getItems()) {
                        if ((x.getFecha().getDate() - 1) == (linearPos - monthOffset)) {
                            return x;
                        }
                    }
                }
                return null;
            }

            @Override
            public int getRowCount() {
                return 6;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Lunes";
                    case 1:
                        return "Martes";
                    case 2:
                        return "Miercoles";
                    case 3:
                        return "Jueves";
                    case 4:
                        return "Viernes";
                    case 5:
                        return "Sabado";
                    case 6:
                        return "Domingo";
                    default:
                        return null;
                }
            }
        };
        jTableCalendar.setModel(model);
        updatePanelEstaidisticas(model.getItems());
//        model.addSelectionListener((PropertyChangeEvent evt) -> {
//            updatePanelEstaidisticas(getSelectedVentas());
//        });
        jTableCalendar.setDefaultRenderer(Venta.class, new VentaCellRender());
        //jTableCalendar.setRowHeight(80);
    }

    public List<Venta> findVentas(int month, int year) {
        ArrayList<Venta> ret = new ArrayList<>();
        getController().getModel().findAll().stream().map((x) -> {
            if (x.getFecha().getMonth() == month && x.getFecha().getYear() + 1900 == year) {
                ret.add(x);
            }
            return x;
        }).forEachOrdered((Venta _item) -> {
            Collections.sort(ret, (Venta o1, Venta o2) -> o1.getFecha().compareTo(o2.getFecha()));
        });
        return ret;
    }

    @Override
    public VentaListController getController() {
        return (VentaListController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }

    public void updateCalendar() {
        cal.set(Calendar.DAY_OF_MONTH, 1);
        cal.set(Calendar.YEAR, jYearChooser1.getYear());
        cal.set(Calendar.MONTH, jMonthChooser1.getMonth());
        monthOffset = cal.get(Calendar.DAY_OF_WEEK) - 2;
    }

    public List<Venta> getSelectedVentas() {
        return model.getSelectedItems();
    }

    public void updatePanelEstaidisticas(List<Venta> ventas) {
        double suma = 0;
        double gastos = 0;
        int cantidad = 0;
        int horas_pico = 0;
        for (Venta x : ventas) {
            if (x.getVentaTotal() != null) {
                suma += x.getVentaTotal();
                gastos += x.getVentagastosEninsumos();
                horas_pico += VentaDAO1.getPickHour(x);
                cantidad ++;
            }
        }
        double promedio = suma / cantidad;

        jLabelTotalVendido.setText(comun.setDosLugaresDecimales((float) suma));
        jLabelPromedioVendido.setText(comun.setDosLugaresDecimales((float) promedio));
        int hora_pico_promedio = VentaDAO1.getModalPickHour(ventas);
        jLabelHoraPico.setText(hora_pico_promedio > 12 ? (hora_pico_promedio-12) + " PM" : hora_pico_promedio + " AM");
    }

    private void editSelected() {
        VentaDetailController controller = new VentaDetailController(model.getValueAt(jTableCalendar.getSelectedRow(), jTableCalendar.getSelectedColumn()), this);
    }

    private void createDetailResumenView() {
        if (jDateChooserAl.getDate() == null || jDateChooserDel.getDate() == null) {
            throw new NoSelectedException(jPanelResumen);
        }
        if (jDateChooserAl.getDate().compareTo(jDateChooserDel.getDate()) < 0) {
            throw new ValidatingException(jPanelResumen);
        }
        getController().createDetailResumenView(jDateChooserDel.getDate(), jDateChooserAl.getDate());
    }

}
