/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.utils;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jgoodies.binding.value.ValueModel;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.swing.utils.BindableListIntelliHint;
import com.jobits.pos.ui.swing.utils.BindableTableModel;

import com.jobits.ui.components.MaterialComponentsFactory;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Jorge
 * @param <T> the table content data
 * @param <K> the combobox model data
 */
@Getter
@Setter
public class AddFromPanel<T, K> extends AbstractViewPanel {

    private String jTextFieldDataName;

    //
    // AutoComplete
    //
    private ValueModel autoCompletitionData;
    private ValueModel autoCompletitionDataSelection;

    //
    //Tabla
    //
    private ValueModel tableDataHolder;
    private ValueModel tableSelectionDataHolder;

    private BindableTableModel<T> tableModel;

    //
    //Buttons
    //
    private Action addAction;
    private Action removeAction;

    /**
     * Creates new form AbstractCrossReferenePanel
     *
     * @param jTextFieldDataName
     * @param autoCompletitionData
     * @param autoCOmpletitionDataSelection
     * @param tableDataHolder
     * @param tableSelectionDataHolder
     * @param addAction
     * @param tableModel
     * @param removeAction
     */
    @Builder()
    public AddFromPanel(
            String jTextFieldDataName,
            ValueModel autoCompletitionData,
            ValueModel autoCOmpletitionDataSelection,
            ValueModel tableDataHolder,
            ValueModel tableSelectionDataHolder,
            Action addAction,
            Action removeAction,
            BindableTableModel<T> tableModel) {
        super();
        this.jTextFieldDataName = jTextFieldDataName;
        this.autoCompletitionData = autoCompletitionData;
        this.autoCompletitionDataSelection = autoCOmpletitionDataSelection;
        this.tableDataHolder = tableDataHolder;
        this.tableSelectionDataHolder = tableSelectionDataHolder;
        this.addAction = addAction;
        this.removeAction = removeAction;
        this.tableModel = tableModel;
        uiInit();
        wireUp();
    }

    public JTable getjTableCrossReference() {
        return jTableCrossReference;
    }

    public JPanel getjPanelOpciones() {
        return jPanelOpciones;
    }

    public JPanel getjPanelOpcionesContainer() {
        return jPanelOpcionesContainer;
    }

    public JButton getjButtonAgregarProd() {
        return jButtonAgregarProd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInsert = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldAutoComplete = MaterialComponentsFactory.Input.getTextField("Buscar...", jTextFieldDataName);
        jButtonAgregarProd = MaterialComponentsFactory.Buttons.getAddButton();
        jScrollPaneCrossReference = MaterialComponentsFactory.Containers.getScrollPane();
        jPanelOpcionesContainer = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonDeleteProd = MaterialComponentsFactory.Buttons.getCancelButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setMinimumSize(new java.awt.Dimension(567, 370));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanelInsert.setMaximumSize(new java.awt.Dimension(2147483647, 64));
        jPanelInsert.setMinimumSize(new java.awt.Dimension(100, 64));
        jPanelInsert.setOpaque(false);
        jPanelInsert.setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 38));

        jTextFieldAutoComplete.setMinimumSize(new java.awt.Dimension(250, 26));
        jTextFieldAutoComplete.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jTextFieldAutoComplete);

        jButtonAgregarProd.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonAgregarProd.setText("Agregar");
        jButtonAgregarProd.setMaximumSize(new java.awt.Dimension(130, 50));
        jButtonAgregarProd.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel1.add(jButtonAgregarProd);

        jPanelInsert.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        add(jPanelInsert, java.awt.BorderLayout.NORTH);

        jScrollPaneCrossReference.setOpaque(false);
        jScrollPaneCrossReference.setPreferredSize(new java.awt.Dimension(500, 130));
        add(jScrollPaneCrossReference, java.awt.BorderLayout.CENTER);

        jPanelOpcionesContainer.setOpaque(false);
        jPanelOpcionesContainer.setLayout(new java.awt.BorderLayout());

        jPanelOpciones.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanelOpciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonDeleteProd.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonDeleteProd.setText("Eliminar");
        jButtonDeleteProd.setToolTipText("Eliminar");
        jButtonDeleteProd.setMaximumSize(new java.awt.Dimension(130, 50));
        jButtonDeleteProd.setMinimumSize(new java.awt.Dimension(32, 50));
        jButtonDeleteProd.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanelOpciones.add(jButtonDeleteProd);

        jPanelOpcionesContainer.add(jPanelOpciones, java.awt.BorderLayout.CENTER);

        add(jPanelOpcionesContainer, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    protected javax.swing.JTable jTableCrossReference;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProd;
    private javax.swing.JButton jButtonDeleteProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInsert;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelOpcionesContainer;
    private javax.swing.JScrollPane jScrollPaneCrossReference;
    private javax.swing.JTextField jTextFieldAutoComplete;
    // End of variables declaration//GEN-END:variables

    @Override
    public AbstractViewPresenter getPresenter() {
        throw new IllegalStateException("Bad call to getPresenter() on embedded object");
    }

    @Override
    public String getViewName() {
        throw new IllegalStateException("Bad call to getViewName() on embedded object");
    }

    @Override
    public void uiInit() {
        initComponents();
        jTableCrossReference = new JTable(tableModel);
        jScrollPaneCrossReference.setViewportView(jTableCrossReference);
        tableModel.setTable(jTableCrossReference);
        jTextFieldAutoComplete.addActionListener(addAction);
    }

    @Override
    public void wireUp() {
        BindableListIntelliHint<K> autoCompleteModel = new BindableListIntelliHint(
                new SelectionInList<K>(autoCompletitionData, autoCompletitionDataSelection), jTextFieldAutoComplete);
        jButtonAgregarProd.addActionListener(addAction);
        jButtonDeleteProd.addActionListener(removeAction);

        Bindings.bind(jTableCrossReference, new SelectionInList(tableDataHolder, tableSelectionDataHolder));

    }

}
