/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.utils;

import GUI.Components.JSpinner;
import com.jobits.pos.ui.AbstractView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JFormattedTextField;
import com.jobits.pos.persistencia.Orden;
import com.jobits.pos.servicios.impresion.Impresion;
import com.jobits.pos.recursos.R;

/**
 *
 * @author Jorge
 */
public class CalcularCambioView extends javax.swing.JDialog {

    /**
     * Creates new form PuestoTrabajoCrear
     */
    private Orden o;

    public CalcularCambioView(AbstractView parent, boolean modal, Orden o) {
        super(parent, modal);
        this.o = o;
        init(o);

    }

    public void init(Orden o) {

        setUndecorated(true);
        initComponents();

        jLabel1.setText(o.toString());
        jLabelValorMontoAPagar.setText(utils.setDosLugaresDecimales(o.getOrdenvalorMonetario()));
        jLabelValorMontoADevolver.setText("");

        ActionListener l = (ActionEvent e) -> {
            ((JFormattedTextField) e.getSource()).transferFocus();
        };
        FocusListener focus = new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                ((JFormattedTextField) e.getSource()).setText(null);
            }

            @Override
            public void focusLost(FocusEvent e) {
            }
        };

        final JFormattedTextField fieldCUC = ((JSpinner.NumberEditor) jSpinnerCUC.getEditor()).getTextField();
        final JFormattedTextField fieldMN = ((JSpinner.NumberEditor) jSpinnerMN.getEditor()).getTextField();

        fieldCUC.addActionListener(l);
        fieldMN.addActionListener(l);
        fieldCUC.addFocusListener(focus);
        fieldMN.addFocusListener(focus);

        ComponentMover cr = new ComponentMover(this, jPanel1);

        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAbirCajon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre1 = new org.jdesktop.swingx.JXLabel();
        jLabelValorMontoAPagar = new org.jdesktop.swingx.JXLabel();
        jLabelNombre2 = new org.jdesktop.swingx.JXLabel();
        jSpinnerCUC = new javax.swing.JSpinner();
        jLabelNombre4 = new org.jdesktop.swingx.JXLabel();
        jSpinnerMN = new javax.swing.JSpinner();
        jLabelSalarioFijo1 = new org.jdesktop.swingx.JXLabel();
        jLabelValorMontoADevolver = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(287, 188));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("O- XXXX ");
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonSalir.setText(bundle.getString("label_salir")); // NOI18N
        jButtonSalir.setOpaque(true);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalir, java.awt.BorderLayout.EAST);

        jButtonAbirCajon.setText(bundle.getString("label_abrir_cajon")); // NOI18N
        jButtonAbirCajon.setOpaque(true);
        jButtonAbirCajon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbirCajonActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAbirCajon, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jLabelNombre1.setText("Total a pagar:");
        jLabelNombre1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jPanel1.add(jLabelNombre1);

        jLabelValorMontoAPagar.setForeground(new java.awt.Color(0, 153, 0));
        jLabelValorMontoAPagar.setText("XX.XX");
        jLabelValorMontoAPagar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel1.add(jLabelValorMontoAPagar);

        jLabelNombre2.setText("CUC");
        jLabelNombre2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jPanel1.add(jLabelNombre2);

        jSpinnerCUC.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jSpinnerCUC.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 5.0f));
        jSpinnerCUC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCUCStateChanged(evt);
            }
        });
        jPanel1.add(jSpinnerCUC);

        jLabelNombre4.setText("MN");
        jLabelNombre4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jPanel1.add(jLabelNombre4);

        jSpinnerMN.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jSpinnerMN.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 10));
        jSpinnerMN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerMNStateChanged(evt);
            }
        });
        jSpinnerMN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSpinnerMNFocusGained(evt);
            }
        });
        jPanel1.add(jSpinnerMN);

        jLabelSalarioFijo1.setText("Monto a devolver:");
        jLabelSalarioFijo1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jPanel1.add(jLabelSalarioFijo1);

        jLabelValorMontoADevolver.setForeground(new java.awt.Color(204, 0, 0));
        jLabelValorMontoADevolver.setText("XX.XX");
        jLabelValorMontoADevolver.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel1.add(jLabelValorMontoADevolver);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerCUCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCUCStateChanged
        actualizarVuelto();
    }//GEN-LAST:event_jSpinnerCUCStateChanged

    private void jSpinnerMNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerMNStateChanged
        actualizarVuelto();
    }//GEN-LAST:event_jSpinnerMNStateChanged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jSpinnerMNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinnerMNFocusGained
    }//GEN-LAST:event_jSpinnerMNFocusGained

    private void jButtonAbirCajonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbirCajonActionPerformed
        Impresion.getDefaultInstance().forceDrawerKick();
        jButtonAbirCajon.transferFocus();
    }//GEN-LAST:event_jButtonAbirCajonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbirCajon;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXLabel jLabelNombre1;
    private org.jdesktop.swingx.JXLabel jLabelNombre2;
    private org.jdesktop.swingx.JXLabel jLabelNombre4;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo1;
    private org.jdesktop.swingx.JXLabel jLabelValorMontoADevolver;
    private org.jdesktop.swingx.JXLabel jLabelValorMontoAPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinnerCUC;
    private javax.swing.JSpinner jSpinnerMN;
    // End of variables declaration//GEN-END:variables

    private void actualizarVuelto() {

        float montoADevolver = o.getOrdenvalorMonetario();

        if (R.COIN_SUFFIX.equals(" CUC")) {
            float cuc = (float) jSpinnerCUC.getValue();
            montoADevolver -= cuc;

            float mn = (int) jSpinnerMN.getValue();
            mn /= R.COINCHANGE;
            montoADevolver -= mn;

        } else {
            float cuc = (float) jSpinnerCUC.getValue();
            utils.setDosLugaresDecimales(cuc *= R.COINCHANGE);
            montoADevolver -= cuc;

            float mn = (int) jSpinnerMN.getValue();
            montoADevolver -= mn;

        }

        if (montoADevolver > 0) {
            jLabelValorMontoADevolver.setText("Falta " + utils.setDosLugaresDecimales(montoADevolver));
        } else {
            jLabelValorMontoADevolver.setText(utils.setDosLugaresDecimales(montoADevolver));

        }

    }

}
