/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.utils;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import com.jobits.pos.exceptions.DuplicatedException;
import com.jobits.pos.exceptions.NoSelectedException;
import com.jobits.pos.domain.models.Carta;

/**
 *
 * @author Jorge
 * @param <T>
 */
public class ComboBoxWithList<T> extends javax.swing.JPanel {

    /**
     * Creates new form ComboBoxWithList
     */
    private RestManagerComboBoxModel<T> comboModel;
    private RestManagerListModel<T> listModel;

    public ComboBoxWithList(List<T> listForComboBox, List<T> listForList) {
        initComponents();
        comboModel = new RestManagerComboBoxModel<>(listForComboBox);
        listModel = new RestManagerListModel<>(listForList);
        jComboBoxT.setModel(comboModel);
        jListT.setModel(listModel);
    }

    public RestManagerComboBoxModel<T> getComboModel() {
        return comboModel;
    }

    public RestManagerListModel<T> getListModel() {
        return listModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxT = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListT = new javax.swing.JList<>();
        jPanel13 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jComboBoxT.setToolTipText("Seleccione la seccion a excluir");
        add(jComboBoxT, java.awt.BorderLayout.PAGE_START);

        jListT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListT);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/aceptar16.png"))); // NOI18N
        jButtonAdd.setToolTipText("Agregar Menu");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonAdd);

        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/borrar16.png"))); // NOI18N
        jButtonDelete.setToolTipText("Quitar Menu");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonDelete);

        add(jPanel13, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        adicionar();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void eliminar() {
        if (jListT.getSelectedIndex() == -1) {
            throw new NoSelectedException(this);
        }

        listModel.getElements().remove(jListT.getSelectedValue());
        jListT.setModel(new RestManagerListModel<>(listModel.getElements()));
    }

    private void adicionar() {
        if (jComboBoxT.getSelectedIndex() == -1) {
            throw new NoSelectedException(this);
        }
        T selected = (T) jComboBoxT.getSelectedItem();

        if (listModel.getElements().contains(selected)) {
            throw new DuplicatedException(this);
        }
        listModel.getElements().add(selected);

        jListT.setModel(new RestManagerListModel<>(listModel.getElements()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JComboBox<T> jComboBoxT;
    private javax.swing.JList<T> jListT;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
