/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.utils;

import com.jobits.pos.main.Application;
import com.jobits.pos.ui.View;
import com.root101.swing.material.standards.MaterialColors;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Jorge
 */
public class PopUpDialog extends javax.swing.JDialog {

    private static PopUpDialog INSTANCE = null;
    private JFrame parentFrame;

    /**
     * Creates new form PopUpDialog
     *
     * @param parent
     * @param modal
     * @param contentPane
     */
    private PopUpDialog(JFrame parent, Component contentPane) {
        super(parent, true);
        initComponents();
        this.parentFrame = parent;
        parentFrame.setEnabled(false);
        addWindowListener(new WindowAdapter() {//TODO: Esto no va aqui. esto tiene que ir en el mainwindows pero no se como hacerlo. o no pincha lo que estoy haciendo
            @Override
            public void windowClosed(WindowEvent e) {
                parentFrame.setEnabled(true);
                super.windowClosed(e);
                parentFrame.requestFocus();
            }

        });
        contentPane.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e);
                setSize(contentPane.getSize());
                setLocationRelativeTo(null);
            }

        });
        setLayout(new BorderLayout());
        setSize(contentPane.getSize());
        this.setBackground(MaterialColors.TRANSPARENT);
        setMaximumSize(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize());
        add(contentPane, BorderLayout.CENTER);
        pack();
        setLocationRelativeTo(null);
    }

//    public static void showPopUP(JFrame parent, boolean modal, JPanel contentPane) {
//        if (INSTANCE != null) {
//            INSTANCE.dispose();
//        }
//        INSTANCE = new PopUpDialog(parent, modal, contentPane);
//        INSTANCE.setVisible(true);
//    }
    public static void showPopUP(View contentPane) {
        if (INSTANCE != null) {
            if (INSTANCE.isVisible()) {
                INSTANCE.dispose();
            }
        }
        INSTANCE = new PopUpDialog(Application.getInstance().getMainWindow(), contentPane.getViewComponent());
        INSTANCE.setVisible(true);
    }

    public static void disposeCurrentDisplayingPopUp() {
        if (INSTANCE != null) {
            INSTANCE.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
