/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.clientes.containers;

import com.jobits.pos.cliente.core.domain.ClienteDomain;
import com.jobits.pos.cliente.core.usecase.ClienteUseCase;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.clientes.ClientesDetailView;
import com.jobits.pos.ui.clientes.ClientesListView;
import com.jobits.pos.ui.clientes.presenter.ClientesDetailViewPresenter;
import com.jobits.pos.ui.clientes.presenter.ClientesListViewPresenter;
import com.jobits.pos.ui.module.PosDesktopUiModule;
import com.jobits.pos.ui.utils.ComponentMover;
import com.jobits.ui.components.MaterialComponentsFactory;
import com.root101.swing.material.standards.MaterialIcons;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Home
 */
public class ClienteViewContainer extends javax.swing.JDialog {

    ClienteUseCase service = PosDesktopUiModule.getInstance().getImplementation(ClienteUseCase.class);
    ClientesListView listView;
    ClientesDetailView detailView;
    ClienteDomain ret = null;

    /**
     * Creates new form ClienteSelectorView
     */
    public ClienteViewContainer() {
        super();
        setModal(true);
        init();
    }

    public void init() {
        setUndecorated(true);
        setBackground(DefaultValues.TRANSPARENT);
        initComponents();
        intitUI();
        wireUp();
        setLocationRelativeTo(null);
        ComponentMover cr = new ComponentMover(this, jPanel1);
    }

    public ClienteDomain showView() {
        this.setVisible(true);
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanelMain = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelList = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelListMain = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelListButtons = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonEditar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonNuevo = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonSeleccionar = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelDetail = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelDetailMain = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelDetailtButtons = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonAtras = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonCrearEditar = MaterialComponentsFactory.Buttons.getOutlinedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelMain.setLayout(new java.awt.CardLayout());

        jPanelList.setLayout(new java.awt.BorderLayout());

        jPanelListMain.setLayout(new java.awt.BorderLayout());
        jPanelList.add(jPanelListMain, java.awt.BorderLayout.CENTER);

        jPanelListButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButtonCancelar.setIcon(MaterialIcons.CANCEL);
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelListButtons.add(jButtonCancelar);

        jButtonEditar.setIcon(MaterialIcons.EDIT);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelListButtons.add(jButtonEditar);

        jButtonNuevo.setIcon(MaterialIcons.ADD_CIRCLE);
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelListButtons.add(jButtonNuevo);

        jButtonSeleccionar.setIcon(MaterialIcons.CHECK_BOX);
        jButtonSeleccionar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelListButtons.add(jButtonSeleccionar);

        jPanelList.add(jPanelListButtons, java.awt.BorderLayout.SOUTH);

        jPanelMain.add(jPanelList, "List");

        jPanelDetail.setLayout(new java.awt.BorderLayout());

        jPanelDetailMain.setLayout(new java.awt.BorderLayout());
        jPanelDetail.add(jPanelDetailMain, java.awt.BorderLayout.CENTER);

        jPanelDetailtButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButtonAtras.setIcon(MaterialIcons.ARROW_BACK);
        jButtonAtras.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelDetailtButtons.add(jButtonAtras);

        jButtonCrearEditar.setIcon(MaterialIcons.EDIT);
        jButtonCrearEditar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelDetailtButtons.add(jButtonCrearEditar);

        jPanelDetail.add(jPanelDetailtButtons, java.awt.BorderLayout.SOUTH);

        jPanelMain.add(jPanelDetail, "Detail");

        jPanel1.add(jPanelMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrearEditar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPanel jPanelDetailMain;
    private javax.swing.JPanel jPanelDetailtButtons;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelListButtons;
    private javax.swing.JPanel jPanelListMain;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables

    private void initList() {
        listView.setPresenter(new ClientesListViewPresenter());
        showList();
    }

    private void initDetailCreate() {
        detailView = new ClientesDetailView(new ClientesDetailViewPresenter(null));
        detailView.getjPanelOpciones().setVisible(false);
        jPanelDetailMain.removeAll();
        jPanelDetailMain.add(detailView, BorderLayout.CENTER);
        jButtonCrearEditar.setIcon(MaterialIcons.ADD_CIRCLE);
        showDetail();
    }

    private void initDetailEdit() {
        ClienteDomain cliente = listView.getPresenter().getBean().getElemento_seleccionado();
        if (cliente == null) {
            throw new IllegalArgumentException("Seleccione un cliente");
        }
        detailView = new ClientesDetailView(new ClientesDetailViewPresenter(cliente));
        detailView.getjPanelOpciones().setVisible(false);
        jPanelDetailMain.removeAll();
        jPanelDetailMain.add(detailView, BorderLayout.CENTER);
        jButtonCrearEditar.setIcon(MaterialIcons.EDIT);
        showDetail();
    }

    private void showList() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "List");
    }

    private void showDetail() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Detail");
    }

    private void selectValue() {
        ret = listView.getPresenter().getBean().getElemento_seleccionado();
        if (ret == null) {
            throw new IllegalArgumentException("Seleccione un cliente");
        }
        dispose();
    }

    private void intitUI() {
        listView = new ClientesListView(new ClientesListViewPresenter());
        listView.getjPanelControles().setVisible(false);
        MouseListener[] list = listView.getjTableList().getMouseListeners();
        for (int i = 2; i < list.length; i++) {
            listView.getjTableList().removeMouseListener(list[i]);
        }
        listView.getjTableList().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    selectValue();
                }
            }
        });
        jPanelListMain.add(listView, BorderLayout.CENTER);
    }

    private void wireUp() {
        jButtonAtras.addActionListener((ActionEvent e) -> {
            initList();
        });
        jButtonCancelar.addActionListener((ActionEvent e) -> {
            dispose();
        });
        jButtonCrearEditar.addActionListener((ActionEvent e) -> {
            detailView.getPresenter().onAgregarClick();
            initList();
        });
        jButtonEditar.addActionListener((ActionEvent e) -> {
            initDetailEdit();
        });
        jButtonNuevo.addActionListener((ActionEvent e) -> {
            initDetailCreate();
        });
        jButtonSeleccionar.addActionListener((ActionEvent e) -> {
            selectValue();
        });

    }

}
