/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.clientes.containers;

import com.jobits.pos.cliente.core.domain.ClienteDomain;
import com.jobits.pos.cliente.core.domain.DireccionEnvioDomain;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.clientes.DireccionEnvioDetailView;
import com.jobits.pos.ui.clientes.presenter.DireccionEnvioDetailViewPresenter;
import com.jobits.pos.ui.utils.ComponentMover;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;

/**
 *
 * @author Home
 */
public class DireccionEnvioDetailContainer extends javax.swing.JDialog {

    DireccionEnvioDetailView detailView;
    ClienteDomain cliente;
    DireccionEnvioDomain ret;

    /**
     * Creates new form ClienteSelectorView
     *
     * @param cliente
     */
    public DireccionEnvioDetailContainer(ClienteDomain cliente) {
        super();
        this.cliente = cliente;
        setModal(true);
        init();
    }

    public void init() {
        setUndecorated(true);
        setBackground(DefaultValues.TRANSPARENT);
        initComponents();
        intitUI();
        wireUp();
        setLocationRelativeTo(null);
        ComponentMover cr = new ComponentMover(this, jPanelList);
    }

    public DireccionEnvioDomain showView() {
        this.setVisible(true);
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelList = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanelListMain = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelOpciones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getAcceptButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelList.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanelList.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanelList.setLayout(new java.awt.BorderLayout());

        jPanelListMain.setLayout(new java.awt.BorderLayout());
        jPanelList.add(jPanelListMain, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(239, 70));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanelOpciones.setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonCancelar.setText(bundle.getString("label_cancelar")); // NOI18N
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelOpciones.add(jButtonCancelar, new java.awt.GridBagConstraints());

        jButtonAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAceptar.setMnemonic('c');
        jButtonAceptar.setText(bundle.getString("label_crear_producto")); // NOI18N
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelOpciones.add(jButtonAceptar, new java.awt.GridBagConstraints());

        jPanelList.add(jPanelOpciones, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelList, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JPanel jPanelList;
    private javax.swing.JPanel jPanelListMain;
    private javax.swing.JPanel jPanelOpciones;
    // End of variables declaration//GEN-END:variables

    private void selectValue() {
        ret = detailView.getPresenter().onAceptarClick();
        if (ret != null) {
            dispose();
        }
    }

    private void intitUI() {
        detailView = new DireccionEnvioDetailView(new DireccionEnvioDetailViewPresenter(cliente));
        detailView.getjPanelBotones().setVisible(false);
        jPanelListMain.add(detailView, BorderLayout.CENTER);
    }

    private void wireUp() {
        jButtonCancelar.addActionListener((ActionEvent e) -> {
            dispose();
        });
        jButtonAceptar.addActionListener((ActionEvent e) -> {
            selectValue();
        });

    }

}
