/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.reportes;

import com.jgoodies.binding.adapter.Bindings;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import static com.jobits.pos.ui.reportes.presenter.ReportarBugViewModel.*;
import static com.jobits.pos.ui.reportes.presenter.ReportarBugViewPresenter.*;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.util.ResourceBundle;

/**
 *
 * @author Home
 */
public class ReportarBugView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Reportar Bug";

    /**
     * Creates new form ReportarBugView
     *
     * @param presenter
     */
    public ReportarBugView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldTitulo = MaterialComponentsFactory.Input.getTextField("", ResourceBundle.getBundle("Strings").getString("label_titulo_reporte"));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButtonCerrar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonReportar = MaterialComponentsFactory.Buttons.getMaterialButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Reportar Bug"));
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha");
        jPanel4.add(jLabelFecha);

        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText("Usuario");
        jPanel4.add(jLabelUsuario);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextFieldTitulo.setPreferredSize(new java.awt.Dimension(14, 60));
        jPanel2.add(jTextFieldTitulo, java.awt.BorderLayout.NORTH);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescripcion);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jButtonCerrar.setText("Cerrar");
        jPanel3.add(jButtonCerrar);

        jButtonReportar.setText("Reportar");
        jButtonReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonReportar);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportarActionPerformed
        jTextFieldTitulo.requestFocusInWindow();
    }//GEN-LAST:event_jButtonReportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonReportar;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jLabelFecha, getPresenter().getModel(PROP_FECHA));
        Bindings.bind(jLabelUsuario, getPresenter().getModel(PROP_USUARIO_LOGGEADO));
        Bindings.bind(jTextFieldTitulo, getPresenter().getModel(PROP_TITULO_REPORTE));
        Bindings.bind(jTextAreaDescripcion, getPresenter().getModel(PROP_DESCRIPCION_REPORTE));

        jButtonReportar.setAction(getPresenter().getOperation(ACTION_REPORTAR));
        jButtonCerrar.setAction(getPresenter().getOperation(ACTION_CERRAR));

    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }
}
