/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jobits.pos.core.domain.models.Orden;
import com.jobits.pos.core.domain.models.ProductovOrden;
import com.jobits.pos.utils.utils;
import java.awt.Color;

/**
 *
 * @author Jorge
 */
public class CellRenderOrden extends javax.swing.JPanel implements Comparable<CellRenderOrden> {

    /**
     * Creates new form CellRenderPedido
     */
    private Orden o;

    public CellRenderOrden(Orden o, boolean selected) {
        initComponents();
        this.o = o;
        if (o.getMesacodMesa() != null) {
            jLabelCodMesa.setText(o.getMesacodMesa().getCodMesa());
            if (o.getMesacodMesa().getNombre() == null) {
                jLabelNombreMesa.setVisible(false);
            }
            if (selected) {
                jLabelNombreMesa.setForeground(Color.white);
            }
            jLabelNombreMesa.setText(o.getMesacodMesa().getNombre());
        }
        jLabelPrecio.setText(utils.setDosLugaresDecimales(o.getOrdenvalorMonetario()));
        jLabelOrden.setText(o.getCodOrden());
        jLabelGratis.setVisible(o.getDeLaCasa());
        jLabelPorciento.setVisible(o.getPorciento() != 0);
        jLabelTerminada.setVisible(o.getHoraTerminada() != null);
        setOpaque(selected);
    }

    @Override
    public int compareTo(CellRenderOrden instance) {
        return o.compareTo(instance.getOrden());
    }

    public Orden getOrden() {
        return o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelNombreMesa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCodMesa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPorciento = new javax.swing.JLabel();
        jLabelGratis = new javax.swing.JLabel();
        jLabelOrden = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelTerminada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLabelNombreMesa.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelNombreMesa.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNombreMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreMesa.setText("<NombreMesa>");
        add(jLabelNombreMesa, java.awt.BorderLayout.NORTH);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabelCodMesa.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabelCodMesa.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodMesa.setText("<CodMesa>");
        jPanel1.add(jLabelCodMesa);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabelPorciento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPorciento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-percentage.png"))); // NOI18N
        jLabelPorciento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabelPorciento, gridBagConstraints);

        jLabelGratis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGratis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-gratis-negro.png"))); // NOI18N
        jLabelGratis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        jPanel2.add(jLabelGratis, gridBagConstraints);

        jPanel1.add(jPanel2);

        jLabelOrden.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelOrden.setForeground(new java.awt.Color(153, 0, 153));
        jLabelOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOrden.setText("<O-145567>");
        jPanel1.add(jLabelOrden);

        jLabelPrecio.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 102, 51));
        jLabelPrecio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPrecio.setText("1200 MN");
        jPanel1.add(jLabelPrecio);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabelTerminada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTerminada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-checkmark.png"))); // NOI18N
        jLabelTerminada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabelTerminada, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCodMesa;
    private javax.swing.JLabel jLabelGratis;
    private javax.swing.JLabel jLabelNombreMesa;
    private javax.swing.JLabel jLabelOrden;
    private javax.swing.JLabel jLabelPorciento;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTerminada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
