/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jobits.pos.domain.models.ProductovOrden;
import com.jobits.pos.ui.utils.utils;
import java.awt.Dimension;

/**
 *
 * @author Jorge
 */
public class CellRenderPedido extends javax.swing.JPanel {

    /**
     * Creates new form CellRenderPedido
     */
    public CellRenderPedido(ProductovOrden o, boolean selected) {
        initComponents();
        if (o.getAgregadoA() != null) {
            jLabelProducto.setFont(jLabelProducto.getFont().deriveFont(10));
            jLabelAgrego.setFont(jLabelProducto.getFont().deriveFont(10));
        }
        jLabelAgrego.setVisible(o.getAgregadoA() != null);
        jLabelAgrego1.setVisible(o.getAgregadoA() != null);
//        jLabelProducto.setText(o.getNombreProductoVendido());
        int rows = (int) Math.ceil(o.getNombreProductoVendido().length() / 20);
        System.out.println(rows);
        jTextAreaProducto.setRows(rows);
        if (rows > 1) {
            int heigth = (rows * 11) + 50;
            setPreferredSize(new Dimension(254, heigth));
        }
        jTextAreaProducto.setText(o.getNombreProductoVendido());
        jLabelCantidad.setText("x" + o.getCantidad());
        jLabelCantidadEnviada.setVisible(false);
        if (o.getCantidad() > o.getEnviadosacocina()) {
            jLabelCantidadEnviada.setVisible(true);
            jLabelCantidadEnviada.setText("x" + (o.getCantidad() - o.getEnviadosacocina()));
        }
        jLabelPrecio.setText(utils.setDosLugaresDecimales(o.getCantidad() * o.getPrecioVendido()));
        setOpaque(selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelProducto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelAgrego = new javax.swing.JLabel();
        jTextAreaProducto = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelAgrego1 = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelCantidadEnviada = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();

        jLabelProducto.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabelProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProducto.setText("<Producto>");

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5));
        setMinimumSize(new java.awt.Dimension(122, 50));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(254, 50));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelAgrego.setForeground(new java.awt.Color(0, 153, 204));
        jLabelAgrego.setText("-->");
        jLabelAgrego.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        jPanel2.add(jLabelAgrego, java.awt.BorderLayout.WEST);

        jTextAreaProducto.setEditable(false);
        jTextAreaProducto.setColumns(20);
        jTextAreaProducto.setLineWrap(true);
        jTextAreaProducto.setRows(2);
        jTextAreaProducto.setText("qwertyuiopasdfghjklz");
        jTextAreaProducto.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 25));
        jTextAreaProducto.setMinimumSize(new java.awt.Dimension(4, 10));
        jTextAreaProducto.setOpaque(false);
        jPanel2.add(jTextAreaProducto, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelAgrego1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgrego1.setText("     ");
        jLabelAgrego1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 3));
        jPanel1.add(jLabelAgrego1);

        jLabelCantidad.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(153, 0, 153));
        jLabelCantidad.setText("x3");
        jLabelCantidad.setToolTipText("total");
        jPanel1.add(jLabelCantidad);

        jLabelCantidadEnviada.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelCantidadEnviada.setForeground(new java.awt.Color(255, 102, 102));
        jLabelCantidadEnviada.setText("x3");
        jLabelCantidadEnviada.setToolTipText("por enviar");
        jPanel1.add(jLabelCantidadEnviada);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabelPrecio.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 102, 51));
        jLabelPrecio.setText("1200 MN");
        jPanel3.add(jLabelPrecio, java.awt.BorderLayout.EAST);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgrego;
    private javax.swing.JLabel jLabelAgrego1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCantidadEnviada;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea jTextAreaProducto;
    // End of variables declaration//GEN-END:variables
}
