/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jobits.pos.domain.models.Orden;
import com.jobits.pos.domain.models.ProductovOrden;
import com.jobits.pos.ui.utils.utils;

/**
 *
 * @author Jorge
 */
public class CellRenderOrden extends javax.swing.JPanel implements Comparable<CellRenderOrden> {

    /**
     * Creates new form CellRenderPedido
     */
    private Orden o;

    public CellRenderOrden(Orden o, boolean selected) {
        initComponents();
        this.o = o;
        jLabelMesa.setText(o.getMesacodMesa().getCodMesa());
        jLabelPrecio.setText(utils.setDosLugaresDecimales(o.getOrdenvalorMonetario()));
        jLabelOrden.setText(o.getCodOrden());
        jLabelGratis.setVisible(o.getDeLaCasa());
        jLabelPorciento.setVisible(o.getPorciento() != 0);
        jLabelTerminada.setVisible(o.getHoraTerminada() != null);
        setOpaque(selected);
    }

    @Override
    public int compareTo(CellRenderOrden instance) {
        return o.compareTo(instance.getOrden());
    }

    public Orden getOrden() {
        return o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTerminada = new javax.swing.JLabel();
        jLabelPorciento = new javax.swing.JLabel();
        jLabelGratis = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelMesa = new javax.swing.JLabel();
        jLabelOrden = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabelTerminada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTerminada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-checkmark.png"))); // NOI18N
        jLabelTerminada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(jLabelTerminada, gridBagConstraints);

        jLabelPorciento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPorciento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-percentage.png"))); // NOI18N
        jLabelPorciento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        add(jLabelPorciento, gridBagConstraints);

        jLabelGratis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGratis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-gratis-negro.png"))); // NOI18N
        jLabelGratis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        add(jLabelGratis, gridBagConstraints);

        jLabelPrecio.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(0, 102, 51));
        jLabelPrecio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPrecio.setText("1200 MN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        add(jLabelPrecio, gridBagConstraints);

        jLabelMesa.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabelMesa.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa.setText("<CodMesa>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabelMesa, gridBagConstraints);

        jLabelOrden.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelOrden.setForeground(new java.awt.Color(153, 0, 153));
        jLabelOrden.setText("<O-145567>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(jLabelOrden, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelGratis;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelOrden;
    private javax.swing.JLabel jLabelPorciento;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTerminada;
    // End of variables declaration//GEN-END:variables
}
