/*
     * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.ui.utils.RestManagerCellRender;
import javax.swing.event.ListSelectionEvent;
import com.jobits.pos.core.domain.models.ProductoVenta;
import com.jobits.pos.core.domain.models.ProductovOrden;
import com.jobits.pos.core.domain.models.Seccion;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.AddFromPanel;
import com.jobits.pos.ui.swing.utils.BindableTableModel;
import com.jobits.pos.utils.utils;
import com.jobits.pos.ui.venta.orden.presenter.OrdenDetailViewModel;
import com.jobits.pos.ui.venta.orden.presenter.OrdenDetailViewPresenter;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Jorge
 */
public class OrdenDetailFragmentView extends AbstractViewPanel {

    private static boolean showMenu = true;
    private AddFromPanel<ProductovOrden, ProductoVenta> crossReferencePanel;
    public static final String VIEW_NAME = "Detalles de orden";

    public OrdenDetailFragmentView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelroot = new javax.swing.JPanel();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelCrossReference = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jideButtonImpimirTicket = new javax.swing.JButton();
        jideButtonAgregarNota = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jideButtonEnviarCocina = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jideButtonCerrarMesa = MaterialComponentsFactory.Buttons.getMaterialButton();
        jToggleButtonGratis = new javax.swing.JToggleButton();
        jSpinnerPorciento = new javax.swing.JSpinner();
        jPanelInfo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelVALORFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelVALORHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelVALORUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelVALORMesa = new javax.swing.JLabel();
        jLabelVALORNOORDEN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVALORTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSecciones = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelroot.setBackground(new java.awt.Color(0, 204, 204));
        jPanelroot.setMinimumSize(new java.awt.Dimension(300, 370));
        jPanelroot.setOpaque(false);
        jPanelroot.setPreferredSize(new java.awt.Dimension(300, 570));
        jPanelroot.setLayout(new java.awt.BorderLayout());

        jPanelDetalles.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetalles.setLayout(new java.awt.BorderLayout());

        jPanelCrossReference.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        jPanelCrossReference.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Controles"));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jToggleButton1.setFont(jToggleButton1.getFont());
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/vista_menu.png"))); // NOI18N
        jToggleButton1.setSelected(true);
        jToggleButton1.setToolTipText("Agregar");
        jToggleButton1.setMaximumSize(new java.awt.Dimension(40, 30));
        jPanel5.add(jToggleButton1);

        jideButtonImpimirTicket.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonImpimirTicket.setFont(jideButtonImpimirTicket.getFont());
        jideButtonImpimirTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/impresora.png"))); // NOI18N
        jideButtonImpimirTicket.setToolTipText("Imprimir Ticket");
        jideButtonImpimirTicket.setBorderPainted(false);
        jideButtonImpimirTicket.setFocusable(false);
        jPanel5.add(jideButtonImpimirTicket);

        jideButtonAgregarNota.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonAgregarNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-note.png"))); // NOI18N
        jideButtonAgregarNota.setToolTipText("Agregar Nota");
        jideButtonAgregarNota.setBorderPainted(false);
        jideButtonAgregarNota.setFocusable(false);
        jPanel5.add(jideButtonAgregarNota);

        jideButtonEnviarCocina.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonEnviarCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-notification.png"))); // NOI18N
        jideButtonEnviarCocina.setToolTipText("Enviar a cocina");
        jideButtonEnviarCocina.setBorderPainted(false);
        jideButtonEnviarCocina.setFocusable(false);
        jPanel5.add(jideButtonEnviarCocina);

        jideButtonCerrarMesa.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonCerrarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-money.png"))); // NOI18N
        jideButtonCerrarMesa.setToolTipText("Cobrar orden");
        jideButtonCerrarMesa.setBorderPainted(false);
        jideButtonCerrarMesa.setFocusable(false);
        jPanel5.add(jideButtonCerrarMesa);

        jToggleButtonGratis.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButtonGratis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-gratis-negro.png"))); // NOI18N
        jToggleButtonGratis.setToolTipText("De la casa");
        jToggleButtonGratis.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/icons8-gratis.png"))); // NOI18N
        jPanel5.add(jToggleButtonGratis);

        jSpinnerPorciento.setFont(jSpinnerPorciento.getFont());
        jSpinnerPorciento.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(-100.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinnerPorciento.setToolTipText("Pociento por servicio");
        jSpinnerPorciento.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel5.add(jSpinnerPorciento);

        jPanelCrossReference.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanelInfo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelInfo.setOpaque(false);
        jPanelInfo.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jLabel3.setText(bundle.getString("label_fecha")); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabelVALORFecha.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORFecha.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelVALORFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORFecha.setText("dd/mm/yy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel4.add(jLabelVALORFecha, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText(bundle.getString("label_hora")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabelVALORHora.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORHora.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelVALORHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORHora.setText("hh:mm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel4.add(jLabelVALORHora, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(bundle.getString("label_dependiente")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabelVALORUsuario.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORUsuario.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelVALORUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORUsuario.setText("Nombre Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel4.add(jLabelVALORUsuario, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font(".SF NS Text", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText(bundle.getString("label_mesa")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabelVALORMesa.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORMesa.setFont(new java.awt.Font(".SF NS Text", 0, 12)); // NOI18N
        jLabelVALORMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORMesa.setText("M-xx");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        jPanel4.add(jLabelVALORMesa, gridBagConstraints);

        jLabelVALORNOORDEN.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabelVALORNOORDEN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelVALORNOORDEN.setText("No: 5534");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabelVALORNOORDEN, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+5));
        jLabel2.setText("Total: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabelVALORTotal.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORTotal.setFont(jLabelVALORTotal.getFont().deriveFont(jLabelVALORTotal.getFont().getStyle() | java.awt.Font.BOLD, jLabelVALORTotal.getFont().getSize()+5));
        jLabelVALORTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVALORTotal.setText("0.00 CUC");
        jLabelVALORTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jLabelVALORTotal, gridBagConstraints);

        jPanelInfo.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanelCrossReference.add(jPanelInfo, java.awt.BorderLayout.PAGE_START);

        jPanelDetalles.add(jPanelCrossReference, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), "Selección de productos"));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 130));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jListSecciones.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jListSecciones.setForeground(new java.awt.Color(0, 102, 102));
        jListSecciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListSecciones);

        jPanel3.add(jScrollPane3);

        jListProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jListProductos.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jListProductos.setForeground(new java.awt.Color(0, 102, 102));
        jListProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListProductos);

        jPanel3.add(jScrollPane4);

        jPanelDetalles.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanelroot.add(jPanelDetalles, java.awt.BorderLayout.CENTER);

        add(jPanelroot, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelVALORFecha;
    private javax.swing.JLabel jLabelVALORHora;
    private javax.swing.JLabel jLabelVALORMesa;
    private javax.swing.JLabel jLabelVALORNOORDEN;
    private javax.swing.JLabel jLabelVALORTotal;
    private javax.swing.JLabel jLabelVALORUsuario;
    private javax.swing.JList<Seccion> jListProductos;
    private javax.swing.JList<Seccion> jListSecciones;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCrossReference;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelroot;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerPorciento;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButtonGratis;
    private javax.swing.JButton jideButtonAgregarNota;
    private javax.swing.JButton jideButtonCerrarMesa;
    private javax.swing.JButton jideButtonEnviarCocina;
    private javax.swing.JButton jideButtonImpimirTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {

        Bindings.bind(jLabelVALORFecha, getPresenter().getModel(OrdenDetailViewModel.PROP_FECHA_ORDEN));
        Bindings.bind(jLabelVALORHora, getPresenter().getModel(OrdenDetailViewModel.PROP_HORA_PEDIDO));
        Bindings.bind(jLabelVALORNOORDEN, getPresenter().getModel(OrdenDetailViewModel.PROP_ID_ORDEN));
        Bindings.bind(jLabelVALORTotal, getPresenter().getModel(OrdenDetailViewModel.PROP_TOTAL_ORDEN));
        Bindings.bind(jLabelVALORUsuario, getPresenter().getModel(OrdenDetailViewModel.PROP_USUARIO));
        Bindings.bind(jLabelVALORMesa, getPresenter().getModel(OrdenDetailViewModel.PROP_MESA_PEDIDO));

        Bindings.bind(jListSecciones, new SelectionInList<Seccion>(
                getPresenter().getModel(OrdenDetailViewModel.PROP_LISTA_SECCIONES),
                getPresenter().getModel(OrdenDetailViewModel.PROP_SECCION_SELECCIONADA)));

        Bindings.bind(jListProductos, new SelectionInList<ProductoVenta>(
                getPresenter().getModel(OrdenDetailViewModel.PROP_LISTA_PRODUCTO_VENTA_SECCION),
                getPresenter().getModel(OrdenDetailViewModel.PROP_PRODUCTO_VENTA_SELECCIONADO)));
        jListProductos.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (e.getValueIsAdjusting()) {
                return;
            }
            if (jListProductos.getSelectedIndex() == -1) {
                return;
            }
            getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_ADD_PRODUCTO);
        });

        jideButtonAgregarNota.addActionListener(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_ADD_NOTA));
        jideButtonCerrarMesa.addActionListener(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_CERRAR_ORDEN));
        jideButtonEnviarCocina.addActionListener(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_ENVIAR_ELABORAR));
        jideButtonImpimirTicket.addActionListener(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_IMPRIMIR_CIERRE_PARCIAL));

        Bindings.bind(jSpinnerPorciento, "value", getPresenter().getModel(OrdenDetailViewModel.PROP_PORCIENTO_SERVICIO));
        Bindings.bind(jToggleButtonGratis, "selected",getPresenter().getModel(OrdenDetailViewModel.PROP_ES_AUTORIZO));

    }

    @Override
    public void uiInit() {
        initComponents();
        initAddFromPanel();
        jPanel3.setVisible(showMenu);
        crossReferencePanel.getJTextFieldAutoComplete().requestFocus();
        jListSecciones.setVisibleRowCount(12);
        jToggleButton1.addChangeListener((ChangeEvent e) -> {
            showMenu = jToggleButton1.isSelected();
            jPanel3.setVisible(showMenu);
        });

    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void initAddFromPanel() {

        AddFromPanel.AddFromPanelBuilder<ProductovOrden, ProductoVenta> builder = AddFromPanel.builder();
        builder.jTextFieldDataName("Productos de venta");
        builder.addAction(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_ADD_PRODUCTO));
        builder.autoCompletitionData(getPresenter().getModel(OrdenDetailViewModel.PROP_LISTA_PRODUCTOS_VENTA));
        builder.autoCOmpletitionDataSelection(getPresenter().getModel(OrdenDetailViewModel.PROP_PRODUCTO_VENTA_SELECCIONADO));
        builder.removeAction(getPresenter().getOperation(OrdenDetailViewPresenter.ACTION_REMOVE_PRODUCTO));
        builder.tableDataHolder(getPresenter().getModel(OrdenDetailViewModel.PROP_LISTA_PRODUCTO_ORDEN));
        builder.tableSelectionDataHolder(getPresenter().getModel(OrdenDetailViewModel.PROP_PRODUCTO_ORDEN_SELECCIONADO));
        builder.tableModel(new BindableTableModel<ProductovOrden>() {
            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return getRow(rowIndex).getProductoVenta().getNombre();
                    case 1:
                        return getRow(rowIndex).getCantidad();
                    case 2:
                        return utils.redondeoPorExceso(getRow(rowIndex).getCantidad()
                                * getRow(rowIndex).getPrecioVendido());
                    default:
                        return null;
                }
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Nombre Producto";
                    case 1:
                        return "Cantidad";
                    case 2:
                        return "Precio Final";
                    default:
                        return null;
                }
            }
        });
        crossReferencePanel = builder.build();

        jPanelCrossReference.add(crossReferencePanel,BorderLayout.CENTER);
        //crossReferencePanel.getJTableCrossReference().getColumnModel().getColumn(1).setCellRenderer(new RestManagerCellRender());

    }

}
