/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.SpinnerToValueModelConnector;
import com.jgoodies.binding.list.SelectionInList;
import com.jgoodies.binding.value.ValueModel;
import com.jobits.ui.components.MaterialComponentsFactory;
import com.jobits.ui.components.swing.containers.TaskButton;
import java.awt.Component;
import javax.swing.Action;
import javax.swing.JLabel;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.ProductoVenta;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import com.jobits.pos.domain.models.ProductovOrden;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.CellRenderPedido;
import static com.jobits.pos.ui.venta.orden.presenter.OrdenDetailViewModel.*;
import static com.jobits.pos.ui.venta.orden.presenter.OrdenDetailViewPresenter.*;
import static com.jobits.pos.ui.venta.orden.presenter.ProductoVentaSelectorViewModel.PROP_PV_FILTRADO;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Home
 */
public class PedidoCardView extends AbstractViewPanel {

    String imageURL, title, secondaryText, mediaURL, supportText;
    Action mainButtonAction, secundaryButtonAction;
    ValueModel valueModelTitle, valueModelSecundaryText;
    List<Action> menuActionsList = new ArrayList<>();

    public PedidoCardView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Main = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelEstado = new javax.swing.JPanel();
        jLabelTest = new javax.swing.JLabel();
        jToggleButtonAutorizo = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelOrdenNo = MaterialComponentsFactory.Displayers.getH3Label();
        jLabelMesa = MaterialComponentsFactory.Displayers.getLabel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelTerminada = new javax.swing.JLabel();
        jToggleButtonExpand = new javax.swing.JToggleButton();
        jPanelMedia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>()
        ;
        jPanel1 = new javax.swing.JPanel();
        jButton1 = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButton2 = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButton3 = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButton4 = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelSupportText = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jideButtonCierreParcial = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jideButtonEnviarCocina = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jideButtonCerrarMesa = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelVALORHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelVALORUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanelActionButtons = new javax.swing.JPanel();
        jLabelVALORTotal = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        setToolTipText(null);
        setMaximumSize(new java.awt.Dimension(32773, 500));
        setMinimumSize(new java.awt.Dimension(300, 500));
        setPreferredSize(new java.awt.Dimension(300, 650));
        setLayout(new java.awt.BorderLayout());

        Main.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        Main.setLayout(new javax.swing.BoxLayout(Main, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, DefaultValues.SECONDARY_COLOR));
        jPanelHeader.setToolTipText(null);
        jPanelHeader.setMaximumSize(new java.awt.Dimension(400, 80));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(20, 80));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jPanelEstado.setToolTipText(null);
        jPanelEstado.setMaximumSize(new java.awt.Dimension(25, 200));
        jPanelEstado.setMinimumSize(new java.awt.Dimension(0, 60));
        jPanelEstado.setOpaque(false);
        jPanelEstado.setPreferredSize(new java.awt.Dimension(45, 80));
        jPanelEstado.setLayout(new java.awt.GridLayout(2, 0));

        jLabelTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/porciento_gris.png"))); // NOI18N
        jLabelTest.setIconTextGap(0);
        jLabelTest.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabelTest.setMinimumSize(new java.awt.Dimension(40, 40));
        jLabelTest.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelEstado.add(jLabelTest);

        jToggleButtonAutorizo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/billete_gris.png"))); // NOI18N
        jToggleButtonAutorizo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/billete_indigo.png"))); // NOI18N
        jPanelEstado.add(jToggleButtonAutorizo);

        jPanelHeader.add(jPanelEstado, java.awt.BorderLayout.WEST);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel2.setToolTipText(null);
        jPanel2.setMaximumSize(new java.awt.Dimension(30000, 30000));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabelOrdenNo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelOrdenNo.setText("<No Orden>");
        jLabelOrdenNo.setToolTipText(null);
        jLabelOrdenNo.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jLabelOrdenNo.setMinimumSize(new java.awt.Dimension(20, 25));
        jLabelOrdenNo.setPreferredSize(new java.awt.Dimension(20, 25));
        jPanel2.add(jLabelOrdenNo);

        jLabelMesa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelMesa.setText("<Mesa>");
        jLabelMesa.setToolTipText(null);
        jLabelMesa.setMaximumSize(new java.awt.Dimension(3000, 3000));
        jLabelMesa.setMinimumSize(new java.awt.Dimension(20, 16));
        jLabelMesa.setPreferredSize(new java.awt.Dimension(20, 16));
        jPanel2.add(jLabelMesa);

        jPanelHeader.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelMenu.setToolTipText(null);
        jPanelMenu.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanelMenu.setOpaque(false);
        jPanelMenu.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanelMenu.setLayout(new java.awt.BorderLayout());

        jLabelTerminada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTerminada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/ok_verde.png"))); // NOI18N
        jLabelTerminada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTerminada.setOpaque(true);
        jPanelMenu.add(jLabelTerminada, java.awt.BorderLayout.PAGE_START);

        jToggleButtonExpand.setIcon(MaterialIcons.EXPAND_LESS);
        jToggleButtonExpand.setSelected(true);
        jToggleButtonExpand.setBorderPainted(false);
        jToggleButtonExpand.setContentAreaFilled(false);
        jToggleButtonExpand.setEnabled(false);
        jToggleButtonExpand.setPreferredSize(new java.awt.Dimension(18, 18));
        jToggleButtonExpand.setSelectedIcon(MaterialIcons.EXPAND_LESS);
        jPanelMenu.add(jToggleButtonExpand, java.awt.BorderLayout.CENTER);

        jPanelHeader.add(jPanelMenu, java.awt.BorderLayout.EAST);

        Main.add(jPanelHeader);

        jPanelMedia.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanelMedia.setToolTipText(null);
        jPanelMedia.setMaximumSize(new java.awt.Dimension(600, 200));
        jPanelMedia.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelMedia.setPreferredSize(new java.awt.Dimension(0, 300));
        jPanelMedia.setRequestFocusEnabled(false);
        jPanelMedia.setLayout(new java.awt.BorderLayout());

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanelMedia.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(MaterialIcons.ADD_CIRCLE);
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton1);

        jButton2.setIcon(MaterialIcons.REMOVE_CIRCLE);
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/agregar nota_indigo_ligth.png"))); // NOI18N
        jButton3.setToolTipText("Agregar Nota");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/informacion_indigo_ligth.png"))); // NOI18N
        jButton4.setToolTipText("Ver Detalles");
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton4);

        jPanelMedia.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        Main.add(jPanelMedia);

        jPanelSupportText.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 5, 3));
        jPanelSupportText.setToolTipText(null);
        jPanelSupportText.setMinimumSize(new java.awt.Dimension(0, 50));
        jPanelSupportText.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanelSupportText.setLayout(new java.awt.BorderLayout());

        jideButtonCierreParcial.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonCierreParcial.setIcon(MaterialIcons.PRINT);
        jideButtonCierreParcial.setToolTipText("Cierre Parcial");
        jideButtonCierreParcial.setBorderPainted(false);
        jideButtonCierreParcial.setFocusable(false);
        jideButtonCierreParcial.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jideButtonCierreParcial);

        jideButtonEnviarCocina.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonEnviarCocina.setIcon(MaterialIcons.NOTIFICATIONS);
        jideButtonEnviarCocina.setToolTipText("Enviar a cocina");
        jideButtonEnviarCocina.setBorderPainted(false);
        jideButtonEnviarCocina.setFocusable(false);
        jideButtonEnviarCocina.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jideButtonEnviarCocina);

        jideButtonCerrarMesa.setBackground(new java.awt.Color(204, 204, 204));
        jideButtonCerrarMesa.setIcon(MaterialIcons.MONETIZATION_ON);
        jideButtonCerrarMesa.setToolTipText("Cobrar orden");
        jideButtonCerrarMesa.setBorderPainted(false);
        jideButtonCerrarMesa.setFocusable(false);
        jideButtonCerrarMesa.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(jideButtonCerrarMesa);

        jPanelSupportText.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jLabel7.setText(bundle.getString("label_hora")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabelVALORHora.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORHora.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabelVALORHora.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORHora.setText("hh:mm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabelVALORHora, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText(bundle.getString("label_dependiente")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabelVALORUsuario.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORUsuario.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jLabelVALORUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelVALORUsuario.setText("Nombre Apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel4.add(jLabelVALORUsuario, gridBagConstraints);

        jPanelSupportText.add(jPanel4, java.awt.BorderLayout.CENTER);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jPanel5.add(jSpinner1);

        jLabel1.setText("%");
        jPanel5.add(jLabel1);

        jPanelSupportText.add(jPanel5, java.awt.BorderLayout.SOUTH);

        Main.add(jPanelSupportText);

        jPanelActionButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanelActionButtons.setToolTipText(null);
        jPanelActionButtons.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanelActionButtons.setMinimumSize(new java.awt.Dimension(0, 25));
        jPanelActionButtons.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanelActionButtons.setLayout(new java.awt.BorderLayout());

        jLabelVALORTotal.setBackground(new java.awt.Color(153, 255, 255));
        jLabelVALORTotal.setFont(jLabelVALORTotal.getFont().deriveFont(jLabelVALORTotal.getFont().getStyle() | java.awt.Font.BOLD, jLabelVALORTotal.getFont().getSize()+5));
        jLabelVALORTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVALORTotal.setText("0.00"+R.COIN_SUFFIX);
        jLabelVALORTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total"));
        jPanelActionButtons.add(jLabelVALORTotal, java.awt.BorderLayout.CENTER);

        Main.add(jPanelActionButtons);

        add(Main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public String getTitle() {
        return title;
    }

    public String getSecondaryText() {
        return secondaryText;
    }

    public String getSupportText() {
        return supportText;
    }

    public JLabel getjLabelCardTitle() {
        return jLabelOrdenNo;
    }

    public void setSecondaryTextColor(Color color) {
        jLabelMesa.setForeground(color);
    }

    private void setMenuUI() {
        jPanelSubActions = new org.jdesktop.swingx.JXTaskPaneContainer();
        jPopupMenu1 = new javax.swing.JPopupMenu();

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jPanelSubActions.setLayout(verticalLayout1);
    }

    private org.jdesktop.swingx.JXTaskPaneContainer jPanelSubActions;
    private javax.swing.JPopupMenu jPopupMenu1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelOrdenNo;
    private javax.swing.JLabel jLabelTerminada;
    private javax.swing.JLabel jLabelTest;
    private javax.swing.JLabel jLabelVALORHora;
    private javax.swing.JLabel jLabelVALORTotal;
    private javax.swing.JLabel jLabelVALORUsuario;
    private javax.swing.JList<ProductovOrden> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelActionButtons;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMedia;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelSupportText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButtonAutorizo;
    private javax.swing.JToggleButton jToggleButtonExpand;
    private javax.swing.JButton jideButtonCerrarMesa;
    private javax.swing.JButton jideButtonCierreParcial;
    private javax.swing.JButton jideButtonEnviarCocina;
    // End of variables declaration//GEN-END:variables

    private Component addMenuItem(Action action) {
        Component c = jPanelSubActions.add(buildFromAction(action));
        jPopupMenu1.add(action);
        return c;
    }

    private Component buildFromAction(Action a) {
        return new TaskButton(a, jPanelSubActions.getWidth());
    }

    private void createPopupPanel() {
//        jPopupMenu1.show(jButtonMenu, jButtonMenu.getBounds().x - jPopupMenu1.getWidth(), jButtonMenu.getBounds().y + jButtonMenu.getHeight());
//        jPopupMenu1.show(jButtonMenu, jButtonMenu.getBounds().x - jPopupMenu1.getWidth(), jButtonMenu.getBounds().y + jButtonMenu.getHeight());
    }

    @Override
    public void wireUp() {
        Bindings.bind(jLabelOrdenNo, getPresenter().getModel(PROP_ID_ORDEN));
        Bindings.bind(jLabelMesa, getPresenter().getModel(PROP_MESA_PEDIDO));
        Bindings.bind(jLabelVALORHora, getPresenter().getModel(PROP_HORA_PEDIDO));
        Bindings.bind(jLabelVALORTotal, getPresenter().getModel(PROP_TOTAL_ORDEN));
        Bindings.bind(jLabelVALORUsuario, getPresenter().getModel(PROP_USUARIO));
//        Bindings.bind(jLabelGratis, "visible", getPresenter().getModel(PROP_ES_AUTORIZO));
//        Bindings.bind(jLabelPorciento, "visible", getPresenter().getModel(PROP_TIENE_PORCIENTO));
        Bindings.bind(jLabelTerminada, "visible", getPresenter().getModel(PROP_ORDEN_TERMINADA));

        jideButtonCerrarMesa.addActionListener(getPresenter().getOperation(ACTION_CERRAR_ORDEN));
        jideButtonEnviarCocina.addActionListener(getPresenter().getOperation(ACTION_ENVIAR_ELABORAR));
        jButton1.addActionListener(getPresenter().getOperation(ACTION_ADD_PRODUCTO));
        jButton2.addActionListener(getPresenter().getOperation(ACTION_REMOVE_PRODUCTO));
        jButton3.addActionListener(getPresenter().getOperation(ACTION_ADD_NOTA));
        jButton4.addActionListener(getPresenter().getOperation(ACTION_SHOW_LOGS));
        jideButtonCierreParcial.addActionListener(getPresenter().getOperation(ACTION_IMPRIMIR_CIERRE_PARCIAL));

//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_ADD_NOTA)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_ADD_PRODUCTO)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_REMOVE_PRODUCTO)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_SHOW_LOGS)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_IMPRIMIR_CIERRE_PARCIAL)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_SET_AUTORIZO)));
//        jPanelSubActions.add(addMenuItem(getPresenter().getOperation(ACTION_SET_PORCIENTO)));

        SpinnerToValueModelConnector connector5 = new SpinnerToValueModelConnector(jSpinner1.getModel(),
                getPresenter().getModel(PROP_PORCIENTO_SERVICIO), 0);
        Bindings.bind(jSpinner1, "value", getPresenter().getModel(PROP_PORCIENTO_SERVICIO));

        Bindings.bind(jLabelTest, "icon", getPresenter().getModel(PROP_ICONO_PORCIENTO));

        Bindings.bind(jToggleButtonAutorizo, "selected", getPresenter().getModel(PROP_ES_AUTORIZO));
        jToggleButtonAutorizo.addActionListener(getPresenter().getOperation(ACTION_SET_AUTORIZO));
        

        jToggleButtonExpand.addActionListener((ActionEvent e) -> {
            jPanelMedia.setVisible(jToggleButtonExpand.isSelected());
        });

        Bindings.bind(jList1, new SelectionInList<ProductovOrden>(
                getPresenter().getModel(PROP_LISTA_PRODUCTO_ORDEN),
                getPresenter().getModel(PROP_PRODUCTO_ORDEN_SELECCIONADO)));


    }

    @Override
    public void uiInit() {
        initComponents();
        setMenuUI();
        jList1.setCellRenderer(new ListCellRenderer<ProductovOrden>() {
            @Override
            public Component getListCellRendererComponent(JList<? extends ProductovOrden> list,
                    ProductovOrden value, int index, boolean isSelected, boolean cellHasFocus) {
                return new CellRenderPedido(value, isSelected);
            }
        });
    }

    @Override
    public String getViewName() {
        return "PedidoCard";
    }
}
