/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.ProductoVenta;
import com.jobits.pos.domain.models.Seccion;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableListIntelliHint;
import com.jobits.pos.ui.utils.utils;
import com.jobits.pos.ui.venta.orden.presenter.ProductoVentaSelectorViewModel;
import static com.jobits.pos.ui.venta.orden.presenter.ProductoVentaSelectorViewModel.*;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Jorge
 */
public class ProductoVentaSelectorView extends AbstractViewPanel {

    BindableListIntelliHint<ProductoVenta> autoCompleteModel;

    public ProductoVentaSelectorView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    @Override
    public String getViewName() {
        return "MenuListView";
    }

    @Override
    public void uiInit() {
        initComponents();
        // jListSecciones.setVisibleRowCount(5);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(80);
        jListSecciones.setCellRenderer(new ListCellRenderer<Seccion>() {
            @Override
            public Component getListCellRendererComponent(JList<? extends Seccion> list, Seccion value, int index, boolean isSelected, boolean cellHasFocus) {
                return new CellRenderLabel(value.getNombreSeccion(), null, isSelected, null);
            }
        });
        jList2.setCellRenderer(new ListCellRenderer<ProductoVenta>() {
            @Override
            public Component getListCellRendererComponent(JList<? extends ProductoVenta> list, ProductoVenta value, int index, boolean isSelected, boolean cellHasFocus) {
                return new CellRenderLabel(value.getNombre(), utils.setDosLugaresDecimales(value.getPrecioVenta()), isSelected, value.getDescripcion());
            }
        });
    }

    @Override
    public void wireUp() {
        Bindings.bind(jListSecciones, new SelectionInList<Seccion>(
                getPresenter().getModel(ProductoVentaSelectorViewModel.PROP_LISTA_ELEMENTOS),
                getPresenter().getModel(ProductoVentaSelectorViewModel.PROP_ELEMENTO_SELECCIONADO)));

        Bindings.bind(jList2, new SelectionInList<Seccion>(
                getPresenter().getModel(ProductoVentaSelectorViewModel.PROP_LISTAPRODUCTOS),
                getPresenter().getModel(ProductoVentaSelectorViewModel.PROP_PRODUCTOVENTASELECCIONADO)));

        Bindings.bind(jTextFieldSearch, getPresenter().getModel(PROP_PV_FILTRADO));
        Bindings.bind(jTextFieldSearch, "enabled", getPresenter().getModel(PROP_CAMPO_BUSQUEDA_ENABLED));

        getPresenter().addBeanPropertyChangeListener(PROP_PV_FILTRADO, (PropertyChangeEvent evt) -> {
            jList2.revalidate();
            jList2.repaint();
            jListSecciones.revalidate();
            jListSecciones.repaint();
        });
        getPresenter().addBeanPropertyChangeListener(PROP_CAMPO_BUSQUEDA_ENABLED, (PropertyChangeEvent evt) -> {
            if ((boolean) evt.getNewValue()) {
                jTextFieldSearch.requestFocusInWindow();
            }
        });
        getPresenter().addBeanPropertyChangeListener(PROP_LISTAPRODUCTOS, (PropertyChangeEvent evt) -> {
            jList2.revalidate();
            jList2.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelBusqueda = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelBuscarIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSecciones = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanelBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 200, 10, 200));
        jPanelBusqueda.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanelBusqueda.setLayout(new java.awt.BorderLayout());

        jTextFieldSearch.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSearchFocusLost(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyTyped(evt);
            }
        });
        jPanelBusqueda.add(jTextFieldSearch, java.awt.BorderLayout.CENTER);

        jLabelBuscarIcon.setIcon(MaterialIcons.SEARCH);
        jPanelBusqueda.add(jLabelBuscarIcon, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanelBusqueda, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0), "Secciones"));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 120));

        jListSecciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSecciones.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jListSecciones.setVisibleRowCount(-1);
        jScrollPane1.setViewportView(jListSecciones);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 0, 0), "Productos"));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setFocusable(false);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setFixedCellHeight(120);
        jList2.setFixedCellWidth(140);
        jList2.setFocusable(false);
        jList2.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jList2.setVisibleRowCount(-1);
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyTyped
    }//GEN-LAST:event_jTextFieldSearchKeyTyped
    private void jTextFieldSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusGained
        jTextFieldSearch.setText("");
    }//GEN-LAST:event_jTextFieldSearchFocusGained
    private void jTextFieldSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSearchFocusLost
    }//GEN-LAST:event_jTextFieldSearchFocusLost

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        jList2.clearSelection();
        jList2.revalidate();
        jList2.repaint();
    }//GEN-LAST:event_jList2ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBuscarIcon;
    private javax.swing.JList<ProductoVenta> jList2;
    private javax.swing.JList<Seccion> jListSecciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
