/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.orden;

import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.venta.orden.presenter.OrdenDetailViewPresenter;
import static com.jobits.pos.ui.venta.orden.presenter.VentaOrdenListViewPresenter.*;
import com.jobits.pos.ui.venta.orden.presenter.VentaOrdenListViewPresenter;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Jorge
 */
public class VentaListOrdenesView extends AbstractViewPanel implements ListDataListener {

    public static final String VIEW_NAME = "Lista Ordenes";

    public VentaListOrdenesView(VentaOrdenListViewPresenter ventaPresenter) {
        super(ventaPresenter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelOrdenesActivas = new javax.swing.JPanel();
        jXPanelOrdenControl = new org.jdesktop.swingx.JXPanel();
        jButtonNuevaOrden = new javax.swing.JButton();
        jButtonCalcCAmbio = new javax.swing.JButton();
        jButtonEnviarCerrarCrearNueva = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanelOrdenesActivas.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanelOrdenesActivas.setPreferredSize(new java.awt.Dimension(300, 438));
        jPanelOrdenesActivas.setLayout(new java.awt.BorderLayout());

        jXPanelOrdenControl.setBackground(new java.awt.Color(204, 204, 204));
        jXPanelOrdenControl.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jXPanelOrdenControl.setMaximumSize(new java.awt.Dimension(300, 300));
        jXPanelOrdenControl.setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonNuevaOrden.setText(bundle.getString("label_agregar")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jXPanelOrdenControl.add(jButtonNuevaOrden, gridBagConstraints);

        jButtonCalcCAmbio.setText(bundle.getString("label_calcular_cambio")); // NOI18N
        jButtonCalcCAmbio.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jXPanelOrdenControl.add(jButtonCalcCAmbio, gridBagConstraints);

        jButtonEnviarCerrarCrearNueva.setMnemonic('r');
        jButtonEnviarCerrarCrearNueva.setText("Cerrado Rapido");
        jButtonEnviarCerrarCrearNueva.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jXPanelOrdenControl.add(jButtonEnviarCerrarCrearNueva, gridBagConstraints);

        jPanelOrdenesActivas.add(jXPanelOrdenControl, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setViewportView(jPanel2);

        jPanelOrdenesActivas.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanelOrdenesActivas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcCAmbio;
    private javax.swing.JButton jButtonEnviarCerrarCrearNueva;
    private javax.swing.JButton jButtonNuevaOrden;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelOrdenesActivas;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXPanel jXPanelOrdenControl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        getPresenter().getBean().getLista_elementos().addListDataListener(this);
        jButtonNuevaOrden.addActionListener(getPresenter().getOperation(ACTION_ABRIR_ORDEN));
    }

    @Override
    public VentaOrdenListViewPresenter getPresenter() {
        return (VentaOrdenListViewPresenter) super.getPresenter(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void uiInit() {
        initComponents();
        populatePedidosPanel();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void populatePedidosPanel() {
        clearPedidosPanel();
        for (OrdenDetailViewPresenter x : getPresenter().getOrdenPresenter()) {
            PedidoCardView newView = new PedidoCardView(x);
            jPanel2.add(newView);
        }
    }

    private void clearPedidosPanel() {
        jPanel2.removeAll();
    }

    @Override
    public void intervalAdded(ListDataEvent e) {
        populatePedidosPanel();
    }

    @Override
    public void intervalRemoved(ListDataEvent e) {
        populatePedidosPanel();
    }

    @Override
    public void contentsChanged(ListDataEvent e) {
        populatePedidosPanel();
    }
}
