/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.edisoncor.gui.comboBox.ComboBoxRect;
import restManager.persistencia.Area;
import restManager.persistencia.Mesa;
import restManager.persistencia.jpa.staticContent;
import restManager.util.comun;

/**
 *
 * @author Jorge
 */
public class EsquemaSalon extends javax.swing.JDialog {

    /**
     * Creates new form EsquemaSalon
     */
    List<Mesa > mesas;
    List<Area> areas;
    
    String [] estados = {"vacia","ocupada"};
    
    public EsquemaSalon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        initDialog();
        
        setVisible(true);
    }
    
    private void initDialog() {
        comboBoxEstado.addItem(estados[0]);
        comboBoxEstado.addItem(estados[1]);
        updateAreasTable();
        updateMesasTable();        
        
    }
    
    private void updateMesasTable() {
        mesas = staticContent.mesasJPA.findMesaEntities();
        
        ArrayList [] rowdata = comun.initArray(new ArrayList[4]);
        
        
        for (Mesa mesa : mesas) {
            rowdata[0].add(mesa.getCodMesa());
            rowdata[1].add(mesa.getEstado());
            rowdata[2].add(mesa.getCapacidadMax());
            rowdata[3].add(mesa.getAreacodArea().getCodArea());
        }
        try {
            comun.UpdateTable(rowdata, jXTableListadoMesas);
        } catch (Exception ex) {
            Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void updateAreasTable() {
         areas = staticContent.areaJPA.findAreaEntities();
        comboBoxCodigoArea.removeAllItems();
         
        ArrayList [] rowdata = comun.initArray(new ArrayList[3]);
        
        
        for (Area a : areas) {
            rowdata[0].add(a.getCodArea());
            rowdata[1].add(a.getNombre());
            rowdata[2].add(a.getCapacidad());
            comboBoxCodigoArea.addItem(a.getCodArea());
        }
        try {
            comun.UpdateTable(rowdata, jXTableListadoAreas);
        } catch (Exception ex) {
            Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        buttonEliminarMesa = new org.edisoncor.gui.button.ButtonTextDown();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTableListadoMesas = new org.jdesktop.swingx.JXTable();
        panelRoundNuevaMesa = new org.edisoncor.gui.panel.PanelRound();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        comboBoxEstado = new org.edisoncor.gui.comboBox.ComboBoxRect();
        jXLabelCodMesa = new org.jdesktop.swingx.JXLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jSpinnerMesa = new javax.swing.JSpinner();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        comboBoxCodigoArea = new org.edisoncor.gui.comboBox.ComboBoxRect();
        buttonAgregarMesa = new org.edisoncor.gui.button.ButtonTextDown();
        jXLabelNuevaMesa = new org.jdesktop.swingx.JXLabel();
        jXLabelListaAreas = new org.jdesktop.swingx.JXLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTableListadoAreas = new org.jdesktop.swingx.JXTable();
        jXLabelListaMesas1 = new org.jdesktop.swingx.JXLabel();
        panelRoundNuevaArea = new org.edisoncor.gui.panel.PanelRound();
        jXLabelCodArea = new org.jdesktop.swingx.JXLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jSpinnerArea = new javax.swing.JSpinner();
        textFieldNombre = new org.edisoncor.gui.textField.TextFieldRectBackground();
        buttonAgregarArea = new org.edisoncor.gui.button.ButtonTextDown();
        jXLabelNuevaArea = new org.jdesktop.swingx.JXLabel();
        buttonEliminarArea = new org.edisoncor.gui.button.ButtonTextDown();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrador de mesas");

        buttonEliminarMesa.setForeground(new java.awt.Color(0, 0, 0));
        buttonEliminarMesa.setText("Eliminar Mesa");
        buttonEliminarMesa.setDistanciaDeSombra(0);
        buttonEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarMesaActionPerformed(evt);
            }
        });

        jXTableListadoMesas.setAutoCreateRowSorter(true);
        jXTableListadoMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Estado", "Capacidad", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jXTableListadoMesas);

        jXLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jXLabel1.setText("Estado");

        jXLabelCodMesa.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelCodMesa.setText("<Código Mesa>");

        jXLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jXLabel3.setText("Capacidad");

        jXLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jXLabel4.setText("Código area");

        buttonAgregarMesa.setForeground(new java.awt.Color(0, 0, 0));
        buttonAgregarMesa.setText("Crear/Editar Mesa");
        buttonAgregarMesa.setDistanciaDeSombra(0);
        buttonAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRoundNuevaMesaLayout = new javax.swing.GroupLayout(panelRoundNuevaMesa);
        panelRoundNuevaMesa.setLayout(panelRoundNuevaMesaLayout);
        panelRoundNuevaMesaLayout.setHorizontalGroup(
            panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundNuevaMesaLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabelCodMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRoundNuevaMesaLayout.createSequentialGroup()
                        .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCodigoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerMesa)
                            .addComponent(comboBoxEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(buttonAgregarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelRoundNuevaMesaLayout.setVerticalGroup(
            panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundNuevaMesaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jXLabelCodMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerMesa))
                .addGap(18, 18, 18)
                .addGroup(panelRoundNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxCodigoArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buttonAgregarMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jXLabelNuevaMesa.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelNuevaMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelNuevaMesa.setText("Nueva Mesa");
        jXLabelNuevaMesa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jXLabelListaAreas.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelListaAreas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelListaAreas.setText("Listado de areas");
        jXLabelListaAreas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jXTableListadoAreas.setAutoCreateRowSorter(true);
        jXTableListadoAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jXTableListadoAreas);

        jXLabelListaMesas1.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelListaMesas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelListaMesas1.setText("Listado de mesas");
        jXLabelListaMesas1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jXLabelCodArea.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelCodArea.setText("<Código Area>");

        jXLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jXLabel6.setText("Capacidad");

        textFieldNombre.setDescripcion("Nombre");

        buttonAgregarArea.setForeground(new java.awt.Color(0, 0, 0));
        buttonAgregarArea.setText("Crear/Editar Area");
        buttonAgregarArea.setDistanciaDeSombra(0);
        buttonAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRoundNuevaAreaLayout = new javax.swing.GroupLayout(panelRoundNuevaArea);
        panelRoundNuevaArea.setLayout(panelRoundNuevaAreaLayout);
        panelRoundNuevaAreaLayout.setHorizontalGroup(
            panelRoundNuevaAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundNuevaAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRoundNuevaAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRoundNuevaAreaLayout.createSequentialGroup()
                        .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerArea, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXLabelCodArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAgregarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoundNuevaAreaLayout.setVerticalGroup(
            panelRoundNuevaAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundNuevaAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXLabelCodArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRoundNuevaAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAgregarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXLabelNuevaArea.setForeground(new java.awt.Color(255, 255, 0));
        jXLabelNuevaArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelNuevaArea.setText("Nueva Area");
        jXLabelNuevaArea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        buttonEliminarArea.setForeground(new java.awt.Color(0, 0, 0));
        buttonEliminarArea.setText("Eliminar Area");
        buttonEliminarArea.setDistanciaDeSombra(0);
        buttonEliminarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRect1Layout = new javax.swing.GroupLayout(panelRect1);
        panelRect1.setLayout(panelRect1Layout);
        panelRect1Layout.setHorizontalGroup(
            panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRect1Layout.createSequentialGroup()
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRect1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabelListaMesas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRoundNuevaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabelNuevaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                    .addGroup(panelRect1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(buttonEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRect1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEliminarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(panelRect1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(panelRoundNuevaArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabelNuevaArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXLabelListaAreas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        panelRect1Layout.setVerticalGroup(
            panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRect1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXLabelListaAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabelListaMesas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXLabelNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabelNuevaArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRoundNuevaArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRoundNuevaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelRect1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEliminarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEliminarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        getContentPane().add(panelRect1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarMesaActionPerformed
       try {
            if (jXTableListadoMesas.getSelectedRow() != -1) {
                String cod = (String) jXTableListadoMesas.getValueAt(jXTableListadoMesas.getSelectedRow(), 0);
                if (JOptionPane.showConfirmDialog(this, "Seguro desea eliminar la mesa " + cod ) == JOptionPane.YES_OPTION) {
                    staticContent.mesasJPA.destroy(cod);
                    
                    updateMesasTable();
                }
                
                
                
            } else {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun elemento.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el puesto.");
        }
    }//GEN-LAST:event_buttonEliminarMesaActionPerformed

    private void buttonEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarAreaActionPerformed
       try {
            if (jXTableListadoAreas.getSelectedRow() != -1) {
                String cod = (String) jXTableListadoAreas.getValueAt(jXTableListadoAreas.getSelectedRow(), 0);
                if (JOptionPane.showConfirmDialog(this, "Seguro desea eliminar el Area " + cod ) == JOptionPane.YES_OPTION) {
                    staticContent.areaJPA.destroy(cod);
                    
                    updateAreasTable();
                }
                
                
                
            } else {
                JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun elemento.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el puesto.");
        }
    }//GEN-LAST:event_buttonEliminarAreaActionPerformed

    private void buttonAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarAreaActionPerformed
        
        String nombre = textFieldNombre.getText();//TODO: faltan excepciones aqui
        int cap = (int) jSpinnerArea.getValue();
                
        if(this.jXLabelCodArea.getText().contains("A-")){
          Area a = staticContent.areaJPA.findArea(jXLabelCodArea.getText());
          a.setNombre(nombre);
          a.setCapacidad(cap);
            try {
                staticContent.areaJPA.edit(a);
            } catch (Exception ex) {
                Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
             Area a = new Area("A-"+ areas.size());
          a.setNombre(nombre);
          a.setCapacidad(cap);
            try {
                staticContent.areaJPA.create(a);
            } catch (Exception ex) {
                Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        updateAreasTable();
        cleanPanel();
        
        
    }//GEN-LAST:event_buttonAgregarAreaActionPerformed

    private void buttonAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarMesaActionPerformed
        String estado = (String) this.comboBoxEstado.getSelectedItem();//TODO: faltan excepciones aqui
        int cap = (int) jSpinnerMesa.getValue();
        String codArea = (String) comboBoxCodigoArea.getSelectedItem();
                
        if(this.jXLabelCodMesa.getText().contains("M-")){
          Mesa m = staticContent.mesasJPA.findMesa(jXLabelCodMesa.getText());
          m.setEstado(estado);
          m.setCapacidadMax(cap);
          m.setAreacodArea(staticContent.areaJPA.findArea(codArea));
            try {
                staticContent.mesasJPA.edit(m);
            } catch (Exception ex) {
                Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
             Mesa m = new Mesa("M-"+ mesas.size());
          m.setEstado(estado);
          m.setCapacidadMax(cap);
          m.setAreacodArea(staticContent.areaJPA.findArea(codArea));
            try {
                staticContent.mesasJPA.create(m);
            } catch (Exception ex) {
                Logger.getLogger(EsquemaSalon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        updateMesasTable();
        cleanMesasPanel();
    }//GEN-LAST:event_buttonAgregarMesaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTextDown buttonAgregarArea;
    private org.edisoncor.gui.button.ButtonTextDown buttonAgregarMesa;
    private org.edisoncor.gui.button.ButtonTextDown buttonEliminarArea;
    private org.edisoncor.gui.button.ButtonTextDown buttonEliminarMesa;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboBoxCodigoArea;
    private org.edisoncor.gui.comboBox.ComboBoxRect comboBoxEstado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerArea;
    private javax.swing.JSpinner jSpinnerMesa;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabelCodArea;
    private org.jdesktop.swingx.JXLabel jXLabelCodMesa;
    private org.jdesktop.swingx.JXLabel jXLabelListaAreas;
    private org.jdesktop.swingx.JXLabel jXLabelListaMesas1;
    private org.jdesktop.swingx.JXLabel jXLabelNuevaArea;
    private org.jdesktop.swingx.JXLabel jXLabelNuevaMesa;
    private org.jdesktop.swingx.JXTable jXTableListadoAreas;
    private org.jdesktop.swingx.JXTable jXTableListadoMesas;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private org.edisoncor.gui.panel.PanelRound panelRoundNuevaArea;
    private org.edisoncor.gui.panel.PanelRound panelRoundNuevaMesa;
    private org.edisoncor.gui.textField.TextFieldRectBackground textFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void cleanPanel() {
    this.textFieldNombre.setText("");
    jSpinnerArea.setValue(0);
    }

    private void cleanMesasPanel() {
        jSpinnerMesa.setValue(0);
        comboBoxCodigoArea.setSelectedIndex(0);
        comboBoxEstado.setSelectedIndex(0);
    }

    

    
}
