/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Views.trabajadores.TrabajadorCrear;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import restManager.controller.almacen.AlmacenListController;
import restManager.controller.cocina.CocinaListController;
import restManager.controller.insumo.InsumoListController;
import restManager.controller.productoventa.ProductoVentaListController;
import restManager.controller.seccion.SeccionListController;
import restManager.controller.trabajadores.PersonalListController;
import restManager.controller.trabajadores.PuestoTrabajoCreateEditController;
import restManager.controller.trabajadores.PuestoTrabajoListController;
import restManager.persistencia.Personal;
import restManager.persistencia.PuestoTrabajo;
import restManager.persistencia.Venta;
import restManager.persistencia.jpa.staticContent;
import restManager.resources.R;

/**
 *
 * @author Jorge
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main2
     */
    static Personal logUser;

    /**
     * nivel mas bajo para los clientes
     */
    public static boolean NIVEL_0 = false;
    /**
     * nivel para los camareros y personas con acceso a la gestion de ordenes
     */
    public static boolean NIVEL_1 = false;
    /**
     * nivel para los almaceneros y personas con acceso a la gestion de los
     * insumos
     */
    public static boolean NIVEL_2 = false;
    /**
     * nivel para los contadores y personas con acceso a la visualizacion de
     * estadisticas, resumenes gasto/ganancia
     */
    public static boolean NIVEL_3 = false;
    /**
     * nivel para los administradores que gestionan a los trabajadores,
     * administran el sistema como tal
     */
    public static boolean NIVEL_4 = false;
    /**
     * nivel para los desarrolladores tener acceso a la configuracion del
     * software
     */
    public static boolean NIVEL_5 = false;

    public Main(Personal p) {
        logUser = p;
        grantPermission(p);
        initComponents();
        labelMetricNOMBRE.setText(staticContent.cartaJPA.findCarta("Mnu-1").getNombreCarta()); //quitar esto
        R.coinSuffix = " " + staticContent.cartaJPA.findCartaEntities().get(0).getMonedaPrincipal();
        setVisible(true);

    }

    private void cleanAuxPanel() {
        panelRectAUX.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonABRIRMENU = new org.edisoncor.gui.button.ButtonTextDown();
        buttonVERSECCIONES = new org.edisoncor.gui.button.ButtonTextDown();
        buttonVERCOCINAS = new org.edisoncor.gui.button.ButtonTextDown();
        buttonVERINSUMOS = new org.edisoncor.gui.button.ButtonTextDown();
        buttonABRIRALMACEN = new org.edisoncor.gui.button.ButtonTextDown();
        buttonABRIRIPV = new org.edisoncor.gui.button.ButtonTextDown();
        buttonCALENDARIO = new org.edisoncor.gui.button.ButtonTextDown();
        buttonCOMENZARDIA = new org.edisoncor.gui.button.ButtonTextDown();
        buttonDIASSINARCHIVAR = new org.edisoncor.gui.button.ButtonTextDown();
        buttonPRESUPUESTO = new org.edisoncor.gui.button.ButtonTextDown();
        buttonVERTRAB = new org.edisoncor.gui.button.ButtonTextDown();
        buttonVERPUESTOS = new org.edisoncor.gui.button.ButtonTextDown();
        buttonCREARTRAB = new org.edisoncor.gui.button.ButtonTextDown();
        buttonCREARPUESTO = new org.edisoncor.gui.button.ButtonTextDown();
        buttonEsquemaSalon = new org.edisoncor.gui.button.ButtonTextDown();
        buttonCopiaSeguridad = new org.edisoncor.gui.button.ButtonTextDown();
        buttonALMACENNUEVAFICHA = new org.edisoncor.gui.button.ButtonTextDown();
        buttonALMACENVERFICHAS = new org.edisoncor.gui.button.ButtonTextDown();
        buttonALMACENSTOCK = new org.edisoncor.gui.button.ButtonTextDown();
        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        labelMetricNOMBRE = new org.edisoncor.gui.label.LabelMetric();
        labelMetricPANELPRINC = new org.edisoncor.gui.label.LabelMetric();
        labelMetricNOMBRE2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetricPANELCSEC = new org.edisoncor.gui.label.LabelMetric();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        jScrollPaneAUX = new javax.swing.JScrollPane();
        panelRectAUX = new org.edisoncor.gui.panel.PanelRect();
        jScrollPanePRINC = new javax.swing.JScrollPane();
        panelRectPRINC = new org.edisoncor.gui.panel.PanelRect();
        buttonTextDownPDV = new org.edisoncor.gui.button.ButtonTextDown();
        buttonTextDownALMANCEN = new org.edisoncor.gui.button.ButtonTextDown();
        buttonTextDownCONTABILIDAD = new org.edisoncor.gui.button.ButtonTextDown();
        buttonTextDownTRAB = new org.edisoncor.gui.button.ButtonTextDown();
        buttonTextDownCONF = new org.edisoncor.gui.button.ButtonTextDown();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();

        buttonABRIRMENU.setText("Lista Productos");
        buttonABRIRMENU.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonABRIRMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonABRIRMENUActionPerformed(evt);
            }
        });

        buttonVERSECCIONES.setText("Secciones");
        buttonVERSECCIONES.setEnabled(Main.NIVEL_3);
        buttonVERSECCIONES.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonVERSECCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVERSECCIONESActionPerformed(evt);
            }
        });

        buttonVERCOCINAS.setText("Cocinas");
        buttonVERCOCINAS.setEnabled(Main.NIVEL_3);
        buttonVERCOCINAS.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonVERCOCINAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVERCOCINASActionPerformed(evt);
            }
        });

        buttonVERINSUMOS.setText("Insumos");
        buttonVERINSUMOS.setEnabled(Main.NIVEL_3);
        buttonVERINSUMOS.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonVERINSUMOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVERINSUMOSActionPerformed(evt);
            }
        });

        buttonABRIRALMACEN.setText("Listar Almacenes");
        buttonABRIRALMACEN.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonABRIRALMACEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonABRIRALMACENActionPerformed(evt);
            }
        });

        buttonABRIRIPV.setText("Abrir IPVs");
        buttonABRIRIPV.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonABRIRIPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonABRIRIPVActionPerformed(evt);
            }
        });

        buttonCALENDARIO.setText("Calendario");
        buttonCALENDARIO.setEnabled(false);
        buttonCALENDARIO.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N

        buttonCOMENZARDIA.setText("Comenzar Día");
        buttonCOMENZARDIA.setEnabled(NIVEL_1);
        buttonCOMENZARDIA.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonCOMENZARDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCOMENZARDIAActionPerformed(evt);
            }
        });

        buttonDIASSINARCHIVAR.setText("Dias sin archivar");
        buttonDIASSINARCHIVAR.setEnabled(NIVEL_3);
        buttonDIASSINARCHIVAR.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonDIASSINARCHIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDIASSINARCHIVARActionPerformed(evt);
            }
        });

        buttonPRESUPUESTO.setText("Presupuesto");
        buttonPRESUPUESTO.setEnabled(false);
        buttonPRESUPUESTO.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N

        buttonVERTRAB.setText("Ver Trabajadores");
        buttonVERTRAB.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonVERTRAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVERTRABActionPerformed(evt);
            }
        });

        buttonVERPUESTOS.setText("Ver Puestos");
        buttonVERPUESTOS.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonVERPUESTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVERPUESTOSActionPerformed(evt);
            }
        });

        buttonCREARTRAB.setText("Crear Trabajador");
        buttonCREARTRAB.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonCREARTRAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCREARTRABActionPerformed(evt);
            }
        });

        buttonCREARPUESTO.setText("Crear Puesto");
        buttonCREARPUESTO.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonCREARPUESTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCREARPUESTOActionPerformed(evt);
            }
        });

        buttonEsquemaSalon.setText("Esquema del salón");
        buttonEsquemaSalon.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonEsquemaSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsquemaSalonActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        buttonCopiaSeguridad.setText(bundle.getString("label_copia_seguridad")); // NOI18N
        buttonCopiaSeguridad.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonCopiaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCopiaSeguridadActionPerformed(evt);
            }
        });

        buttonALMACENNUEVAFICHA.setText("Nueva Ficha");
        buttonALMACENNUEVAFICHA.setEnabled(Main.NIVEL_3);
        buttonALMACENNUEVAFICHA.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonALMACENNUEVAFICHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonALMACENNUEVAFICHAActionPerformed(evt);
            }
        });

        buttonALMACENVERFICHAS.setText("Ver fichas");
        buttonALMACENVERFICHAS.setEnabled(Main.NIVEL_3);
        buttonALMACENVERFICHAS.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonALMACENVERFICHAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonALMACENVERFICHASActionPerformed(evt);
            }
        });

        buttonALMACENSTOCK.setText("Ver Stock");
        buttonALMACENSTOCK.setEnabled(Main.NIVEL_3);
        buttonALMACENSTOCK.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonALMACENSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonALMACENSTOCKActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(927, 625));
        setName("MainMenu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelRect1.setLayout(new java.awt.BorderLayout());

        labelMetricNOMBRE.setForeground(new java.awt.Color(255, 255, 0));
        labelMetricNOMBRE.setText("Los Anturios");
        labelMetricNOMBRE.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelMetricNOMBRE.setMaximumSize(new java.awt.Dimension(32767, 39));
        labelMetricNOMBRE.setMinimumSize(new java.awt.Dimension(222, 39));

        labelMetricPANELPRINC.setForeground(new java.awt.Color(255, 255, 0));
        labelMetricPANELPRINC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetricPANELPRINC.setText("Panel Principal");
        labelMetricPANELPRINC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelMetricPANELPRINC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelMetricNOMBRE2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetricNOMBRE2.setText("=>");
        labelMetricNOMBRE2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelMetricNOMBRE2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelMetricPANELCSEC.setForeground(new java.awt.Color(255, 255, 0));
        labelMetricPANELCSEC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetricPANELCSEC.setText("Opciones");
        labelMetricPANELCSEC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelMetricPANELCSEC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        clockDigital1.setForeground(new java.awt.Color(255, 255, 0));
        clockDigital1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N

        jScrollPaneAUX.setAutoscrolls(true);

        panelRectAUX.setLayout(new java.awt.GridLayout(0, 1, 0, 20));
        jScrollPaneAUX.setViewportView(panelRectAUX);

        jScrollPanePRINC.setAutoscrolls(true);

        panelRectPRINC.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        buttonTextDownPDV.setText("Productos");
        buttonTextDownPDV.setEnabled(NIVEL_0);
        buttonTextDownPDV.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonTextDownPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextDownPDVActionPerformed(evt);
            }
        });
        panelRectPRINC.add(buttonTextDownPDV);

        buttonTextDownALMANCEN.setText("Almacén");
        buttonTextDownALMANCEN.setEnabled(NIVEL_2);
        buttonTextDownALMANCEN.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonTextDownALMANCEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextDownALMANCENActionPerformed(evt);
            }
        });
        panelRectPRINC.add(buttonTextDownALMANCEN);

        buttonTextDownCONTABILIDAD.setText("Contabilidad");
        buttonTextDownCONTABILIDAD.setEnabled(NIVEL_1);
        buttonTextDownCONTABILIDAD.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonTextDownCONTABILIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextDownCONTABILIDADActionPerformed(evt);
            }
        });
        panelRectPRINC.add(buttonTextDownCONTABILIDAD);

        buttonTextDownTRAB.setText("Trabajadores");
        buttonTextDownTRAB.setEnabled(NIVEL_4);
        buttonTextDownTRAB.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonTextDownTRAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextDownTRABActionPerformed(evt);
            }
        });
        panelRectPRINC.add(buttonTextDownTRAB);

        buttonTextDownCONF.setText("Configuracion");
        buttonTextDownCONF.setActionCommand("Configuración");
        buttonTextDownCONF.setEnabled(NIVEL_4);
        buttonTextDownCONF.setFont(new java.awt.Font("BlairMdITC TT", 1, 24)); // NOI18N
        buttonTextDownCONF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextDownCONFActionPerformed(evt);
            }
        });
        panelRectPRINC.add(buttonTextDownCONF);

        jScrollPanePRINC.setViewportView(panelRectPRINC);

        jXLabel1.setText("jXLabel1");

        javax.swing.GroupLayout panelCurves2Layout = new javax.swing.GroupLayout(panelCurves2);
        panelCurves2.setLayout(panelCurves2Layout);
        panelCurves2Layout.setHorizontalGroup(
            panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves2Layout.createSequentialGroup()
                .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCurves2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelMetricNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCurves2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetricPANELPRINC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPanePRINC, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMetricNOMBRE2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCurves2Layout.createSequentialGroup()
                                .addComponent(labelMetricPANELCSEC, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
                            .addGroup(panelCurves2Layout.createSequentialGroup()
                                .addComponent(jScrollPaneAUX)
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCurves2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        panelCurves2Layout.setVerticalGroup(
            panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMetricNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetricPANELPRINC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMetricPANELCSEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneAUX))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMetricNOMBRE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCurves2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPanePRINC)))
                .addGap(78, 78, 78)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelRect1.add(panelCurves2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelRect1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTextDownCONTABILIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDownCONTABILIDADActionPerformed
        cleanAuxPanel();
        panelRectAUX.add(buttonCALENDARIO);
        panelRectAUX.add(buttonCOMENZARDIA);
        panelRectAUX.add(buttonDIASSINARCHIVAR);
        panelRectAUX.add(buttonPRESUPUESTO);
    }//GEN-LAST:event_buttonTextDownCONTABILIDADActionPerformed

    private void buttonTextDownPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDownPDVActionPerformed
        cleanAuxPanel();
        panelRectAUX.add(buttonABRIRMENU);
        panelRectAUX.add(buttonVERINSUMOS);
        panelRectAUX.add(buttonVERSECCIONES);
        panelRectAUX.add(buttonVERCOCINAS);
        panelRectAUX.add(buttonEsquemaSalon);

    }//GEN-LAST:event_buttonTextDownPDVActionPerformed

    private void buttonTextDownALMANCENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDownALMANCENActionPerformed
        cleanAuxPanel();
        panelRectAUX.add(buttonABRIRALMACEN);
        panelRectAUX.add(buttonABRIRIPV);
        panelRectAUX.add(buttonALMACENNUEVAFICHA);
        panelRectAUX.add(buttonALMACENVERFICHAS);
        panelRectAUX.add(buttonALMACENSTOCK);
    }//GEN-LAST:event_buttonTextDownALMANCENActionPerformed

    private void buttonABRIRMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonABRIRMENUActionPerformed
        ProductoVentaListController controller = new ProductoVentaListController(this);
    }//GEN-LAST:event_buttonABRIRMENUActionPerformed

    private void buttonTextDownTRABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDownTRABActionPerformed
        cleanAuxPanel();
        panelRectAUX.add(buttonVERTRAB);
        panelRectAUX.add(buttonVERPUESTOS);
        panelRectAUX.add(buttonCREARTRAB);
        panelRectAUX.add(buttonCREARPUESTO);

    }//GEN-LAST:event_buttonTextDownTRABActionPerformed

    private void buttonVERTRABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVERTRABActionPerformed
        PersonalListController personalList = new PersonalListController(this);
    }//GEN-LAST:event_buttonVERTRABActionPerformed

    private void buttonCOMENZARDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCOMENZARDIAActionPerformed
        if (Main.NIVEL_4) {
            String date = JOptionPane.showInputDialog("Introduzca el dia a trabajar en el formato dd/mm/aa \n "
                    + "o deje la casilla en blanco para comenzar en el dia actual ");
            if (date == null) {
                VentaMain.getInstance(this, true, getDiaDeVenta());
            } else {
                try {
                    Date fecha = R.DATE_FORMAT.parse(date);
                    VentaMain.getInstance(this, true, fecha);
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            }
        } else {
            VentaMain.getInstance(this, true, getDiaDeVenta());
        }


    }//GEN-LAST:event_buttonCOMENZARDIAActionPerformed

    private void buttonEsquemaSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsquemaSalonActionPerformed
        new EsquemaSalon(this, true);
    }//GEN-LAST:event_buttonEsquemaSalonActionPerformed

    private void buttonCREARTRABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCREARTRABActionPerformed
        new TrabajadorCrear(this, true, null);
    }//GEN-LAST:event_buttonCREARTRABActionPerformed

    private void buttonDIASSINARCHIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDIASSINARCHIVARActionPerformed
        new VentaLista(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_buttonDIASSINARCHIVARActionPerformed

    private void buttonCREARPUESTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCREARPUESTOActionPerformed
        new PuestoTrabajoCreateEditController(this);
    }//GEN-LAST:event_buttonCREARPUESTOActionPerformed

    private void buttonVERPUESTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVERPUESTOSActionPerformed
        PuestoTrabajoListController controller = new PuestoTrabajoListController(this);
    }//GEN-LAST:event_buttonVERPUESTOSActionPerformed

    private void buttonVERCOCINASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVERCOCINASActionPerformed
        CocinaListController controller = new CocinaListController(this);
    }//GEN-LAST:event_buttonVERCOCINASActionPerformed

    private void buttonVERINSUMOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVERINSUMOSActionPerformed
        R.setLookAndFeels();
        new InsumoListController(this);
    }//GEN-LAST:event_buttonVERINSUMOSActionPerformed

    private void buttonVERSECCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVERSECCIONESActionPerformed
        SeccionListController controller = new SeccionListController(this);
    }//GEN-LAST:event_buttonVERSECCIONESActionPerformed

    private void buttonABRIRIPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonABRIRIPVActionPerformed
        new IPVsLista(this, true);
    }//GEN-LAST:event_buttonABRIRIPVActionPerformed

    private void buttonCopiaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCopiaSeguridadActionPerformed
        new copiaSegView(this, true);
    }//GEN-LAST:event_buttonCopiaSeguridadActionPerformed

    private void buttonTextDownCONFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextDownCONFActionPerformed
        cleanAuxPanel();
        panelRectAUX.add(buttonCopiaSeguridad);
    }//GEN-LAST:event_buttonTextDownCONFActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new LogInDialog(new JFrame(), true);       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void buttonABRIRALMACENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonABRIRALMACENActionPerformed
        R.setLookAndFeels();
        new AlmacenListController(this);
    }//GEN-LAST:event_buttonABRIRALMACENActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void buttonALMACENNUEVAFICHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonALMACENNUEVAFICHAActionPerformed

    }//GEN-LAST:event_buttonALMACENNUEVAFICHAActionPerformed

    private void buttonALMACENVERFICHASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonALMACENVERFICHASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonALMACENVERFICHASActionPerformed

    private void buttonALMACENSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonALMACENSTOCKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonALMACENSTOCKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTextDown buttonABRIRALMACEN;
    private org.edisoncor.gui.button.ButtonTextDown buttonABRIRIPV;
    private org.edisoncor.gui.button.ButtonTextDown buttonABRIRMENU;
    private org.edisoncor.gui.button.ButtonTextDown buttonALMACENNUEVAFICHA;
    private org.edisoncor.gui.button.ButtonTextDown buttonALMACENSTOCK;
    private org.edisoncor.gui.button.ButtonTextDown buttonALMACENVERFICHAS;
    private org.edisoncor.gui.button.ButtonTextDown buttonCALENDARIO;
    private org.edisoncor.gui.button.ButtonTextDown buttonCOMENZARDIA;
    private org.edisoncor.gui.button.ButtonTextDown buttonCREARPUESTO;
    private org.edisoncor.gui.button.ButtonTextDown buttonCREARTRAB;
    private org.edisoncor.gui.button.ButtonTextDown buttonCopiaSeguridad;
    private org.edisoncor.gui.button.ButtonTextDown buttonDIASSINARCHIVAR;
    private org.edisoncor.gui.button.ButtonTextDown buttonEsquemaSalon;
    private org.edisoncor.gui.button.ButtonTextDown buttonPRESUPUESTO;
    private org.edisoncor.gui.button.ButtonTextDown buttonTextDownALMANCEN;
    private org.edisoncor.gui.button.ButtonTextDown buttonTextDownCONF;
    private org.edisoncor.gui.button.ButtonTextDown buttonTextDownCONTABILIDAD;
    private org.edisoncor.gui.button.ButtonTextDown buttonTextDownPDV;
    private org.edisoncor.gui.button.ButtonTextDown buttonTextDownTRAB;
    private org.edisoncor.gui.button.ButtonTextDown buttonVERCOCINAS;
    private org.edisoncor.gui.button.ButtonTextDown buttonVERINSUMOS;
    private org.edisoncor.gui.button.ButtonTextDown buttonVERPUESTOS;
    private org.edisoncor.gui.button.ButtonTextDown buttonVERSECCIONES;
    private org.edisoncor.gui.button.ButtonTextDown buttonVERTRAB;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JScrollPane jScrollPaneAUX;
    private javax.swing.JScrollPane jScrollPanePRINC;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.edisoncor.gui.label.LabelMetric labelMetricNOMBRE;
    private org.edisoncor.gui.label.LabelMetric labelMetricNOMBRE2;
    private org.edisoncor.gui.label.LabelMetric labelMetricPANELCSEC;
    private org.edisoncor.gui.label.LabelMetric labelMetricPANELPRINC;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private org.edisoncor.gui.panel.PanelRect panelRectAUX;
    private org.edisoncor.gui.panel.PanelRect panelRectPRINC;
    // End of variables declaration//GEN-END:variables

    private void grantPermission(Personal p) {
        int nivelAcceso = 0;
        for (PuestoTrabajo x : p.getPuestoTrabajoList()) {
            if (x.getNivelAcceso() > nivelAcceso) {
                nivelAcceso = x.getNivelAcceso();
            }
        }
        switch (nivelAcceso) {
            case 0:
                NIVEL_0 = true;
                break;
            case 1:
                NIVEL_0 = true;
                NIVEL_1 = true;
                break;
            case 2:
                NIVEL_0 = true;
                NIVEL_1 = true;
                NIVEL_2 = true;
                break;
            case 3:
                NIVEL_0 = true;
                NIVEL_1 = true;
                NIVEL_2 = true;
                NIVEL_3 = true;
                break;
            case 4:
                NIVEL_0 = true;
                NIVEL_1 = true;
                NIVEL_2 = true;
                NIVEL_3 = true;
                NIVEL_4 = true;
                break;
            case 5:
                NIVEL_0 = true;
                NIVEL_1 = true;
                NIVEL_2 = true;
                NIVEL_3 = true;
                NIVEL_4 = true;
                NIVEL_5 = true;
                break;

        }

    }

    private Venta getDiaDeVenta() {
        List<Venta> ventas = staticContent.ventaJPA.findVentaEntities();
        for (int i = ventas.size() - 1; i >= 0; i--) {
            if (ventas.get(i).getVentaTotal() == null) {
                return ventas.get(i);
            }

        }

        return staticContent.ventaJPA.findVenta(new Date());
    }

}
