/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Main;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import restManager.persistencia.PuestoTrabajo;
import restManager.persistencia.jpa.staticContent;
import restManager.util.ComponentMover;

/**
 *
 * @author Jorge
 */
public class PuestoTrabajoCrear extends javax.swing.JDialog {

    /**
     * Creates new form PuestoTrabajoCrear
     */
    private PuestoTrabajo p;

    public PuestoTrabajoCrear(java.awt.Frame parent, boolean modal, PuestoTrabajo p) {
        super(parent, modal);
        init(p);

    }

    public PuestoTrabajoCrear(java.awt.Dialog parent, boolean modal, PuestoTrabajo p) {
        super(parent, modal);
        init(p);

    }

    public void init(PuestoTrabajo p) {
        if (p == null) {
            this.p = new PuestoTrabajo("");

            this.p.setNivelAcceso(0);
            this.p.setPuestosDisponibles(0);
            this.p.setSalarioFijo(0);
            this.p.setAPartirDe(0);
            this.p.setSalarioPorcientoDeArea(Float.parseFloat("0"));
            this.p.setSalarioPorcientoVentaTotal(Float.parseFloat("0"));
            this.p.setAreaPago("");

        } else {
            this.p = p;

        }
        setUndecorated(true);
        setShape(new RoundRectangle2D.Double(10, 10, 335, 383, 61, 61));
        initComponents();
//        jFormattedTextFieldSalarioFijo.setFormatterFactory(
//                new javax.swing.text.DefaultFormatterFactory(
//                        new javax.swing.text.NumberFormatter(
//                                new java.text.DecimalFormat("#,##0.00"+ Main.moneda))));
//        
        ComponentMover cr = new ComponentMover(this, panelRound1);
        updateDialog(this.p);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jTextFieldNombre = new javax.swing.JTextField();
        comboBoxNivelAcceso = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jLabelNivelDeAcceso = new org.jdesktop.swingx.JXLabel();
        jLabelNombre = new org.jdesktop.swingx.JXLabel();
        jLabelSalarioFijo = new org.jdesktop.swingx.JXLabel();
        jLabelMoneda = new org.jdesktop.swingx.JXLabel();
        jLabelPuestosDisponibles = new org.jdesktop.swingx.JXLabel();
        jSpinnerPuestosDisponibles = new javax.swing.JSpinner();
        buttonCrear = new org.edisoncor.gui.button.ButtonAction();
        buttonCancelar = new org.edisoncor.gui.button.ButtonAction();
        jLabelSalarioFijo1 = new org.jdesktop.swingx.JXLabel();
        jLabelSalarioFijo2 = new org.jdesktop.swingx.JXLabel();
        jLabelSalarioFijo3 = new org.jdesktop.swingx.JXLabel();
        jLabelSalarioFijo4 = new org.jdesktop.swingx.JXLabel();
        comboBoxAreaPago = new org.edisoncor.gui.comboBox.ComboBoxRound();
        jSpinnerSalarioFijo = new javax.swing.JSpinner();
        jSpinnerPorcientoArea = new javax.swing.JSpinner();
        jSpinnerAPartir = new javax.swing.JSpinner();
        jSpinnerPorcientoVenta = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound1.setAnchoDeBorde(0.0F);

        comboBoxNivelAcceso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));

        jLabelNivelDeAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNivelDeAcceso.setText("Nivel de acceso");

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jLabelSalarioFijo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioFijo.setText("Salario fijo");

        jLabelMoneda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMoneda.setText(Main.moneda);

        jLabelPuestosDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPuestosDisponibles.setText("Puestos disponibles");

        jSpinnerPuestosDisponibles.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        jLabelSalarioFijo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioFijo1.setText("% de la venta");

        jLabelSalarioFijo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioFijo2.setText("% de area");

        jLabelSalarioFijo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioFijo3.setText("Area de Pago");

        jLabelSalarioFijo4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalarioFijo4.setText("A partir de");

        comboBoxAreaPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguna" }));

        jSpinnerSalarioFijo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jSpinnerPorcientoArea.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));

        jSpinnerAPartir.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerPorcientoVenta.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalarioFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelRound1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jSpinnerPuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRound1Layout.createSequentialGroup()
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNivelDeAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSalarioFijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSalarioFijo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSalarioFijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboBoxNivelAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jSpinnerAPartir)
                                            .addComponent(jSpinnerPorcientoArea)
                                            .addComponent(jSpinnerSalarioFijo)
                                            .addComponent(comboBoxAreaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSpinnerPorcientoVenta))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalarioFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSalarioFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioFijo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPorcientoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerPorcientoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalarioFijo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioFijo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAPartir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioFijo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxAreaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNivelDeAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxNivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPuestosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(panelRound1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        crear();
    }//GEN-LAST:event_buttonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction buttonCancelar;
    private org.edisoncor.gui.button.ButtonAction buttonCrear;
    private org.edisoncor.gui.comboBox.ComboBoxRound comboBoxAreaPago;
    private org.edisoncor.gui.comboBox.ComboBoxRound comboBoxNivelAcceso;
    private org.jdesktop.swingx.JXLabel jLabelMoneda;
    private org.jdesktop.swingx.JXLabel jLabelNivelDeAcceso;
    private org.jdesktop.swingx.JXLabel jLabelNombre;
    private org.jdesktop.swingx.JXLabel jLabelPuestosDisponibles;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo1;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo2;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo3;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo4;
    private javax.swing.JSpinner jSpinnerAPartir;
    private javax.swing.JSpinner jSpinnerPorcientoArea;
    private javax.swing.JSpinner jSpinnerPorcientoVenta;
    private javax.swing.JSpinner jSpinnerPuestosDisponibles;
    private javax.swing.JSpinner jSpinnerSalarioFijo;
    private javax.swing.JTextField jTextFieldNombre;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables

    private void updateDialog(PuestoTrabajo p) {

        jTextFieldNombre.setText(p.getNombrePuesto());
        jSpinnerSalarioFijo.setValue(p.getSalarioFijo());
        comboBoxNivelAcceso.setSelectedIndex(p.getNivelAcceso());
        jSpinnerPuestosDisponibles.setValue(p.getPuestosDisponibles());
        jSpinnerAPartir.setValue(p.getAPartirDe());
        jSpinnerPorcientoArea.setValue(p.getSalarioPorcientoDeArea());
        jSpinnerPorcientoVenta.setValue(p.getSalarioPorcientoVentaTotal());

    }

    private void crear() {
        int resp = JOptionPane.showConfirmDialog(this, "Desea crear el puesto de trabajo");
        if(resp == JOptionPane.YES_OPTION){
        try{
            
        String nombreOld = p.getNombrePuesto();
        p.setNombrePuesto(jTextFieldNombre.getText());
        p.setNombrePuesto(jTextFieldNombre.getText());
        p.setSalarioFijo((Integer) jSpinnerSalarioFijo.getValue());
        p.setAPartirDe((Integer) jSpinnerAPartir.getValue());
        p.setAreaPago((String) comboBoxAreaPago.getSelectedItem());
        p.setSalarioPorcientoDeArea((Float) jSpinnerPorcientoVenta.getValue());
        p.setSalarioPorcientoDeArea((Float) jSpinnerPorcientoArea.getValue());
        p.setNivelAcceso(comboBoxNivelAcceso.getSelectedIndex());
       
        p.setPuestosDisponibles((Integer) this.jSpinnerPuestosDisponibles.getValue());
        
        
        if(!nombreOld.isEmpty()){
        staticContent.puestosJPA.destroy(nombreOld);
        }
        
        staticContent.puestosJPA.create(p); 
        

    }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }
     JOptionPane.showMessageDialog(this, "Operacion realizada exitosamente");
     dispose();
    }
}
