/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views;

import GUI.Views.util.TableWithComboBoxAutoComplete;
import java.util.List;
import javax.swing.JTable;
import restManager.util.RestManagerAbstractTableModel;
import restManager.util.RestManagerComboBoxModel;

/**
 *
 * @author Jorge
 * @param <T> the table content data
 * @param <K> the combobox model data
 */
public abstract class AbstractCrossReferenePanel<T, K> extends javax.swing.JPanel {

    private final TableWithComboBoxAutoComplete<K, T> handler;

    /**
     * Creates new form AbstractCrossReferenePanel
     * @param comboBoxDataName
     * @param comboBoxData
     */
    public AbstractCrossReferenePanel(String comboBoxDataName, List<K> comboBoxData) {
        initComponents();
        jLabel1.setText(comboBoxDataName);
        handler = new TableWithComboBoxAutoComplete<K, T>(
                jTableCrossReference, jButtonAgregarProd,
                jButtonDeleteProd, jComboBoxAutoComplete,
                getTableModel(), new RestManagerComboBoxModel<K>(comboBoxData)) {
            @Override
            public T transformK_to_T(K selected) {
                return transformK_T(selected);
            }
        };
    }

    public abstract RestManagerAbstractTableModel<T> getTableModel();

    public abstract T transformK_T(K selected);

    public TableWithComboBoxAutoComplete<K, T> getHandler() {
        return handler;
    }

    public JTable getjTableCrossReference() {
        return jTableCrossReference;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAutoComplete = new com.jidesoft.swing.AutoCompletionComboBox();
        jButtonAgregarProd = new javax.swing.JButton();
        jScrollPaneCrossReference = new javax.swing.JScrollPane();
        jTableCrossReference = new javax.swing.JTable();
        jButtonDeleteProd = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jLabel1.setText(bundle.getString("label_producto_venta")); // NOI18N
        jPanel2.add(jLabel1);

        jComboBoxAutoComplete.setMaximumRowCount(5);
        jComboBoxAutoComplete.setPreferredSize(new java.awt.Dimension(250, 26));
        jPanel2.add(jComboBoxAutoComplete);

        jButtonAgregarProd.setText(bundle.getString("label_agregar")); // NOI18N
        jPanel2.add(jButtonAgregarProd);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPaneCrossReference.setMinimumSize(new java.awt.Dimension(454, 0));

        jTableCrossReference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPaneCrossReference.setViewportView(jTableCrossReference);

        add(jScrollPaneCrossReference, java.awt.BorderLayout.CENTER);

        jButtonDeleteProd.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProdActionPerformed(evt);
            }
        });
        add(jButtonDeleteProd, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProdActionPerformed

    }//GEN-LAST:event_jButtonDeleteProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProd;
    private javax.swing.JButton jButtonDeleteProd;
    private com.jidesoft.swing.AutoCompletionComboBox jComboBoxAutoComplete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneCrossReference;
    private javax.swing.JTable jTableCrossReference;
    // End of variables declaration//GEN-END:variables
}
