/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.almacen.ipv;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.domain.InsumoPedidoModel;
import com.jobits.pos.domain.ProdcutoVentaPedidoModel;
import com.jobits.pos.domain.models.Almacen;
import com.jobits.pos.domain.models.IpvVentaRegistro;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import static com.jobits.pos.ui.almacen.ipv.presenter.IPVPedidoVentasViewPresenter.*;
import static com.jobits.pos.ui.almacen.ipv.presenter.IPVPedidoVentasViewModel.*;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.AddFromPanel;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.utils.utils;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;

/**
 *
 * @author Home
 */
public class IPVPedidoVentasView extends AbstractViewPanel {

    public static final String VIEW_NAME = "IPV Pedido Ventas";
    private AddFromPanel<ProdcutoVentaPedidoModel, IpvVentaRegistro> tableAPedir;

    /**
     * Creates new form IPVPedidoVentasView
     *
     * @param presenter
     */
    public IPVPedidoVentasView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelMain = new javax.swing.JPanel();
        jPanelAPedir = new javax.swing.JPanel();
        jPanelPedido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getMaterialButton();

        setBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_COLOR, 2, true));
        setMaximumSize(new java.awt.Dimension(810, 550));
        setMinimumSize(new java.awt.Dimension(810, 550));
        setPreferredSize(new java.awt.Dimension(810, 550));
        setLayout(new java.awt.BorderLayout());

        jPanelTop.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        jLabel1.setText("Pedir del almcen");
        jPanel1.add(jLabel1);

        jComboBox1.setToolTipText("Pedir del almcen");
        jComboBox1.setPreferredSize(new java.awt.Dimension(170, 27));
        jPanel1.add(jComboBox1);

        jPanelTop.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        jPanelMain.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanelAPedir.setBorder(javax.swing.BorderFactory.createTitledBorder("A pedir"));
        jPanelAPedir.setPreferredSize(new java.awt.Dimension(100, 0));
        jPanelAPedir.setLayout(new java.awt.BorderLayout());
        jPanelMain.add(jPanelAPedir);

        jPanelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        jPanelPedido.setPreferredSize(new java.awt.Dimension(300, 0));
        jPanelPedido.setLayout(new java.awt.BorderLayout());

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePedido);

        jPanelPedido.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelMain.add(jPanelPedido);

        add(jPanelMain, java.awt.BorderLayout.CENTER);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorderPainted(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonCancelar);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonAceptar.setText(bundle.getString("label_confirmar")); // NOI18N
        jButtonAceptar.setBorderPainted(false);
        jButtonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAceptar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonAceptar);

        add(jPanelOpciones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
//        if (getController().realizarPedidoDeIpv(listaPedido.getItems(),
//            porPedirTable.getHandler().getTableModel().getItems(),
//            elaboracion, (Almacen) jComboBox1.getSelectedItem())) {
//        dispose();
//        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
//        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<Almacen> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAPedir;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPedido;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedido;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jComboBox1, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_ALMACEN),
                getPresenter().getModel(PROP_SELECCIONADO_ALMACEN)));

        Bindings.bind(jTablePedido, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_INSUMO_PEDIDO_MODEL),
                getPresenter().getModel(PROP_SELECCIONADO_INSUMO_PEDIDO)));

        jButtonAceptar.addActionListener(getPresenter().getOperation(ACTION_ACEPTAR));
        jButtonCancelar.addActionListener(getPresenter().getOperation(ACTION_CANCELAR));

    }

    @Override
    public void uiInit() {
        initComponents();

        AddFromPanel.AddFromPanelBuilder<ProdcutoVentaPedidoModel, IpvVentaRegistro> builder = AddFromPanel.builder();

        builder.addAction(getPresenter().getOperation(ACTION_AGREGAR_IPV));
        builder.removeAction(getPresenter().getOperation(ACTION_ELIMINAR_IPV));
        builder.autoCompletitionData(getPresenter().getModel(PROP_LISTA_IPV_VENTA_REGISTRO));
        builder.autoCOmpletitionDataSelection(getPresenter().getModel(PROP_SELECCIONADO_IPV_VENTAS));
        builder.jTextFieldDataName("Productos de IPV");
        builder.tableDataHolder(getPresenter().getModel(PROP_LISTA_PRODUCTO_VENTA_MODEL));
        builder.tableSelectionDataHolder(getPresenter().getModel(PROP_SELECCIONADO_PRODUCTO_VENTA));

        BindableTableModel<ProdcutoVentaPedidoModel> tableModel
                = new BindableTableModel<ProdcutoVentaPedidoModel>() {
            @Override
            public int getColumnCount() {
                return 2;

            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return getRow(rowIndex).getIpvProducto().getProductoVenta();
                    case 1:
                        return getRow(rowIndex).getCantidad();
                    default:
                        return null;
                }
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Producto IPV";
                    case 1:
                        return "Cantidad pedida";
                    default:
                        return null;
                }
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 1:
                        return Float.class;
                    default:
                        return super.getColumnClass(columnIndex);
                }
            }
        };
        builder.tableModel(tableModel);

        tableAPedir = builder.build();
        tableAPedir.getjTableCrossReference().getColumnModel().getColumn(1).setCellRenderer(utils.numberColumCellRender());
//        tableAPedir.getjButtonAgregarProd().setText("Registrar");
        jPanelAPedir.add(tableAPedir, BorderLayout.CENTER);

        jTablePedido.setModel(new BindableTableModel<InsumoPedidoModel>(jTablePedido) {
            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Insumo en almacen";
                    case 1:
                        return "Cantidad";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((InsumoPedidoModel) getListModel().getElementAt(rowIndex)).getInsumo();
                    case 1:
                        return ((InsumoPedidoModel) getListModel().getElementAt(rowIndex)).getCantidad();
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 1:
                        return Float.class;
                    default:
                        return super.getColumnClass(columnIndex);
                }
            }
        });
        jTablePedido.getRowSorter().toggleSortOrder(0);
        jTablePedido.getColumnModel().getColumn(1).setCellRenderer(utils.numberColumCellRender());
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;

    }
}
