/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.mesas;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jgoodies.common.collect.ArrayListModel;
import com.jobits.pos.core.domain.models.Area;
import com.jobits.pos.core.domain.models.Mesa;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.PopUpDialog;
import com.jobits.pos.ui.utils.WrapLayout;
import com.jobits.pos.ui.venta.mesas.presenter.MesaListViewModel;
import com.jobits.pos.ui.venta.mesas.presenter.MesaListViewPresenter;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.Component;
import java.awt.FlowLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JDialog;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Jorge
 */
public class MesaListView extends AbstractViewPanel implements PropertyChangeListener {

    public static final String VIEW_NAME = "Distribución mesas";

    private ArrayListModel<Mesa> listaMesas;
    private ArrayListModel<FloorTableButton> listaMesasBotones = new ArrayListModel<>();

    public MesaListView(AbstractViewPresenter presenter) {
        super(presenter);
        listUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = MaterialComponentsFactory.Buttons.getLinedButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), "Listado de mesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font(".SF NS Text", 1, 24))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setSize(new java.awt.Dimension(700, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jComboBox1.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel3.add(jComboBox1);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButton1.setText(bundle.getString("label_cancelar")); // NOI18N
        jPanel2.add(jButton1);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(700, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(700, 600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 0));
        jScrollPane1.setSize(new java.awt.Dimension(700, 0));

        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 2000));
        jPanel1.setSize(new java.awt.Dimension(700, 600));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void wireUp() {
        Bindings.bind(jComboBox1,
                new SelectionInList<Area>(
                        getPresenter().getModel(MesaListViewModel.PROP_LISTA_AREAS),
                        getPresenter().getModel(MesaListViewModel.PROP_AREA_SELECCIONADA)),"Seleccionar Area");
        jButton1.setAction(getPresenter().getOperation(MesaListViewPresenter.ACTION_CANCELAR));
      
    }

    @Override
    public void uiInit() {
        initComponents();
        listaMesas = ((MesaListViewModel) getPresenter().getBean()).getLista_elementos();
        listaMesas.addListDataListener(new ListDataListener() {
            @Override
            public void intervalAdded(ListDataEvent e) {
                listUpdate();
            }

            @Override
            public void intervalRemoved(ListDataEvent e) {
                listUpdate();
            }

            @Override
            public void contentsChanged(ListDataEvent e) {
                listUpdate();
            }

        });
        jPanel1.setLayout(new WrapLayout());
       
    }

    private void listUpdate() {
        jPanel1.removeAll();
        for (Mesa x : listaMesas) {
            jPanel1.add(createAndAttachButton(x));
        }

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Area> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Component createAndAttachButton(Mesa m) {
        FloorTableButton button = new FloorTableButton(m);
        listaMesasBotones.add(button);
        button.addPropertyChangeListener(this);
        return button;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(FloorTableButton.PROP_CLICK_MESA)) {
            firePropertyChange(evt.getPropertyName(), evt.getOldValue(), evt.getNewValue());
            getPresenter().setValue(MesaListViewModel.PROP_ELEMENTO_SELECCIONADO, evt.getNewValue());
            getPresenter().getOperation(MesaListViewPresenter.ACTION_ABRIR_MESA).doAction();
        }
    }

}
