/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui;

import com.jobits.pos.cordinator.MainNavigator;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.dashboard.DashBoardView;
import com.jobits.pos.ui.login.LogInView;
import com.jobits.pos.ui.login.UbicacionView;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.AutenticacionFragmentView;
import com.jobits.ui.components.MaterialComponentsFactory;
import components.containers.MaterialPanel;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;

/**
 *
 * @author Jorge
 */
public class RootView extends MaterialPanel {

    public static String VIEW_NAME = "Root View";

    private final CardLayout cards = new CardLayout();

    private MainMenuView dashboard;

    private StatusBarView statusBar = new StatusBarView(new StatusBarPresenter());

    private String currentDisplayedViewName;

    private Map<String, View> views = new HashMap<>();

    private static RootView instance;

    /**
     * Creates new form RootView
     */
    private RootView() {
        super();
        initComponents();
        jPanelContent.setLayout(cards);
        jPanelStatus.add(statusBar);

    }

    public static RootView getInstance() {
        if (instance == null) {
            instance = new RootView();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonBack = MaterialComponentsFactory.Buttons.getBackButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelMainMenu = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jPanelStatus = MaterialComponentsFactory.Containers.getSecondaryPanel();

        setLayout(new java.awt.BorderLayout());

        jPanelHeader.setOpaque(false);
        jPanelHeader.setPreferredSize(new java.awt.Dimension(120, 80));
        jPanelHeader.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButtonBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBack.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonBack.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonBack.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack);

        jPanelHeader.add(jPanel1, java.awt.BorderLayout.WEST);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/logo/banner.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelHeader.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        jPanelMainMenu.setOpaque(false);
        add(jPanelMainMenu, java.awt.BorderLayout.WEST);

        jPanelContent.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        add(jPanelContent, java.awt.BorderLayout.CENTER);

        jPanelStatus.setBackground(new java.awt.Color(204, 204, 204));
        jPanelStatus.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jPanelStatus.setMinimumSize(new java.awt.Dimension(5, 40));
        jPanelStatus.setPreferredSize(new java.awt.Dimension(5, 60));
        jPanelStatus.setLayout(new java.awt.BorderLayout());
        add(jPanelStatus, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        MainNavigator.getInstance().navigateUp();
    }//GEN-LAST:event_jButtonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelStatus;
    // End of variables declaration//GEN-END:variables

    private void addView(View view) {
        views.put(view.getViewName(), view);
        jPanelContent.add(view.getViewComponent(), view.getViewName());
    }

    public void showView(String viewNameToDisplay, AbstractViewPresenter presenter) {
        if (!views.containsKey(viewNameToDisplay)) {
            if (viewNameToDisplay.equals(MainMenuView.VIEW_NAME)) {
                if (dashboard == null) {
                    dashboard = (MainMenuView) ViewFacade.getView(viewNameToDisplay, presenter);
                    jPanelMainMenu.add(dashboard);
                    statusBar.refreshView();
                }
                viewNameToDisplay = DashBoardView.VIEW_NAME;//TODO: cuando se vuelva a la ventana de loggeo vaciar el usuario loggeado

            }

        } else {
            cards.removeLayoutComponent(views.get(viewNameToDisplay).getViewComponent());
        }
        addView(ViewFacade.getView(viewNameToDisplay, presenter));
        currentDisplayedViewName = viewNameToDisplay;
        boolean displayAggregatesViews = !(currentDisplayedViewName.equals(LogInView.VIEW_NAME)
                || currentDisplayedViewName.equals(UbicacionView.VIEW_NAME));
        jPanelHeader.setVisible(!currentDisplayedViewName.equals(LogInView.VIEW_NAME));
        jPanelMainMenu.setVisible(displayAggregatesViews);
        jPanelStatus.setVisible(displayAggregatesViews);
        cards.show(jPanelContent, currentDisplayedViewName);
        repaint();

    }

    public String getCurrentViewName(String name) {
        return currentDisplayedViewName;
    }

}
