/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.clientes;

import com.jobits.pos.cliente.core.domain.DireccionEnvioDomain;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.ui.components.MaterialComponentsFactory;

/**
 *
 * @author Home
 */
public class CellRenderDireccionEnvio extends javax.swing.JPanel {

    DireccionEnvioDomain direccion;

    /**
     * Creates new form CellRenderDireccionEnvio
     *
     * @param direccion
     * @param selected
     */
    public CellRenderDireccionEnvio(DireccionEnvioDomain direccion, boolean selected) {
        initComponents();
        this.direccion = direccion;
        this.setToolTipText(getDescription());
        jPanel1.setOpaque(selected);
        jLabelAlias.setText(direccion.getAlias());
        jLabelTelefono.setText(direccion.getTelefono());
        jTextAreaDireccion.setText(direccion.getDireccion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAlias = new javax.swing.JLabel();
        jTextAreaDireccion = new javax.swing.JTextArea();
        jLabelTelefono = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setMaximumSize(new java.awt.Dimension(150, 120));
        setMinimumSize(new java.awt.Dimension(150, 120));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(150, 120));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(DefaultValues.SECONDARY_COLOR);
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_DARK, 1, true), javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelAlias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAlias.setText("<Alias>");
        jPanel1.add(jLabelAlias, java.awt.BorderLayout.NORTH);

        jTextAreaDireccion.setEditable(false);
        jTextAreaDireccion.setColumns(20);
        jTextAreaDireccion.setLineWrap(true);
        jTextAreaDireccion.setRows(5);
        jTextAreaDireccion.setText("<Direccion>");
        jTextAreaDireccion.setWrapStyleWord(true);
        jTextAreaDireccion.setOpaque(false);
        jPanel1.add(jTextAreaDireccion, java.awt.BorderLayout.CENTER);

        jLabelTelefono.setForeground(DefaultValues.PRIMARY_COLOR_DARK);
        jLabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefono.setText("<Telefono>");
        jPanel1.add(jLabelTelefono, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlias;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextAreaDireccion;
    // End of variables declaration//GEN-END:variables
    private String getDescription() {
        String apellidos, empresa, direccion_adicional;

        apellidos = direccion.getApellidos() != null ? direccion.getApellidos() : "---";
        empresa = direccion.getEmpresa() != null ? direccion.getEmpresa() : "---";
        direccion_adicional = direccion.getDireccionAdicional() != null ? direccion.getDireccionAdicional() : "---";

        return "<html>"
                + "Alias: " + direccion.getAlias() + "<br>"
                + "Nombre: " + direccion.getNombre() + "<br>"
                + "Apellidos: " + apellidos + "<br>"
                + "Telefono: " + direccion.getTelefono() + "<br>"
                + "Empresa: " + empresa + "<br>"
                + "Direccion: " + direccion.getDireccion() + "<br>"
                + "Direccion Adicional: " + direccion_adicional + "<br>"
                + "Ciudad: " + direccion.getCiudad() + "<br>"
                + "Provincia: " + direccion.getProvincia() + "<br>"
                + "</html>";

    }
}
