/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.Almacen;

import GUI.Views.AbstractView;
import GUI.Views.util.RestaurantManagerListIntelliHint;
import java.awt.Dialog;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import restManager.controller.AbstractDialogController;
import restManager.controller.almacen.AlmacenManageController;
import restManager.controller.almacen.AlmacenManageController.CheckBoxType;
import restManager.exceptions.DevelopingOperationException;
import restManager.exceptions.UnExpectedErrorException;
import restManager.persistencia.Almacen;
import restManager.persistencia.Cocina;
import restManager.persistencia.InsumoAlmacen;
import restManager.persistencia.volatil.TransaccionSimple;
import restManager.util.RestManagerComboBoxModel;

/**
 *
 * @author Jorge
 */
public class OperacionView extends AbstractView {

    private AlmacenManageController controller;
    private CheckBoxType tipoOperacion = CheckBoxType.ENTRADA;
    private ArrayList<TransaccionSimple> transacciones = new ArrayList<>();
    private RestaurantManagerListIntelliHint<InsumoAlmacen> list;

    public OperacionView(AbstractDialogController controller) {

        super(DialogType.INPUT_LARGE, controller);
        this.controller = (AlmacenManageController) controller;
        initComponents();
        buttonGroup1.add(jRadioButtonTraspaso);
        buttonGroup1.add(jRadioButtonSalida);
        buttonGroup1.add(jRadioButtonRebaja);
        buttonGroup1.add(jRadioButtonEntrada);
        jComboBoxAlmacenExistencias.setVisible(false);
        jTextFieldCausa.setVisible(false);
        list = new RestaurantManagerListIntelliHint<>(jTextFieldInsumo, this.controller.getInsumoAlmacenList(this.controller.getInstance()));
        setVisible(true);

    }

    /**
     * Creates new form OperacionView
     *
     * @param controller
     * @param owner
     * @param modal
     */
    public OperacionView(AbstractDialogController controller, Dialog owner, boolean modal) {
        super(DialogType.INPUT_LARGE, controller, owner, modal);
        this.controller = (AlmacenManageController) controller;
        initComponents();
        buttonGroup1.add(jRadioButtonTraspaso);
        buttonGroup1.add(jRadioButtonSalida);
        buttonGroup1.add(jRadioButtonRebaja);
        buttonGroup1.add(jRadioButtonEntrada);
        jComboBoxAlmacenExistencias.setVisible(false);
        jTextFieldCausa.setVisible(false);
        list = new RestaurantManagerListIntelliHint<>(jTextFieldInsumo, this.controller.getInsumoAlmacenList(this.controller.getInstance()));
        jDateChooser1.setDate(new Date());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonConfirmar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButtonEntrada = new javax.swing.JRadioButton();
        jRadioButtonTraspaso = new javax.swing.JRadioButton();
        jRadioButtonSalida = new javax.swing.JRadioButton();
        jRadioButtonRebaja = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInsumo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldCantidad = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldMonto = new javax.swing.JFormattedTextField();
        jComboBoxAlmacenExistencias = new javax.swing.JComboBox<>();
        jTextFieldCausa = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRecibo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonConfirmar.setForeground(new java.awt.Color(0, 153, 153));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/confirmar.png"))); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonConfirmar.setToolTipText(bundle.getString("label_confirmar")); // NOI18N
        jButtonConfirmar.setBorderPainted(false);
        jButtonConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConfirmar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel8.setOpaque(false);

        jRadioButtonEntrada.setSelected(true);
        jRadioButtonEntrada.setText(bundle.getString("label_entrada")); // NOI18N
        jRadioButtonEntrada.setToolTipText("");
        jRadioButtonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonEntrada);

        jRadioButtonTraspaso.setText(bundle.getString("label_traspaso")); // NOI18N
        jRadioButtonTraspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTraspasoActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonTraspaso);

        jRadioButtonSalida.setText(bundle.getString("label_salida")); // NOI18N
        jRadioButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSalidaActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonSalida);

        jRadioButtonRebaja.setText(bundle.getString("label_rebaja")); // NOI18N
        jRadioButtonRebaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRebajaActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButtonRebaja);

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel1.add(jDateChooser1, java.awt.BorderLayout.EAST);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/logout40.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumo", "Cantidad", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Agregar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Insumo");
        jPanel5.add(jLabel2);

        jTextFieldInsumo.setToolTipText("Insumo");
        jTextFieldInsumo.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextFieldInsumo.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextFieldInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsumoActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldInsumo);

        jLabel3.setText("Cantidad");
        jPanel5.add(jLabel3);

        jFormattedTextFieldCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldCantidad.setPreferredSize(new java.awt.Dimension(80, 26));
        jFormattedTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel5.add(jFormattedTextFieldCantidad);

        jLabel4.setText("Monto");
        jPanel5.add(jLabel4);

        jFormattedTextFieldMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldMonto.setPreferredSize(new java.awt.Dimension(80, 26));
        jFormattedTextFieldMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMontoActionPerformed(evt);
            }
        });
        jPanel5.add(jFormattedTextFieldMonto);

        jComboBoxAlmacenExistencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(jComboBoxAlmacenExistencias);

        jTextFieldCausa.setText("Causa");
        jTextFieldCausa.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel5.add(jTextFieldCausa);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAdd, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setText("No. Recibo");
        jPanel4.add(jLabel1);

        jTextFieldRecibo.setToolTipText("");
        jTextFieldRecibo.setPreferredSize(new java.awt.Dimension(150, 26));
        jTextFieldRecibo.setSize(new java.awt.Dimension(150, 26));
        jPanel4.add(jTextFieldRecibo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        aceptarOperacion();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jRadioButtonRebajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRebajaActionPerformed
        onCheckedCheckBox(CheckBoxType.REBAJA);
    }//GEN-LAST:event_jRadioButtonRebajaActionPerformed

    private void jRadioButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSalidaActionPerformed
        onCheckedCheckBox(CheckBoxType.SALIDA);
    }//GEN-LAST:event_jRadioButtonSalidaActionPerformed

    private void jRadioButtonTraspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTraspasoActionPerformed
        onCheckedCheckBox(CheckBoxType.TRASPASO);
    }//GEN-LAST:event_jRadioButtonTraspasoActionPerformed

    private void jRadioButtonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaActionPerformed
        onCheckedCheckBox(CheckBoxType.ENTRADA);
    }//GEN-LAST:event_jRadioButtonEntradaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        ejecutarOperacion();

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsumoActionPerformed
        jTextFieldInsumo.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsumoActionPerformed

    private void jFormattedTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCantidadActionPerformed
        jFormattedTextFieldCantidad.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCantidadActionPerformed

    private void jFormattedTextFieldMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMontoActionPerformed
        jFormattedTextFieldMonto.transferFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldMontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<Object> jComboBoxAlmacenExistencias;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCantidad;
    private javax.swing.JFormattedTextField jFormattedTextFieldMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButtonEntrada;
    private javax.swing.JRadioButton jRadioButtonRebaja;
    private javax.swing.JRadioButton jRadioButtonSalida;
    private javax.swing.JRadioButton jRadioButtonTraspaso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCausa;
    private javax.swing.JTextField jTextFieldInsumo;
    private javax.swing.JTextField jTextFieldRecibo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
        throw new DevelopingOperationException(); //To change body of generated methods, choose Tools | Templates.
    }

    private void onCheckedCheckBox(CheckBoxType checkBoxType) {
        //configurando modelo del combo box
        switch (checkBoxType) {
            case SALIDA:
                jComboBoxAlmacenExistencias.setModel(new RestManagerComboBoxModel(controller.getCocinaList()));
                break;
            case TRASPASO:
                jComboBoxAlmacenExistencias.setModel(new RestManagerComboBoxModel(controller.getItems()));
                break;
        }

        //cambiando columna tabla
        String columnName;
        switch (tipoOperacion) {
            case ENTRADA:
                columnName = "Monto";
                break;
            case REBAJA:
                columnName = "Causa Rebaja";
                break;
            case TRASPASO:
            case SALIDA:
                columnName = "Destino";
                break;
            default:
                columnName = "No Definido";
        }
        jTable1.getColumnModel().getColumn(2).setHeaderValue(columnName);

        //cambiando la estructura de los campos a rellenar
        jTextFieldCausa.setVisible(checkBoxType == CheckBoxType.REBAJA);
        jFormattedTextFieldMonto.setVisible(checkBoxType == CheckBoxType.ENTRADA);
        jComboBoxAlmacenExistencias.setVisible(checkBoxType == CheckBoxType.SALIDA || checkBoxType == CheckBoxType.TRASPASO);
        tipoOperacion = checkBoxType;
    }

    private void ejecutarOperacion() {
        long cantidad = (long) jFormattedTextFieldCantidad.getValue();
        TransaccionSimple transaccion = new TransaccionSimple(list.getSelectedHint(), (float) cantidad);
        Object[] row = new Object[3];
        row[0] = transaccion.getInsumo();
        row[1] = transaccion.getCantidad();
        switch (tipoOperacion) {
            case ENTRADA:
                long c = (long) jFormattedTextFieldMonto.getValue();
                transaccion.setMonto((float) c);

                row[2] = transaccion.getMonto();
                break;
            case SALIDA:
                transaccion.setcDestino((Cocina) jComboBoxAlmacenExistencias.getSelectedItem());
                row[2] = transaccion.getcDestino();
                break;
            case REBAJA:
                transaccion.setCausa(jTextFieldCausa.getText());
                row[2] = transaccion.getCausa();
                break;
            case TRASPASO:
                transaccion.setaDestino((Almacen) jComboBoxAlmacenExistencias.getSelectedItem());
                row[2] = transaccion.getaDestino();
                break;
            default:
                throw new UnExpectedErrorException(this, "Tipo de operacion no soportada");
        }
        transacciones.add(transaccion);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(row);

    }

    private void aceptarOperacion() {
        controller.crearOperacion(this.transacciones, tipoOperacion, jDateChooser1.getDate(), jTextFieldRecibo.getText());
        dispose();
    }

}
