/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.configuracion;

import com.jobits.pos.ui.OldAbstractView;
import com.jobits.pos.ui.utils.ComboBoxWithList;
import com.jobits.pos.ui.utils.TableWithComboBoxAutoComplete;
import java.awt.Dialog;
import java.util.Arrays;
import com.jobits.pos.controller.AbstractDialogController;
import com.jobits.pos.controller.licencia.Licence;
import com.jobits.pos.controller.licencia.LicenceController;
import com.jobits.pos.controller.configuracion.ConfiguracionController;
import com.jobits.pos.controller.login.UbicacionConexionController;
import com.jobits.pos.exceptions.DevelopingOperationException;
import com.jobits.pos.domain.models.Seccion;
import com.jobits.pos.domain.UbicacionConexionModel;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.utils.RestManagerComboBoxModel;
import com.jobits.pos.ui.utils.RestManagerListModel;

/**
 *
 * @author Jorge
 */
public class ConfiguracionView extends OldAbstractView {

    private ComboBoxWithList<Seccion> bebida, excluir;

    public ConfiguracionView(AbstractDialogController controller, Dialog owner) {
        super(DialogType.INPUT, controller, owner);
        initComponents();
        fetchComponentData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAplicar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelGenerales = new javax.swing.JPanel();
        jPanelNegocio = new javax.swing.JPanel();
        jPanel24HR = new javax.swing.JPanel();
        jCheckBoxMultiplesTurnos = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipoNegocio = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCambioMoneda = new javax.swing.JComboBox<>();
        jPanelCaja = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxPermEsp = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxMesaFija = new javax.swing.JCheckBox();
        jPanelImpresion = new javax.swing.JPanel();
        jPanelGeneral = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jCheckBoxTicketCocina = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jCheckBoxRounding = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jCheckBoxBuzzer = new javax.swing.JCheckBox();
        jPanelCaracterSeparador1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCantCopias = new javax.swing.JComboBox<>();
        jPanelTickets = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jCheckBoxEncabezadoRestaurante = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jCheckBoxSegundaMoneda = new javax.swing.JCheckBox();
        jPanelCaracterSeparador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCaracterSeparador = new javax.swing.JComboBox<>();
        jPanelTamannoPapel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTamannoTicket = new javax.swing.JComboBox<>();
        jPanelSincronizacion = new javax.swing.JPanel();
        jPanelNegocio1 = new javax.swing.JPanel();
        jPanel24HR1 = new javax.swing.JPanel();
        jCheckBoxHabilitarSincronizacion = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSincronizacionUbicacion = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jPanelY = new javax.swing.JPanel();
        jPanelPorcientoEstimado = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerM = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerC = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jPanelExcluir = new javax.swing.JPanel();
        jPanelBebidas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(getMinimumSize());
        setUndecorated(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonCancelar.setText(bundle.getString("label_cancelar")); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonCancelar);

        jButtonAplicar.setText(bundle.getString("label_aplicar")); // NOI18N
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonAplicar);

        jButtonAceptar.setText(bundle.getString("label_aceptar")); // NOI18N
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonAceptar);

        getContentPane().add(jPanel12, java.awt.BorderLayout.PAGE_END);

        jPanelGenerales.setLayout(new javax.swing.BoxLayout(jPanelGenerales, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelNegocio.setBorder(javax.swing.BorderFactory.createTitledBorder("Negocio"));
        jPanelNegocio.setLayout(new java.awt.GridLayout(3, 1, 0, 3));

        jPanel24HR.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxMultiplesTurnos.setText("Abierto 24 horas");
        jCheckBoxMultiplesTurnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBoxMultiplesTurnos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel24HR.add(jCheckBoxMultiplesTurnos);

        jPanelNegocio.add(jPanel24HR);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Tipo Negocio");
        jPanel7.add(jLabel2);

        jComboBoxTipoNegocio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurante", "Cafeteria", "Bar", "Carniceria", "Dulceria", "Tienda" }));
        jPanel7.add(jComboBoxTipoNegocio);

        jPanelNegocio.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Cambio de moneda");
        jPanel9.add(jLabel1);

        jComboBoxCambioMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24", "25" }));
        jPanel9.add(jComboBoxCambioMoneda);

        jPanelNegocio.add(jPanel9);

        jPanelGenerales.add(jPanelNegocio);

        jPanelCaja.setBorder(javax.swing.BorderFactory.createTitledBorder("Caja"));
        jPanelCaja.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxPermEsp.setText("Permisos Especiales");
        jCheckBoxPermEsp.setToolTipText("Marcar para que el cajero pueda tener acceso a la venta general del dia");
        jPanel2.add(jCheckBoxPermEsp);

        jPanelCaja.add(jPanel2);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxMesaFija.setText("Venta por mesa fija");
        jCheckBoxMesaFija.setToolTipText("Marcar si el cajero solo puede vender por una mesa especifica");
        jPanel1.add(jCheckBoxMesaFija);

        jPanelCaja.add(jPanel1);

        jPanelGenerales.add(jPanelCaja);

        jTabbedPane1.addTab("Generales", jPanelGenerales);

        jPanelImpresion.setLayout(new javax.swing.BoxLayout(jPanelImpresion, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Generales"));
        jPanelGeneral.setLayout(new javax.swing.BoxLayout(jPanelGeneral, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxTicketCocina.setText("Imprimir ticket a elaboracion");
        jCheckBoxTicketCocina.setToolTipText("");
        jPanel11.add(jCheckBoxTicketCocina);

        jPanelGeneral.add(jPanel11);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxRounding.setText("Redondeo por exceso en tickets");
        jCheckBoxRounding.setToolTipText("Redondear todos los valores por exceso");
        jPanel10.add(jCheckBoxRounding);

        jPanelGeneral.add(jPanel10);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxBuzzer.setText("Buzzer");
        jCheckBoxBuzzer.setToolTipText("Redondear todos los valores por exceso");
        jPanel14.add(jCheckBoxBuzzer);

        jPanelGeneral.add(jPanel14);

        jPanelCaracterSeparador1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Cantidad de copias de impresión");
        jPanelCaracterSeparador1.add(jLabel5);

        jComboBoxCantCopias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBoxCantCopias.setToolTipText("el valor 0 es solo la original");
        jPanelCaracterSeparador1.add(jComboBoxCantCopias);

        jPanelGeneral.add(jPanelCaracterSeparador1);

        jPanelImpresion.add(jPanelGeneral);

        jPanelTickets.setBorder(javax.swing.BorderFactory.createTitledBorder("Tickets"));
        jPanelTickets.setLayout(new javax.swing.BoxLayout(jPanelTickets, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxEncabezadoRestaurante.setText("Mostrar encabezado en tickets");
        jCheckBoxEncabezadoRestaurante.setToolTipText("");
        jPanel8.add(jCheckBoxEncabezadoRestaurante);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxSegundaMoneda.setText("Imprimir total en segunda moneda");
        jCheckBoxSegundaMoneda.setToolTipText("");
        jPanel13.add(jCheckBoxSegundaMoneda);

        jPanel8.add(jPanel13);

        jPanelTickets.add(jPanel8);

        jPanelCaracterSeparador.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Caracter separador");
        jPanelCaracterSeparador.add(jLabel3);

        jComboBoxCaracterSeparador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "-", "/", "+", "ˆ" }));
        jPanelCaracterSeparador.add(jComboBoxCaracterSeparador);

        jPanelTickets.add(jPanelCaracterSeparador);

        jPanelTamannoPapel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Tamanno Ticket");
        jLabel4.setToolTipText("");
        jPanelTamannoPapel.add(jLabel4);

        jComboBoxTamannoTicket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "58mm", "80mm" }));
        jPanelTamannoPapel.add(jComboBoxTamannoTicket);

        jPanelTickets.add(jPanelTamannoPapel);

        jPanelImpresion.add(jPanelTickets);

        jTabbedPane1.addTab("Impresion", jPanelImpresion);

        jPanelSincronizacion.setLayout(new javax.swing.BoxLayout(jPanelSincronizacion, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelNegocio1.setBorder(javax.swing.BorderFactory.createTitledBorder("Negocio"));
        jPanelNegocio1.setLayout(new java.awt.GridLayout(3, 1, 0, 3));

        jPanel24HR1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBoxHabilitarSincronizacion.setText("Habilitar sincronizacion");
        jCheckBoxHabilitarSincronizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBoxHabilitarSincronizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel24HR1.add(jCheckBoxHabilitarSincronizacion);

        jPanelNegocio1.add(jPanel24HR1);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Ubicacion");
        jPanel15.add(jLabel6);

        jComboBoxSincronizacionUbicacion.setPreferredSize(new java.awt.Dimension(200, 27));
        jPanel15.add(jComboBoxSincronizacionUbicacion);

        jPanelNegocio1.add(jPanel15);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Sincronizar cada");
        jPanel16.add(jLabel7);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));
        jSpinner1.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel16.add(jSpinner1);

        jLabel8.setText("Minuto(s)");
        jLabel8.setToolTipText("");
        jPanel16.add(jLabel8);

        jPanelNegocio1.add(jPanel16);

        jPanelSincronizacion.add(jPanelNegocio1);

        jTabbedPane1.addTab("Sincronizacion", jPanelSincronizacion);

        jPanelY.setLayout(new java.awt.BorderLayout());

        jPanelPorcientoEstimado.setOpaque(false);

        jLabel12.setText("M");
        jPanelPorcientoEstimado.add(jLabel12);

        jSpinnerM.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        jPanelPorcientoEstimado.add(jSpinnerM);

        jLabel13.setText("C");
        jPanelPorcientoEstimado.add(jLabel13);

        jSpinnerC.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 5));
        jPanelPorcientoEstimado.add(jSpinnerC);

        jPanelY.add(jPanelPorcientoEstimado, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanelExcluir.setBorder(javax.swing.BorderFactory.createTitledBorder("Excluir"));
        jPanelExcluir.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanelExcluir.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanelExcluir);

        jPanelBebidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Bebidas"));
        jPanelBebidas.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanelBebidas.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanelBebidas);

        jPanelY.add(jPanel3, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Y", jPanelY);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        validateData();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        validateData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    @Override
    public void fetchComponentData() {
        UbicacionConexionController ubicacionController = new UbicacionConexionController();
        jComboBoxSincronizacionUbicacion.setModel(new RestManagerComboBoxModel<>(Arrays.asList(ubicacionController.getUbicaciones().getUbicaciones())));
    }

    @Override
    public void updateView() {
        jCheckBoxMultiplesTurnos.setSelected((boolean) fetch(R.SettingID.GENERAL_TURNOS_VARIOS));
        jComboBoxCambioMoneda.setSelectedItem(fetch(R.SettingID.GENERAL_CAMBIO_MONEDA));
        jCheckBoxPermEsp.setSelected((boolean) fetch(R.SettingID.GENERAL_CAJERO_PERMISOS_ESP));
        jCheckBoxMesaFija.setSelected((boolean) fetch(R.SettingID.GENERAL_MESA_FIJA_CAJERO));
        jCheckBoxTicketCocina.setSelected((boolean) fetch(R.SettingID.IMPRESION_IMPRIMIR_TICKET_EN_COCINA));
        jCheckBoxRounding.setSelected((boolean) fetch(R.SettingID.IMPRESION_REDONDEO_EXCESO));
        jComboBoxCantCopias.setSelectedItem(fetch(R.SettingID.IMPRESION_CANTIDAD_COPIAS));
        jCheckBoxEncabezadoRestaurante.setSelected((boolean) fetch(R.SettingID.IMPRESION_TICKET_ENCABEZADO_RESTAURANTE));
        jComboBoxCaracterSeparador.setSelectedItem(fetch(R.SettingID.IMPRESION_TICKET_CARACTER_SEPARADOR));
        jComboBoxTipoNegocio.setSelectedItem(fetch(R.SettingID.IMPRESION_TICKET_VALOR_ENCABEZADO));
        jCheckBoxSegundaMoneda.setSelected((boolean) fetch(R.SettingID.IMPRESION_IMPRIMIR_MONEDA_SECUNDARIA));
        jCheckBoxBuzzer.setSelected((boolean) fetch(R.SettingID.IMPRESION_BUZZER_ON));
        jCheckBoxHabilitarSincronizacion.setSelected((boolean) fetch(R.SettingID.SINCRONIZACION_HABILITAR));
        jComboBoxSincronizacionUbicacion.setSelectedIndex(Integer.valueOf(fetch(R.SettingID.SINCRONIZACION_UBICACION).toString()));
        jSpinner1.setValue(Integer.parseInt(fetch(R.SettingID.SINCRONIZACION_TIEMPO_LOOP).toString())/60/1000);
        int selected = 0;
        if (fetch(R.SettingID.IMPRESION_TICKET_TAMANO_PAPEL).equals("48")) {
            selected = 1;
        }
        jComboBoxTamannoTicket.setSelectedIndex(selected);

        LicenceController controller = new LicenceController(Licence.TipoLicencia.SECUNDARIA);
        if (!controller.getLicence().LICENCIA_ACTIVA || !controller.getLicence().LICENCIA_VALIDA) {
            jTabbedPane1.remove(2);
        }

        getController().cargarConfiguracionY();
        jSpinnerC.setValue(new Byte(getController().getConfiguracionY().getC()).intValue());
        jSpinnerM.setValue(new Byte(getController().getConfiguracionY().getM()).intValue());

        excluir = new ComboBoxWithList<>(getController().getSeccionList(), getController().getConfiguracionY().getExcluidos());
        bebida = new ComboBoxWithList<>(getController().getSeccionList(), getController().getConfiguracionY().getBebidas());
        jPanelBebidas.add(bebida);
        jPanelExcluir.add(excluir);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxBuzzer;
    private javax.swing.JCheckBox jCheckBoxEncabezadoRestaurante;
    private javax.swing.JCheckBox jCheckBoxHabilitarSincronizacion;
    private javax.swing.JCheckBox jCheckBoxMesaFija;
    private javax.swing.JCheckBox jCheckBoxMultiplesTurnos;
    private javax.swing.JCheckBox jCheckBoxPermEsp;
    private javax.swing.JCheckBox jCheckBoxRounding;
    private javax.swing.JCheckBox jCheckBoxSegundaMoneda;
    private javax.swing.JCheckBox jCheckBoxTicketCocina;
    private javax.swing.JComboBox<String> jComboBoxCambioMoneda;
    private javax.swing.JComboBox<String> jComboBoxCantCopias;
    private javax.swing.JComboBox<String> jComboBoxCaracterSeparador;
    private javax.swing.JComboBox<UbicacionConexionModel> jComboBoxSincronizacionUbicacion;
    private javax.swing.JComboBox<String> jComboBoxTamannoTicket;
    private javax.swing.JComboBox<String> jComboBoxTipoNegocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24HR;
    private javax.swing.JPanel jPanel24HR1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBebidas;
    private javax.swing.JPanel jPanelCaja;
    private javax.swing.JPanel jPanelCaracterSeparador;
    private javax.swing.JPanel jPanelCaracterSeparador1;
    private javax.swing.JPanel jPanelExcluir;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelGenerales;
    private javax.swing.JPanel jPanelImpresion;
    private javax.swing.JPanel jPanelNegocio;
    private javax.swing.JPanel jPanelNegocio1;
    private javax.swing.JPanel jPanelPorcientoEstimado;
    private javax.swing.JPanel jPanelSincronizacion;
    private javax.swing.JPanel jPanelTamannoPapel;
    private javax.swing.JPanel jPanelTickets;
    private javax.swing.JPanel jPanelY;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerC;
    private javax.swing.JSpinner jSpinnerM;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public ConfiguracionController getController() {
        return (ConfiguracionController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }

    private Object fetch(R.SettingID settingID) {
        return getController().getConfiguracion(settingID);
    }

    private void save(R.SettingID settingID, Object update) {
        getController().updateConfiguracion(settingID, update);
    }

    private void validateData() {
        save(R.SettingID.GENERAL_TURNOS_VARIOS, jCheckBoxMultiplesTurnos.isSelected());
        save(R.SettingID.GENERAL_CAMBIO_MONEDA, jComboBoxCambioMoneda.getSelectedItem());
        save(R.SettingID.GENERAL_CAJERO_PERMISOS_ESP, jCheckBoxPermEsp.isSelected());
        save(R.SettingID.GENERAL_MESA_FIJA_CAJERO, jCheckBoxMesaFija.isSelected());
        save(R.SettingID.IMPRESION_IMPRIMIR_TICKET_EN_COCINA, jCheckBoxTicketCocina.isSelected());
        save(R.SettingID.IMPRESION_REDONDEO_EXCESO, jCheckBoxRounding.isSelected());
        save(R.SettingID.IMPRESION_CANTIDAD_COPIAS, jComboBoxCantCopias.getSelectedItem());
        save(R.SettingID.IMPRESION_TICKET_ENCABEZADO_RESTAURANTE, jCheckBoxEncabezadoRestaurante.isSelected());
        save(R.SettingID.IMPRESION_TICKET_CARACTER_SEPARADOR, jComboBoxCaracterSeparador.getSelectedItem());
        save(R.SettingID.IMPRESION_TICKET_VALOR_ENCABEZADO, jComboBoxTipoNegocio.getSelectedItem());
        save(R.SettingID.IMPRESION_IMPRIMIR_MONEDA_SECUNDARIA, jCheckBoxSegundaMoneda.isSelected());
        save(R.SettingID.IMPRESION_BUZZER_ON, jCheckBoxBuzzer.isSelected());
        save(R.SettingID.SINCRONIZACION_HABILITAR,jCheckBoxHabilitarSincronizacion.isSelected());
        save(R.SettingID.SINCRONIZACION_UBICACION, jComboBoxSincronizacionUbicacion.getSelectedIndex());
        save(R.SettingID.SINCRONIZACION_TIEMPO_LOOP,((int) jSpinner1.getValue() * 60 * 1000));
        String selected = "32";
        if (jComboBoxTamannoTicket.getSelectedItem().equals("80mm")) {
            selected = "48";
        }
        save(R.SettingID.IMPRESION_TICKET_TAMANO_PAPEL, selected);

        getController().getConfiguracionY().setC(new Integer((int) jSpinnerC.getValue()).byteValue());
        getController().getConfiguracionY().setM(new Integer((int) jSpinnerM.getValue()).byteValue());
        getController().getConfiguracionY().setBebidas(bebida.getListModel().getElements());
        getController().getConfiguracionY().setExcluidos(excluir.getListModel().getElements());
        getController().updateConfiguracionY(getController().getConfiguracionY());

    }

}
