/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.configuracion;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.controller.productos.ProductoVentaListController;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.configuracion.presenter.ImportarExportarViewModel;
import com.jobits.pos.ui.configuracion.presenter.ImportarExportarViewPresenter;
import com.jobits.pos.ui.configuracion.presenter.ImpresorasViewModel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import java.awt.Container;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.util.ResourceBundle;

/**
 *
 * @author Home
 */
public class ImportarExportar extends AbstractViewPanel {

    public static final String VIEW_NAME = "Importar Exportar";

    /**
     * Creates new form ImportarExportar2
     *
     * @param presenter
     */
    public ImportarExportar(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImportarExportar = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel2 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxImportarExportar = MaterialComponentsFactory.Displayers.getComboBox();
        jComboBoxDatosAGuardar = MaterialComponentsFactory.Displayers.getComboBox();
        jPanel3 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel1 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jButtonAbrirGuardar = MaterialComponentsFactory.Buttons.getOutlinedButton();

        setPreferredSize(new java.awt.Dimension(730, 525));

        jPanelImportarExportar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelImportarExportar.setPreferredSize(new java.awt.Dimension(730, 525));
        jPanelImportarExportar.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(150, 1, 1, 1));

        jPanel5.setLayout(new java.awt.GridLayout(2, 1, 20, 100));

        jComboBoxImportarExportar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxImportarExportar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxImportarExportar.setPreferredSize(new java.awt.Dimension(200, 50));
        jComboBoxImportarExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxImportarExportarActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBoxImportarExportar);

        jComboBoxDatosAGuardar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBoxDatosAGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBoxDatosAGuardar.setPreferredSize(new java.awt.Dimension(200, 50));
        jComboBoxDatosAGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDatosAGuardarActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBoxDatosAGuardar);

        jPanel2.add(jPanel5);

        jPanelImportarExportar.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 5, 20));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, DefaultValues.SECONDARY_COLOR_LIGHT));

        jButtonAbrirGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAbrirGuardar.setText("---");
        jButtonAbrirGuardar.setAutoscrolls(true);
        jButtonAbrirGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAbrirGuardar);

        jPanel3.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanelImportarExportar.add(jPanel3, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelImportarExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelImportarExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirGuardarActionPerformed
    }//GEN-LAST:event_jButtonAbrirGuardarActionPerformed

    private void jComboBoxImportarExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxImportarExportarActionPerformed
    }//GEN-LAST:event_jComboBoxImportarExportarActionPerformed

    private void jComboBoxDatosAGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDatosAGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDatosAGuardarActionPerformed
    @Override
    public void wireUp() {
        Bindings.bind(jComboBoxImportarExportar, new SelectionInList<String>(
                getPresenter().getModel(ImportarExportarViewModel.PROP_IMPORTAR_EXPORTAR_OPCIONES),
                getPresenter().getModel(ImportarExportarViewModel.PROP_IMPORTAR_EXPORTAR_OPCION_SELECCIONADA)),
                ResourceBundle.getBundle("Strings").getString("label_opcion"));
        Bindings.bind(jComboBoxDatosAGuardar, new SelectionInList<String>(
                getPresenter().getModel(ImportarExportarViewModel.PROP_LISTA_TIPO_DATOS),
                getPresenter().getModel(ImportarExportarViewModel.PROP_TIPO_DATO_SELECCIONADO)),
                "Archivo");
        Bindings.bind(jButtonAbrirGuardar, "text", getPresenter().getModel(ImportarExportarViewModel.PROP_BUTTON_TEXT));
        Bindings.bind(jButtonAbrirGuardar, "enabled", getPresenter().getModel(ImportarExportarViewModel.PROP_BUTTON_ENABLED));
        Bindings.bind(jComboBoxDatosAGuardar, "enabled", getPresenter().getModel(ImportarExportarViewModel.PROP_TIPO_DATO_ENABLED));
        jButtonAbrirGuardar.addActionListener(getPresenter().getOperation(ImportarExportarViewPresenter.ACTION_IMPORTAR_EXPORTAR));
    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirGuardar;
    private javax.swing.JComboBox<String> jComboBoxDatosAGuardar;
    private javax.swing.JComboBox<String> jComboBoxImportarExportar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelImportarExportar;
    // End of variables declaration//GEN-END:variables
}
