/*

 * To change this license header, choose License Headers in Project Properties.

 * To change this template file, choose Tools | Templates

 * and open the template in the editor.

 */
package com.jobits.pos.ui.configuracion;

import com.jobits.pos.persistencia.volatil.Impresora;
import com.jobits.pos.recursos.R;
import com.jobits.pos.servicios.impresion.ImpresoraService;
import com.jobits.pos.servicios.impresion.ImpresoraUseCase;
import com.jobits.pos.ui.utils.RestManagerAbstractTableModel;
import com.jobits.pos.ui.utils.RestManagerComboBoxModel;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 *
 *
 *
 * @author Javier
 *
 */
public class ImpresionConfiguracionView extends javax.swing.JPanel {

    ImpresoraUseCase impresoraService;

    private RestManagerAbstractTableModel<Impresora> tableModel;

    /**
     *
     * Creates new form Impresion
     *
     */
    public ImpresionConfiguracionView(ImpresoraUseCase impresoraService) {
        initComponents();
        this.impresoraService = impresoraService;
        uiInit();
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     *
     * WARNING: Do NOT modify this code. The content of this method is always
     *
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNombreImpresora = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxImpresorasSistema = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGrupos = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxPorDefecto = new javax.swing.JCheckBox();
        jButtonAceptar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableImpresoras = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setPreferredSize(new java.awt.Dimension(500, 440));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nueva"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel1);

        jTextNombreImpresora.setMaximumSize(new java.awt.Dimension(999999, 30));
        jTextNombreImpresora.setMinimumSize(null);
        jPanel4.add(jTextNombreImpresora);
        jPanel4.add(filler2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Impresoras Sistema");
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jComboBoxImpresorasSistema.setMaximumSize(new java.awt.Dimension(999999, 30));
        jPanel4.add(jComboBoxImpresorasSistema);
        jPanel4.add(filler1);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Areas");
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        jComboBoxGrupos.setMaximumSize(new java.awt.Dimension(999999, 30));
        jPanel4.add(jComboBoxGrupos);
        jPanel4.add(filler3);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jCheckBoxPorDefecto.setText("Por Defecto");
        jCheckBoxPorDefecto.setMaximumSize(new java.awt.Dimension(99999, 23));
        jCheckBoxPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPorDefectoActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBoxPorDefecto, java.awt.BorderLayout.PAGE_START);

        jButtonAceptar.setText("Agregar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonAceptar, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel7);
        jPanel4.add(filler5);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);
        jPanel2.add(filler4, java.awt.BorderLayout.PAGE_START);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout(0, 5));

        jTableImpresoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableImpresoras);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEliminar, java.awt.BorderLayout.PAGE_END);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        onBottonAgregar();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        onBottonEliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jCheckBoxPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPorDefectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPorDefectoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JCheckBox jCheckBoxPorDefecto;
    private javax.swing.JComboBox<String> jComboBoxGrupos;
    private javax.swing.JComboBox<String> jComboBoxImpresorasSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableImpresoras;
    private javax.swing.JTextField jTextNombreImpresora;
    // End of variables declaration//GEN-END:variables

    private void uiInit() {

        tableModel = new RestManagerAbstractTableModel<Impresora>(impresoraService.findAll(), jTableImpresoras) {
            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return getItems().get(rowIndex).getNombreImpresoraVirtual();
                    case 1:
                        return getItems().get(rowIndex).getNombreImpresoraSistema();
                    case 2:
                        return getItems().get(rowIndex).getGrupo();
                }
                return null;
            }

            @Override

            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Nombre";
                    case 1:
                        return "Impresora";
                    case 2:
                        return "Grupo";
                }
                return null;
            }
        };

        jTableImpresoras.setModel(tableModel);
        jComboBoxImpresorasSistema.setModel(new RestManagerComboBoxModel<>(impresoraService.getNombreImpresorasSistema()));
        jComboBoxGrupos.setModel(new RestManagerComboBoxModel<>(impresoraService.getNombreGrupos()));

    }

    private void onBottonAgregar() {
        if (!jTextNombreImpresora.getText().equals("")) {
            if (showConfirmDialog(jPanel2)) {
                String nombreVirtual = jTextNombreImpresora.getText();
                String nombreSistema = jComboBoxImpresorasSistema.getSelectedItem().toString();
                String grupos = jComboBoxGrupos.getSelectedItem().toString();
                boolean isDefault = jCheckBoxPorDefecto.isSelected();
                Impresora newImpresora = new Impresora(nombreVirtual, nombreSistema, grupos, isDefault);

                if (impresoraService.crear(newImpresora) != null) {
                    showSuccessDialog(jPanel2, "Se ha agregado la impresora con éxito");
                    tableModel.addObject(newImpresora);
                    jTextNombreImpresora.setText("");
                    jComboBoxImpresorasSistema.setModel(new RestManagerComboBoxModel<>(impresoraService.getNombreImpresorasSistema()));
                    jComboBoxGrupos.setModel(new RestManagerComboBoxModel<>(impresoraService.getNombreGrupos()));
                    jCheckBoxPorDefecto.setSelected(false);
                }
            }

        }
        else{
            JOptionPane.showMessageDialog(jPanel1, "Rellene todos los campos");
        }

    }

    private void onBottonEliminar() {
            Impresora impresoraToDelete = tableModel.getObjectAtSelectedRow();
        if (showConfirmDialog(jPanel2)) {
            if (impresoraService.delete(impresoraToDelete) != null) {
                tableModel.setItems(impresoraService.findAll());
                showSuccessDialog(jPanel2, "Se ha eliminado la impresora con éxito");
            }
        }
    }

    public void showSuccessDialog(Container view, String text) {

        JOptionPane.showMessageDialog(view, text,
                R.RESOURCE_BUNDLE.getString("label_informacion"), JOptionPane.INFORMATION_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/exitoso.png")));

    }

    protected boolean showConfirmDialog(Container view) {

        return true ? JOptionPane.showConfirmDialog(view, R.RESOURCE_BUNDLE.getString("desea_aplicar_cambios"),
                R.RESOURCE_BUNDLE.getString("label_confirmacion"), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pregunta.png")))
                == JOptionPane.YES_OPTION : true;

    }

}
