/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.trabajadores;

import GUI.Views.AbstractDetailView;
import GUI.Views.AbstractView;
import GUI.Components.JSpinner;
import GUI.Components.JTextField;
import java.awt.Dialog;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import restManager.controller.AbstractDialogController;
import restManager.controller.AbstractDetailController;
import restManager.controller.trabajadores.PuestoTrabajoCreateEditController;
import restManager.exceptions.DevelopingOperationException;
import restManager.exceptions.ValidatingException;
import restManager.persistencia.Cocina;
import restManager.persistencia.PuestoTrabajo;
import restManager.resources.R;
import restManager.resources.RegularExpressions;
import restManager.util.RestManagerComboBoxModel;

/**
 *
 * @author Jorge
 */
public class PuestoTrabajoCreateEditView extends AbstractDetailView<PuestoTrabajo> {

    public PuestoTrabajoCreateEditView(AbstractDetailController<PuestoTrabajo> controller, Frame owner, boolean modal, PuestoTrabajo p) {
        super(p, DialogType.DEFINED, controller,owner, modal);
        initComponents();
        fetchComponentData();
        updateView();

    }

    public PuestoTrabajoCreateEditView(AbstractDetailController<PuestoTrabajo> controller, Dialog owner, boolean modal, PuestoTrabajo p) {
        super(p, DialogType.DEFINED, controller,owner, modal);
        initComponents();
        fetchComponentData();
        updateView();
    }

    public PuestoTrabajo getInstance() {
        return instance;
    }

    @Override
    public void fetchComponentData() {
        jComboBoxAreaPago.setModel(new RestManagerComboBoxModel<>(((PuestoTrabajoCreateEditController) getController()).getAreasPago()));
        jComboBoxAreaPago.setSelectedIndex(1);
        jComboBoxNivelAccesso.setModel(new DefaultComboBoxModel<>(R.NivelAcceso.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jLabelMoneda = new org.jdesktop.swingx.JXLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new org.jdesktop.swingx.JXLabel();
        jTextFieldNombre = new JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelPuestosDisponibles = new org.jdesktop.swingx.JXLabel();
        jSpinnerPuestosDisponibles = new JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabelNivelDeAcceso = new org.jdesktop.swingx.JXLabel();
        jComboBoxNivelAccesso = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSalarioFijo = new org.jdesktop.swingx.JXLabel();
        jSpinnerSalarioFijo = new JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabelSalarioFijo1 = new org.jdesktop.swingx.JXLabel();
        jSpinnerPorcientoVenta = new JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabelSalarioFijo4 = new org.jdesktop.swingx.JXLabel();
        jSpinnerAPartir = new JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabelSalarioFijo2 = new org.jdesktop.swingx.JXLabel();
        jSpinnerPorcientoAPartirDe = new JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabelSalarioFijo3 = new org.jdesktop.swingx.JXLabel();
        jComboBoxAreaPago = new javax.swing.JComboBox<>();
        jCheckBoxPagoVentaTotal = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jButtonCrear = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Puesto de Trabajo");
        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(582, 292));
        setMinimumSize(new java.awt.Dimension(582, 292));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(582, 292));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setBackground(getBackground());
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jXLabel1.setText(bundle.getString("label_moneda")); // NOI18N
        jPanel10.add(jXLabel1);

        jLabelMoneda.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMoneda.setText(R.COIN_SUFFIX);
        jPanel10.add(jLabelMoneda);

        getContentPane().add(jPanel10);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(150, 25));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jTextFieldNombre);

        getContentPane().add(jPanel1);

        jPanel12.setLayout(new java.awt.GridLayout(1, 1));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelPuestosDisponibles.setText("Puestos disponibles");
        jPanel8.add(jLabelPuestosDisponibles);

        jSpinnerPuestosDisponibles.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinnerPuestosDisponibles.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel8.add(jSpinnerPuestosDisponibles);

        jPanel12.add(jPanel8);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNivelDeAcceso.setText("Nivel de acceso");
        jPanel7.add(jLabelNivelDeAcceso);

        jComboBoxNivelAccesso.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel7.add(jComboBoxNivelAccesso);

        jPanel12.add(jPanel7);

        getContentPane().add(jPanel12);

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Gastos"));
        jPanel11.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setBackground(jPanel11.getBackground());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelSalarioFijo.setText("Salario fijo");
        jPanel2.add(jLabelSalarioFijo);

        jSpinnerSalarioFijo.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 5.0f));
        jSpinnerSalarioFijo.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel2.add(jSpinnerSalarioFijo);

        jPanel11.add(jPanel2);

        jPanel3.setBackground(jPanel11.getBackground());
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabelSalarioFijo1.setText("% de la venta");
        jPanel3.add(jLabelSalarioFijo1);

        jSpinnerPorcientoVenta.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinnerPorcientoVenta.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel3.add(jSpinnerPorcientoVenta);

        jPanel11.add(jPanel3);

        jPanel5.setBackground(jPanel11.getBackground());
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelSalarioFijo4.setText("A partir de");
        jPanel5.add(jLabelSalarioFijo4);

        jSpinnerAPartir.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerAPartir.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel5.add(jSpinnerAPartir);

        jPanel11.add(jPanel5);

        jPanel4.setBackground(jPanel11.getBackground());
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabelSalarioFijo2.setText("% a partir de");
        jPanel4.add(jLabelSalarioFijo2);

        jSpinnerPorcientoAPartirDe.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinnerPorcientoAPartirDe.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel4.add(jSpinnerPorcientoAPartirDe);

        jPanel11.add(jPanel4);

        jPanel6.setBackground(jPanel11.getBackground());
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelSalarioFijo3.setText("Area de Pago");
        jPanel6.add(jLabelSalarioFijo3);

        jComboBoxAreaPago.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel6.add(jComboBoxAreaPago);

        jPanel11.add(jPanel6);

        jCheckBoxPagoVentaTotal.setText(bundle.getString("label_pagode_venta_general")); // NOI18N
        jCheckBoxPagoVentaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPagoVentaTotalActionPerformed(evt);
            }
        });
        jPanel11.add(jCheckBoxPagoVentaTotal);

        getContentPane().add(jPanel11);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        jButtonCrear.setText(bundle.getString("label_aceptar")); // NOI18N
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonCrear);

        jButtonCancelar.setText(bundle.getString("label_cancelar")); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonCancelar);

        getContentPane().add(jPanel13);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jCheckBoxPagoVentaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPagoVentaTotalActionPerformed
        jComboBoxAreaPago.setEnabled(!jCheckBoxPagoVentaTotal.isSelected());
    }//GEN-LAST:event_jCheckBoxPagoVentaTotalActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        getController().createUpdateInstance();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    @Override
    public void updateView() {
        jTextFieldNombre.setText(this.instance.getNombrePuesto());
        jSpinnerPuestosDisponibles.setValue(instance.getPuestosDisponibles());
        jSpinnerSalarioFijo.setValue(instance.getSalarioFijo());
        jSpinnerPorcientoVenta.setValue(instance.getSalarioPorcientoVentaTotal());
        jSpinnerPorcientoAPartirDe.setValue(instance.getSalarioPorcientoDeArea());
        jSpinnerAPartir.setValue(instance.getAPartirDe());

        if (instance.getNivelAcceso() != null) {
            jComboBoxNivelAccesso.setSelectedIndex(instance.getNivelAcceso());

        } else {
            jComboBoxNivelAccesso.setSelectedIndex(0);
        }

        if (instance.getAreaPago() == null) {
            jCheckBoxPagoVentaTotal.setSelected(true);
            jCheckBoxPagoVentaTotalActionPerformed(null);
        } else {
            jComboBoxAreaPago.setSelectedItem(instance.getAreaPago());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JCheckBox jCheckBoxPagoVentaTotal;
    private javax.swing.JComboBox<Cocina> jComboBoxAreaPago;
    private javax.swing.JComboBox<R.NivelAcceso> jComboBoxNivelAccesso;
    private org.jdesktop.swingx.JXLabel jLabelMoneda;
    private org.jdesktop.swingx.JXLabel jLabelNivelDeAcceso;
    private org.jdesktop.swingx.JXLabel jLabelNombre;
    private org.jdesktop.swingx.JXLabel jLabelPuestosDisponibles;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo1;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo2;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo3;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinnerAPartir;
    private javax.swing.JSpinner jSpinnerPorcientoAPartirDe;
    private javax.swing.JSpinner jSpinnerPorcientoVenta;
    private javax.swing.JSpinner jSpinnerPuestosDisponibles;
    private javax.swing.JSpinner jSpinnerSalarioFijo;
    private javax.swing.JTextField jTextFieldNombre;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEditingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_editar"));
    }

    @Override
    public void setCreatingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_crear"));
    }

    @Override
    public boolean validateData() {
        String nombre = jTextFieldNombre.getText();
        if (nombre.length() > 30 || !nombre.matches(RegularExpressions.ONLY_WORDS_SEPARATED_WITH_SPACES)) {
            return false;
        }
        instance.setNombrePuesto(nombre);

        if (jCheckBoxPagoVentaTotal.isSelected()) {
            instance.setAreaPago(null);
        } else {
            instance.setAreaPago(jComboBoxAreaPago.getItemAt(jComboBoxAreaPago.getSelectedIndex()).getNombreCocina());
        }
        instance.setNivelAcceso(jComboBoxNivelAccesso.getItemAt(jComboBoxNivelAccesso.getSelectedIndex()).getNivel());
        instance.setPuestosDisponibles((Integer) jSpinnerPuestosDisponibles.getValue());
        instance.setAPartirDe((Integer) jSpinnerAPartir.getValue());
        instance.setSalarioFijo((Float) jSpinnerSalarioFijo.getValue());
        instance.setSalarioPorcientoDeArea(Float.valueOf(jSpinnerPorcientoAPartirDe.getValue().toString()));
        instance.setSalarioPorcientoVentaTotal(Float.valueOf(jSpinnerPorcientoVenta.getValue().toString()));
        if (instance.getPersonalList() == null) {
            instance.setPersonalList(new ArrayList<>());
        }
        return true;
    }
}
