/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.trabajadores;

import GUI.Views.AbstractDetailView;
import GUI.Views.AbstractView;
import GUI.Components.JSpinner;
import GUI.Components.JTextField;
import java.awt.Dialog;
import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import restManager.controller.AbstractDialogController;
import restManager.controller.AbstractDetailController;
import restManager.controller.trabajadores.PersonalCreateEditController;
import restManager.controller.trabajadores.PuestoTrabajoCreateEditController;
import restManager.exceptions.DevelopingOperationException;
import restManager.exceptions.ValidatingException;
import restManager.persistencia.Area;
import restManager.persistencia.Cocina;
import restManager.persistencia.PuestoTrabajo;
import restManager.resources.R;
import restManager.resources.RegularExpressions;
import restManager.util.RestManagerComboBoxModel;

/**
 *
 * @author Jorge
 */
public class PuestoTrabajoCreateEditView extends AbstractDetailView<PuestoTrabajo> {

    public PuestoTrabajoCreateEditView(AbstractDetailController<PuestoTrabajo> controller, Frame owner, boolean modal, PuestoTrabajo p) {
        super(p, DialogType.DEFINED, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();

    }

    public PuestoTrabajoCreateEditView(AbstractDetailController<PuestoTrabajo> controller, Dialog owner, boolean modal, PuestoTrabajo p) {
        super(p, DialogType.DEFINED, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();
    }

    @Override
    public PuestoTrabajo getInstance() {
        return instance;
    }

    @Override
    public void fetchComponentData() {
        jComboBoxAreaPago.setModel(new RestManagerComboBoxModel<>(((PuestoTrabajoCreateEditController) getController()).getAreasPago()));
        jComboBoxAreaPago.setSelectedIndex(0);
        jComboBoxAreaPago.addItem(null);
        jComboBoxNivelAccesso.setModel(new DefaultComboBoxModel<>(R.NivelAcceso.values()));
        jComboBoxAreaTrabajo.setModel(new RestManagerComboBoxModel<>(getController().getAreaList()));
        jComboBoxAreaTrabajo.addItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new org.jdesktop.swingx.JXLabel();
        jTextFieldNombre = new JTextField();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jLabelMoneda = new org.jdesktop.swingx.JXLabel();
        jPanelcentro = new javax.swing.JPanel();
        jPanelpuesto = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabelNivelDeAcceso1 = new org.jdesktop.swingx.JXLabel();
        jComboBoxAreaTrabajo = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabelPuestosDisponibles = new org.jdesktop.swingx.JXLabel();
        jSpinnerPuestosDisponibles = new JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jLabelNivelDeAcceso = new org.jdesktop.swingx.JXLabel();
        jComboBoxNivelAccesso = new javax.swing.JComboBox<>();
        jPanelbasico = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSalarioFijo = new org.jdesktop.swingx.JXLabel();
        jSpinnerSalarioFijo = new JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabelSalarioFijo1 = new org.jdesktop.swingx.JXLabel();
        jSpinnerPorcientoVenta = new JSpinner();
        jPanel11 = new javax.swing.JPanel();
        jCheckBoxPagoPorVentas = new javax.swing.JCheckBox();
        jPanelvanzado = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelSalarioFijo3 = new org.jdesktop.swingx.JXLabel();
        jComboBoxAreaPago = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabelSalarioFijo4 = new org.jdesktop.swingx.JXLabel();
        jSpinnerAPartir = new JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabelSalarioFijo2 = new org.jdesktop.swingx.JXLabel();
        jSpinnerPorcientoAPartirDe = new JSpinner();
        jPanelOtros = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jCheckBoxPropina = new javax.swing.JCheckBox();
        jPanelopciones = new javax.swing.JPanel();
        jButtonCrear = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Puesto de Trabajo");
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(500, 444));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 444));
        setSize(new java.awt.Dimension(500, 444));

        jPanel10.setBackground(getBackground());
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNombre.setText("Nombre Puesto");
        jPanel1.add(jLabelNombre);

        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(150, 25));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jTextFieldNombre);

        jPanel10.add(jPanel1);

        jXLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jXLabel1.setText(bundle.getString("label_moneda")); // NOI18N
        jPanel10.add(jXLabel1);

        jLabelMoneda.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMoneda.setText(R.COIN_SUFFIX);
        jPanel10.add(jLabelMoneda);

        getContentPane().add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanelcentro.setBackground(new java.awt.Color(0, 153, 153));
        jPanelcentro.setLayout(new javax.swing.BoxLayout(jPanelcentro, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelpuesto.setLayout(new java.awt.GridLayout(0, 3));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNivelDeAcceso1.setText("Area de trabajo");
        jPanel9.add(jLabelNivelDeAcceso1);

        jComboBoxAreaTrabajo.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel9.add(jComboBoxAreaTrabajo);

        jPanelpuesto.add(jPanel9);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelPuestosDisponibles.setText("Puestos disponibles");
        jPanel8.add(jLabelPuestosDisponibles);

        jSpinnerPuestosDisponibles.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinnerPuestosDisponibles.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel8.add(jSpinnerPuestosDisponibles);

        jPanelpuesto.add(jPanel8);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNivelDeAcceso.setText("Nivel de acceso");
        jPanel7.add(jLabelNivelDeAcceso);

        jComboBoxNivelAccesso.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel7.add(jComboBoxNivelAccesso);

        jPanelpuesto.add(jPanel7);

        jPanelcentro.add(jPanelpuesto);

        jPanelbasico.setBackground(new java.awt.Color(0, 153, 153));
        jPanelbasico.setBorder(javax.swing.BorderFactory.createTitledBorder("Salario Basico"));
        jPanelbasico.setLayout(new javax.swing.BoxLayout(jPanelbasico, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel16.setMinimumSize(new java.awt.Dimension(100, 36));
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(jPanelbasico.getBackground());
        jPanel2.setOpaque(false);

        jLabelSalarioFijo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSalarioFijo.setText("Salario fijo");
        jPanel2.add(jLabelSalarioFijo);

        jSpinnerSalarioFijo.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 5.0f));
        jSpinnerSalarioFijo.setMaximumSize(new java.awt.Dimension(32767, 26));
        jSpinnerSalarioFijo.setPreferredSize(new java.awt.Dimension(120, 26));
        jPanel2.add(jSpinnerSalarioFijo);

        jPanel16.add(jPanel2);

        jPanel3.setBackground(jPanelbasico.getBackground());
        jPanel3.setOpaque(false);

        jLabelSalarioFijo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSalarioFijo1.setText("Salario por porciento de venta");
        jPanel3.add(jLabelSalarioFijo1);

        jSpinnerPorcientoVenta.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinnerPorcientoVenta.setPreferredSize(new java.awt.Dimension(120, 26));
        jPanel3.add(jSpinnerPorcientoVenta);

        jPanel16.add(jPanel3);

        jPanel11.setBackground(jPanelbasico.getBackground());
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jCheckBoxPagoPorVentas.setText("Pago por ventas");
        jCheckBoxPagoPorVentas.setToolTipText("");
        jCheckBoxPagoPorVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxPagoPorVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBoxPagoPorVentas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel11.add(jCheckBoxPagoPorVentas);

        jPanel16.add(jPanel11);

        jPanelbasico.add(jPanel16);

        jPanelcentro.add(jPanelbasico);

        jPanelvanzado.setBackground(new java.awt.Color(0, 153, 153));
        jPanelvanzado.setBorder(javax.swing.BorderFactory.createTitledBorder("Salario Avanzado"));
        jPanelvanzado.setLayout(new javax.swing.BoxLayout(jPanelvanzado, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBackground(jPanelbasico.getBackground());

        jLabelSalarioFijo3.setText("Area de Pago");
        jPanel6.add(jLabelSalarioFijo3);

        jComboBoxAreaPago.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel6.add(jComboBoxAreaPago);

        jPanelvanzado.add(jPanel6);

        jPanel5.setBackground(jPanelbasico.getBackground());

        jLabelSalarioFijo4.setText("A partir de");
        jPanel5.add(jLabelSalarioFijo4);

        jSpinnerAPartir.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        jSpinnerAPartir.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel5.add(jSpinnerAPartir);

        jPanelvanzado.add(jPanel5);

        jPanel4.setBackground(jPanelbasico.getBackground());

        jLabelSalarioFijo2.setText("% a partir de");
        jPanel4.add(jLabelSalarioFijo2);

        jSpinnerPorcientoAPartirDe.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinnerPorcientoAPartirDe.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel4.add(jSpinnerPorcientoAPartirDe);

        jPanelvanzado.add(jPanel4);

        jPanelcentro.add(jPanelvanzado);

        jPanelOtros.setBackground(new java.awt.Color(0, 153, 153));
        jPanelOtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros"));
        jPanelOtros.setLayout(new javax.swing.BoxLayout(jPanelOtros, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setBackground(jPanelbasico.getBackground());

        jCheckBoxPropina.setText("Propina");
        jCheckBoxPropina.setToolTipText("");
        jCheckBoxPropina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxPropina.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel14.add(jCheckBoxPropina);

        jPanelOtros.add(jPanel14);

        jPanelcentro.add(jPanelOtros);

        getContentPane().add(jPanelcentro, java.awt.BorderLayout.CENTER);

        jPanelopciones.setBackground(new java.awt.Color(204, 204, 204));
        jPanelopciones.setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        jButtonCrear.setText(bundle.getString("label_aceptar")); // NOI18N
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanelopciones.add(jButtonCrear);

        jButtonCancelar.setText(bundle.getString("label_cancelar")); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelopciones.add(jButtonCancelar);

        getContentPane().add(jPanelopciones, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        getController().createUpdateInstance();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    @Override
    public void updateView() {
        jTextFieldNombre.setText(this.instance.getNombrePuesto());
        jSpinnerPuestosDisponibles.setValue(instance.getPuestosDisponibles());
        jSpinnerSalarioFijo.setValue(instance.getSalarioFijo());
        jSpinnerPorcientoVenta.setValue(instance.getSalarioPorcientoVentaTotal());
        jSpinnerPorcientoAPartirDe.setValue(instance.getSalarioPorcientoDeArea());
        jSpinnerAPartir.setValue(instance.getAPartirDe());
        jCheckBoxPagoPorVentas.setSelected(instance.getPagoPorVentas() == null ? false : instance.getPagoPorVentas());
        jCheckBoxPropina.setSelected(instance.getPropina() == null ? false : instance.getPropina());
        

        if (instance.getNivelAcceso() != null) {
            jComboBoxNivelAccesso.setSelectedIndex(instance.getNivelAcceso());

        } else {
            jComboBoxNivelAccesso.setSelectedIndex(0);
        }

        if (instance.getAreaPago() == null) {
            jComboBoxAreaPago.setSelectedItem(null);
        } else {
            jComboBoxAreaPago.setSelectedItem(instance.getAreaPago());
        }

        if (instance.getAreacodArea() == null) {
            jComboBoxAreaTrabajo.setSelectedItem(null);
        } else {
            jComboBoxAreaTrabajo.setSelectedItem(instance.getAreacodArea());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JCheckBox jCheckBoxPagoPorVentas;
    private javax.swing.JCheckBox jCheckBoxPropina;
    private javax.swing.JComboBox<Cocina> jComboBoxAreaPago;
    private javax.swing.JComboBox<Area> jComboBoxAreaTrabajo;
    private javax.swing.JComboBox<R.NivelAcceso> jComboBoxNivelAccesso;
    private org.jdesktop.swingx.JXLabel jLabelMoneda;
    private org.jdesktop.swingx.JXLabel jLabelNivelDeAcceso;
    private org.jdesktop.swingx.JXLabel jLabelNivelDeAcceso1;
    private org.jdesktop.swingx.JXLabel jLabelNombre;
    private org.jdesktop.swingx.JXLabel jLabelPuestosDisponibles;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo1;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo2;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo3;
    private org.jdesktop.swingx.JXLabel jLabelSalarioFijo4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelOtros;
    private javax.swing.JPanel jPanelbasico;
    private javax.swing.JPanel jPanelcentro;
    private javax.swing.JPanel jPanelopciones;
    private javax.swing.JPanel jPanelpuesto;
    private javax.swing.JPanel jPanelvanzado;
    private javax.swing.JSpinner jSpinnerAPartir;
    private javax.swing.JSpinner jSpinnerPorcientoAPartirDe;
    private javax.swing.JSpinner jSpinnerPorcientoVenta;
    private javax.swing.JSpinner jSpinnerPuestosDisponibles;
    private javax.swing.JSpinner jSpinnerSalarioFijo;
    private javax.swing.JTextField jTextFieldNombre;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setEditingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_editar"));
    }

    @Override
    public void setCreatingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_crear"));
    }

    @Override
    public PuestoTrabajoCreateEditController getController() {
        return (PuestoTrabajoCreateEditController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean validateData() {
        String nombre = jTextFieldNombre.getText();
        if (nombre.length() > 30 || !nombre.matches(RegularExpressions.ONLY_WORDS_SEPARATED_WITH_SPACES)) {
            return false;
        }
        instance.setNombrePuesto(nombre);

        if (jComboBoxAreaPago.getSelectedItem() == null) {
            instance.setAreaPago(null);
        } else {
            instance.setAreaPago(jComboBoxAreaPago.getItemAt(jComboBoxAreaPago.getSelectedIndex()).getCodCocina());
        }
        if (jComboBoxAreaTrabajo.getSelectedItem() == null) {
            instance.setAreacodArea(null);
        } else {
            instance.setAreacodArea((Area) jComboBoxAreaTrabajo.getSelectedItem());
        }
        instance.setPagoPorVentas(jCheckBoxPagoPorVentas.isSelected());
        instance.setPropina(jCheckBoxPropina.isSelected());
        instance.setNivelAcceso(jComboBoxNivelAccesso.getItemAt(jComboBoxNivelAccesso.getSelectedIndex()).getNivel());
        instance.setPuestosDisponibles((Integer) jSpinnerPuestosDisponibles.getValue());
        instance.setAPartirDe((Float) jSpinnerAPartir.getValue());
        instance.setSalarioFijo(Float.parseFloat(jSpinnerSalarioFijo.getValue().toString()));
        instance.setSalarioPorcientoDeArea(Float.valueOf(jSpinnerPorcientoAPartirDe.getValue().toString()));
        instance.setSalarioPorcientoVentaTotal(Float.valueOf(jSpinnerPorcientoVenta.getValue().toString()));
        if (instance.getPersonalList() == null) {
            instance.setPersonalList(new ArrayList<>());
        }
        return true;
    }
}
