/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.reserva;

import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.reserva.core.domain.Categoria;
import com.jobits.pos.reserva.core.domain.Reserva;
import com.jobits.pos.reserva.core.domain.Ubicacion;
import com.jobits.pos.ui.reserva.components.ScheduleModel;
import com.jobits.pos.ui.reserva.scheduler.AppointmentListener;
import com.jobits.pos.ui.reserva.scheduler.ExampleComponentFactory;
import com.jobits.pos.ui.reserva.scheduler.ExampleScheduleModel;
import com.jobits.pos.ui.reserva.scheduler.ResourceListener;
import com.jobits.ui.components.MaterialComponentsFactory;
import com.jobits.ui.scheduler.Appointment;
import com.jobits.ui.scheduler.Resource;
import com.jobits.ui.scheduler.ScheduleListener;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Home
 */
public class ReservaSchedulerView extends javax.swing.JPanel {

    private final ExampleScheduleModel _model;

    /**
     * Creates new form ReservaSchedulerView
     */
    public ReservaSchedulerView() {
        initComponents();
        _scheduler.addScheduleListener(new ScheduleListener() {
            @Override
            public void actionPerformed(Resource resource, LocalDateTime time) {
//                handleAddAppointment(resource, time);
            }
        });

        _model = new ExampleScheduleModel();

        ExampleComponentFactory componentFactory = new ExampleComponentFactory();
        componentFactory.setAppointmentListener(new AppointmentListener() {
            @Override
            public void handleClick(Appointment appointment, int clickCount) {
                if (clickCount == 1) {
//                    handleAppointmentClick(appointment);
                } else {
//                    handleAppointmentEdit(appointment);
                }
            }

            @Override
            public void handleDelete(Appointment appointment) {
                _model.deleteAppointment(appointment);
            }

            @Override
            public void handleEdit(Appointment appointment) {
//                handleAppointmentEdit(appointment);
            }
        });

        componentFactory.setResourceListener(new ResourceListener() {
            @Override
            public void handleDelete(Resource resource) {
                // Pass this directly down to the model
//                LocalDate date = _todayRadio.isSelected() ? Today : Tomorrow;
//                _model.deleteResource(resource, date);
            }

            @Override
            public void handleEdit(Resource resource) {
//                handleResourceEdit(resource);
            }
        });

        _scheduler.setComponentFactory(componentFactory);

        _scheduler.setModel(_model);
        _scheduler.showDate(LocalDate.now());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeleccion = new javax.swing.JPanel();
        jPanelPeriodo = new javax.swing.JPanel();
        jButtonPeriodoSelector = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelPeriodoActual = new javax.swing.JLabel();
        jPanelPeriodChooser = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDateChooserDel = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonRestablecer = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanelMainScheduler = new javax.swing.JPanel();
        _scheduler = new com.jobits.ui.scheduler.Scheduler();

        setLayout(new java.awt.BorderLayout());

        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jPanelPeriodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanelPeriodo.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanelPeriodo.setLayout(new java.awt.BorderLayout());

        jButtonPeriodoSelector.setIcon(MaterialIcons.ARROW_DROP_RIGHT);
        jButtonPeriodoSelector.setPreferredSize(new java.awt.Dimension(40, 32));
        jPanelPeriodo.add(jButtonPeriodoSelector, java.awt.BorderLayout.EAST);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabelPeriodoActual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPeriodoActual.setText("De :");
        jLabelPeriodoActual.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelPeriodoActualPropertyChange(evt);
            }
        });
        jPanel5.add(jLabelPeriodoActual, java.awt.BorderLayout.CENTER);

        jPanelPeriodo.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanelSeleccion.add(jPanelPeriodo, java.awt.BorderLayout.WEST);

        jPanelPeriodChooser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jPanelPeriodChooser.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanelPeriodChooser.setLayout(new java.awt.GridLayout(1, 3));

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel8.setMinimumSize(new java.awt.Dimension(254, 20));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jDateChooserDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserDelActionPerformed(evt);
            }
        });
        jPanel8.add(jDateChooserDel);

        jPanelPeriodChooser.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(MaterialIcons.ARROW_BACK);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setIcon(MaterialIcons.ARROW_FORWARD);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.add(jButton2, java.awt.BorderLayout.EAST);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("[x-x]");
        jPanel9.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanelPeriodChooser.add(jPanel9);

        jPanelSeleccion.add(jPanelPeriodChooser, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(110, 50));
        jPanelOpciones.setLayout(new java.awt.GridLayout(1, 2, 5, 1));

        jButtonRestablecer.setText("Imprimir");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonRestablecer);

        jPanelSeleccion.add(jPanelOpciones, java.awt.BorderLayout.EAST);

        add(jPanelSeleccion, java.awt.BorderLayout.NORTH);

        jPanelDetails.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);

        jTextField2.setText("jTextField2");
        jPanel2.add(jTextField2);

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);

        jTextField3.setText("jTextField3");
        jPanel2.add(jTextField3);

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        jTextField4.setText("jTextField4");
        jPanel2.add(jTextField4);

        jPanelDetails.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanelDetails, java.awt.BorderLayout.WEST);

        jPanelMainScheduler.setLayout(new java.awt.BorderLayout());
        jPanelMainScheduler.add(_scheduler, java.awt.BorderLayout.CENTER);

        add(jPanelMainScheduler, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPeriodoActualPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelPeriodoActualPropertyChange

    }//GEN-LAST:event_jLabelPeriodoActualPropertyChange

    private void jDateChooserDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserDelActionPerformed

    }//GEN-LAST:event_jDateChooserDelActionPerformed

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed

        //        try {
        //
        //            MessageFormat footer = new MessageFormat("-Pag {0}-");
        //
        //            jTableGastos.print(JTable.PrintMode.FIT_WIDTH, headerGastos, footer);
        //            jTableVentas.print(JTable.PrintMode.FIT_WIDTH, headerVentas, footer);
        //
        //        } catch (PrinterException ex) {
        //            Logger.getLogger(Resumenes.class.getName()).log(Level.SEVERE, null, ex);
        //        }
    }//GEN-LAST:event_jButtonRestablecerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jobits.ui.scheduler.Scheduler _scheduler;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPeriodoSelector;
    private javax.swing.JButton jButtonRestablecer;
    private org.jdesktop.swingx.JXDatePicker jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPeriodoActual;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDetails;
    private javax.swing.JPanel jPanelMainScheduler;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeriodChooser;
    private javax.swing.JPanel jPanelPeriodo;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
