/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.reserva;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.SpinnerToValueModelConnector;
import com.jgoodies.binding.list.SelectionInList;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.Cliente;
import com.jobits.pos.domain.models.ProductovOrden;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import static com.jobits.pos.ui.reserva.presenter.ReservaDetailViewModel.*;
import com.jobits.pos.ui.reserva.presenter.ReservaDetailViewPresenter;
import static com.jobits.pos.ui.reserva.presenter.ReservaDetailViewPresenter.*;
import com.jobits.pos.ui.venta.orden.CellRenderPedido;
import com.jobits.pos.ui.venta.orden.ProductoVentaSelectorView;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JList;
import javax.swing.JSpinner;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Home
 */
public class ReservasDetailView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Detalles Reserva";

    /**
     * Creates new form ReservasDetailView
     *
     * @param presenter
     */
    public ReservasDetailView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        jPanelfecha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jDateChooserFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jSpinnerHora = new javax.swing.JSpinner();
        jSpinnerMinutos = new javax.swing.JSpinner();
        jSpinnerPmAm = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jComboBoxMesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jPanelProductos = new javax.swing.JPanel();
        jPanelProductoSelector = new javax.swing.JPanel();
        jPanelProductosOrden = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListaProductos = new javax.swing.JList<>()
        ;
        jPanel1 = new javax.swing.JPanel();
        jButtonEliminar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jToggleButtonAgregos = new javax.swing.JToggleButton();
        jPanelBotones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jPanel8 = new javax.swing.JPanel();
        jButtonShowFecha = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel12 = new javax.swing.JPanel();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanel10 = new javax.swing.JPanel();
        jButtonShowProductos = MaterialComponentsFactory.Buttons.getOutlinedButton();

        setBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_COLOR, 2, true));
        setPreferredSize(new java.awt.Dimension(840, 602));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelMain.setLayout(new java.awt.CardLayout());

        jPanelfecha.setLayout(new java.awt.GridLayout(4, 2));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha");
        jPanelfecha.add(jLabel3);

        jPanel24.setLayout(new java.awt.GridBagLayout());

        jDateChooserFecha.setPreferredSize(new java.awt.Dimension(200, 50));
        jDateChooserFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserFechaActionPerformed(evt);
            }
        });
        jPanel24.add(jDateChooserFecha, new java.awt.GridBagConstraints());

        jPanelfecha.add(jPanel24);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hora");
        jPanelfecha.add(jLabel4);

        jPanel25.setLayout(new java.awt.GridBagLayout());

        jSpinnerHora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSpinnerHora.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jSpinnerHora.setPreferredSize(new java.awt.Dimension(60, 50));
        jPanel25.add(jSpinnerHora, new java.awt.GridBagConstraints());

        jSpinnerMinutos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSpinnerMinutos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jSpinnerMinutos.setPreferredSize(new java.awt.Dimension(60, 50));
        jPanel25.add(jSpinnerMinutos, new java.awt.GridBagConstraints());

        jSpinnerPmAm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSpinnerPmAm.setModel(new javax.swing.SpinnerListModel(new String[] {"PM", "AM"}));
        jSpinnerPmAm.setPreferredSize(new java.awt.Dimension(60, 50));
        jPanel25.add(jSpinnerPmAm, new java.awt.GridBagConstraints());

        jPanelfecha.add(jPanel25);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mesa");
        jPanelfecha.add(jLabel1);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jComboBoxMesa.setMinimumSize(new java.awt.Dimension(200, 50));
        jComboBoxMesa.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel22.add(jComboBoxMesa, new java.awt.GridBagConstraints());

        jPanelfecha.add(jPanel22);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cliente");
        jPanelfecha.add(jLabel2);

        jPanel23.setLayout(new java.awt.GridBagLayout());

        jComboBoxCliente.setMinimumSize(new java.awt.Dimension(200, 50));
        jComboBoxCliente.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel23.add(jComboBoxCliente, new java.awt.GridBagConstraints());

        jPanelfecha.add(jPanel23);

        jPanelMain.add(jPanelfecha, "Fecha");

        jPanelProductos.setLayout(new java.awt.BorderLayout());

        jPanelProductoSelector.setMinimumSize(new java.awt.Dimension(350, 200));
        jPanelProductoSelector.setPreferredSize(new java.awt.Dimension(350, 481));
        jPanelProductoSelector.setLayout(new java.awt.BorderLayout());
        jPanelProductos.add(jPanelProductoSelector, java.awt.BorderLayout.CENTER);

        jPanelProductosOrden.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 200));

        jListListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListListaProductos);

        jPanelProductosOrden.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonEliminar.setIcon(MaterialIcons.REMOVE_CIRCLE);
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButtonEliminar, java.awt.BorderLayout.EAST);

        jToggleButtonAgregos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/agregar_agrego_gris.png"))); // NOI18N
        jToggleButtonAgregos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/agregar_agrego_indigo.png"))); // NOI18N
        jPanel1.add(jToggleButtonAgregos, java.awt.BorderLayout.WEST);

        jPanelProductosOrden.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanelProductos.add(jPanelProductosOrden, java.awt.BorderLayout.EAST);

        jPanelMain.add(jPanelProductos, "Productos");

        jPanel5.add(jPanelMain, java.awt.BorderLayout.CENTER);

        jPanelBotones.setPreferredSize(new java.awt.Dimension(916, 80));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jButtonShowFecha.setIcon(MaterialIcons.DATE_RANGE);
        jButtonShowFecha.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonShowFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowFechaActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonShowFecha, new java.awt.GridBagConstraints());

        jPanelBotones.add(jPanel8);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setIcon(MaterialIcons.CLOSE);
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel11.add(jButtonCancelar, new java.awt.GridBagConstraints());

        jPanel9.add(jPanel11);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jButtonAceptar.setIcon(MaterialIcons.DONE);
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel12.add(jButtonAceptar, new java.awt.GridBagConstraints());

        jPanel9.add(jPanel12);

        jPanelBotones.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jButtonShowProductos.setIcon(MaterialIcons.FORMAT_LIST_BULLETED);
        jButtonShowProductos.setToolTipText("Debe seleccionar una Mesa primero");
        jButtonShowProductos.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonShowProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowProductosActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonShowProductos, new java.awt.GridBagConstraints());

        jPanelBotones.add(jPanel10);

        jPanel5.add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooserFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserFechaActionPerformed

    }//GEN-LAST:event_jDateChooserFechaActionPerformed

    private void jButtonShowProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowProductosActionPerformed
        mostrarPanelProductos();
    }//GEN-LAST:event_jButtonShowProductosActionPerformed

    private void jButtonShowFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowFechaActionPerformed
        mostrarPanelFecha();
    }//GEN-LAST:event_jButtonShowFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonShowFecha;
    private javax.swing.JButton jButtonShowProductos;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxMesa;
    private org.jdesktop.swingx.JXDatePicker jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<ProductovOrden> jListListaProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelProductoSelector;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelProductosOrden;
    private javax.swing.JPanel jPanelfecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerHora;
    private javax.swing.JSpinner jSpinnerMinutos;
    private javax.swing.JSpinner jSpinnerPmAm;
    private javax.swing.JToggleButton jToggleButtonAgregos;
    // End of variables declaration//GEN-END:variables

    @Override
    public ReservaDetailViewPresenter getPresenter() {
        return (ReservaDetailViewPresenter) super.getPresenter(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void wireUp() {
        //Compomentes Enabled

        Bindings.bind(jComboBoxMesa, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_MESAS),
                getPresenter().getModel(PROP_MESA_SELECCIONADA)));
        Bindings.bind(jComboBoxCliente, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_CLIENTES),
                getPresenter().getModel(PROP_CLIENTE)));

        Bindings.bind(jDateChooserFecha, "date", getPresenter().getModel(PROP_FECHA));

        SpinnerToValueModelConnector connectorHora = new SpinnerToValueModelConnector(jSpinnerHora.getModel(),
                getPresenter().getModel(PROP_HORA), 0);
        Bindings.bind(jSpinnerHora, "value", getPresenter().getModel(PROP_HORA));

        SpinnerToValueModelConnector connectorMinutos = new SpinnerToValueModelConnector(jSpinnerMinutos.getModel(),
                getPresenter().getModel(PROP_MINUTOS), 0);
        Bindings.bind(jSpinnerMinutos, "value", getPresenter().getModel(PROP_MINUTOS));

        SpinnerToValueModelConnector connectorPMAM = new SpinnerToValueModelConnector(jSpinnerPmAm.getModel(),
                getPresenter().getModel(PROP_PM_AM), 0);
        Bindings.bind(jSpinnerPmAm, "value", getPresenter().getModel(PROP_PM_AM));

        Bindings.bind(jListListaProductos, new SelectionInList<ProductovOrden>(
                getPresenter().getModel(PROP_LISTA_PRODUCTO),
                getPresenter().getModel(PROP_PRODUCTO_SELECCIONADO)));

        jButtonCancelar.addActionListener(getPresenter().getOperation(ACTION_CANCELAR));
        jButtonEliminar.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR));
        jButtonAceptar.addActionListener(getPresenter().getOperation(ACTION_ACEPTAR));

        jToggleButtonAgregos.addActionListener(getPresenter().getOperation(ACTION_MODO_AGREGO));
        Bindings.bind(jToggleButtonAgregos, "selected", getPresenter().getModel(PROP_MODO_AGREGO));

        Bindings.bind(jToggleButtonAgregos, "enabled", getPresenter().getModel(PROP_BOTTON_AGREGO_ENABLED));
        Bindings.bind(jButtonShowProductos, "enabled", getPresenter().getModel(PROP_SHOW_PRODUCTOS));

        getPresenter().addBeanPropertyChangeListener(PROP_SHOW_PRODUCTOS, (PropertyChangeEvent evt) -> {
            if ((boolean) evt.getNewValue()) {
                jButtonShowProductos.setToolTipText(null);
            } else {
                jButtonShowProductos.setToolTipText("Debe seleccionar una Mesa primero");
            }
        });

    }

    @Override
    public void uiInit() {
        initComponents();
        jSpinnerMinutos.setEditor(new JSpinner.NumberEditor(jSpinnerMinutos, "00"));
        jListListaProductos.setCellRenderer(new ListCellRenderer<ProductovOrden>() {
            @Override
            public Component getListCellRendererComponent(JList<? extends ProductovOrden> list,
                    ProductovOrden value, int index, boolean isSelected, boolean cellHasFocus) {
                return new CellRenderPedido(value, isSelected);
            }
        });
        jPanelProductoSelector.add(new ProductoVentaSelectorView(
                getPresenter().getProductoSelectorPresenter()), BorderLayout.CENTER);
        
        getPresenter().addBeanPropertyChangeListener(PROP_LISTA_PRODUCTO, (PropertyChangeEvent evt) -> {
            jListListaProductos.revalidate();
            jListListaProductos.repaint();
        });
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void mostrarPanelProductos() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Productos");
    }

    private void mostrarPanelFecha() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Fecha");
    }
}
