/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.reserva;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.SpinnerToValueModelConnector;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.cliente.core.domain.ClienteDomain;
import com.root101.swing.material.standards.MaterialIcons;
import com.jobits.pos.core.domain.models.ProductovOrden;
import com.jobits.pos.core.repo.impl.ConfiguracionDAO;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.clientes.ClientesDetailView;
import com.jobits.pos.ui.clientes.ClientesListView;
import com.jobits.pos.ui.clientes.presenter.ClientesDetailViewPresenter;
import com.jobits.pos.ui.clientes.presenter.ClientesListViewPresenter;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import static com.jobits.pos.ui.reserva.presenter.ReservaDetailViewModel.*;
import com.jobits.pos.ui.reserva.presenter.ReservaDetailViewPresenter;
import static com.jobits.pos.ui.reserva.presenter.ReservaDetailViewPresenter.*;
import com.jobits.pos.ui.swing.utils.BindableTableModel;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeEvent;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Home
 */
public class ReservasDetailView extends AbstractViewPanel {

    ClientesListView listView;
    ClientesDetailView detailView;

    public static final String VIEW_NAME = "Detalles Reserva";

    /**
     * Creates new form ReservasDetailView
     *
     * @param presenter
     */
    public ReservasDetailView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProductos = MaterialComponentsFactory.Containers.getTransparentPanel()
        ;
        jPanelProductoSelector = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelProductosOrden = MaterialComponentsFactory.Containers.getTransparentPanel();
        jScrollPane1 = MaterialComponentsFactory.Containers.getScrollPane();
        jListListaProductos = new javax.swing.JList<>()
        ;
        jPanel1 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonEliminar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jToggleButtonAgregos = new javax.swing.JToggleButton();
        jPanel4 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel2 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jTextFieldNombre = MaterialComponentsFactory.Input.getTextField("", "Nombre");
        jTextFieldApellidos = MaterialComponentsFactory.Input.getTextField("", "Apellidos");
        jTextFieldTelefono = MaterialComponentsFactory.Input.getTextField(" ", java.util.ResourceBundle.getBundle("Strings").getString("label_telefono"));
        jButtonAddCliente = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel3 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jTextFieldBusqueda = MaterialComponentsFactory.Input.getTextField("Buscar cliente", "");
        jScrollPane2 = MaterialComponentsFactory.Containers.getScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanelMain = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelfecha = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel21 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jTextFieldNombreReserva = MaterialComponentsFactory.Input.getTextField("", "Nombre de la Reserva");
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooserFecha = MaterialComponentsFactory.Input.getDatePicker();
        jPanel19 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jButtonShowNewClient = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel17 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jComboBoxHora = new javax.swing.JComboBox();
        jComboBoxMinuto = new javax.swing.JComboBox();
        jComboBoxPMAM = new javax.swing.JComboBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(30, 32767));
        jSpinnerDuracion = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxUbicacion = MaterialComponentsFactory.Displayers.getComboBox("");
        jButtonShowProductos = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel20 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCategoria = MaterialComponentsFactory.Displayers.getComboBox("");
        jPanelNewClient = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelListaCliente = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelNuevoCliente = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelBotones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jPanel9 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelGoBack = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonGoBack = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelToClienteList = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonToClienteList = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelCrearCliente = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonCrearCliente = MaterialComponentsFactory.Buttons.getLinedButton();
        jPanelToNuevoCliente = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonToNuevoCliente = MaterialComponentsFactory.Buttons.getLinedButton();
        jPanelSeleccionar = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonSeleccionar = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelCancelarReserva = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getLinedButton();
        jPanelAceptarReserva = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getMaterialButton();

        jPanelProductos.setLayout(new java.awt.BorderLayout());

        jPanelProductoSelector.setMinimumSize(new java.awt.Dimension(350, 200));
        jPanelProductoSelector.setPreferredSize(new java.awt.Dimension(350, 481));
        jPanelProductoSelector.setLayout(new java.awt.BorderLayout());
        jPanelProductos.add(jPanelProductoSelector, java.awt.BorderLayout.CENTER);

        jPanelProductosOrden.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(259, 200));

        jListListaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListListaProductos);

        jPanelProductosOrden.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButtonEliminar.setIcon(MaterialIcons.REMOVE_CIRCLE);
        jButtonEliminar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonEliminar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButtonEliminar, java.awt.BorderLayout.EAST);

        jToggleButtonAgregos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/agregar_agrego_gris.png"))); // NOI18N
        jToggleButtonAgregos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/agregar_agrego_indigo.png"))); // NOI18N
        jPanel1.add(jToggleButtonAgregos, java.awt.BorderLayout.WEST);

        jPanelProductosOrden.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanelProductos.add(jPanelProductosOrden, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jTextFieldNombre.setToolTipText(bundle.getString("tooltip_Nombre")); // NOI18N
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(130, 60));
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldNombre);

        jTextFieldApellidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldApellidos.setToolTipText(bundle.getString("tooltip_Nombre")); // NOI18N
        jTextFieldApellidos.setMinimumSize(new java.awt.Dimension(250, 60));
        jTextFieldApellidos.setPreferredSize(new java.awt.Dimension(130, 60));
        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldApellidos);

        jTextFieldTelefono.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldTelefono.setPreferredSize(new java.awt.Dimension(130, 60));
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldTelefono);

        jButtonAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/add_cliente_color.png"))); // NOI18N
        jButtonAddCliente.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanel2.add(jButtonAddCliente);

        jPanel4.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextFieldBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBusqueda.setPreferredSize(new java.awt.Dimension(300, 50));
        jTextFieldBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBusquedaFocusLost(evt);
            }
        });
        jPanel3.add(jTextFieldBusqueda, java.awt.BorderLayout.NORTH);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        setMinimumSize(new java.awt.Dimension(565, 530));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(565, 530));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelMain.setLayout(new java.awt.CardLayout());

        jPanelfecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 40, 20, 40));
        jPanelfecha.setLayout(new java.awt.GridLayout(5, 1));

        jPanel21.setLayout(new java.awt.BorderLayout());
        jPanel21.add(jTextFieldNombreReserva, java.awt.BorderLayout.CENTER);

        jPanelfecha.add(jPanel21);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/calendar_indigo.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel15.add(jLabel9, java.awt.BorderLayout.WEST);

        jDateChooserFecha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jDateChooserFecha.setPreferredSize(new java.awt.Dimension(300, 50));
        jDateChooserFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserFechaActionPerformed(evt);
            }
        });
        jPanel15.add(jDateChooserFecha, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel15);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/perosna_indigo.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel19.add(jLabel12, java.awt.BorderLayout.WEST);

        jLabelNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreCliente.setText("---");
        jPanel19.add(jLabelNombreCliente, java.awt.BorderLayout.CENTER);

        jButtonShowNewClient.setIcon(MaterialIcons.ADD_CIRCLE_OUTLINE);
        jButtonShowNewClient.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonShowNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowNewClientActionPerformed(evt);
            }
        });
        jPanel19.add(jButtonShowNewClient, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel19);

        jPanelfecha.add(jPanel6);

        jPanel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/reloj_indigo.png"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel17.add(jLabel10, java.awt.BorderLayout.WEST);

        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jComboBoxHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxHora.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel16.add(jComboBoxHora);

        jComboBoxMinuto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxMinuto.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel16.add(jComboBoxMinuto);

        jComboBoxPMAM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxPMAM.setPreferredSize(new java.awt.Dimension(35, 26));
        jPanel16.add(jComboBoxPMAM);
        jPanel16.add(filler1);

        jSpinnerDuracion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSpinnerDuracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 120, 5));
        jSpinnerDuracion.setMinimumSize(new java.awt.Dimension(25, 26));
        jSpinnerDuracion.setPreferredSize(new java.awt.Dimension(25, 26));
        jPanel16.add(jSpinnerDuracion);

        jLabel1.setText("Min");
        jPanel16.add(jLabel1);

        jPanel17.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanelfecha.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/location_indigo.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel18.add(jLabel11, java.awt.BorderLayout.WEST);

        jComboBoxUbicacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxUbicacion.setMinimumSize(new java.awt.Dimension(200, 50));
        jComboBoxUbicacion.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel18.add(jComboBoxUbicacion, java.awt.BorderLayout.CENTER);

        jButtonShowProductos.setIcon(MaterialIcons.FORMAT_LIST_BULLETED);
        jButtonShowProductos.setToolTipText("Debe seleccionar una Mesa primero");
        jButtonShowProductos.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonShowProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowProductosActionPerformed(evt);
            }
        });
        jPanel18.add(jButtonShowProductos, java.awt.BorderLayout.LINE_END);

        jPanelfecha.add(jPanel18);

        jPanel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/categoria_2_indigo.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel20.add(jLabel13, java.awt.BorderLayout.WEST);

        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBoxCategoria.setMinimumSize(new java.awt.Dimension(200, 50));
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel20.add(jComboBoxCategoria, java.awt.BorderLayout.CENTER);

        jPanelfecha.add(jPanel20);

        jPanelMain.add(jPanelfecha, "Fecha");

        jPanelNewClient.setLayout(new java.awt.CardLayout());

        jPanelListaCliente.setLayout(new java.awt.BorderLayout());
        jPanelNewClient.add(jPanelListaCliente, "listaClientes");

        jPanelNuevoCliente.setLayout(new java.awt.BorderLayout());
        jPanelNewClient.add(jPanelNuevoCliente, "nuevoCliente");

        jPanelMain.add(jPanelNewClient, "Nuevo Cliente");

        jPanel5.add(jPanelMain, java.awt.BorderLayout.CENTER);

        jPanelBotones.setPreferredSize(new java.awt.Dimension(916, 50));
        jPanelBotones.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jPanelGoBack.setOpaque(false);
        jPanelGoBack.setLayout(new java.awt.GridBagLayout());

        jButtonGoBack.setIcon(MaterialIcons.ARROW_BACK);
        jButtonGoBack.setPreferredSize(new java.awt.Dimension(50, 40));
        jButtonGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoBackActionPerformed(evt);
            }
        });
        jPanelGoBack.add(jButtonGoBack, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelGoBack);

        jPanelToClienteList.setOpaque(false);
        jPanelToClienteList.setLayout(new java.awt.GridBagLayout());

        jButtonToClienteList.setIcon(MaterialIcons.ARROW_BACK);
        jButtonToClienteList.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanelToClienteList.add(jButtonToClienteList, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelToClienteList);

        jPanelCrearCliente.setOpaque(false);
        jPanelCrearCliente.setLayout(new java.awt.GridBagLayout());

        jButtonCrearCliente.setText("Crear Cliente");
        jButtonCrearCliente.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelCrearCliente.add(jButtonCrearCliente, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelCrearCliente);

        jPanelToNuevoCliente.setOpaque(false);
        jPanelToNuevoCliente.setLayout(new java.awt.GridBagLayout());

        jButtonToNuevoCliente.setText("Crear");
        jButtonToNuevoCliente.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelToNuevoCliente.add(jButtonToNuevoCliente, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelToNuevoCliente);

        jPanelSeleccionar.setOpaque(false);
        jPanelSeleccionar.setLayout(new java.awt.GridBagLayout());

        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelSeleccionar.add(jButtonSeleccionar, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelSeleccionar);

        jPanelCancelarReserva.setOpaque(false);
        jPanelCancelarReserva.setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelCancelarReserva.add(jButtonCancelar, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelCancelarReserva);

        jPanelAceptarReserva.setOpaque(false);
        jPanelAceptarReserva.setLayout(new java.awt.GridBagLayout());

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelAceptarReserva.add(jButtonAceptar, new java.awt.GridBagConstraints());

        jPanel9.add(jPanelAceptarReserva);

        jPanelBotones.add(jPanel9);

        jPanel5.add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowProductosActionPerformed
        mostrarPanelProductos();
    }//GEN-LAST:event_jButtonShowProductosActionPerformed

    private void jButtonGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoBackActionPerformed
        mostrarMainPanel();
    }//GEN-LAST:event_jButtonGoBackActionPerformed

    private void jDateChooserFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserFechaActionPerformed

    private void jButtonShowNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowNewClientActionPerformed
        mostrarPanelNuevoCliente();
    }//GEN-LAST:event_jButtonShowNewClientActionPerformed

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
        char c = evt.getKeyChar();
        int l = jTextFieldTelefono.getText().length();
        if (((l >= 8) || (c < '0') || (c > '9')) && (c != '\b')) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jTextFieldBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaFocusLost

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldApellidos.requestFocusInWindow();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldTelefono.requestFocusInWindow();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosKeyPressed

    private void jTextFieldTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getPresenter().getOperation(ACTION_AGREGAR_CLIENTE).doAction();
            jTextFieldBusqueda.requestFocusInWindow();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAddCliente;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrearCliente;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGoBack;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JButton jButtonShowNewClient;
    private javax.swing.JButton jButtonShowProductos;
    private javax.swing.JButton jButtonToClienteList;
    private javax.swing.JButton jButtonToNuevoCliente;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxHora;
    private javax.swing.JComboBox jComboBoxMinuto;
    private javax.swing.JComboBox jComboBoxPMAM;
    private javax.swing.JComboBox<String> jComboBoxUbicacion;
    private org.jdesktop.swingx.JXDatePicker jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JList<ProductovOrden> jListListaProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAceptarReserva;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelCancelarReserva;
    private javax.swing.JPanel jPanelCrearCliente;
    private javax.swing.JPanel jPanelGoBack;
    private javax.swing.JPanel jPanelListaCliente;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNewClient;
    private javax.swing.JPanel jPanelNuevoCliente;
    private javax.swing.JPanel jPanelProductoSelector;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelProductosOrden;
    private javax.swing.JPanel jPanelSeleccionar;
    private javax.swing.JPanel jPanelToClienteList;
    private javax.swing.JPanel jPanelToNuevoCliente;
    private javax.swing.JPanel jPanelfecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerDuracion;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreReserva;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JToggleButton jToggleButtonAgregos;
    // End of variables declaration//GEN-END:variables

    @Override
    public ReservaDetailViewPresenter getPresenter() {
        return (ReservaDetailViewPresenter) super.getPresenter(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void wireUp() {
        Bindings.bind(jTextFieldNombreReserva, getPresenter().getModel(PROP_NOMBRE_RESERVA));
        Bindings.bind(jLabelNombreCliente, getPresenter().getModel(PROP_NOMBRE_CLIENTE));
        Bindings.bind(jComboBoxUbicacion, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_UBICACIONES),
                getPresenter().getModel(PROP_UBICACION_SELECCIONADA)));
        Bindings.bind(jComboBoxCategoria, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_CATEGORIAS),
                getPresenter().getModel(PROP_CATEGORIA_SELECCIONADA)));
//        Bindings.bind(jComboBoxCliente, new SelectionInList<>(
//                getPresenter().getModel(PROP_LISTA_CLIENTES),
//                getPresenter().getModel(PROP_CLIENTE)));
        Bindings.bind(jTable1, new SelectionInList<ClienteDomain>(
                getPresenter().getModel(PROP_LISTA_CLIENTES),
                getPresenter().getModel(PROP_CLIENTE)));
        Bindings.bind(jComboBoxHora, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_HORAS),
                getPresenter().getModel(PROP_HORA_SELECCIONADA)));
        Bindings.bind(jComboBoxMinuto, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_MINUTOS),
                getPresenter().getModel(PROP_MINUTO_SELECCIONADO)));
        Bindings.bind(jComboBoxPMAM, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_AM_PM),
                getPresenter().getModel(PROP_AM_PM_SELECCIONADO)));

        Bindings.bind(jDateChooserFecha, "date", getPresenter().getModel(PROP_FECHA));

        SpinnerToValueModelConnector connectorDuracion = new SpinnerToValueModelConnector(jSpinnerDuracion.getModel(),
                getPresenter().getModel(PROP_DURACION), 0);
        Bindings.bind(jSpinnerDuracion, "value", getPresenter().getModel(PROP_DURACION));

//        Bindings.bind(jListListaProductos, new SelectionInList<ProductovOrden>(
//                getPresenter().getModel(PROP_LISTA_PRODUCTO),
//                getPresenter().getModel(PROP_PRODUCTO_SELECCIONADO)));
        jButtonCancelar.addActionListener(getPresenter().getOperation(ACTION_CANCELAR));
        jButtonEliminar.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR));
        jButtonAceptar.addActionListener(getPresenter().getOperation(ACTION_ACEPTAR));
//        jButtonAddCliente.addActionListener(getPresenter().getOperation(ACTION_AGREGAR_CLIENTE));

        Bindings.bind(jTextFieldNombre, getPresenter().getModel(PROP_NOMBRE_CLIENTE));
        Bindings.bind(jTextFieldApellidos, getPresenter().getModel(PROP_APELLIDO_CLIENTE));
        Bindings.bind(jTextFieldTelefono, getPresenter().getModel(PROP_TELEFONO_CLIENTE));

//        jToggleButtonAgregos.addActionListener(getPresenter().getOperation(ACTION_MODO_AGREGO));
//        Bindings.bind(jToggleButtonAgregos, "selected", getPresenter().getModel(PROP_MODO_AGREGO));
//        Bindings.bind(jToggleButtonAgregos, "enabled", getPresenter().getModel(PROP_BOTTON_AGREGO_ENABLED));
        Bindings.bind(jButtonShowProductos, "enabled", getPresenter().getModel(PROP_SHOW_PRODUCTOS));
        Bindings.bind(jTextFieldBusqueda, getPresenter().getModel(PROP_CLIENTE_KEY_WORD));

        jButtonToClienteList.addActionListener(getPresenter().getOperation(ACTION_TO_CLIENTES_LIST));
        jButtonToNuevoCliente.addActionListener(getPresenter().getOperation(ACTION_TO_CREATE_CLIENTE));
        jButtonCrearCliente.addActionListener(getPresenter().getOperation(ACTION_CREATE_CLIENTE));
        jButtonSeleccionar.addActionListener(getPresenter().getOperation(ACTION_SELECT_CLIENTE));

    }

    @Override
    public void uiInit() {
        initComponents();
        intitClientesListUI();
        jComboBoxHora.setRenderer(new TimeCellRender("h"));
        jComboBoxMinuto.setRenderer(new TimeCellRender("mm"));
        jComboBoxPMAM.setRenderer(new TimeCellRender("a"));
        ((SpinnerNumberModel) jSpinnerDuracion.getModel()).setMinimum(ConfiguracionDAO.getInstance().find(R.SettingID.HORARIO_TIEMPO_MIN_SERVICIO).getValor());
//        jListListaProductos.setCellRenderer(new ListCellRenderer<ProductovOrden>() {
//            @Override
//            public Component getListCellRendererComponent(JList<? extends ProductovOrden> list,
//                    ProductovOrden value, int index, boolean isSelected, boolean cellHasFocus) {
//                return new CellRenderPedido(value, isSelected);
//            }
//        });
//        jPanelProductoSelector.add(new ProductoVentaSelectorView(
//                getPresenter().getProductoSelectorPresenter()), BorderLayout.CENTER);
//
//        getPresenter().addBeanPropertyChangeListener(PROP_LISTA_PRODUCTO, (PropertyChangeEvent evt) -> {
//            jListListaProductos.revalidate();
//            jListListaProductos.repaint();
//        });
        jPanelGoBack.setVisible(false);

        jPanelToClienteList.setVisible(false);
        jPanelCrearCliente.setVisible(false);

        jPanelToNuevoCliente.setVisible(false);
        jPanelSeleccionar.setVisible(false);

        jButtonShowProductos.setVisible(false);

        jTable1.setModel(new BindableTableModel<ClienteDomain>(jTable1) {
            @Override
            public int getColumnCount() {
                return 3;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Nombre";
                    case 1:
                        return "Apellido";
                    case 2:
                        return "Telefono";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return getRow(rowIndex).getNombre();
                    case 1:
                        return getRow(rowIndex).getApellidos();
                    case 2:
                        return getRow(rowIndex).getTelefono();
                }
                return null;
            }
        });
        jTable1.getRowSorter().toggleSortOrder(0);

        getPresenter().addPropertyChangeListener(PROP_TO_CLIENTES_LIST, (PropertyChangeEvent evt) -> {
            initList();
        });
        getPresenter().addPropertyChangeListener(PROP_TO_CREATE_CLIENTE, (PropertyChangeEvent evt) -> {
            initCreate();
        });
        getPresenter().addPropertyChangeListener(PROP_SELECT_CLIENTE, (PropertyChangeEvent evt) -> {
            mostrarMainPanel();
        });
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void mostrarMainPanel() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Fecha");
        jPanelGoBack.setVisible(false);
        mainButtonsVisible(true);
        listClientButtonsVisible(false);
        createClientButtonsVisible(false);
    }

    private void mostrarPanelProductos() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Productos");
        jPanelGoBack.setVisible(true);
    }

    private void mostrarPanelNuevoCliente() {
        CardLayout cards = (CardLayout) jPanelMain.getLayout();
        cards.show(jPanelMain, "Nuevo Cliente");
        jTextFieldNombre.requestFocusInWindow();
        jTextFieldBusqueda.setText(null);
        jPanelGoBack.setVisible(true);
        mainButtonsVisible(false);
        listClientButtonsVisible(true);
        createClientButtonsVisible(false);
    }

    private void intitClientesListUI() {
        listView = new ClientesListView(getPresenter().getClienteListPresenter());
        listView.getjPanelControles().setVisible(false);
        MouseListener[] list = listView.getjTableList().getMouseListeners();
        for (int i = 2; i < list.length; i++) {
            listView.getjTableList().removeMouseListener(list[i]);
        }
        listView.getjTableList().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    getPresenter().getOperation(ACTION_SELECT_CLIENTE).doAction();
                }
            }
        });
        jPanelListaCliente.add(listView, BorderLayout.CENTER);
    }

    private void initList() {//inizializa la lista de clientes
        listView.setPresenter(getPresenter().getClienteListPresenter());
        showList();
    }

    private void initCreate() {//inizializa la vista de crear cliente
        detailView = new ClientesDetailView(getPresenter().getClienteDetailPresenter());
        detailView.getjPanelOpciones().setVisible(false);
        jPanelNuevoCliente.removeAll();
        jPanelNuevoCliente.add(detailView, BorderLayout.CENTER);
        showDetail();
    }

    private void showList() {//muestra la lista de clientes
        CardLayout cards = (CardLayout) jPanelNewClient.getLayout();
        cards.show(jPanelNewClient, "listaClientes");
        jPanelGoBack.setVisible(true);
        mainButtonsVisible(false);
        listClientButtonsVisible(true);
        createClientButtonsVisible(false);
    }

    private void showDetail() {//muestra la vista de crear cliente
        CardLayout cards = (CardLayout) jPanelNewClient.getLayout();
        cards.show(jPanelNewClient, "nuevoCliente");
        jPanelGoBack.setVisible(false);
        mainButtonsVisible(false);
        listClientButtonsVisible(false);
        createClientButtonsVisible(true);
    }

    private void mainButtonsVisible(boolean value) {
        jPanelCancelarReserva.setVisible(value);
        jPanelAceptarReserva.setVisible(value);
    }

    private void listClientButtonsVisible(boolean value) {
        jPanelToNuevoCliente.setVisible(value);
        jPanelSeleccionar.setVisible(value);
    }

    private void createClientButtonsVisible(boolean value) {
        jPanelToClienteList.setVisible(value);
        jPanelCrearCliente.setVisible(value);
    }

}
