/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.reserva;

import com.jobits.pos.ui.reserva.util.CustomComponentFactory;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.core.repo.impl.ConfiguracionDAO;
import com.jobits.pos.main.Application;
import com.jobits.pos.notification.TipoNotificacion;
import com.jobits.pos.recursos.R;
import com.jobits.pos.reserva.core.domain.Categoria;
import com.jobits.pos.reserva.core.domain.Reserva;
import com.jobits.pos.reserva.core.domain.Ubicacion;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.reserva.util.AppointmentListener;
import com.jobits.pos.ui.reserva.model.CategoriaWrapper;
import com.jobits.pos.ui.reserva.model.Category;
import com.jobits.pos.ui.reserva.model.ScheduleModel;
import com.jobits.pos.ui.reserva.model.ReservaWrapper;
import com.jobits.pos.ui.reserva.util.ResourceListener;
import com.jobits.pos.ui.reserva.model.UbicacionWrapper;
import static com.jobits.pos.ui.reserva.presenter.ReservaSchedulerViewModel.lista_ubicaciones;
import com.jobits.pos.ui.reserva.presenter.ReservaSchedulerViewPresenter;
import com.jobits.ui.scheduler.Appointment;
import com.jobits.ui.scheduler.Resource;
import com.jobits.ui.components.MaterialComponentsFactory;
import com.jobits.ui.scheduler.Availability;
import java.awt.Color;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;

/**
 *
 * @author Home
 */
public class ReservaSchedulerView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Reserva Scheduler";

    private ScheduleModel model;

    /**
     * Creates new form ReservaSchedulerView
     *
     * @param presenter
     */
    public ReservaSchedulerView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    private void handleAppointmentClick(Appointment appointment) {
        Application.getInstance().getNotificationService().notify("Click " + appointment.getTitle(), TipoNotificacion.SUCCESS);
    }

    private void handleAppointmentEdit(Appointment appointment) {
        Application.getInstance().getNotificationService().notify("Edit " + appointment.getTitle(), TipoNotificacion.SUCCESS);
    }

    private void handleAddAppointment(Resource resource, LocalDateTime time) {
        addTestReserva(resource, time);
        Application.getInstance().getNotificationService().notify("Edit " + resource.getTitle(), TipoNotificacion.SUCCESS);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanelSeleccion = new javax.swing.JPanel();
        jPanelPeriodo = new javax.swing.JPanel();
        jButtonPeriodoSelector = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelPeriodoActual = new javax.swing.JLabel();
        jPanelPeriodChooser = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDateChooserDel = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonRestablecer = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelDetails = new javax.swing.JPanel();
        jPanelMainScheduler = new javax.swing.JPanel();
        scheduler = new com.jobits.ui.scheduler.Scheduler();

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);

        jTextField2.setText("jTextField2");
        jPanel2.add(jTextField2);

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);

        jTextField3.setText("jTextField3");
        jPanel2.add(jTextField3);

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        jTextField4.setText("jTextField4");
        jPanel2.add(jTextField4);

        setLayout(new java.awt.BorderLayout());

        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jPanelPeriodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanelPeriodo.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanelPeriodo.setLayout(new java.awt.BorderLayout());

        jButtonPeriodoSelector.setIcon(MaterialIcons.ARROW_DROP_RIGHT);
        jButtonPeriodoSelector.setPreferredSize(new java.awt.Dimension(40, 32));
        jPanelPeriodo.add(jButtonPeriodoSelector, java.awt.BorderLayout.EAST);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabelPeriodoActual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPeriodoActual.setText("De :");
        jLabelPeriodoActual.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelPeriodoActualPropertyChange(evt);
            }
        });
        jPanel5.add(jLabelPeriodoActual, java.awt.BorderLayout.CENTER);

        jPanelPeriodo.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanelSeleccion.add(jPanelPeriodo, java.awt.BorderLayout.WEST);

        jPanelPeriodChooser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jPanelPeriodChooser.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanelPeriodChooser.setLayout(new java.awt.GridLayout(1, 3));

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel8.setMinimumSize(new java.awt.Dimension(254, 20));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jDateChooserDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserDelActionPerformed(evt);
            }
        });
        jPanel8.add(jDateChooserDel);

        jPanelPeriodChooser.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(MaterialIcons.ARROW_BACK);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setIcon(MaterialIcons.ARROW_FORWARD);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel9.add(jButton2, java.awt.BorderLayout.EAST);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("[x-x]");
        jPanel9.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanelPeriodChooser.add(jPanel9);

        jPanelSeleccion.add(jPanelPeriodChooser, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(110, 50));
        jPanelOpciones.setLayout(new java.awt.GridLayout(1, 2, 5, 1));

        jButtonRestablecer.setText("Imprimir");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonRestablecer);

        jPanelSeleccion.add(jPanelOpciones, java.awt.BorderLayout.EAST);

        add(jPanelSeleccion, java.awt.BorderLayout.NORTH);

        jPanelDetails.setLayout(new java.awt.BorderLayout());
        add(jPanelDetails, java.awt.BorderLayout.WEST);

        jPanelMainScheduler.setLayout(new java.awt.BorderLayout());
        jPanelMainScheduler.add(scheduler, java.awt.BorderLayout.CENTER);

        add(jPanelMainScheduler, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPeriodoActualPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelPeriodoActualPropertyChange

    }//GEN-LAST:event_jLabelPeriodoActualPropertyChange

    private void jDateChooserDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserDelActionPerformed

    }//GEN-LAST:event_jDateChooserDelActionPerformed

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed
    }//GEN-LAST:event_jButtonRestablecerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPeriodoSelector;
    private javax.swing.JButton jButtonRestablecer;
    private org.jdesktop.swingx.JXDatePicker jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPeriodoActual;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDetails;
    private javax.swing.JPanel jPanelMainScheduler;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeriodChooser;
    private javax.swing.JPanel jPanelPeriodo;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.jobits.ui.scheduler.Scheduler scheduler;
    // End of variables declaration//GEN-END:variables

    //TODO: borrar despues de probar
    private void addTestData() {
        // Resources
        Resource ra = new UbicacionWrapper(new Ubicacion("Carlos", LocalTime.of(8, 0, 0), LocalTime.of(18, 0, 0)));
        Resource rb = new UbicacionWrapper(new Ubicacion("ALberto", LocalTime.of(8, 0, 0), LocalTime.of(18, 0, 0)));
        Resource rc = new UbicacionWrapper(new Ubicacion("Juan", LocalTime.of(8, 0, 0), LocalTime.of(18, 0, 0)));

        // Our categories for our appointments
        Category Green = new CategoriaWrapper(new Categoria("Green", new Color(9, 246, 76, 200).getRGB()));
        Category Blue = new CategoriaWrapper(new Categoria("Blue", new Color(9, 171, 246, 200).getRGB()));

        model.addResource(ra, model.getDate(), -1);
        model.addResource(rb, model.getDate(), -1);
        model.addResource(rc, model.getDate(), -1);

        model.addCategory(Blue);
        model.addCategory(Green);

        addTestReserva(rc, LocalDateTime.of(model.getDate(), LocalTime.of(5, 30)));
    }

    private void addTestReserva(Resource resource, LocalDateTime time) {
        Availability a = resource.getAvailability(time.toLocalDate()).next();
        Ubicacion u = new Ubicacion(resource.getTitle(), a.getTime(), a.getTime().plus(a.getDuration()));
        Reserva r = new Reserva(time.toLocalDate(), time.toLocalTime(), 3600, u); // 6 pm
        r.setNotasreserva("Clases a erick");
        ReservaWrapper wrapper = new ReservaWrapper(r,
                new CategoriaWrapper(new Categoria("Green",
                        new Color(9, 246, 76, 200).getRGB())), resource);
        model.addAppointment(wrapper);

    }

    @Override
    public void wireUp() {
    }

    @Override
    public void uiInit() {
        initComponents();
        scheduler.addScheduleListener((Resource resource, LocalDateTime time) -> {
            handleAddAppointment(resource, time);
        });

//        model = new ScheduleModel(LocalDate.now(),
//                LocalTime.now().minusHours(4).truncatedTo(ChronoUnit.HOURS),
//                LocalTime.now().truncatedTo(ChronoUnit.HOURS), Duration.ofMinutes(30));//TODO obviamente ponerlo de otra manera
        ReservaSchedulerViewPresenter a = new ReservaSchedulerViewPresenter();

        model = new ScheduleModel(LocalDate.now(), lista_ubicaciones, new ArrayList<>(), new ArrayList<>());
        //TODO obviamente ponerlo de otra manera
//        addTestData();
        //TODO borrar

        CustomComponentFactory componentFactory = new CustomComponentFactory();
        componentFactory.setAppointmentListener(new AppointmentListener() {
            @Override
            public void handleClick(Appointment appointment, int clickCount) {
                if (clickCount == 1) {
                    handleAppointmentClick(appointment);
                } else {
                    handleAppointmentEdit(appointment);
                }
            }

            @Override
            public void handleDelete(Appointment appointment) {
                model.deleteAppointment(appointment);
            }

            @Override
            public void handleEdit(Appointment appointment) {
                handleAppointmentEdit(appointment);
            }

        });

        componentFactory.setResourceListener(new ResourceListener() {
            @Override
            public void handleDelete(Resource resource) {
                // Pass this directly down to the model
//                LocalDate date = _todayRadio.isSelected() ? date : Tomorrow;
//                _model.deleteResource(resource, date);
            }

            @Override
            public void handleEdit(Resource resource) {
//                handleResourceEdit(resource);
            }
        });

        scheduler.setComponentFactory(componentFactory);
        scheduler.setModel(model);
        scheduler.showDate(model.getDate());
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

}
