/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.resumen;

import com.jobits.pos.core.domain.models.ProductovOrden;
import com.jobits.pos.core.domain.models.temporal.DayReviewWrapper;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractListResumenViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.utils.utils;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author Home
 */
public class DetailResumenAutorizoView extends AbstractListResumenViewPanel<DayReviewWrapper, ProductovOrden> {

    public static final String VIEW_NAME = "Resumen Autorizo View";

    /**
     * Creates new form DetailResumenAutorizoView
     *
     * @param presenter
     */
    public DetailResumenAutorizoView(AbstractViewPresenter presenter) {
        super(presenter);
        jTableMain.getColumnModel().getColumn(1).setCellRenderer(utils.numberColumCellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public BindableTableModel<DayReviewWrapper> generateMainTableModel() {
        return new BindableTableModel<DayReviewWrapper>(jTableMain) {
            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Fecha";
                    case 1:
                        return "Total";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return getRow(rowIndex)
                                .getFecha().format(DateTimeFormatter.ofPattern("d/MM/yyyy"));
                    case 1:
                        return utils.setDosLugaresDecimalesFloat(
                                getRow(rowIndex).getTotal());
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 1 ? Float.class : LocalDate.class;
            }
        };
    }

    @Override
    public BindableTableModel<ProductovOrden> generateDetailTableModel() {
        return new BindableTableModel<ProductovOrden>(jTableDetail) {
            @Override
            public int getColumnCount() {
                return 5;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Fecha";
                    case 1:
                        return "Producto Venta";
                    case 2:
                        return "Precio (" + R.COIN_SUFFIX.substring(1) + ")";
                    case 3:
                        return "Cantidad";
                    case 4:
                        return "Recaudado (" + R.COIN_SUFFIX.substring(1) + ")";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        Date d = getRow(rowIndex).getOrden().getVentafecha();
                        return Instant.ofEpochMilli(d.getTime()).atZone(ZoneId.systemDefault()).toLocalDate()
                                .format(DateTimeFormatter.ofPattern("d/MM/yyyy"));
                    case 1:
                        return getRow(rowIndex).getProductoVenta().getNombre();
                    case 2:
                        return getRow(rowIndex).getPrecioVendido();
                    case 3:
                        ProductovOrden p = getRow(rowIndex);
                        return utils.setDosLugaresDecimalesFloat(p.getCantidad());
                    case 4:
                        ProductovOrden x = getRow(rowIndex);
                        return utils.setDosLugaresDecimalesFloat(x.getPrecioVendido() * x.getCantidad());
                }
                return null;
            }
        };
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
