/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.resumen;

import com.jobits.pos.core.domain.models.AsistenciaPersonal;
import com.jobits.pos.core.domain.models.ProductovOrden;
import com.jobits.pos.core.domain.models.temporal.DayReviewWrapper;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractListResumenViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.utils.utils;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author Home
 */
public class DetailResumenSalarioView extends AbstractListResumenViewPanel<DayReviewWrapper, AsistenciaPersonal> {

    public static final String VIEW_NAME = "Resumen Salario View";

    /**
     * Creates new form DetailResumenAutorizoView
     *
     * @param presenter
     */
    public DetailResumenSalarioView(AbstractViewPresenter presenter) {
        super(presenter);
        jTableMain.getColumnModel().getColumn(1).setCellRenderer(utils.numberColumCellRender());
        jTableDetail.getColumnModel().getColumn(2).setCellRenderer(utils.numberColumCellRender());
        jTableDetail.getColumnModel().getColumn(3).setCellRenderer(utils.numberColumCellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public BindableTableModel<DayReviewWrapper> generateMainTableModel() {
        return new BindableTableModel<DayReviewWrapper>(jTableMain) {
            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Fecha";
                    case 1:
                        return "Total";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((DayReviewWrapper) getListModel().getElementAt(rowIndex))
                                .getFecha().format(DateTimeFormatter.ofPattern("d/MM/yyyy"));
                    case 1:
                        return utils.setDosLugaresDecimalesFloat(
                                ((DayReviewWrapper) getListModel().getElementAt(rowIndex)).getTotal());
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 1 ? Float.class : LocalDate.class;
            }
        };
    }

    @Override
    public BindableTableModel<AsistenciaPersonal> generateDetailTableModel() {
        return new BindableTableModel<AsistenciaPersonal>(jTableDetail) {
            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Dia de Trabajo";
                    case 1:
                        return "Personal";
                    case 2:
                        return "Salario";
                    case 3:
                        return "A Mayores";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                AsistenciaPersonal p = ((AsistenciaPersonal) getListModel().getElementAt(rowIndex));
                switch (columnIndex) {
                    case 0:
                        Date d = p.getVenta().getFecha();
                        return Instant.ofEpochMilli(d.getTime()).atZone(ZoneId.systemDefault()).toLocalDate()
                                .format(DateTimeFormatter.ofPattern("d/MM/yyyy"));
                    case 1:
                        return p.getPersonal().getUsuario();
                    case 2:
                        if (p.getPago() != null) {
                            return utils.setDosLugaresDecimalesFloat(p.getPago());
                        }
                    case 3:
                        if (p.getaMayores() != null) {
                            return utils.setDosLugaresDecimalesFloat(p.getaMayores());
                        }
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return LocalDate.class;
                    case 2:
                    case 3:
                        return Float.class;
                }
                return super.getColumnClass(columnIndex); //To change body of generated methods, choose Tools | Templates.
            }

        };
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
