/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta.resumen;

import com.jgoodies.binding.adapter.Bindings;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import static com.jobits.pos.ui.venta.resumen.presenter.ResumenMainViewModel.*;
import com.jobits.pos.ui.venta.resumen.presenter.ResumenMainViewPresenter;
import static com.jobits.pos.ui.venta.resumen.presenter.ResumenMainViewPresenter.*;
import com.jobits.ui.components.MaterialComponentsFactory;
import com.jobits.ui.components.swing.displayers.Card;
import java.awt.CardLayout;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import javax.swing.border.LineBorder;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.style.PieStyler;
import org.knowm.xchart.style.Styler;

/**
 *
 * @author Home
 */
public class ResumenMainview extends AbstractViewPanel {

    public static final String VIEW_NAME = "Resumenes";

    /**
     * Creates new form ResumenMainview
     *
     * @param presenter
     */
    public ResumenMainview(ResumenMainViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeleccion = new javax.swing.JPanel();
        jButtonPeriodoSelector = new javax.swing.JButton();
        jPanelPeriodChooser = new javax.swing.JPanel();
        jDateChooserDel = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();
        jDateChooserAl = new org.jdesktop.swingx.JXDatePicker();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonCargarResumen = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelsContainer = new javax.swing.JPanel();
        jPanelMainDashBoard = new javax.swing.JPanel();
        jPanelValoresEstadisticos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCostoporPeso = new javax.swing.JLabel();
        jButtonImpimir = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelGraficaPrincipal = new javax.swing.JPanel();
        jPanelResumenesDetallados = new javax.swing.JPanel();
        jPanelDetallesVenta = new javax.swing.JPanel();
        jPanelDetallesAutorizo = new javax.swing.JPanel();
        jPanelDetallesCostos = new javax.swing.JPanel();
        jPanelDetallesSalarios = new javax.swing.JPanel();
        jPanelDetallesGastos = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jButtonPeriodoSelector.setIcon(MaterialIcons.ARROW_DROP_LEFT);
        jButtonPeriodoSelector.setPreferredSize(new java.awt.Dimension(40, 32));
        jPanelSeleccion.add(jButtonPeriodoSelector, java.awt.BorderLayout.WEST);

        jPanelPeriodChooser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jPanelPeriodChooser.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanelPeriodChooser.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        jDateChooserDel.setPreferredSize(new java.awt.Dimension(150, 24));
        jDateChooserDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserDelActionPerformed(evt);
            }
        });
        jPanelPeriodChooser.add(jDateChooserDel);

        jLabel15.setText("hasta");
        jLabel15.setToolTipText("");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPeriodChooser.add(jLabel15);

        jDateChooserAl.setPreferredSize(new java.awt.Dimension(150, 24));
        jDateChooserAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserAlActionPerformed(evt);
            }
        });
        jPanelPeriodChooser.add(jDateChooserAl);

        jPanelSeleccion.add(jPanelPeriodChooser, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanelOpciones.setLayout(new java.awt.BorderLayout());

        jButtonCargarResumen.setText("Cargar Resumen");
        jButtonCargarResumen.setMaximumSize(new java.awt.Dimension(100, 32));
        jButtonCargarResumen.setMinimumSize(new java.awt.Dimension(100, 32));
        jButtonCargarResumen.setPreferredSize(new java.awt.Dimension(100, 32));
        jButtonCargarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarResumenActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonCargarResumen, java.awt.BorderLayout.CENTER);

        jPanelSeleccion.add(jPanelOpciones, java.awt.BorderLayout.EAST);

        add(jPanelSeleccion, java.awt.BorderLayout.NORTH);

        jPanelsContainer.setLayout(new java.awt.CardLayout());

        jPanelMainDashBoard.setLayout(new java.awt.BorderLayout());

        jPanelValoresEstadisticos.setPreferredSize(new java.awt.Dimension(791, 35));
        jPanelValoresEstadisticos.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelCostoporPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/dolar_indigo.png"))); // NOI18N
        jLabelCostoporPeso.setText("0.0");
        jLabelCostoporPeso.setToolTipText("Costo por Peso");
        jPanel1.add(jLabelCostoporPeso);

        jPanelValoresEstadisticos.add(jPanel1, java.awt.BorderLayout.CENTER);

        jButtonImpimir.setText("Imprimir");
        jPanelValoresEstadisticos.add(jButtonImpimir, java.awt.BorderLayout.EAST);

        jPanelMainDashBoard.add(jPanelValoresEstadisticos, java.awt.BorderLayout.SOUTH);

        jPanelGraficaPrincipal.setLayout(new java.awt.BorderLayout());
        jPanelMainDashBoard.add(jPanelGraficaPrincipal, java.awt.BorderLayout.CENTER);

        jPanelResumenesDetallados.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanelResumenesDetallados.setLayout(new java.awt.GridLayout(6, 1, 0, 10));
        jPanelMainDashBoard.add(jPanelResumenesDetallados, java.awt.BorderLayout.EAST);

        jPanelsContainer.add(jPanelMainDashBoard, "Main");

        jPanelDetallesVenta.setLayout(new java.awt.BorderLayout());
        jPanelsContainer.add(jPanelDetallesVenta, "Detalles Venta");

        jPanelDetallesAutorizo.setLayout(new java.awt.BorderLayout());
        jPanelsContainer.add(jPanelDetallesAutorizo, "Detalles Autorizo");

        jPanelDetallesCostos.setLayout(new java.awt.BorderLayout());
        jPanelsContainer.add(jPanelDetallesCostos, "Detalles Costos");

        jPanelDetallesSalarios.setLayout(new java.awt.BorderLayout());
        jPanelsContainer.add(jPanelDetallesSalarios, "Detalles Salario");

        jPanelDetallesGastos.setLayout(new java.awt.BorderLayout());
        jPanelsContainer.add(jPanelDetallesGastos, "Detalles Gastos");

        add(jPanelsContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooserDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserDelActionPerformed

    }//GEN-LAST:event_jDateChooserDelActionPerformed

    private void jDateChooserAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserAlActionPerformed
    }//GEN-LAST:event_jDateChooserAlActionPerformed

    private void jButtonCargarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarResumenActionPerformed
    }//GEN-LAST:event_jButtonCargarResumenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarResumen;
    private javax.swing.JButton jButtonImpimir;
    private javax.swing.JButton jButtonPeriodoSelector;
    private org.jdesktop.swingx.JXDatePicker jDateChooserAl;
    private org.jdesktop.swingx.JXDatePicker jDateChooserDel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelCostoporPeso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDetallesAutorizo;
    private javax.swing.JPanel jPanelDetallesCostos;
    private javax.swing.JPanel jPanelDetallesGastos;
    private javax.swing.JPanel jPanelDetallesSalarios;
    private javax.swing.JPanel jPanelDetallesVenta;
    private javax.swing.JPanel jPanelGraficaPrincipal;
    private javax.swing.JPanel jPanelMainDashBoard;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeriodChooser;
    private javax.swing.JPanel jPanelResumenesDetallados;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JPanel jPanelValoresEstadisticos;
    private javax.swing.JPanel jPanelsContainer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jButtonPeriodoSelector, "visible", getPresenter().getModel(PROP_CONTROLS_VISIBILITY));
        Bindings.bind(jLabelCostoporPeso, getPresenter().getModel(PROP_COSTO_PESO));

        Bindings.bind(jDateChooserDel, "date", getPresenter().getModel(PROP_FECHA_DESDE));
        Bindings.bind(jDateChooserAl, "date", getPresenter().getModel(PROP_FECHA_HASTA));

        jButtonPeriodoSelector.addActionListener(getPresenter().getOperation(ACTION_TO_MAIN_PANEL));
        jButtonCargarResumen.addActionListener(getPresenter().getOperation(ACTION_CARGAR_RESUMEN));
    }

    @Override
    public void uiInit() {
        initComponents();
        initListeners();
        updateChartValues();
        jPanelDetallesVenta.add(new DetailResumenVentaView(getPresenter().getPresenterVenta()));
        jPanelDetallesAutorizo.add(new DetailResumenAutorizoView(getPresenter().getPresenterAutorizo()));
        jPanelDetallesCostos.add(new DetailResumenCostoView(getPresenter().getPresenterCosto()));
        jPanelDetallesSalarios.add(new DetailResumenSalarioView(getPresenter().getPresenterSalario()));
        jPanelDetallesGastos.add(new DetailResumenGastoView(getPresenter().getPresenterGasto()));

        Card utilCard = MaterialComponentsFactory.Displayers.getSmallCardImageValueModel(null, null, "Utilidades",
                getPresenter().getModel(PROP_TOTAL_UTILIDADES), getPresenter().getModel(PROP_PROFITS_ICON));
        utilCard.setBorder(new LineBorder(Color.BLACK, 6, true));
        utilCard.setSecondaryTextFont(new java.awt.Font("Dialog", 1, 18));
        jPanelResumenesDetallados.add(utilCard);
        jPanelResumenesDetallados.add(MaterialComponentsFactory.Displayers.getSmallCardValueModel(null, null, "Venta",
                getPresenter().getModel(PROP_TOTAL_VENTA), getPresenter().getOperation(ACTION_TO_DETAILS_VENTA)));
        jPanelResumenesDetallados.add(MaterialComponentsFactory.Displayers.getSmallCardValueModel(null, null, "Autorizos",
                getPresenter().getModel(PROP_TOTAL_AUTORIZOS), getPresenter().getOperation(ACTION_TO_DETAILS_AUTORIZO)));
        jPanelResumenesDetallados.add(MaterialComponentsFactory.Displayers.getSmallCardValueModel(null, null, "Costos",
                getPresenter().getModel(PROP_TOTAL_COSTOS), getPresenter().getOperation(ACTION_TO_DETAILS_COSTO)));
        jPanelResumenesDetallados.add(MaterialComponentsFactory.Displayers.getSmallCardValueModel(null, null, "Salarios",
                getPresenter().getModel(PROP_TOTAL_SALARIOS), getPresenter().getOperation(ACTION_TO_DETAILS_SALARIO)));
        jPanelResumenesDetallados.add(MaterialComponentsFactory.Displayers.getSmallCardValueModel(null, null, "Gastos",
                getPresenter().getModel(PROP_TOTAL_GASTOS), getPresenter().getOperation(ACTION_TO_DETAILS_GASTO)));

    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    @Override
    public ResumenMainViewPresenter getPresenter() {
        return (ResumenMainViewPresenter) super.getPresenter(); //To change body of generated methods, choose Tools | Templates.
    }

    private void initListeners() {
        getPresenter().addPropertyChangeListener((PropertyChangeEvent evt) -> {
            CardLayout cards;
            switch (evt.getPropertyName()) {
                case "TO_MAIN_PANEL":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Main");
                    break;
                case "TO_DETAILS_VENTA":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Detalles Venta");
                    break;
                case "TO_DETAILS_AUTORIZO":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Detalles Autorizo");
                    break;
                case "TO_DETAILS_COSTO":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Detalles Costos");
                    break;
                case "TO_DETAILS_SALARIO":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Detalles Salario");
                    break;
                case "TO_DETAILS_GASTO":
                    cards = (CardLayout) jPanelsContainer.getLayout();
                    cards.show(jPanelsContainer, "Detalles Gastos");
                    break;
                case "REFRESH_STATE_EXECUTED":
                    updateChartValues();
                    break;
            }
        });
    }

    private void updateChartValues() {
        PieChart chartPie = new PieChartBuilder().theme(Styler.ChartTheme.XChart).title("Resumen General").build();
        chartPie.getStyler().setAnnotationType(PieStyler.AnnotationType.Percentage);
        chartPie.getStyler().setChartTitleBoxVisible(true);
        chartPie.getStyler().setLegendPosition(Styler.LegendPosition.InsideSE);
        chartPie.getStyler().setLegendBackgroundColor(new Color(255, 255, 255, 0));

        String venta = getPresenter().getBean().getTotal_utilidades();
        if (venta != null) {
            float ventaValue = Float.parseFloat(venta);
            chartPie.addSeries("Utilidades", ventaValue).setFillColor(Color.green);
        }
        String costos = getPresenter().getBean().getTotal_costos();
        if (costos != null) {
            float costosValue = Float.parseFloat(costos);
            chartPie.addSeries("Costos", costosValue).setFillColor(Color.ORANGE);
        }
        String salarios = getPresenter().getBean().getTotal_salarios();
        if (salarios != null) {
            float salariosValue = Float.parseFloat(salarios);
            chartPie.addSeries("Salarios", salariosValue).setFillColor(Color.yellow);
        }
        String gastos = getPresenter().getBean().getTotal_gastos();
        if (gastos != null) {
            float gastosValue = Float.parseFloat(gastos);
            chartPie.addSeries("Gastos", gastosValue).setFillColor(Color.cyan);
        }

        XChartPanel wrapperPie = new XChartPanel(chartPie);
        if (jPanelGraficaPrincipal.getComponentCount() > 0) {
            jPanelGraficaPrincipal.removeAll();
        }
        jPanelGraficaPrincipal.add(wrapperPie);
    }
}
