/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.imagemanager;

import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.imagemanager.presenter.ImageManagerViewPresenter;
import com.jobits.pos.ui.utils.ComponentMover;
import com.jobits.ui.components.MaterialComponentsFactory;

/**
 *
 * @author Home
 */
public class ImageManagerPopUpContainer extends javax.swing.JDialog {

    private final String codProd;

    /**
     * Creates new form ImageEditor
     *
     * @param parent
     * @param codProd
     */
    public ImageManagerPopUpContainer(java.awt.Frame parent, String codProd) {
        super(parent, true);
        this.codProd = codProd;
        init();
    }

    public void init() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        ComponentMover cr = new ComponentMover(this, this);
        jPanelMainPanel.add(new ImageManagerView(
                new ImageManagerViewPresenter(codProd)), java.awt.BorderLayout.CENTER);
        jLabel1.setText(codProd);
        this.setVisible(true);
    }

//    /**
//     * @param newFileName nombre de la imagen que se va a guardar
//     * @param oldImagePath ruta dela imagen actual del producto
//     * @return Devuelve la ruta donde fue almacenada la imagen
//     */
//    public void showView(String newFileName, String oldImagePath) {
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainPanel = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel3 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonClose = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanelMainPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/cerrar_indigo.png"))); // NOI18N
        jButtonClose.setToolTipText(null);
        jButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonClose, java.awt.BorderLayout.EAST);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<Producto de Venta>");
        jLabel1.setToolTipText(null);
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelMainPanel.add(jPanel3, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanelMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMainPanel;
    // End of variables declaration//GEN-END:variables
}
