/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.login;

import GUI.Views.AbstractView;
import java.awt.Color;
import javax.swing.JFrame;
import restManager.controller.AbstractDialogController;
import restManager.controller.Licence.Licence;
import restManager.controller.login.MainController;
import restManager.resources.R;
import restManager.util.ComponentMover;

/**
 *
 * @author Jorge
 */
public class MainView extends AbstractView {

    public MainView(AbstractDialogController controller) {
        super(DialogType.FULL_SCREEN, controller);
        initComponents();
        ComponentMover cr = new ComponentMover(this, getRootPane());
    }

    public MainView(AbstractDialogController controller, JFrame owner, boolean modal) {
        super(DialogType.FULL_SCREEN, controller, owner, modal);
        initComponents();
        ComponentMover cr = new ComponentMover(this, styledLabelRestName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jPanel1 = new javax.swing.JPanel();
        styledLabelRestName = new com.jidesoft.swing.StyledLabel();
        jideButton1 = new com.jidesoft.swing.JideButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelPDV = new javax.swing.JPanel();
        BotonMenu = new javax.swing.JButton();
        BotonInsumo = new javax.swing.JButton();
        BotonCocina = new javax.swing.JButton();
        BotonSeccion = new javax.swing.JButton();
        jButtonSalon = new javax.swing.JButton();
        jPanelAlmacen = new javax.swing.JPanel();
        jButtonAlmacen = new javax.swing.JButton();
        jButtonStocking = new javax.swing.JButton();
        jButtonIPVs = new javax.swing.JButton();
        jPanelContabilidad = new javax.swing.JPanel();
        jButtonVender = new javax.swing.JButton();
        jButtonVentas = new javax.swing.JButton();
        jButtonArchivos = new javax.swing.JButton();
        jButtonPresupuesto = new javax.swing.JButton();
        jPanelTrabajadores = new javax.swing.JPanel();
        jButtonTrabajadores = new javax.swing.JButton();
        jButtonNominas = new javax.swing.JButton();
        jButtonPTrabajo = new javax.swing.JButton();
        jPanelConfiguracion = new javax.swing.JPanel();
        jButtonCopiaSeguridad = new javax.swing.JButton();
        jButtonCONFIG = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jideLabelLicencia = new com.jidesoft.swing.JideLabel();
        jButton1 = new javax.swing.JButton();
        jideLabel3 = new com.jidesoft.swing.JideLabel();
        jideLabel1 = new com.jidesoft.swing.JideLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(840, 720));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        styledLabelRestName.setForeground(new java.awt.Color(255, 255, 255));
        styledLabelRestName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        styledLabelRestName.setText(R.REST_NAME);
        styledLabelRestName.setFont(new java.awt.Font("Marker Felt", 2, 60)); // NOI18N
        styledLabelRestName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        styledLabelRestName.setMinimumSize(new java.awt.Dimension(400, 68));
        jPanel1.add(styledLabelRestName, java.awt.BorderLayout.CENTER);

        jideButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/logout40.png"))); // NOI18N
        jideButton1.setFocusable(false);
        jideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jideButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jideButton1, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanelDetalles.setLayout(new javax.swing.BoxLayout(jPanelDetalles, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelPDV.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPDV.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createTitledBorder(null, "Productos de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 24)))); // NOI18N
        jPanelPDV.setLayout(new java.awt.GridLayout(1, 0));

        BotonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonmenu.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        BotonMenu.setText(bundle.getString("label_abrir_menu")); // NOI18N
        BotonMenu.setBorderPainted(false);
        BotonMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMenuActionPerformed(evt);
            }
        });
        jPanelPDV.add(BotonMenu);

        BotonInsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botoninsumos.png"))); // NOI18N
        BotonInsumo.setText(bundle.getString("label_ver_insumos")); // NOI18N
        BotonInsumo.setBorderPainted(false);
        BotonInsumo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonInsumo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsumoActionPerformed(evt);
            }
        });
        jPanelPDV.add(BotonInsumo);

        BotonCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botoncocina.png"))); // NOI18N
        BotonCocina.setText(bundle.getString("label_ver_punto_elaboracion")); // NOI18N
        BotonCocina.setBorderPainted(false);
        BotonCocina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCocina.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCocinaActionPerformed(evt);
            }
        });
        jPanelPDV.add(BotonCocina);

        BotonSeccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonsecciones.png"))); // NOI18N
        BotonSeccion.setText(bundle.getString("label_menu_seccion")); // NOI18N
        BotonSeccion.setBorderPainted(false);
        BotonSeccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSeccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeccionActionPerformed(evt);
            }
        });
        jPanelPDV.add(BotonSeccion);

        jButtonSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botosalon.png"))); // NOI18N
        jButtonSalon.setText(bundle.getString("label_ver_esquema_salon")); // NOI18N
        jButtonSalon.setBorderPainted(false);
        jButtonSalon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalonActionPerformed(evt);
            }
        });
        jPanelPDV.add(jButtonSalon);

        jPanelDetalles.add(jPanelPDV);

        jPanelAlmacen.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Almacén", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 24)))); // NOI18N
        jPanelAlmacen.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonalmacen.png"))); // NOI18N
        jButtonAlmacen.setText(bundle.getString("label_almacen")); // NOI18N
        jButtonAlmacen.setBorderPainted(false);
        jButtonAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlmacen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlmacenActionPerformed(evt);
            }
        });
        jPanelAlmacen.add(jButtonAlmacen);

        jButtonStocking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botoninventario.png"))); // NOI18N
        jButtonStocking.setText(bundle.getString("label_inventario")); // NOI18N
        jButtonStocking.setBorderPainted(false);
        jButtonStocking.setEnabled(false);
        jButtonStocking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStocking.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStockingActionPerformed(evt);
            }
        });
        jPanelAlmacen.add(jButtonStocking);

        jButtonIPVs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonipv.png"))); // NOI18N
        jButtonIPVs.setText(bundle.getString("label_ipv")); // NOI18N
        jButtonIPVs.setBorderPainted(false);
        jButtonIPVs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIPVs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonIPVs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIPVsActionPerformed(evt);
            }
        });
        jPanelAlmacen.add(jButtonIPVs);

        jPanelDetalles.add(jPanelAlmacen);

        jPanelContabilidad.setBackground(new java.awt.Color(204, 204, 204));
        jPanelContabilidad.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createTitledBorder(null, "Contabilidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 24)))); // NOI18N
        jPanelContabilidad.setLayout(new java.awt.GridLayout(1, 0));

        jButtonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/caja-registradora.png"))); // NOI18N
        jButtonVender.setText(bundle.getString("label_comenzar_dia")); // NOI18N
        jButtonVender.setBorderPainted(false);
        jButtonVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });
        jPanelContabilidad.add(jButtonVender);

        jButtonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonventas.png"))); // NOI18N
        jButtonVentas.setText(bundle.getString("label_ventas")); // NOI18N
        jButtonVentas.setBorderPainted(false);
        jButtonVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentasActionPerformed(evt);
            }
        });
        jPanelContabilidad.add(jButtonVentas);

        jButtonArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/gastos.png"))); // NOI18N
        jButtonArchivos.setText(bundle.getString("label_gastos")); // NOI18N
        jButtonArchivos.setBorderPainted(false);
        jButtonArchivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonArchivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivosActionPerformed(evt);
            }
        });
        jPanelContabilidad.add(jButtonArchivos);

        jButtonPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonpresupuesto.png"))); // NOI18N
        jButtonPresupuesto.setText(bundle.getString("label_presupuesto")); // NOI18N
        jButtonPresupuesto.setBorderPainted(false);
        jButtonPresupuesto.setEnabled(false);
        jButtonPresupuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPresupuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPresupuestoActionPerformed(evt);
            }
        });
        jPanelContabilidad.add(jButtonPresupuesto);

        jPanelDetalles.add(jPanelContabilidad);

        jPanelTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trabajadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 24))); // NOI18N
        jPanelTrabajadores.setLayout(new java.awt.GridLayout(1, 0));

        jButtonTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botontrabajador.png"))); // NOI18N
        jButtonTrabajadores.setText(bundle.getString("label_trabajadores")); // NOI18N
        jButtonTrabajadores.setBorderPainted(false);
        jButtonTrabajadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrabajadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrabajadoresActionPerformed(evt);
            }
        });
        jPanelTrabajadores.add(jButtonTrabajadores);

        jButtonNominas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonnominas.png"))); // NOI18N
        jButtonNominas.setText(bundle.getString("label_nominas")); // NOI18N
        jButtonNominas.setBorderPainted(false);
        jButtonNominas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNominas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNominasActionPerformed(evt);
            }
        });
        jPanelTrabajadores.add(jButtonNominas);

        jButtonPTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botonpuestotrabajo.png"))); // NOI18N
        jButtonPTrabajo.setText(bundle.getString("label_puesto_trabajo")); // NOI18N
        jButtonPTrabajo.setBorderPainted(false);
        jButtonPTrabajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPTrabajo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPTrabajoActionPerformed(evt);
            }
        });
        jPanelTrabajadores.add(jButtonPTrabajo);

        jPanelDetalles.add(jPanelTrabajadores);

        jPanelConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelConfiguracion.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createTitledBorder(null, "Configuración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 24)))); // NOI18N
        jPanelConfiguracion.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCopiaSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/botoncopiaseg.png"))); // NOI18N
        jButtonCopiaSeguridad.setText(bundle.getString("label_copia_seguridad")); // NOI18N
        jButtonCopiaSeguridad.setBorderPainted(false);
        jButtonCopiaSeguridad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCopiaSeguridad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCopiaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiaSeguridadActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButtonCopiaSeguridad);

        jButtonCONFIG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/config.png"))); // NOI18N
        jButtonCONFIG.setText(bundle.getString("label_configuracion")); // NOI18N
        jButtonCONFIG.setBorderPainted(false);
        jButtonCONFIG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCONFIG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCONFIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCONFIGActionPerformed(evt);
            }
        });
        jPanelConfiguracion.add(jButtonCONFIG);

        jPanelDetalles.add(jPanelConfiguracion);

        jScrollPane1.setViewportView(jPanelDetalles);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);

        jideLabelLicencia.setForeground(new java.awt.Color(255, 255, 255));
        jideLabelLicencia.setText("<Estado Licencia>");
        jPanel4.add(jideLabelLicencia);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/key.png"))); // NOI18N
        jButton1.setToolTipText("Activar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        jideLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jideLabel3.setText(R.RELEASE_VERSION);
        jPanel2.add(jideLabel3, java.awt.BorderLayout.LINE_END);

        jideLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jideLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jideLabel1.setText(R.loggedUser.getUsuario());
        jideLabel1.setToolTipText("");
        jPanel2.add(jideLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMenuActionPerformed
        action(MainController.MenuButtons.MENU);
    }//GEN-LAST:event_BotonMenuActionPerformed

    private void BotonInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsumoActionPerformed
        action(MainController.MenuButtons.INSUMO);
    }//GEN-LAST:event_BotonInsumoActionPerformed

    private void BotonCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCocinaActionPerformed
        action(MainController.MenuButtons.COCINA);        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCocinaActionPerformed

    private void BotonSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeccionActionPerformed
        action(MainController.MenuButtons.SECCION);        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSeccionActionPerformed

    private void jButtonSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalonActionPerformed
        action(MainController.MenuButtons.SALON);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalonActionPerformed

    private void jButtonAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlmacenActionPerformed
        action(MainController.MenuButtons.ALMACEN);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlmacenActionPerformed

    private void jButtonStockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStockingActionPerformed
        action(MainController.MenuButtons.INVENTARIO);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonStockingActionPerformed

    private void jButtonIPVsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIPVsActionPerformed
        action(MainController.MenuButtons.IPV);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIPVsActionPerformed

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed
        action(MainController.MenuButtons.COMENZAR_VENTAS);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
        action(MainController.MenuButtons.VENTAS);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVentasActionPerformed

    private void jButtonArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivosActionPerformed
        action(MainController.MenuButtons.CUENTAS_CONTABLES);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonArchivosActionPerformed

    private void jButtonPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPresupuestoActionPerformed
        action(MainController.MenuButtons.PRESUPUESTO);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPresupuestoActionPerformed

    private void jButtonTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrabajadoresActionPerformed
        action(MainController.MenuButtons.TRABAJADORES);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrabajadoresActionPerformed

    private void jButtonPTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPTrabajoActionPerformed
        action(MainController.MenuButtons.PUESTOS_TRABAJO);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPTrabajoActionPerformed

    private void jButtonCopiaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiaSeguridadActionPerformed
        action(MainController.MenuButtons.COPIA_SEG);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCopiaSeguridadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        action(MainController.MenuButtons.LICENCIA);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        updateView();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jideButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jideButton1ActionPerformed

    private void jButtonCONFIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCONFIGActionPerformed
        action(MainController.MenuButtons.CONFIGURACION);
    }//GEN-LAST:event_jButtonCONFIGActionPerformed

    private void jButtonNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNominasActionPerformed
        action(MainController.MenuButtons.NOMINAS);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNominasActionPerformed

    @Override
    public void updateView() {
        updateLicenceStatus();
    }

    private void updateLicenceStatus() {
        Licence l = getController().getEstadoLicencia();

        if (!l.LICENCIA_ACTIVA || !l.LICENCIA_VALIDA) {
            jButtonVentas.setEnabled(false);
            jButtonVender.setEnabled(false);
            jButtonIPVs.setEnabled(false);
            jButtonAlmacen.setEnabled(false);
            jideLabelLicencia.setForeground(Color.red);
            jideLabelLicencia.setText("Licencia vencida o faltante");
        } else {
            jButtonVender.setEnabled(true);
            jButtonVentas.setEnabled(true);
            jButtonIPVs.setEnabled(true);
            jButtonAlmacen.setEnabled(true);
            jideLabelLicencia.setForeground(Color.white);
            jideLabelLicencia.setText("Dias Restantes de licencia " + l.DIAS_RESTANTES);
        }
    }

    @Override
    public MainController getController() {
        return (MainController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCocina;
    private javax.swing.JButton BotonInsumo;
    private javax.swing.JButton BotonMenu;
    private javax.swing.JButton BotonSeccion;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlmacen;
    private javax.swing.JButton jButtonArchivos;
    private javax.swing.JButton jButtonCONFIG;
    private javax.swing.JButton jButtonCopiaSeguridad;
    private javax.swing.JButton jButtonIPVs;
    private javax.swing.JButton jButtonNominas;
    private javax.swing.JButton jButtonPTrabajo;
    private javax.swing.JButton jButtonPresupuesto;
    private javax.swing.JButton jButtonSalon;
    private javax.swing.JButton jButtonStocking;
    private javax.swing.JButton jButtonTrabajadores;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAlmacen;
    private javax.swing.JPanel jPanelConfiguracion;
    private javax.swing.JPanel jPanelContabilidad;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelPDV;
    private javax.swing.JPanel jPanelTrabajadores;
    private javax.swing.JScrollPane jScrollPane1;
    private com.jidesoft.swing.JideButton jideButton1;
    private com.jidesoft.swing.JideLabel jideLabel1;
    private com.jidesoft.swing.JideLabel jideLabel3;
    private com.jidesoft.swing.JideLabel jideLabelLicencia;
    private com.jidesoft.swing.StyledLabel styledLabelRestName;
    // End of variables declaration//GEN-END:variables

    private void action(MainController.MenuButtons menuButtons) {
        getController().actionButton(menuButtons);
    }
}
