/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.trabajadores;

import GUI.Views.AbstractDetailView;
import GUI.Components.JTextField;
import GUI.Views.util.RestManagerInputVerifier;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Frame;
import java.util.Arrays;
import java.util.Date;
import javax.swing.border.LineBorder;
import restManager.controller.AbstractDetailController;
import restManager.controller.trabajadores.PersonalCreateEditController;
import restManager.exceptions.DevelopingOperationException;
import restManager.persistencia.Personal;
import restManager.persistencia.PuestoTrabajo;
import restManager.resources.R;
import restManager.resources.RegularExpressions;
import restManager.util.RestManagerComboBoxModel;

/**
 *
 * @author Jorge
 */
public class PersonalCreateEditView extends AbstractDetailView<Personal> {

    public PersonalCreateEditView(Personal instance, AbstractDetailController controller, Frame owner, boolean modal) {
        super(instance, DialogType.LIST, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();
    }

    public PersonalCreateEditView(Personal instance, AbstractDetailController controller, Dialog owner, boolean modal) {
        super(instance, DialogType.LIST, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxPuestoTrabajo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new JTextField();
        jLabelpassword = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPasswordFieldPassAntigua = new javax.swing.JPasswordField();
        jToggleButtonMostrarPass = new javax.swing.JToggleButton();
        jLabelpassword1 = new javax.swing.JLabel();
        jPasswordFieldPassNueva = new javax.swing.JPasswordField();
        jLabelpassword2 = new javax.swing.JLabel();
        jPasswordFieldPassRepetir = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldMovil = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldFijo = new javax.swing.JFormattedTextField();
        jPanel12 = new javax.swing.JPanel();
        jButtonCrear = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Planilla Trabajador");
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(getBackground());
        jPanel3.setLayout(new java.awt.GridLayout(2, 2));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNombre.setText("Nombre*");
        jPanel3.add(jLabelNombre);

        jTextFieldNombre.setToolTipText("El nombre no debe exceder de 30 caracteres");
        jTextFieldNombre.setName(""); // NOI18N
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel3.add(jTextFieldNombre);
        jTextFieldNombre.getAccessibleContext().setAccessibleName("");

        jLabelApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelApellidos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelApellidos.setText("Apellidos*");
        jPanel3.add(jLabelApellidos);

        jTextFieldApellidos.setMaximumSize(new java.awt.Dimension(150, 26));
        jTextFieldApellidos.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextFieldApellidos.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel3.add(jTextFieldApellidos);

        getContentPane().add(jPanel3);

        jPanel2.setBackground(getBackground());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Puesto de Trabajo");
        jPanel2.add(jLabel9);

        jComboBoxPuestoTrabajo.setBackground(getBackground());
        jComboBoxPuestoTrabajo.setMaximumSize(new java.awt.Dimension(200, 27));
        jComboBoxPuestoTrabajo.setMinimumSize(new java.awt.Dimension(100, 27));
        jComboBoxPuestoTrabajo.setPreferredSize(new java.awt.Dimension(150, 27));
        jComboBoxPuestoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuestoTrabajoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxPuestoTrabajo);

        getContentPane().add(jPanel2);

        jPanel1.setBackground(getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguridad"));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelUsuario.setText("Usuario*");
        jPanel1.add(jLabelUsuario);

        jTextFieldUsuario.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel1.add(jTextFieldUsuario);

        jLabelpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelpassword.setText("Contraseña Antigua");
        jPanel1.add(jLabelpassword);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jPasswordFieldPassAntigua, java.awt.BorderLayout.CENTER);

        jToggleButtonMostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/visualizar.PNG"))); // NOI18N
        jToggleButtonMostrarPass.setBorderPainted(false);
        jToggleButtonMostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMostrarPassActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButtonMostrarPass, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5);

        jLabelpassword1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpassword1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelpassword1.setText("Contraseña Nueva");
        jPanel1.add(jLabelpassword1);
        jPanel1.add(jPasswordFieldPassNueva);

        jLabelpassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpassword2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelpassword2.setText("Repetir contraseña nueva");
        jPanel1.add(jLabelpassword2);
        jPanel1.add(jPasswordFieldPassRepetir);

        getContentPane().add(jPanel1);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBackground(jPanel6.getBackground());
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sexo");
        jPanel4.add(jLabel4);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jPanel4.add(jComboBoxSexo);

        jPanel6.add(jPanel4);

        jPanel14.setBackground(jPanel6.getBackground());
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha Nacimiento");
        jPanel14.add(jLabel8);
        jPanel14.add(jDateChooser1);

        jPanel6.add(jPanel14);

        jPanel13.setBackground(jPanel6.getBackground());
        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefono Móvil");
        jPanel13.add(jLabel6);

        try {
            jFormattedTextFieldMovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMovil.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel13.add(jFormattedTextFieldMovil);

        jPanel6.add(jPanel13);

        jPanel9.setBackground(jPanel6.getBackground());
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono Fijo");
        jPanel9.add(jLabel7);

        try {
            jFormattedTextFieldFijo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFijo.setText("");
        jFormattedTextFieldFijo.setToolTipText("");
        jFormattedTextFieldFijo.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel9.add(jFormattedTextFieldFijo);

        jPanel6.add(jPanel9);

        getContentPane().add(jPanel6);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(new org.edisoncor.gui.util.DropShadowBorder());

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonCrear);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonCancelar);

        getContentPane().add(jPanel12);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPuestoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuestoTrabajoActionPerformed
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_jComboBoxPuestoTrabajoActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        getController().createUpdateInstance();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jToggleButtonMostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarPassActionPerformed
        jPasswordFieldPassAntigua.setEchoChar(!jToggleButtonMostrarPass.isSelected() ? '*' : (char) 0);
    }//GEN-LAST:event_jToggleButtonMostrarPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<PuestoTrabajo> jComboBoxPuestoTrabajo;
    private javax.swing.JComboBox jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldFijo;
    private javax.swing.JFormattedTextField jFormattedTextFieldMovil;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JLabel jLabelpassword1;
    private javax.swing.JLabel jLabelpassword2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordFieldPassAntigua;
    private javax.swing.JPasswordField jPasswordFieldPassNueva;
    private javax.swing.JPasswordField jPasswordFieldPassRepetir;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JToggleButton jToggleButtonMostrarPass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
        if (instance.getDatosPersonales() != null) {
            jTextFieldNombre.setText(instance.getDatosPersonales().getNombre());
            jTextFieldApellidos.setText(instance.getDatosPersonales().getApellidos());
            jDateChooser1.setDate(instance.getDatosPersonales().getFechaNacimineto());
            jFormattedTextFieldMovil.setText("" + instance.getDatosPersonales().getTelefonoMovil());
            jFormattedTextFieldFijo.setText("" + instance.getDatosPersonales().getTelefonoFijo());
            jTextFieldUsuario.setText(instance.getUsuario());
            jPasswordFieldPassAntigua.setText(instance.getContrasenna());
            if (instance.getDatosPersonales().getSexo() != null) {
                if (instance.getDatosPersonales().getSexo() == 'M') {
                    jComboBoxSexo.setSelectedIndex(0);
                } else {
                    jComboBoxSexo.setSelectedIndex(1);
                }
            }
            jComboBoxPuestoTrabajo.setSelectedItem(instance.getPuestoTrabajonombrePuesto());
        }
    }

    @Override
    public void fetchComponentData() {
        jComboBoxPuestoTrabajo.setModel(new RestManagerComboBoxModel<>(((PersonalCreateEditController) getController()).getPuestoTrabajoList()));
        jTextFieldUsuario.setInputVerifier(new RestManagerInputVerifier(RegularExpressions.USER_NAME));

    }

    @Override
    public void setEditingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_editar"));
    }

    @Override
    public void setCreatingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_crear"));
    }

    @Override
    public boolean validateData() {
        if (jPasswordFieldPassNueva.getPassword().length > 0) {
            if (!Arrays.equals(jPasswordFieldPassNueva.getPassword(), (jPasswordFieldPassRepetir.getPassword()))) {
                jPasswordFieldPassRepetir.setBorder(new LineBorder(Color.red));
                return false;
            } else {
                jPasswordFieldPassRepetir.setBorder(null);
                instance.setContrasenna(jPasswordFieldPassNueva.getText());
            }

        }
        instance.getDatosPersonales().setNombre(jTextFieldNombre.getText());
        instance.getDatosPersonales().setApellidos(jTextFieldApellidos.getText());
        instance.getDatosPersonales().setFechaNacimineto(jDateChooser1.getDate());
        if (jFormattedTextFieldMovil.getValue() == null) {
            instance.getDatosPersonales().setTelefonoMovil(null);
        } else {
            instance.getDatosPersonales().setTelefonoMovil(Integer.parseInt((String) jFormattedTextFieldMovil.getValue()));
        }
        if (jFormattedTextFieldFijo.getValue() == null) {
            instance.getDatosPersonales().setTelefonoFijo(null);
        } else {
            instance.getDatosPersonales().setTelefonoFijo(Integer.parseInt((String) jFormattedTextFieldFijo.getValue()));

        }
        instance.setUsuario(jTextFieldUsuario.getText());
        instance.getDatosPersonales().setPersonalusuario(instance.getUsuario());
        if (jComboBoxSexo.getSelectedIndex() == 0) {
            instance.getDatosPersonales().setSexo('M');
        } else {
            instance.getDatosPersonales().setSexo('F');
        }
        instance.setUltimodiaPago(new Date());
        instance.setPagoPendiente((float) 0);
        instance.setPuestoTrabajonombrePuesto((PuestoTrabajo) jComboBoxPuestoTrabajo.getSelectedItem());
        instance.setOnline(false);
        return true;
    }

}
