/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.gastos_pagos;

import GUI.Views.util.RestaurantManagerListIntelliHint;
import java.awt.Dialog;
import java.util.Date;
import java.util.List;
import restManager.persistencia.ContabilidadCuenta;
import restManager.persistencia.Factura;
import restManager.persistencia.Pago;
import restManager.persistencia.PagoPK;
import restManager.resources.R;
import restManager.resources.values.Colors;
import restManager.util.utils;

/**
 *
 * @author Jorge
 */
public class ObligacionDePago extends javax.swing.JDialog {

    /**
     * Creates new form ObligacionDePago
     *
     * @param parent
     * @param selected
     */
    private final Factura selected;
    private final boolean esCobro;
    private Pago p;
    private RestaurantManagerListIntelliHint<ContabilidadCuenta> listaCuentaAsociada;


    public ObligacionDePago(Dialog parent, Factura selected,List<ContabilidadCuenta> cuentas,boolean esCobro) {
        super(parent, true);
        this.selected = selected;
        this.esCobro = esCobro;
        initComponents();
        if (esCobro) {
            jLabel1.setText("Obligacion de COBRO");
        }
        else{
            jLabel1.setText("Obligacion de PAGO");
        }
        buttonGroup1.add(jRadioButtonCheque);
        buttonGroup1.add(jRadioButtonTransaccion);
        buttonGroup1.add(jRadioButtonEfectivo);
        listaCuentaAsociada = new RestaurantManagerListIntelliHint<>(jTextFieldCuentaAsociada,cuentas);
    }

    public Pago getPago() {
        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelRoot = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jButtonCancelar = new components.buttons.MaterialButton();
        jButtonAceptar = new components.buttons.MaterialButton();
        jPanelMenu = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        materialPanel2 = new components.containers.MaterialPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFactura = new javax.swing.JLabel();
        jLabelMonto = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelPagado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSpinnerMontoAPagar = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonCheque = new javax.swing.JRadioButton();
        jRadioButtonTransaccion = new javax.swing.JRadioButton();
        jRadioButtonEfectivo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelOpcionMetodoPago = new javax.swing.JLabel();
        jTextFieldJustOpcion = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldCuentaAsociada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 500));
        setUndecorated(true);

        jPanelRoot.setBorder(new javax.swing.border.LineBorder(Colors.WINDOW_BORDER_COLOR, 3, true));
        jPanelRoot.setLayout(new java.awt.BorderLayout());

        jButtonCancelar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonCancelar);

        jButtonAceptar.setBackground(new java.awt.Color(51, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonAceptar);

        jPanelRoot.add(jPanelControls, java.awt.BorderLayout.PAGE_END);

        jPanelMenu.setLayout(new java.awt.BorderLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/logout40.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelMenu.add(jButton6, java.awt.BorderLayout.WEST);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Obligacion de cobro/pago");
        jPanelMenu.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanelRoot.add(jPanelMenu, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        materialPanel2.setBackground(new java.awt.Color(0, 204, 204));
        materialPanel2.setLayout(new java.awt.GridLayout(5, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabelFactura.setText(selected.getNoSerieFactura());
        jLabelFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.add(jLabelFactura);

        jLabelMonto.setText(""+utils.setDosLugaresDecimalesFloat(selected.getMontoAPagar()));
        jLabelMonto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Monto total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.add(jLabelMonto);

        jLabelFecha.setText(R.DATE_FORMAT.format(selected.getFecha()));
        jLabelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Fecha Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.add(jLabelFecha);

        jLabelPagado.setText("" + utils.setDosLugaresDecimalesFloat(selected.getMontoPagado()));
        jLabelPagado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Monto pagado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.add(jLabelPagado);

        materialPanel2.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "cobrar/pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setOpaque(false);

        jSpinnerMontoAPagar.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        jSpinnerMontoAPagar.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel3.add(jSpinnerMontoAPagar);

        materialPanel2.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Método cobro/pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel4.setOpaque(false);

        jRadioButtonCheque.setText("Cheque");
        jRadioButtonCheque.setToolTipText("");
        jRadioButtonCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonChequeActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonCheque);

        jRadioButtonTransaccion.setText("Transacción");
        jRadioButtonTransaccion.setToolTipText("");
        jRadioButtonTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTransaccionActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonTransaccion);

        jRadioButtonEfectivo.setSelected(true);
        jRadioButtonEfectivo.setText("Efectivo");
        jRadioButtonEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEfectivoActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButtonEfectivo);

        materialPanel2.add(jPanel4);

        jPanel5.setOpaque(false);

        jLabelOpcionMetodoPago.setText("No. Recibo");
        jPanel5.add(jLabelOpcionMetodoPago);

        jTextFieldJustOpcion.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel5.add(jTextFieldJustOpcion);

        materialPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel6.setOpaque(false);

        jTextFieldCuentaAsociada.setToolTipText("");
        jTextFieldCuentaAsociada.setPreferredSize(new java.awt.Dimension(170, 26));
        jTextFieldCuentaAsociada.setSize(new java.awt.Dimension(150, 26));
        jPanel6.add(jTextFieldCuentaAsociada);

        materialPanel2.add(jPanel6);

        jPanel1.add(materialPanel2, java.awt.BorderLayout.CENTER);

        jPanelRoot.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioButtonChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonChequeActionPerformed
        if (jRadioButtonCheque.isSelected()) {
            jLabelOpcionMetodoPago.setText("No. Cheque");
        }
    }//GEN-LAST:event_jRadioButtonChequeActionPerformed

    private void jRadioButtonTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTransaccionActionPerformed
        if (jRadioButtonTransaccion.isSelected()) {
            jLabelOpcionMetodoPago.setText("");
        }
    }//GEN-LAST:event_jRadioButtonTransaccionActionPerformed

    private void jRadioButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEfectivoActionPerformed
        if (jRadioButtonEfectivo.isSelected()) {
            jLabelOpcionMetodoPago.setText("No. Recibo");
        }
    }//GEN-LAST:event_jRadioButtonEfectivoActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        PagoPK pk = new PagoPK();
        pk.setFacturaidFactura(selected.getIdFactura());
        p = new Pago();
        p.setPagoPK(pk);
        p.setIdCuentaARebajar(listaCuentaAsociada.getSelectedHint());
        p.setEsCobro(esCobro);
        p.setFactura(selected);
        p.setFecha(new Date());
        p.setMontoPagado(utils.setDosLugaresDecimalesFloat((Float) jSpinnerMontoAPagar.getValue()));
            String texto = jTextFieldJustOpcion.getText();
        if (jRadioButtonCheque.isSelected()) {
            p.setNoCheque(texto);
        }
        if (jRadioButtonEfectivo.isSelected()) {
            p.setNoRecibo(texto);
        }
        if (jRadioButtonTransaccion.isSelected()) {
            p.setACuenta(true);
        }
        dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton6;
    private components.buttons.MaterialButton jButtonAceptar;
    private components.buttons.MaterialButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFactura;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JLabel jLabelOpcionMetodoPago;
    private javax.swing.JLabel jLabelPagado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JRadioButton jRadioButtonCheque;
    private javax.swing.JRadioButton jRadioButtonEfectivo;
    private javax.swing.JRadioButton jRadioButtonTransaccion;
    private javax.swing.JSpinner jSpinnerMontoAPagar;
    private javax.swing.JTextField jTextFieldCuentaAsociada;
    private javax.swing.JTextField jTextFieldJustOpcion;
    private components.containers.MaterialPanel materialPanel2;
    // End of variables declaration//GEN-END:variables
}
