/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.gastos;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.SpinnerToValueModelConnector;
import com.jgoodies.binding.list.SelectionInList;
import com.root101.swing.material.standards.MaterialIcons;
import com.jobits.pos.core.domain.models.GastoVenta;
import com.jobits.pos.core.domain.models.temporal.DefaultGasto;
import com.jobits.pos.recursos.R;
import com.jobits.pos.ui.AbstractViewPanel;
import static com.jobits.pos.ui.gastos.presenter.GastosViewModel.*;
import static com.jobits.pos.ui.gastos.presenter.GastosViewPresenter.*;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableListIntelliHint;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.utils.utils;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.util.ResourceBundle;
import javax.swing.event.TableModelEvent;
import org.checkerframework.checker.units.qual.K;

/**
 *
 * @author Home
 */
public class GastosView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Gastos";
    BindableListIntelliHint<K> autoCompleteModel;

    /**
     * Creates new form GastosView
     *
     * @param presenter
     */
    public GastosView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanelContainer = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanelAgregar1 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel8 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel11 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel2 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jComboBoxCategoria = MaterialComponentsFactory.Displayers.getComboBox("");
        jPanel6 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jTextFieldTipoGasto = MaterialComponentsFactory.Input.getTextField("", "");
        jPanel5 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jTextFieldMonto = MaterialComponentsFactory.Input.getTextField("", "");
        jPanelDesc = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jScrollPane1 = MaterialComponentsFactory.Containers.getScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jPanel3 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jPanel9 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jComboBoxDefaultGastos = MaterialComponentsFactory.Displayers.getComboBox("");
        jButtonEliminarDefaultGasto = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAgregarDefaultGasto = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanel10 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonLimpiarEntradas = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonCrearGasto = MaterialComponentsFactory.Buttons.getLinedButton();
        jPanel7 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jLabelGast = new javax.swing.JLabel();
        jPanelInfo = MaterialComponentsFactory.Containers.getTransparentPanel();
        jScrollPane4 = MaterialComponentsFactory.Containers.getScrollPane();
        jTableInfo = new javax.swing.JTable();
        jPanel4 = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonImprimirGastos = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonEliminarGasto = MaterialComponentsFactory.Buttons.getOutlinedButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelContainer.setToolTipText(null);
        jPanelContainer.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanelContainer.setMinimumSize(new java.awt.Dimension(200, 85));
        jPanelContainer.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelContainer.setLayout(new java.awt.BorderLayout());

        jPanelAgregar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nuevo/Editar Gasto"));
        jPanelAgregar1.setToolTipText(null);
        jPanelAgregar1.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanelAgregar1.setMinimumSize(new java.awt.Dimension(200, 85));
        jPanelAgregar1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelAgregar1.setLayout(new java.awt.BorderLayout());

        jPanel8.setToolTipText(null);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.GridLayout(3, 1));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), bundle.getString("label_categoria"))); // NOI18N
        jPanel2.setToolTipText(null);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxCategoria.setToolTipText(null);
        jComboBoxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(150, 36));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCategoria, new java.awt.GridBagConstraints());

        jPanel11.add(jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), "Tipo"));
        jPanel6.setToolTipText(null);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jTextFieldTipoGasto.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextFieldTipoGasto.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel6.add(jTextFieldTipoGasto);

        jPanel11.add(jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), "Monto (" + R.COIN_SUFFIX + " )"));
        jPanel5.setToolTipText(null);
        jPanel5.setMinimumSize(new java.awt.Dimension(150, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(170, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jSpinnerMonto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 5.0f));
        jSpinnerMonto.setToolTipText(null);
        jSpinnerMonto.setOpaque(false);
        jSpinnerMonto.setPreferredSize(new java.awt.Dimension(150, 26));
        jSpinnerMonto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerMontoStateChanged(evt);
            }
        });
        jSpinnerMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSpinnerMontoFocusGained(evt);
            }
        });
        jPanel5.add(jSpinnerMonto, new java.awt.GridBagConstraints());

        jPanel11.add(jPanel5);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanelDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), bundle.getString("label_descripcion"))); // NOI18N
        jPanelDesc.setPreferredSize(new java.awt.Dimension(170, 160));
        jPanelDesc.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaDescripcion.setColumns(5);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setTabSize(5);
        jTextAreaDescripcion.setToolTipText(null);
        jTextAreaDescripcion.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextAreaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jPanelDesc.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanelDesc, java.awt.BorderLayout.SOUTH);

        jPanelAgregar1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.setToolTipText(null);
        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jComboBoxDefaultGastos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxDefaultGastos.setToolTipText(null);
        jComboBoxDefaultGastos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jComboBoxDefaultGastos.setPreferredSize(new java.awt.Dimension(150, 36));
        jComboBoxDefaultGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDefaultGastosActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxDefaultGastos, java.awt.BorderLayout.CENTER);

        jButtonEliminarDefaultGasto.setIcon(MaterialIcons.DELETE);
        jButtonEliminarDefaultGasto.setToolTipText("Eliminar Plantilla");
        jButtonEliminarDefaultGasto.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonEliminarDefaultGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarDefaultGastoActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonEliminarDefaultGasto, java.awt.BorderLayout.WEST);

        jButtonAgregarDefaultGasto.setIcon(MaterialIcons.ADD);
        jButtonAgregarDefaultGasto.setToolTipText("Agregar Plantilla");
        jButtonAgregarDefaultGasto.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonAgregarDefaultGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarDefaultGastoActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonAgregarDefaultGasto, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jButtonLimpiarEntradas.setToolTipText("Limpiar");
        jButtonLimpiarEntradas.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLimpiarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarEntradasActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonLimpiarEntradas, java.awt.BorderLayout.WEST);

        jButtonCrearGasto.setText("Crear");
        jButtonCrearGasto.setToolTipText(null);
        jButtonCrearGasto.setPreferredSize(new java.awt.Dimension(164, 28));
        jButtonCrearGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearGastoActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonCrearGasto, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel10);

        jPanelAgregar1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanelContainer.add(jPanelAgregar1, java.awt.BorderLayout.CENTER);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 15, 15));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabelGast.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelGast.setForeground(new java.awt.Color(153, 0, 0));
        jLabelGast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGast.setText("XXXX.XX CUC");
        jLabelGast.setToolTipText(null);
        jLabelGast.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Total"));
        jPanel7.add(jLabelGast, java.awt.BorderLayout.SOUTH);

        jPanelContainer.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanelContainer, java.awt.BorderLayout.WEST);

        jPanelInfo.setLayout(new java.awt.BorderLayout());

        jTableInfo.setAutoCreateRowSorter(true);
        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo", "Monto", "Descripcion"
            }
        ));
        jScrollPane4.setViewportView(jTableInfo);

        jPanelInfo.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jPanel4.setPreferredSize(new java.awt.Dimension(146, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButtonImprimirGastos.setText("Gastos");
        jButtonImprimirGastos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonImprimirGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirGastosActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonImprimirGastos, java.awt.BorderLayout.WEST);

        jButtonEliminarGasto.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEliminarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarGastoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonEliminarGasto, java.awt.BorderLayout.EAST);

        jPanelInfo.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanelInfo, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirGastosActionPerformed
    }//GEN-LAST:event_jButtonImprimirGastosActionPerformed

    private void jButtonEliminarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarGastoActionPerformed
    }//GEN-LAST:event_jButtonEliminarGastoActionPerformed

    private void jButtonLimpiarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarEntradasActionPerformed
        clear();
    }//GEN-LAST:event_jButtonLimpiarEntradasActionPerformed

    private void jButtonCrearGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearGastoActionPerformed
        clear();
    }//GEN-LAST:event_jButtonCrearGastoActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
//        if (jComboBoxCategoria.getSelectedIndex() != 0) {
//            jTextFieldTipo.setEnabled(true);
//            jSpinnerMonto.setEnabled(true);
//            intellihints = new ListDataIntelliHints(jTextFieldTipo,
//                    getController().getNombres(jComboBoxCategoria.getSelectedItem().toString()));
//        } else {
//            jTextFieldTipo.setEnabled(false);
//        }
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextAreaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionKeyTyped
        int max = 90;
        String s = jTextAreaDescripcion.getText();
        int l = s.length();
        setCounterInBorder(max, l);
        if (l >= max) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextAreaDescripcionKeyTyped

    private void jComboBoxDefaultGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDefaultGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDefaultGastosActionPerformed

    private void jButtonEliminarDefaultGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarDefaultGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarDefaultGastoActionPerformed

    private void jButtonAgregarDefaultGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarDefaultGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarDefaultGastoActionPerformed

    private void jTextFieldMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMontoKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != '\b') && (c != '.')) {
            evt.consume();
        }
        if ((c == '.') && (jTextFieldMonto.getText().contains("."))) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldMontoKeyTyped

    @Override
    public void wireUp() {
        Bindings.bind(jTableInfo, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_GASTO_VENTA),
                getPresenter().getModel(PROP_GASTO_VENTA_SELECCIONADO)));

        Bindings.bind(jComboBoxDefaultGastos, new SelectionInList<DefaultGasto>(
                getPresenter().getModel(PROP_DEFAULT_GASTO_LIST),
                getPresenter().getModel(PROP_DEFAULT_GASTO_SELECCIONADO)));
        Bindings.bind(jComboBoxCategoria, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_CATEGORIA_GASTOS),
                getPresenter().getModel(PROP_CATEGORIA_GASTO_SELECCIONADA)));
        BindableListIntelliHint lih = new BindableListIntelliHint(new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_TIPO_GASTO),
                getPresenter().getModel(PROP_TIPO_GASTO_SELECCIONADO)), jTextFieldTipoGasto);
        Bindings.bind(jTextFieldTipoGasto, getPresenter().getModel(PROP_TIPO_GASTO));

        SpinnerToValueModelConnector connector = new SpinnerToValueModelConnector(jSpinnerMonto.getModel(),
                getPresenter().getModel(PROP_MONTO_GASTO), 0);
        Bindings.bind(jSpinnerMonto, "value", getPresenter().getModel(PROP_MONTO_GASTO));

        Bindings.bind(jTextAreaDescripcion, getPresenter().getModel(PROP_DESCRIPCION_GASTO));
        Bindings.bind(jLabelGast, getPresenter().getModel(PROP_TOTAL_GASTOS));

//        autoCompleteModel = new BindableListIntelliHint(
//                new SelectionInList<R.TipoGasto>(getPresenter().getModel(PROP_LISTA_TIPO_GASTO),
//                        getPresenter().getModel(PROP_TIPO_GASTO_SELECCIONADO)), jTextFieldTipo);
//        Bindings.bind(jTextFieldTipo, getPresenter().getModel(PROP_TIPO_GASTO_SELECCIONADO));
        jButtonCrearGasto.addActionListener(getPresenter().getOperation(ACTION_AGREGAR_GASTO));

        jButtonEliminarGasto.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR_GASTO));
        jButtonImprimirGastos.addActionListener(getPresenter().getOperation(ACTION_IMPRIMIR_GASTOS));
        jButtonLimpiarEntradas.addActionListener(getPresenter().getOperation(ACTION_LIMPIAR));
        jButtonAgregarDefaultGasto.addActionListener(getPresenter().getOperation(ACTION_AGREGAR_DEFAULT_GASTO));
        jButtonEliminarDefaultGasto.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR_DEFAULT_GASTO));

    }

    @Override
    public void uiInit() {
        initComponents();
        jButtonLimpiarEntradas.setIcon(MaterialIcons.LOOP);
        jButtonImprimirGastos.setIcon(MaterialIcons.PRINT);
        jButtonEliminarGasto.setIcon(MaterialIcons.DELETE);
        setCounterInBorder(90, jTextAreaDescripcion.getText().length());

        jTableInfo.setModel(new BindableTableModel<GastoVenta>(jTableInfo) {
            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Categoria";
                    case 1:
                        return "Tipo";
                    case 2:
                        return "Monto";
                    case 3:
                        return "Descripcion";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getGasto().getTipoGastoidGasto().getNombre();
                    case 1:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getGasto().getNombre();
                    case 2:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getImporte();
                    case 3:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getDescripcion();
                }
                return null;
            }
        });
        jTableInfo.getModel().addTableModelListener((TableModelEvent e) -> {
            if (jTableInfo.getModel().getRowCount() != 0) {
                jLabelGast.setText(utils.setDosLugaresDecimales(utils.calcularSumaTabla(jTableInfo, 2)));
            }
        });
        jTableInfo.getRowSorter().toggleSortOrder(0);
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void clear() {
        setCounterInBorder(90, jTextAreaDescripcion.getText().length());
    }

    private void setCounterInBorder(int max, int l) {
        jPanelDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15),
                ResourceBundle.getBundle("Strings").getString("label_descripcion")
                + " (" + String.valueOf(max - l) + ")")); // NOI18N
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarDefaultGasto;
    private javax.swing.JButton jButtonCrearGasto;
    private javax.swing.JButton jButtonEliminarDefaultGasto;
    private javax.swing.JButton jButtonEliminarGasto;
    private javax.swing.JButton jButtonImprimirGastos;
    private javax.swing.JButton jButtonLimpiarEntradas;
    private javax.swing.JComboBox<R.TipoGasto> jComboBoxCategoria;
    private javax.swing.JComboBox<R.TipoGasto> jComboBoxDefaultGastos;
    private javax.swing.JLabel jLabelGast;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAgregar1;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelDesc;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableInfo;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldTipoGasto;
    // End of variables declaration//GEN-END:variables
}
