/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.gastos;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.adapter.SpinnerToValueModelConnector;
import com.jgoodies.binding.list.SelectionInList;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.GastoVenta;
import com.jobits.pos.recursos.R;
import com.jobits.pos.recursos.R.TipoGasto;
import com.jobits.pos.ui.AbstractViewPanel;
import static com.jobits.pos.ui.gastos.presenter.GastosViewModel.*;
import static com.jobits.pos.ui.gastos.presenter.GastosViewPresenter.*;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableListIntelliHint;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.ui.utils.utils;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.util.ResourceBundle;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.checkerframework.checker.units.qual.K;

/**
 *
 * @author Home
 */
public class GastosView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Gastos";
    BindableListIntelliHint<K> autoCompleteModel;

    /**
     * Creates new form GastosView
     *
     * @param presenter
     */
    public GastosView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableInfo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButtonImprimirGastos = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonEliminarGasto = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelContainer = new javax.swing.JPanel();
        jLabelGast = new javax.swing.JLabel();
        jPanelAgregar1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonLimpiarEntradas = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonCrearGasto = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanel8 = new javax.swing.JPanel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jTextFieldTipo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jSpinnerMonto = new javax.swing.JSpinner();
        jLabelMonto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanelInfo.setLayout(new java.awt.BorderLayout());

        jTableInfo.setAutoCreateRowSorter(true);
        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Tipo", "Monto", "Descripcion"
            }
        ));
        jScrollPane4.setViewportView(jTableInfo);

        jPanelInfo.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButtonImprimirGastos.setText("Gastos");
        jButtonImprimirGastos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonImprimirGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirGastosActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonImprimirGastos, java.awt.BorderLayout.WEST);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonEliminarGasto.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEliminarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarGastoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonEliminarGasto, java.awt.BorderLayout.EAST);

        jPanelInfo.add(jPanel4, java.awt.BorderLayout.SOUTH);

        add(jPanelInfo, java.awt.BorderLayout.CENTER);

        jPanelContainer.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanelContainer.setMinimumSize(new java.awt.Dimension(200, 85));
        jPanelContainer.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelContainer.setLayout(new java.awt.BorderLayout());

        jLabelGast.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelGast.setForeground(new java.awt.Color(153, 0, 0));
        jLabelGast.setText("XXXX.XX CUC");
        jLabelGast.setToolTipText(null);
        jLabelGast.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Total"));
        jPanelContainer.add(jLabelGast, java.awt.BorderLayout.SOUTH);

        jPanelAgregar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nuevo/Editar Gasto"));
        jPanelAgregar1.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanelAgregar1.setMinimumSize(new java.awt.Dimension(200, 85));
        jPanelAgregar1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelAgregar1.setLayout(new java.awt.BorderLayout());

        jPanel3.setToolTipText(null);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButtonLimpiarEntradas.setToolTipText("Limpiar");
        jButtonLimpiarEntradas.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonLimpiarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarEntradasActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLimpiarEntradas, java.awt.BorderLayout.WEST);

        jButtonCrearGasto.setText("Crear");
        jButtonCrearGasto.setToolTipText(null);
        jButtonCrearGasto.setPreferredSize(new java.awt.Dimension(164, 28));
        jButtonCrearGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearGastoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCrearGasto, java.awt.BorderLayout.CENTER);

        jPanelAgregar1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel8.setToolTipText(null);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jComboBoxCategoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jComboBoxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("label_categoria"))); // NOI18N
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(170, 60));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxCategoria);

        jTextFieldTipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        jTextFieldTipo.setPreferredSize(new java.awt.Dimension(170, 60));
        jTextFieldTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTipoMouseClicked(evt);
            }
        });
        jPanel8.add(jTextFieldTipo);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Monto"));
        jPanel5.setMinimumSize(new java.awt.Dimension(150, 60));
        jPanel5.setPreferredSize(new java.awt.Dimension(170, 60));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jSpinnerMonto.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 5.0f));
        jSpinnerMonto.setPreferredSize(new java.awt.Dimension(90, 26));
        jSpinnerMonto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerMontoStateChanged(evt);
            }
        });
        jSpinnerMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSpinnerMontoFocusGained(evt);
            }
        });
        jPanel5.add(jSpinnerMonto, java.awt.BorderLayout.CENTER);

        jLabelMonto.setText("CUC");
        jPanel5.add(jLabelMonto, java.awt.BorderLayout.EAST);

        jPanel8.add(jPanel5);

        jPanel1.setPreferredSize(new java.awt.Dimension(170, 166));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("label_descripcion"))); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(150, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(140, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(140, 150));

        jTextAreaDescripcion.setColumns(5);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setTabSize(5);
        jTextAreaDescripcion.setToolTipText(null);
        jTextAreaDescripcion.setMinimumSize(new java.awt.Dimension(140, 140));
        jTextAreaDescripcion.setPreferredSize(new java.awt.Dimension(240, 140));
        jTextAreaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel1);

        jPanelAgregar1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanelContainer.add(jPanelAgregar1, java.awt.BorderLayout.CENTER);

        add(jPanelContainer, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirGastosActionPerformed
    }//GEN-LAST:event_jButtonImprimirGastosActionPerformed

    private void jButtonEliminarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarGastoActionPerformed
    }//GEN-LAST:event_jButtonEliminarGastoActionPerformed

    private void jButtonLimpiarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarEntradasActionPerformed
        clear();
    }//GEN-LAST:event_jButtonLimpiarEntradasActionPerformed

    private void jButtonCrearGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearGastoActionPerformed
        clear();
    }//GEN-LAST:event_jButtonCrearGastoActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
//        if (jComboBoxCategoria.getSelectedIndex() != 0) {
//            jTextFieldTipo.setEnabled(true);
//            jSpinnerMonto.setEnabled(true);
//            intellihints = new ListDataIntelliHints(jTextFieldTipo,
//                    getController().getNombres(jComboBoxCategoria.getSelectedItem().toString()));
//        } else {
//            jTextFieldTipo.setEnabled(false);
//        }
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextFieldTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTipoMouseClicked
//        System.out.println("click");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoMouseClicked

    private void jSpinnerMontoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerMontoStateChanged
//        try {
//            jButtonCrearE.setEnabled((float) jSpinnerMonto.getValue() > 0);
//            jTextAreaDescripcion.setEnabled((float) jSpinnerMonto.getValue() > 0);
//        } catch (ClassCastException e) {
//            jButtonCrearE.setEnabled((int) jSpinnerMonto.getValue() > 0);
//            jTextAreaDescripcion.setEnabled((int) jSpinnerMonto.getValue() > 0);
//        }
    }//GEN-LAST:event_jSpinnerMontoStateChanged

    private void jSpinnerMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinnerMontoFocusGained
//        jSpinnerMonto.setValue(null);
    }//GEN-LAST:event_jSpinnerMontoFocusGained

    private void jTextAreaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionKeyTyped
        int max = 90;
        String s = jTextAreaDescripcion.getText();
        int l = s.length();
        setCounterInBorder(max, l);
        if (l >= max) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextAreaDescripcionKeyTyped

    @Override
    public void wireUp() {
        Bindings.bind(jTableInfo, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_GASTO_VENTA),
                getPresenter().getModel(PROP_GASTO_VENTA_SELECCIONADO)));

        Bindings.bind(jComboBoxCategoria, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_CATEGORIA_GASTOS),
                getPresenter().getModel(PROP_CATEGORIA_GASTO_SELECCIONADA)));

        SpinnerToValueModelConnector connector = new SpinnerToValueModelConnector(jSpinnerMonto.getModel(),
                getPresenter().getModel(PROP_MONTO_GASTO), 0);
        Bindings.bind(jSpinnerMonto, "value", getPresenter().getModel(PROP_MONTO_GASTO));

        Bindings.bind(jTextAreaDescripcion, getPresenter().getModel(PROP_DESCRIPCION_GASTO));
        Bindings.bind(jLabelGast, getPresenter().getModel(PROP_TOTAL_GASTOS));

        autoCompleteModel = new BindableListIntelliHint(
                new SelectionInList<>(getPresenter().getModel(PROP_LISTA_TIPO_GASTO),
                        getPresenter().getModel(PROP_TIPO_GASTO_SELECCIONADO)), jTextFieldTipo);
        Bindings.bind(jTextFieldTipo, getPresenter().getModel(PROP_TIPO_GASTO_SELECCIONADO));
        jButtonCrearGasto.addActionListener(getPresenter().getOperation(ACTION_AGREGAR_GASTO));
        
        jButtonEliminarGasto.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR_GASTO));
        jButtonImprimirGastos.addActionListener(getPresenter().getOperation(ACTION_IMPRIMIR_GASTOS));
        jButtonLimpiarEntradas.addActionListener(getPresenter().getOperation(ACTION_LIMPIAR));

    }

    @Override
    public void uiInit() {
        initComponents();
        jButtonLimpiarEntradas.setIcon(MaterialIcons.LOOP);
        jButtonImprimirGastos.setIcon(MaterialIcons.PRINT);
        jButtonEliminarGasto.setIcon(MaterialIcons.DELETE);
        jLabelMonto.setText(R.COIN_SUFFIX);
        setCounterInBorder(90, jTextAreaDescripcion.getText().length());

        jTableInfo.setModel(new BindableTableModel<GastoVenta>(jTableInfo) {
            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Categoria";
                    case 1:
                        return "Tipo";
                    case 2:
                        return "Monto";
                    case 3:
                        return "Descripcion";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getGasto().getTipoGastoidGasto().getNombre();
                    case 1:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getGasto().getNombre();
                    case 2:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getImporte();
                    case 3:
                        return ((GastoVenta) getListModel().getElementAt(rowIndex)).getDescripcion();
                }
                return null;
            }
        });
        jTableInfo.getModel().addTableModelListener((TableModelEvent e) -> {
            if (jTableInfo.getModel().getRowCount() != 0) {
                jLabelGast.setText(utils.setDosLugaresDecimales(utils.calcularSumaTabla(jTableInfo, 2)));
            }
        });
        jTableInfo.getRowSorter().toggleSortOrder(0);
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void clear() {
        jTextFieldTipo.setText(null);
        jComboBoxCategoria.setSelectedIndex(0);
        setCounterInBorder(90, jTextAreaDescripcion.getText().length());
    }

    private void setCounterInBorder(int max, int l) {
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(
                ResourceBundle.getBundle("Strings").getString("label_descripcion") + " (" + String.valueOf(max - l) + ")")); // NOI18N
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearGasto;
    private javax.swing.JButton jButtonEliminarGasto;
    private javax.swing.JButton jButtonImprimirGastos;
    private javax.swing.JButton jButtonLimpiarEntradas;
    private javax.swing.JComboBox<TipoGasto> jComboBoxCategoria;
    private javax.swing.JLabel jLabelGast;
    private javax.swing.JLabel jLabelMonto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelAgregar1;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinnerMonto;
    private javax.swing.JTable jTableInfo;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
