/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta;

import com.jgoodies.common.collect.ArrayListModel;
import com.jobits.pos.domain.models.Mesa;
import com.jobits.pos.ui.AbstractViewPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Jorge
 */
public class MesaListView extends AbstractViewPanel implements ActionListener{

    public static final String VIEW_NAME = "Distribución mesas";

    
    private ArrayListModel<Mesa> listaMesas;

    public MesaListView(ArrayListModel<Mesa> listaMesas) {
        this.listaMesas = listaMesas;
        for (Mesa x : listaMesas) {
            add(createAndAttachButton(x));
        }
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setOpaque(false);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void wireUp() {
       
    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }


    private void fillPanel(){
        removeAll();
        for (Mesa x : listaMesas) {
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
    private JButton createAndAttachButton(Mesa m){
        FloorTableButton button =  new FloorTableButton(m);
        button.addActionListener(this);
        return button;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        firePropertyChange("click", e.getSource(),e.getSource());
    }

    
    
    

}
