/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.Cocina;
import com.jobits.pos.domain.models.ProductoInsumo;
import com.jobits.pos.domain.models.ProductovOrden;
import com.jobits.pos.main.Application;
import com.jobits.pos.recursos.R;
import com.jobits.pos.servicios.impresion.Impresora;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.configuracion.presenter.ImpresorasViewPresenter;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.ui.utils.utils;
import static com.jobits.pos.ui.venta.presenter.VentaResumenViewModel.*;
import static com.jobits.pos.ui.venta.presenter.VentaResumenViewPresenter.ACTION_IMPRIMIR_RESUMEN;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Home
 */
public class VentaResumenView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Resumen";

    /**
     * Creates new form VentaResumenView
     *
     * @param presenter
     */
    public VentaResumenView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeleccion = new javax.swing.JPanel();
        jPanelPeriodo = new javax.swing.JPanel();
        jButtonPeriodoSelector = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelPeriodoActual = new javax.swing.JLabel();
        jPanelPeriodChooser = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDateChooserDel = new org.jdesktop.swingx.JXDatePicker();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jDateChooserAl = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCocinas = new javax.swing.JComboBox<>();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonRestablecer = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGastos = new javax.swing.JTable();
        jPanel15 = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jToggleButtonMostrarConsumoDeLaCasa = new javax.swing.JToggleButton();
        jPanel24 = new javax.swing.JPanel();
        jTextFieldTotalRecaudado = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jTextFieldGanancia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanelRedondearValores = new javax.swing.JPanel();
        jToggleButtonReodndearValores = new javax.swing.JToggleButton();
        jPanel18 = new javax.swing.JPanel();
        jTextFieldDineroInvertido = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jTextFieldGastosdelaCasa = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jPanelPeriodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanelPeriodo.setPreferredSize(new java.awt.Dimension(320, 50));
        jPanelPeriodo.setLayout(new java.awt.BorderLayout());

        jButtonPeriodoSelector.setIcon(MaterialIcons.ARROW_DROP_RIGHT);
        jButtonPeriodoSelector.setPreferredSize(new java.awt.Dimension(40, 32));
        jPanelPeriodo.add(jButtonPeriodoSelector, java.awt.BorderLayout.EAST);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabelPeriodoActual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelPeriodoActual.setText("De :");
        jLabelPeriodoActual.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelPeriodoActualPropertyChange(evt);
            }
        });
        jPanel5.add(jLabelPeriodoActual, java.awt.BorderLayout.CENTER);

        jPanelPeriodo.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanelSeleccion.add(jPanelPeriodo, java.awt.BorderLayout.WEST);

        jPanelPeriodChooser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 0));
        jPanelPeriodChooser.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanelPeriodChooser.setLayout(new java.awt.GridLayout(1, 3));

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel8.setMinimumSize(new java.awt.Dimension(254, 20));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jDateChooserDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserDelActionPerformed(evt);
            }
        });
        jPanel8.add(jDateChooserDel);

        jPanel6.setMinimumSize(new java.awt.Dimension(20, 26));
        jPanel6.setPreferredSize(new java.awt.Dimension(20, 100));

        jLabel15.setText("hasta");
        jLabel15.setToolTipText("");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel15);

        jPanel8.add(jPanel6);

        jDateChooserAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateChooserAlActionPerformed(evt);
            }
        });
        jPanel8.add(jDateChooserAl);

        jPanelPeriodChooser.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Cocina");
        jPanel9.add(jLabel1);

        jPanel9.add(jComboBoxCocinas);

        jPanelPeriodChooser.add(jPanel9);

        jPanelSeleccion.add(jPanelPeriodChooser, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(110, 50));
        jPanelOpciones.setLayout(new java.awt.GridLayout(1, 2, 5, 1));

        jButtonRestablecer.setText("Imprimir");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jButtonRestablecer);

        jPanelSeleccion.add(jPanelOpciones, java.awt.BorderLayout.EAST);

        add(jPanelSeleccion, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(1158, 600));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        jPanel13.setLayout(new java.awt.BorderLayout());

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVentas);

        jPanel13.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jTableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableGastos);

        jPanel14.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 30));
        jPanel15.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel2.setBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_COLOR

            , 2, true));
    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
    jPanel21.setOpaque(false);
    jPanel21.setLayout(new java.awt.GridLayout(1, 2));

    jPanel22.setOpaque(false);
    jPanel22.setLayout(new java.awt.GridLayout(3, 1));

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/ganancia_verde.png"))); // NOI18N
    jPanel22.add(jLabel12);

    jLabel13.setText("Total Recaudado");
    jPanel22.add(jLabel13);

    jLabel14.setText("Ganancia");
    jPanel22.add(jLabel14);

    jPanel21.add(jPanel22);

    jPanel23.setOpaque(false);
    jPanel23.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

    jPanel7.setOpaque(false);
    jPanel7.setLayout(new java.awt.GridBagLayout());

    jToggleButtonMostrarConsumoDeLaCasa.setText("Mostrar Consumo de la Casa");
    jToggleButtonMostrarConsumoDeLaCasa.setOpaque(false);
    jPanel7.add(jToggleButtonMostrarConsumoDeLaCasa, new java.awt.GridBagConstraints());

    jPanel23.add(jPanel7);

    jPanel24.setOpaque(false);
    jPanel24.setLayout(new java.awt.GridBagLayout());

    jTextFieldTotalRecaudado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    jTextFieldTotalRecaudado.setEnabled(false);
    jTextFieldTotalRecaudado.setOpaque(false);
    jTextFieldTotalRecaudado.setPreferredSize(new java.awt.Dimension(250, 50));
    jPanel24.add(jTextFieldTotalRecaudado, new java.awt.GridBagConstraints());

    jPanel23.add(jPanel24);

    jPanel25.setOpaque(false);
    jPanel25.setLayout(new java.awt.GridBagLayout());

    jTextFieldGanancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    jTextFieldGanancia.setEnabled(false);
    jTextFieldGanancia.setOpaque(false);
    jTextFieldGanancia.setPreferredSize(new java.awt.Dimension(250, 50));
    jPanel25.add(jTextFieldGanancia, new java.awt.GridBagConstraints());

    jPanel23.add(jPanel25);

    jPanel21.add(jPanel23);

    jPanel2.add(jPanel21, java.awt.BorderLayout.CENTER);

    jPanel15.add(jPanel2);

    jPanel3.setBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_COLOR

        , 2, true));
jPanel3.setOpaque(false);
jPanel3.setLayout(new java.awt.BorderLayout());

jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
jPanel16.setOpaque(false);
jPanel16.setLayout(new java.awt.GridLayout(1, 2));

jPanel19.setOpaque(false);
jPanel19.setLayout(new java.awt.GridLayout(3, 1));

jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/perdida_rojo.png"))); // NOI18N
jPanel19.add(jLabel9);

jLabel10.setText("Dinero invertido");
jPanel19.add(jLabel10);

jLabel11.setText("Gastos de la Casa");
jPanel19.add(jLabel11);

jPanel16.add(jPanel19);

jPanel17.setOpaque(false);
jPanel17.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

jPanelRedondearValores.setOpaque(false);
jPanelRedondearValores.setLayout(new java.awt.GridBagLayout());

jToggleButtonReodndearValores.setText("Redondear Valores");
jToggleButtonReodndearValores.setOpaque(false);
jPanelRedondearValores.add(jToggleButtonReodndearValores, new java.awt.GridBagConstraints());

jPanel17.add(jPanelRedondearValores);

jPanel18.setOpaque(false);
jPanel18.setLayout(new java.awt.GridBagLayout());

jTextFieldDineroInvertido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
jTextFieldDineroInvertido.setEnabled(false);
jTextFieldDineroInvertido.setOpaque(false);
jTextFieldDineroInvertido.setPreferredSize(new java.awt.Dimension(250, 50));
jPanel18.add(jTextFieldDineroInvertido, new java.awt.GridBagConstraints());

jPanel17.add(jPanel18);

jPanel20.setOpaque(false);
jPanel20.setLayout(new java.awt.GridBagLayout());

jTextFieldGastosdelaCasa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
jTextFieldGastosdelaCasa.setEnabled(false);
jTextFieldGastosdelaCasa.setOpaque(false);
jTextFieldGastosdelaCasa.setPreferredSize(new java.awt.Dimension(250, 50));
jPanel20.add(jTextFieldGastosdelaCasa, new java.awt.GridBagConstraints());

jPanel17.add(jPanel20);

jPanel16.add(jPanel17);

jPanel3.add(jPanel16, java.awt.BorderLayout.CENTER);

jPanel15.add(jPanel3);

add(jPanel15, java.awt.BorderLayout.SOUTH);
}// </editor-fold>//GEN-END:initComponents

    private void jDateChooserDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserDelActionPerformed
    }//GEN-LAST:event_jDateChooserDelActionPerformed

    private void jDateChooserAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateChooserAlActionPerformed
    }//GEN-LAST:event_jDateChooserAlActionPerformed

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed

//        try {
//
//            MessageFormat footer = new MessageFormat("-Pag {0}-");
//
//            jTableGastos.print(JTable.PrintMode.FIT_WIDTH, headerGastos, footer);
//            jTableVentas.print(JTable.PrintMode.FIT_WIDTH, headerVentas, footer);
//
//        } catch (PrinterException ex) {
//            Logger.getLogger(Resumenes.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jButtonRestablecerActionPerformed

    private void jLabelPeriodoActualPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelPeriodoActualPropertyChange

    }//GEN-LAST:event_jLabelPeriodoActualPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPeriodoSelector;
    private javax.swing.JButton jButtonRestablecer;
    private javax.swing.JComboBox<Cocina> jComboBoxCocinas;
    private org.jdesktop.swingx.JXDatePicker jDateChooserAl;
    private org.jdesktop.swingx.JXDatePicker jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPeriodoActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeriodChooser;
    private javax.swing.JPanel jPanelPeriodo;
    private javax.swing.JPanel jPanelRedondearValores;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGastos;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextFieldDineroInvertido;
    private javax.swing.JTextField jTextFieldGanancia;
    private javax.swing.JTextField jTextFieldGastosdelaCasa;
    private javax.swing.JTextField jTextFieldTotalRecaudado;
    private javax.swing.JToggleButton jToggleButtonMostrarConsumoDeLaCasa;
    private javax.swing.JToggleButton jToggleButtonReodndearValores;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jTableVentas, new SelectionInList<ProductovOrden>(
                getPresenter().getModel(PROP_LISTA_VENTAS),
                getPresenter().getModel(PROP_SELECCIONADA_VENTA)));

        Bindings.bind(jComboBoxCocinas, new SelectionInList<Cocina>(
                getPresenter().getModel(PROP_LISTA_COCINA),
                getPresenter().getModel(PROP_SELECCIONADA_COCINA)), "Todas las Cocinas");

        Bindings.bind(jTableGastos, new SelectionInList<ProductoInsumo>(
                getPresenter().getModel(PROP_LISTA_COSTOS),
                getPresenter().getModel(PROP_SELECCIONADO_GASTO)));

        Bindings.bind(jDateChooserDel, "date", getPresenter().getModel(PROP_FECHA_DESDE));
        Bindings.bind(jDateChooserAl, "date", getPresenter().getModel(PROP_FECHA_HASTA));

        Bindings.bind(jLabelPeriodoActual, "text", getPresenter().getModel(PROP_RANGO_FECHAS_TEXT));

        Bindings.bind(jTextFieldTotalRecaudado, getPresenter().getModel(PROP_TOTAL_RECAUDADO));
        Bindings.bind(jTextFieldGanancia, getPresenter().getModel(PROP_GANANCIA));

        Bindings.bind(jTextFieldDineroInvertido, getPresenter().getModel(PROP_DINERO_INVERTIDO));
        Bindings.bind(jTextFieldGastosdelaCasa, getPresenter().getModel(PROP_GASTOS_DE_LA_CASA));

        Bindings.bind(jToggleButtonMostrarConsumoDeLaCasa, getPresenter().getModel(PROP_MOSTRAR_CONSUMO_DE_LA_CASA));
        Bindings.bind(jToggleButtonReodndearValores, getPresenter().getModel(PROP_REDONDEAR_VALORES));

//        jButtonRestablecer.addActionListener(getPresenter().getOperation(ACTION_IMPRIMIR_RESUMEN));
        jButtonRestablecer.addActionListener((ActionEvent e) -> {
            imprimir();
        });
    }

    @Override
    public void uiInit() {
        initComponents();

        jTableVentas.setModel(new BindableTableModel<ProductovOrden>(jTableVentas) {
            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Producto Venta";
                    case 1:
                        return "Precio (" + R.COIN_SUFFIX.substring(1) + ")";
                    case 2:
                        return "Cantidad";
                    case 3:
                        return "Recaudado (" + R.COIN_SUFFIX.substring(1) + ")";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((ProductovOrden) getListModel().getElementAt(rowIndex)).getNombreProductoVendido();
                    case 1:
                        return ((ProductovOrden) getListModel().getElementAt(rowIndex)).getPrecioVendido();
                    case 2:
                        ProductovOrden p = ((ProductovOrden) getListModel().getElementAt(rowIndex));
                        return utils.setDosLugaresDecimalesFloat(p.getCantidad());
                    case 3:
                        ProductovOrden x = ((ProductovOrden) getListModel().getElementAt(rowIndex));
                        return utils.setDosLugaresDecimalesFloat(x.getPrecioVendido() * x.getCantidad());
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return String.class;
                    default:
                        return Float.class;
                }
            }
        });
        jTableVentas.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableVentas.getColumnModel().getColumn(1).setCellRenderer(utils.numberColumCellRender());
        jTableVentas.getColumnModel().getColumn(2).setCellRenderer(utils.numberColumCellRender());
        jTableVentas.getColumnModel().getColumn(3).setCellRenderer(utils.numberColumCellRender());
        jTableVentas.getRowSorter().toggleSortOrder(0);

        jTableGastos.setModel(new BindableTableModel<ProductoInsumo>(jTableGastos) {
            @Override
            public int getColumnCount() {
                return 4;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Insumo";
                    case 1:
                        return "U/M";
                    case 2:
                        return "Cantidad";
                    case 3:
                        return "Costo (" + R.COIN_SUFFIX.substring(1) + ")";
                }
                return null;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return ((ProductoInsumo) getListModel().getElementAt(rowIndex)).getInsumo().getNombre();
                    case 1:
                        return ((ProductoInsumo) getListModel().getElementAt(rowIndex)).getInsumo().getUm();
                    case 2:
                        ProductoInsumo p = ((ProductoInsumo) getListModel().getElementAt(rowIndex));
                        return utils.setDosLugaresDecimalesFloat(p.getCantidad());
                    case 3:
                        ProductoInsumo x = ((ProductoInsumo) getListModel().getElementAt(rowIndex));
                        return utils.setDosLugaresDecimalesFloat(x.getCosto());
                }
                return null;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    default:
                        return Float.class;
                }
            }
        });
        jTableGastos.getRowSorter().toggleSortOrder(0);
        jTableGastos.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableGastos.getColumnModel().getColumn(2).setCellRenderer(utils.numberColumCellRender());
        jTableGastos.getColumnModel().getColumn(3).setCellRenderer(utils.numberColumCellRender());

        jToggleButtonReodndearValores.addActionListener((ActionEvent e) -> {
            jTableGastos.repaint();
            jTableGastos.revalidate();
            jTableVentas.repaint();
            jTableVentas.revalidate();
        });
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private void imprimir() {
        String hVentas,
                hGastos,
                cDate,
                nombreMenu = R.REST_NAME;
        LocalDate inicio = (jDateChooserDel.getDate()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fin = (jDateChooserAl.getDate()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int diff = (int) ChronoUnit.DAYS.between(inicio, fin);
        if (diff == 0) {
            cDate = R.DATE_FORMAT.format(jDateChooserDel.getDate());
            if (jToggleButtonMostrarConsumoDeLaCasa.isSelected()) {
                hVentas = ("De la Casa del dia " + cDate);
            } else {
                hVentas = ("Ventas del dia " + cDate);
            }
            hGastos = ("Gastos del dia " + cDate);
        } else {
            cDate = R.DATE_FORMAT.format(jDateChooserDel.getDate())
                    + " al " + R.DATE_FORMAT.format(jDateChooserAl.getDate());
            if (jToggleButtonMostrarConsumoDeLaCasa.isSelected()) {
                hVentas = ("De la Casa del " + cDate);
            } else {
                hVentas = ("Ventas del " + cDate);
            }
            hGastos = ("Gastos del " + cDate);
        }
        if (jComboBoxCocinas.getSelectedIndex() != 0) {
            Cocina c = (Cocina) jComboBoxCocinas.getSelectedItem();
            hVentas += " (" + c.getCodCocina() + ")";
            hGastos += " (" + c.getCodCocina() + ")";
        }
        try {
            MessageFormat footer = new MessageFormat("-Pag {0}-");
            jTableVentas.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat(hVentas), footer);
            jTableGastos.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat(hGastos), footer);
        } catch (PrinterException ex) {
            Logger.getLogger(Resumenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
