/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.venta;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.ui.utils.VentaCellRender;
import javax.swing.JFileChooser;
import com.jobits.pos.core.domain.models.Venta;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.ui.venta.presenter.VentaCalendarViewModel;
import com.jobits.pos.ui.venta.presenter.VentaCalendarViewPresenter;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.calendar.DateSelectionModel;

/**
 *
 * @author Jorge
 */
public class VentaCalendarView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Ventas";

    private JFileChooser fileChooser;

    private BindableTableModel<List<Venta>> model;

    public VentaCalendarView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelCalendario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalendar = new javax.swing.JTable();
        jPanelHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelControles = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonImportarVentas = new javax.swing.JButton();
        jPanelSeleccion = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanelEstadisticas = new javax.swing.JPanel();
        jPanelVentas = new javax.swing.JPanel();
        jLabelTotalVendido = new javax.swing.JLabel();
        jLabelPromedioVendido = new javax.swing.JLabel();
        jLabelHoraPico = new javax.swing.JLabel();
        jPanelGastos = new javax.swing.JPanel();
        jLabelInsumo = new javax.swing.JLabel();
        jLabelTrabajadores = new javax.swing.JLabel();
        jLabelOtros = new javax.swing.JLabel();
        jPanelResumen = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserDel = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooserAl = new org.jdesktop.swingx.JXDatePicker();
        jButton3 = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTree1);

        setLayout(new java.awt.BorderLayout(5, 5));

        jPanelDetalles.setLayout(new javax.swing.OverlayLayout(jPanelDetalles));

        jPanelCalendario.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCalendario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelCalendario.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);

        jTableCalendar.setBackground(new java.awt.Color(204, 204, 204));
        jTableCalendar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTableCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCalendar.setColumnSelectionAllowed(true);
        jTableCalendar.setOpaque(false);
        jTableCalendar.setRowHeight(80);
        jTableCalendar.setShowGrid(false);
        jTableCalendar.setTableHeader(null);
        jScrollPane1.setViewportView(jTableCalendar);

        jPanelCalendario.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanelHeader.setLayout(new java.awt.GridLayout(1, 7));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lunes");
        jPanelHeader.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Martes");
        jPanelHeader.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Miercoles");
        jPanelHeader.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jueves");
        jPanelHeader.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Viernes");
        jPanelHeader.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sabado");
        jPanelHeader.add(jLabel7);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Domingo");
        jPanelHeader.add(jLabel1);

        jPanelCalendario.add(jPanelHeader, java.awt.BorderLayout.PAGE_START);

        jPanelDetalles.add(jPanelCalendario);

        add(jPanelDetalles, java.awt.BorderLayout.CENTER);

        jPanelControles.setBackground(new java.awt.Color(204, 204, 204));
        jPanelControles.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonEliminar.setText(bundle.getString("label_eliminar")); // NOI18N
        jPanelControles.add(jButtonEliminar);

        jButtonEditar.setText(bundle.getString("label_editar")); // NOI18N
        jPanelControles.add(jButtonEditar);

        jButtonY.setText("Y");
        jPanelControles.add(jButtonY);

        jButtonImportarVentas.setText("Importar Ventas");
        jPanelControles.add(jButtonImportarVentas);

        add(jPanelControles, java.awt.BorderLayout.PAGE_END);

        jPanelSeleccion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSeleccion.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel9.setText("Año");
        jPanel3.add(jLabel9);

        jYearChooser1.setOpaque(false);
        jYearChooser1.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel3.add(jYearChooser1);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel8.setText("Mes");
        jPanel3.add(jLabel8);

        jMonthChooser1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMonthChooser1.setMinimumSize(new java.awt.Dimension(176, 40));
        jMonthChooser1.setOpaque(false);
        jMonthChooser1.setPreferredSize(new java.awt.Dimension(176, 40));
        jPanel3.add(jMonthChooser1);

        jPanelSeleccion.add(jPanel3, java.awt.BorderLayout.EAST);

        add(jPanelSeleccion, java.awt.BorderLayout.PAGE_START);

        jPanelEstadisticas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estadisticas Generales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelEstadisticas.setLayout(new java.awt.GridLayout(3, 0));

        jPanelVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelVentas.setLayout(new java.awt.GridLayout(3, 0));

        jLabelTotalVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTotalVendido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pulgar-arriba.png"))); // NOI18N
        jLabelTotalVendido.setText("XXXXXX.XX < >");
        jLabelTotalVendido.setToolTipText("Total");
        jLabelTotalVendido.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));
        jPanelVentas.add(jLabelTotalVendido);

        jLabelPromedioVendido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelPromedioVendido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPromedioVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/promedio.png"))); // NOI18N
        jLabelPromedioVendido.setText("XXXXXX.XX < >");
        jLabelPromedioVendido.setToolTipText("Promedio");
        jLabelPromedioVendido.setBorder(javax.swing.BorderFactory.createTitledBorder("Promedio"));
        jPanelVentas.add(jLabelPromedioVendido);

        jLabelHoraPico.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelHoraPico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHoraPico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/hora_pico.png"))); // NOI18N
        jLabelHoraPico.setText("XX PM/AM");
        jLabelHoraPico.setToolTipText("Hora Pico");
        jLabelHoraPico.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora Pico"));
        jPanelVentas.add(jLabelHoraPico);

        jPanelEstadisticas.add(jPanelVentas);

        jPanelGastos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gastos", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelGastos.setLayout(new java.awt.GridLayout(3, 0));

        jLabelInsumo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelInsumo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInsumo.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelInsumo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 3, true), "Insumo"));
        jPanelGastos.add(jLabelInsumo);

        jLabelTrabajadores.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTrabajadores.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 3, true), "Trabajadores"));
        jPanelGastos.add(jLabelTrabajadores);

        jLabelOtros.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelOtros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelOtros.setText(bundle.getString("label_numeros_moneda")); // NOI18N
        jLabelOtros.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true), "Otros"));
        jPanelGastos.add(jLabelOtros);

        jPanelEstadisticas.add(jPanelGastos);

        jPanelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen Detallado", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        jPanelResumen.setLayout(new javax.swing.BoxLayout(jPanelResumen, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel10.setText("Del");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);
        jPanel1.add(jDateChooserDel);

        jPanelResumen.add(jPanel1);

        jLabel11.setText("Al");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jPanel2.add(jDateChooserAl);

        jPanelResumen.add(jPanel2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/detalles.png"))); // NOI18N
        jButton3.setToolTipText("Vista Detallada");
        jButton3.setBorderPainted(false);
        jPanelResumen.add(jButton3);

        jPanelEstadisticas.add(jPanelResumen);

        add(jPanelEstadisticas, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonImportarVentas;
    private javax.swing.JButton jButtonY;
    private org.jdesktop.swingx.JXDatePicker jDateChooserAl;
    private org.jdesktop.swingx.JXDatePicker jDateChooserDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHoraPico;
    private javax.swing.JLabel jLabelInsumo;
    private javax.swing.JLabel jLabelOtros;
    private javax.swing.JLabel jLabelPromedioVendido;
    private javax.swing.JLabel jLabelTotalVendido;
    private javax.swing.JLabel jLabelTrabajadores;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCalendario;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResumen;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCalendar;
    private javax.swing.JTree jTree1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jYearChooser1, "year", getPresenter().getModel(VentaCalendarViewModel.PROP_YEAR_SELECCIONADO));
        Bindings.bind(jMonthChooser1, "month", getPresenter().getModel(VentaCalendarViewModel.PROP_MES_SELECCIONADO));
        Bindings.bind(jDateChooserAl, "date", getPresenter().getModel(VentaCalendarViewModel.PROP_RESUMEN_HASTA));
        Bindings.bind(jDateChooserDel, "date", getPresenter().getModel(VentaCalendarViewModel.PROP_RESUMEN_DESDE));
        Bindings.bind(jLabelHoraPico, getPresenter().getModel(VentaCalendarViewModel.PROP_HORA_PICO_INTERVALOS));
        Bindings.bind(jLabelInsumo, getPresenter().getModel(VentaCalendarViewModel.PROP_GASTO_INSUMO_INTERVALO));
        Bindings.bind(jLabelOtros, getPresenter().getModel(VentaCalendarViewModel.PROP_GASTO_OTROS_INTERVALO));
        Bindings.bind(jLabelPromedioVendido, getPresenter().getModel(VentaCalendarViewModel.PROP_PROMEDIO_VENTAS_INTERVALO));
        Bindings.bind(jLabelTotalVendido, getPresenter().getModel(VentaCalendarViewModel.PROP_TOTAL_VENTAS_INTERVALO));
        Bindings.bind(jLabelTrabajadores, getPresenter().getModel(VentaCalendarViewModel.PROP_GASTO_TRABAJADORES_INTERVALO));
        Bindings.bind(fileChooser, "selectedFile", getPresenter().getModel(VentaCalendarViewModel.PROP_ARCHIVO_A_IMPORTAR));
        Bindings.bind(jButtonY, "visible", getPresenter().getModel(VentaCalendarViewModel.PROP_Y_VISIBLE));
        jButtonEditar.addActionListener(getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_EDITAR));
        jButtonEliminar.addActionListener(getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_ELIMINAR));
        jButtonImportarVentas.addActionListener((e) -> {
            int result = fileChooser.showSaveDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_IMPORTAR_VENTA).doAction();
            }
        });
        Bindings.bind(jTableCalendar, new SelectionInList<List<Venta>>(
                getPresenter().getModel(VentaCalendarViewModel.PROP_LISTA_ELEMENTOS),
                getPresenter().getModel(VentaCalendarViewModel.PROP_ELEMENTO_SELECCIONADO)));
        jButtonY.addActionListener(getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_Y));
        jButton3.addActionListener(getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_RESUMEN_DETALLADO));
        jTableCalendar.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            getPresenter().getModel(VentaCalendarViewModel.PROP_DIA_SELECCIONADO).setValue(getObjectAtSelectedCell());
        });
        jTableCalendar.getColumnModel().getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            getPresenter().getModel(VentaCalendarViewModel.PROP_DIA_SELECCIONADO).setValue(getObjectAtSelectedCell());
        });
        jTableCalendar.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2 && evt.getButton() == 1) {
                    getPresenter().getOperation(VentaCalendarViewPresenter.ACTION_EDITAR).doAction();
                }
            }

        });
    }

    @Override

    public void uiInit() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        fileChooser = new JFileChooser();
        model = new BindableTableModel<List<Venta>>(jTableCalendar) {//findVentas(month, year)
            @Override
            public int getColumnCount() {
                return 7;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return List.class;
            }

            @Override
            public List<Venta> getValueAt(int rowIndex, int columnIndex) {
                int linearPos = (rowIndex * (getColumnCount() - 1) + columnIndex) + rowIndex + 1;
                int relativePos = linearPos - getPresenter().getModel(VentaCalendarViewModel.PROP_MONTH_OFFSET).intValue();

                if (relativePos > 0) {
                    return getObjectAt(relativePos);
                }
                return null;
            }

            @Override
            public List<Venta> getObjectAt(int dayOfMonth) {
                for (int i = 0; i < getListModel().getSize(); i++) {
                    if (super.getRow(i) != null) {
                        if (!super.getRow(i).isEmpty()) {
                            if (super.getRow(i).get(0).getFecha().getDate() == dayOfMonth) {
                                return super.getRow(i);
                            }
                        }
                    }
                }
                return null;
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Lunes";
                    case 1:
                        return "Martes";
                    case 2:
                        return "Miercoles";
                    case 3:
                        return "Jueves";
                    case 4:
                        return "Viernes";
                    case 5:
                        return "Sabado";
                    case 6:
                        return "Domingo";
                    default:
                        return null;
                }
            }

        };
        jTableCalendar.setModel(model);
        jTableCalendar.setDefaultRenderer(List.class, new VentaCellRender());
        jTableCalendar.setCellSelectionEnabled(true);
        jTableCalendar.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jPanelResumen.setVisible(false);

    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    private List<Venta> getObjectAtSelectedCell() {
        if (jTableCalendar.getSelectedRow() == -1 || jTableCalendar.getSelectedColumn() == -1) {
            return null;
        }
        return (List<Venta>) model.getValueAt(jTableCalendar.getSelectedRow(), jTableCalendar.getSelectedColumn());
    }

}
