/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.util;

import GUI.Views.AbstractView;
import restManager.controller.AbstractDialogController;
import restManager.controller.Controller;
import restManager.controller.login.LogInController;
import restManager.exceptions.DevelopingOperationException;
import restManager.persistencia.Orden;
import restManager.printservice.Impresion;
import restManager.resources.R;
import restManager.util.ComponentMover;
import restManager.util.comun;

/**
 *
 * @author Jorge
 */
public class AutenticacionFragmentView extends AbstractView {



    public AutenticacionFragmentView(AbstractView parent, AbstractDialogController controller, boolean modal) {
        super(DialogType.DEFINED, controller, parent, modal);
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelUser = new javax.swing.JPanel();
        jideLabel1 = new com.jidesoft.swing.JideLabel();
        overlayTextField1 = new com.jidesoft.swing.OverlayTextField();
        jPanelPass = new javax.swing.JPanel();
        jideLabel2 = new com.jidesoft.swing.JideLabel();
        jPasswordField = new com.jidesoft.swing.OverlayPasswordField();
        jPanelOptions = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAutenticar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setMinimumSize(new java.awt.Dimension(287, 188));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelUser.setBackground(new java.awt.Color(0, 153, 153));
        jPanelUser.setOpaque(false);

        jideLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/usuario.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jideLabel1.setText(bundle.getString("label_usuario")); // NOI18N
        jPanelUser.add(jideLabel1);

        overlayTextField1.setMinimumSize(new java.awt.Dimension(200, 26));
        overlayTextField1.setPreferredSize(new java.awt.Dimension(257, 22));
        jPanelUser.add(overlayTextField1);

        jPanel1.add(jPanelUser);

        jPanelPass.setBackground(new java.awt.Color(0, 153, 153));
        jPanelPass.setOpaque(false);

        jideLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/contraseña.png"))); // NOI18N
        jideLabel2.setText(bundle.getString("label_contrasena")); // NOI18N
        jPanelPass.add(jideLabel2);

        jPasswordField.setToolTipText("Contraseña");
        jPasswordField.setMaximumSize(new java.awt.Dimension(2147483647, 22));
        jPasswordField.setMinimumSize(new java.awt.Dimension(200, 26));
        jPasswordField.setPreferredSize(new java.awt.Dimension(257, 22));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanelPass.add(jPasswordField);

        jPanel1.add(jPanelPass);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelOptions.setBackground(new java.awt.Color(153, 153, 153));
        jPanelOptions.setBorder(new org.pushingpixels.lafwidget.utils.ShadowPopupBorder());
        jPanelOptions.setMaximumSize(new java.awt.Dimension(272, 44));
        jPanelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButtonCancelar.setText(bundle.getString("label_cancelar")); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelOptions.add(jButtonCancelar);

        jButtonAutenticar.setText(bundle.getString("label_autorizar")); // NOI18N
        jButtonAutenticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutenticarActionPerformed(evt);
            }
        });
        jPanelOptions.add(jButtonAutenticar);

        getContentPane().add(jPanelOptions, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed

    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAutenticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutenticarActionPerformed
        getController().autorizar(overlayTextField1.getText(), jPasswordField.getPassword());
        jPasswordField.setText("");
    }//GEN-LAST:event_jButtonAutenticarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutenticar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelPass;
    private javax.swing.JPanel jPanelUser;
    private com.jidesoft.swing.OverlayPasswordField jPasswordField;
    private com.jidesoft.swing.JideLabel jideLabel1;
    private com.jidesoft.swing.JideLabel jideLabel2;
    private com.jidesoft.swing.OverlayTextField overlayTextField1;
    // End of variables declaration//GEN-END:variables

    
        @Override
    public LogInController getController() {
        return (LogInController) super.getController(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateView() {
        
    }

}
