/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Views.util;

import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.TitledBorder;
import javax.swing.table.TableCellRenderer;
import restManager.persistencia.Venta;
import restManager.util.comun;

/**
 *
 * @author Jorge
 */
public class VentaCellRender extends javax.swing.JPanel implements TableCellRenderer {

    Venta v;

    /**
     * Creates new form VentaCellRender
     *
     */
    public VentaCellRender() {
    }

    private VentaCellRender(Venta v) {
        if(v != null){
            this.v = v;
        initComponents();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGastos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""+v.getFecha().getDate()));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jLabelGastos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelGastos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelGastos.setForeground(new java.awt.Color(102, 0, 0));
        jLabelGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pulgares-abajo.png"))); // NOI18N
        jLabelGastos.setText(v.getVentagastosEninsumos() != null
            ? comun.setDosLugaresDecimales(v.getVentagastosEninsumos().floatValue())
            : "-");
        add(jLabelGastos, java.awt.BorderLayout.PAGE_END);

        jLabelVentas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabelVentas.setForeground(new java.awt.Color(0, 102, 51));
        jLabelVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/pulgar-arriba.png"))); // NOI18N
        jLabelVentas.setText(v.getVentaTotal() != null
            ? comun.setDosLugaresDecimales(v.getVentaTotal().floatValue())
            :"-");
        add(jLabelVentas, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println("selected");        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelVentas;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        VentaCellRender ret = new VentaCellRender((Venta) value);
        
        if (isSelected && ret.getV() != null) {
            ret.setBackground(table.getSelectionBackground());
        } else {
            ret.setBackground(table.getBackground());
        }
        return ret;
    }

    public Venta getV() {
        return v;
    }

    
    
}
