/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.almacen;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.domain.models.Insumo;
import com.jobits.pos.domain.models.InsumoAlmacen;
import static com.jobits.pos.ui.almacen.presenter.AlmacenViewModel.*;
import static com.jobits.pos.ui.almacen.presenter.AlmacenViewPresenter.*;
import com.jobits.pos.ui.utils.AddFromPanel;
import com.jobits.pos.ui.utils.BindableTableModel;
import com.jobits.pos.ui.utils.utils;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author Home
 */
public class AlmacenMainView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Almacenes";

    private AddFromPanel<InsumoAlmacen, Insumo> tableInsumos;

    public AlmacenMainView(AbstractViewPresenter presenter) {
        super(presenter);
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                jTextFieldBusqueda.requestFocus();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSeleccion = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldBusqueda = MaterialComponentsFactory.Input.getTextField("Buscar insumo", "");
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jLabel1 = new javax.swing.JLabel();
        jPanelPeriodo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxAlmacenList = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jButtonNuevoAlmacen = MaterialComponentsFactory.Buttons.getOutlinedButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jButtonEliminarAlmacen = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelTabla = new javax.swing.JPanel();
        jPanelOpciones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelValorTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonNuevaFactura = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonTransacciones = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonDarReporte = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonResumen = MaterialComponentsFactory.Buttons.getOutlinedButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanelSeleccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelSeleccion.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanelSeleccion.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTextFieldBusqueda.setPreferredSize(new java.awt.Dimension(300, 24));
        jTextFieldBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBusquedaFocusLost(evt);
            }
        });
        jPanel4.add(jTextFieldBusqueda);
        jPanel4.add(filler3);

        jLabel1.setIcon(MaterialIcons.SEARCH);
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel4.add(jLabel1);

        jPanelSeleccion.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanelPeriodo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jPanelPeriodo.setOpaque(false);
        jPanelPeriodo.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanelPeriodo.setLayout(new javax.swing.BoxLayout(jPanelPeriodo, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jComboBoxAlmacenList.setMaximumRowCount(20);
        jComboBoxAlmacenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlmacenListActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAlmacenList, java.awt.BorderLayout.CENTER);

        jPanelPeriodo.add(jPanel1);
        jPanelPeriodo.add(filler1);

        jButtonNuevoAlmacen.setIcon(MaterialIcons.ADD);
        jButtonNuevoAlmacen.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonNuevoAlmacen.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonNuevoAlmacen.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelPeriodo.add(jButtonNuevoAlmacen);
        jPanelPeriodo.add(filler2);

        jButtonEliminarAlmacen.setIcon(MaterialIcons.DELETE);
        jButtonEliminarAlmacen.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonEliminarAlmacen.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonEliminarAlmacen.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelPeriodo.add(jButtonEliminarAlmacen);

        jPanelSeleccion.add(jPanelPeriodo, java.awt.BorderLayout.WEST);

        add(jPanelSeleccion, java.awt.BorderLayout.PAGE_START);

        jPanelTabla.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTabla.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTabla.setLayout(new java.awt.BorderLayout());
        add(jPanelTabla, java.awt.BorderLayout.CENTER);

        jPanelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Valor total en almacen", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanelOpciones.setMinimumSize(new java.awt.Dimension(690, 90));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(690, 100));
        jPanelOpciones.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(406, 40));
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        jLabelValorTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelValorTotal.setText("0.00 CUC");
        jLabelValorTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelValorTotal.setFocusable(false);
        jPanel2.add(jLabelValorTotal, java.awt.BorderLayout.CENTER);

        jPanelOpciones.add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jButtonNuevaFactura.setText("Nueva Factura");
        jButtonNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaFacturaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNuevaFactura);

        jButtonTransacciones.setText("Transacciones");
        jButtonTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransaccionesActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTransacciones);

        jButtonDarReporte.setText("Reporte");
        jButtonDarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDarReporteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDarReporte);

        jButtonResumen.setText("Resumen");
        jButtonResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResumenActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonResumen);

        jPanelOpciones.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanelOpciones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaFacturaActionPerformed
        // OperacionView view = new OperacionView(new AlmacenManageController(getInstance()), this, true);
    }//GEN-LAST:event_jButtonNuevaFacturaActionPerformed

    private void jButtonTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransaccionesActionPerformed
        //getController().verTransacciones(getInstance());
    }//GEN-LAST:event_jButtonTransaccionesActionPerformed

    private void jButtonDarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDarReporteActionPerformed
        //getController().imprimirReporteParaCompras(getInstance());
    }//GEN-LAST:event_jButtonDarReporteActionPerformed

    private void jButtonResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResumenActionPerformed
        // getController().imprimirResumenAlmacen(getInstance());
    }//GEN-LAST:event_jButtonResumenActionPerformed

    private void jComboBoxAlmacenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlmacenListActionPerformed
        tableInsumos.getjTableCrossReference().revalidate();
    }//GEN-LAST:event_jComboBoxAlmacenListActionPerformed

    private void jTextFieldBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonDarReporte;
    private javax.swing.JButton jButtonEliminarAlmacen;
    private javax.swing.JButton jButtonNuevaFactura;
    private javax.swing.JButton jButtonNuevoAlmacen;
    private javax.swing.JButton jButtonResumen;
    private javax.swing.JButton jButtonTransacciones;
    private javax.swing.JComboBox<String> jComboBoxAlmacenList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPeriodo;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jComboBoxAlmacenList, new SelectionInList<>(
                getPresenter().getModel(PROP_LISTA_ELEMENTOS),
                getPresenter().getModel(PROP_ELEMENTO_SELECCIONADO)));

        jButtonNuevoAlmacen.setAction(getPresenter().getOperation(ACTION_CREAR_ALMACEN));
        jButtonNuevoAlmacen.setIcon(MaterialIcons.ADD);
        jButtonNuevoAlmacen.setText("");

        jButtonEliminarAlmacen.setAction(getPresenter().getOperation(ACTION_ELIMINAR_ALMACEN));
        jButtonEliminarAlmacen.setIcon(MaterialIcons.DELETE);
        jButtonEliminarAlmacen.setText("");

        Bindings.bind(jLabelValorTotal, getPresenter().getModel(PROP_VALOR_MONETARIO_TEXT));

        jComboBoxAlmacenList.addItemListener((ItemEvent e) -> {
            getPresenter().getOperation(ACTION_ACTUALIZAR_LISTA_ALMACEN).doAction();
            jTextFieldBusqueda.requestFocusInWindow();
        });
        jButtonResumen.setAction(getPresenter().getOperation(ACTION_IMPRIMIR_RESUMEN));
        jButtonResumen.setIcon(MaterialIcons.PRINT);
        jButtonDarReporte.setAction(getPresenter().getOperation(ACTION_IMPRIMIR_REPORTE));
        jButtonDarReporte.setIcon(MaterialIcons.PRINT);

        jButtonTransacciones.setAction(getPresenter().getOperation(ACTION_TRANSACCIONES));
        jButtonNuevaFactura.setAction(getPresenter().getOperation(ACTION_NUEVA_FACTURA));

        tableInsumos.getjTableCrossReference().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    getPresenter().getOperation(ACTION_MODIFICAR_STOCK).doAction();
                }
            }
        });

        Bindings.bind(jPanelTabla, "visible", getPresenter().getModel(PROP_PANEL_VISIBLE));
        Bindings.bind(jPanelOpciones, "visible", getPresenter().getModel(PROP_PANEL_VISIBLE));
        Bindings.bind(jTextFieldBusqueda, getPresenter().getModel(PROP_SEARCH_KEYWORD));
    }

    @Override
    public void uiInit() {
        initComponents();

        AddFromPanel.AddFromPanelBuilder<InsumoAlmacen, Insumo> builder = AddFromPanel.builder();

        builder.addAction(getPresenter().getOperation(ACTION_AGREGAR_INSUMO));
        builder.removeAction(getPresenter().getOperation(ACTION_ELIMINAR_INSUMO));
        builder.autoCompletitionData(getPresenter().getModel(PROP_LISTA_INSUMOS_DISPONIBLES));
        builder.autoCOmpletitionDataSelection(getPresenter().getModel(PROP_INSUMO_DISPONIBLE_SELECCIONADO));
        builder.jTextFieldDataName("Insumos");
        builder.tableDataHolder(getPresenter().getModel(PROP_LISTA_INSUMOS_CONTENIDOS));
        builder.tableSelectionDataHolder(getPresenter().getModel(PROP_INSUMO_CONTENIDO_SELECCIONADO));

        BindableTableModel<InsumoAlmacen> tableModel
                = new BindableTableModel<InsumoAlmacen>() {
            @Override
            public int getColumnCount() {
                return 6;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                switch (columnIndex) {
                    case 0:
                        return (String) getRow(rowIndex).getInsumo().getCodInsumo();
                    case 2:
                        return getRow(rowIndex).getInsumo().getNombre();
                    case 1:
                        return getRow(rowIndex).getInsumo().getUm();
                    case 3:
                        return utils.setDosLugaresDecimalesFloat(getRow(rowIndex).getCantidad());
                    case 4:
                        return getRow(rowIndex).getCantidad() != 0
                                ? utils.setDosLugaresDecimales(getRow(rowIndex).getValorMonetario() / getRow(rowIndex).getCantidad()) : 0;
                    case 5:
                        return utils.setDosLugaresDecimales(getRow(rowIndex).getValorMonetario());
                    default:
                        return null;
                }
            }

            @Override
            public String getColumnName(int column) {
                switch (column) {
                    case 0:
                        return "Codigo";
                    case 2:
                        return "Nombre";
                    case 1:
                        return "UM";
                    case 3:
                        return "En Almacen";
                    case 4:
                        return "Costo Unitario (Prom)";
                    case 5:
                        return "Valor Total";
                    default:
                        return null;
                }
            }
        };
        builder.tableModel(tableModel);

        tableInsumos = builder.build();
        jPanelTabla.add(tableInsumos, BorderLayout.CENTER);
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

}
