/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.almacen;

import com.jobits.pos.ui.OldAbstractView;
import com.jobits.pos.ui.utils.RestaurantManagerListIntelliHint;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import com.jobits.pos.controller.AbstractDialogController;
import com.jobits.pos.controller.almacen.AlmacenManageController;
import com.jobits.pos.controller.almacen.AlmacenManageController.CheckBoxType;
import com.jobits.pos.exceptions.DevelopingOperationException;
import com.jobits.pos.exceptions.UnExpectedErrorException;
import com.jobits.pos.domain.models.Almacen;
import com.jobits.pos.domain.models.Cocina;
import com.jobits.pos.domain.models.InsumoAlmacen;
import com.jobits.pos.domain.TransaccionSimple;
import com.jobits.pos.ui.utils.RestManagerComboBoxModel;
import com.jobits.pos.ui.utils.utils;
import com.jobits.ui.components.MaterialComponentsFactory;

/**
 *
 * @author Jorge
 */
public class OperacionView extends OldAbstractView {

    private AlmacenManageController controller;
    private CheckBoxType tipoOperacion = CheckBoxType.ENTRADA;
    private ArrayList<TransaccionSimple> transacciones = new ArrayList<>();
    private RestaurantManagerListIntelliHint<InsumoAlmacen> list;

    public OperacionView(AbstractDialogController controller) {

        super(DialogType.DEFINED, controller);
        this.controller = (AlmacenManageController) controller;
        initComponents();
        buttonGroup1.add(jRadioButtonTraspaso);
        buttonGroup1.add(jRadioButtonSalida);
        buttonGroup1.add(jRadioButtonRebaja);
        buttonGroup1.add(jRadioButtonEntrada);
        jComboBoxAlmacenExistencias.setVisible(false);
        jTextFieldCausa.setVisible(false);
        list = new RestaurantManagerListIntelliHint<>(jTextFieldInsumo, this.controller.getInsumoAlmacenList(this.controller.getInstance()));
        setVisible(true);

    }

    /**
     * Creates new form OperacionView
     *
     * @param controller
     * @param owner
     * @param modal
     */
    public OperacionView(AbstractDialogController controller, Dialog owner, boolean modal) {
        super(DialogType.DEFINED, controller, owner, modal);
        this.controller = (AlmacenManageController) controller;
        this.controller.setParent(owner);
        this.controller.setView(this);
        initComponents();
        buttonGroup1.add(jRadioButtonTraspaso);
        buttonGroup1.add(jRadioButtonSalida);
        buttonGroup1.add(jRadioButtonRebaja);
        buttonGroup1.add(jRadioButtonEntrada);
        jComboBoxAlmacenExistencias.setVisible(false);
        jTextFieldCausa.setVisible(false);
        list = new RestaurantManagerListIntelliHint<>(jTextFieldInsumo, this.controller.getInsumoAlmacenList(this.controller.getInstance()));
        jDateChooser1.setDate(new Date());
        jSpinnerCantidad.addChangeListener((ChangeEvent e) -> {
            calcularValorEntrada(list.getSelectedHint());
            jSpinnerMonto.requestFocusInWindow();
        });
        JSpinner.DefaultEditor def = (JSpinner.DefaultEditor) jSpinnerCantidad.getEditor();
        def.getTextField().addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                def.getTextField().setText(null);
            }

            @Override
            public void focusLost(FocusEvent e) {
            }
        });

       // jSpinnerMonto.addChangeListener(new );

        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPaneloperaciones = new javax.swing.JPanel();
        jRadioButtonEntrada = new javax.swing.JRadioButton();
        jRadioButtonTraspaso = new javax.swing.JRadioButton();
        jRadioButtonSalida = new javax.swing.JRadioButton();
        jRadioButtonRebaja = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldInsumo = MaterialComponentsFactory.Input.getTextField("", "Insumo");
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel3 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel4 = new javax.swing.JLabel();
        jSpinnerMonto = new javax.swing.JSpinner();
        jComboBoxAlmacenExistencias = new javax.swing.JComboBox<>();
        jTextFieldCausa = MaterialComponentsFactory.Input.getTextField("", "Causa de Rebaja");
        jPanel5 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldRecibo = MaterialComponentsFactory.Input.getTextField("", "No. Recibo");
        jPanel6 = new javax.swing.JPanel();
        jButtonClose = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonConfirmar = MaterialComponentsFactory.Buttons.getAcceptButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 650));
        setUndecorated(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel8.add(jDateChooser1);

        jPanel1.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPaneloperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPaneloperaciones.setOpaque(false);

        jRadioButtonEntrada.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jRadioButtonEntrada.setText(bundle.getString("label_entrada")); // NOI18N
        jRadioButtonEntrada.setToolTipText("");
        jRadioButtonEntrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonEntradaStateChanged(evt);
            }
        });
        jRadioButtonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaActionPerformed(evt);
            }
        });
        jPaneloperaciones.add(jRadioButtonEntrada);

        jRadioButtonTraspaso.setText(bundle.getString("label_traspaso")); // NOI18N
        jRadioButtonTraspaso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonTraspasoStateChanged(evt);
            }
        });
        jRadioButtonTraspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTraspasoActionPerformed(evt);
            }
        });
        jPaneloperaciones.add(jRadioButtonTraspaso);

        jRadioButtonSalida.setText(bundle.getString("label_salida")); // NOI18N
        jRadioButtonSalida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonSalidaStateChanged(evt);
            }
        });
        jRadioButtonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSalidaActionPerformed(evt);
            }
        });
        jPaneloperaciones.add(jRadioButtonSalida);

        jRadioButtonRebaja.setText(bundle.getString("label_rebaja")); // NOI18N
        jRadioButtonRebaja.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonRebajaStateChanged(evt);
            }
        });
        jRadioButtonRebaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRebajaActionPerformed(evt);
            }
        });
        jPaneloperaciones.add(jRadioButtonRebaja);

        jPanel1.add(jPaneloperaciones, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(filler1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Agregar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(783, 140));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextFieldInsumo.setToolTipText("Insumo");
        jTextFieldInsumo.setMinimumSize(new java.awt.Dimension(150, 26));
        jTextFieldInsumo.setPreferredSize(new java.awt.Dimension(150, 50));
        jTextFieldInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInsumoActionPerformed(evt);
            }
        });
        jPanel9.add(jTextFieldInsumo);
        jPanel9.add(filler2);

        jLabel3.setText("Cantidad");
        jPanel9.add(jLabel3);

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        jSpinnerCantidad.setPreferredSize(new java.awt.Dimension(80, 26));
        jPanel9.add(jSpinnerCantidad);
        jPanel9.add(filler3);

        jLabel4.setText("Monto");
        jPanel9.add(jLabel4);

        jSpinnerMonto.setMinimumSize(new java.awt.Dimension(70, 26));
        jSpinnerMonto.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel9.add(jSpinnerMonto);

        jComboBoxAlmacenExistencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAlmacenExistencias.setPreferredSize(new java.awt.Dimension(150, 26));
        jComboBoxAlmacenExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlmacenExistenciasActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBoxAlmacenExistencias);

        jTextFieldCausa.setPreferredSize(new java.awt.Dimension(150, 50));
        jTextFieldCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCausaActionPerformed(evt);
            }
        });
        jPanel9.add(jTextFieldCausa);

        jPanel3.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel5.setMinimumSize(new java.awt.Dimension(512, 20));
        jPanel5.setPreferredSize(new java.awt.Dimension(697, 20));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonAdd.setText("Agregar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAdd);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumo", "Cantidad", "Monto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setMinimumSize(new java.awt.Dimension(89, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(225, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jTextFieldRecibo.setToolTipText("");
        jTextFieldRecibo.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel4.add(jTextFieldRecibo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel7.add(jPanel2, java.awt.BorderLayout.CENTER);

        jButtonClose.setText("Cancelar");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonClose);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonConfirmar);

        jPanel7.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        aceptarOperacion();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jRadioButtonRebajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRebajaActionPerformed

    }//GEN-LAST:event_jRadioButtonRebajaActionPerformed

    private void jRadioButtonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSalidaActionPerformed

    }//GEN-LAST:event_jRadioButtonSalidaActionPerformed

    private void jRadioButtonTraspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTraspasoActionPerformed

    }//GEN-LAST:event_jRadioButtonTraspasoActionPerformed

    private void jRadioButtonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaActionPerformed

    }//GEN-LAST:event_jRadioButtonEntradaActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        lockTipoOp(false);
        ejecutarOperacion();
        limpiarFormulario();
        jTextFieldInsumo.requestFocusInWindow();

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInsumoActionPerformed
        jTextFieldInsumo.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInsumoActionPerformed

    private void jTextFieldCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCausaActionPerformed
        jTextFieldCausa.transferFocus();
    }//GEN-LAST:event_jTextFieldCausaActionPerformed

    private void jComboBoxAlmacenExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlmacenExistenciasActionPerformed
        jComboBoxAlmacenExistencias.transferFocus();
    }//GEN-LAST:event_jComboBoxAlmacenExistenciasActionPerformed

    private void jRadioButtonRebajaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonRebajaStateChanged
        if (jRadioButtonRebaja.isSelected()) {
            onCheckedCheckBox(CheckBoxType.REBAJA);
        }
    }//GEN-LAST:event_jRadioButtonRebajaStateChanged

    private void jRadioButtonSalidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonSalidaStateChanged
        if (jRadioButtonSalida.isSelected()) {
            onCheckedCheckBox(CheckBoxType.SALIDA);
        }
    }//GEN-LAST:event_jRadioButtonSalidaStateChanged

    private void jRadioButtonTraspasoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonTraspasoStateChanged
        if (jRadioButtonTraspaso.isSelected()) {
            onCheckedCheckBox(CheckBoxType.TRASPASO);
        }
    }//GEN-LAST:event_jRadioButtonTraspasoStateChanged

    private void jRadioButtonEntradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaStateChanged
        if (jRadioButtonEntrada.isSelected()) {
            onCheckedCheckBox(CheckBoxType.ENTRADA);
        }
    }//GEN-LAST:event_jRadioButtonEntradaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<Object> jComboBoxAlmacenExistencias;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPaneloperaciones;
    private javax.swing.JRadioButton jRadioButtonEntrada;
    private javax.swing.JRadioButton jRadioButtonRebaja;
    private javax.swing.JRadioButton jRadioButtonSalida;
    private javax.swing.JRadioButton jRadioButtonTraspaso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JSpinner jSpinnerMonto;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCausa;
    private javax.swing.JTextField jTextFieldInsumo;
    private javax.swing.JTextField jTextFieldRecibo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
    }

    private void onCheckedCheckBox(CheckBoxType checkBoxType) {
        //configurando modelo del combo box
        switch (checkBoxType) {
            case SALIDA:
                jComboBoxAlmacenExistencias.setModel(new RestManagerComboBoxModel(controller.getCocinaList()));
                break;
            case TRASPASO:
                jComboBoxAlmacenExistencias.setModel(new RestManagerComboBoxModel(controller.getItems()));
                break;
        }

        //cambiando columna tabla 
        String columnName;
        switch (tipoOperacion) {
            case ENTRADA:
                columnName = "Monto";
                break;
            case REBAJA:
                columnName = "";
                break;
            case TRASPASO:
                columnName = "Destino";
                break;
            case SALIDA:
                columnName = "Destino";
                break;
            default:
                columnName = "No Definido";
        }
        jTable1.getColumnModel().getColumn(2).setHeaderValue(columnName);

        //cambiando la estructura de los campos a rellenar
        jLabel4.setText(columnName);
        jTextFieldCausa.setVisible(checkBoxType == CheckBoxType.REBAJA);
        jSpinnerMonto.setVisible(checkBoxType == CheckBoxType.ENTRADA);
        jComboBoxAlmacenExistencias.setVisible(checkBoxType == CheckBoxType.SALIDA || checkBoxType == CheckBoxType.TRASPASO);
        tipoOperacion = checkBoxType;
    }

    private void ejecutarOperacion() {
        float cantidad = (float) jSpinnerCantidad.getValue();
        TransaccionSimple transaccion = new TransaccionSimple(list.getSelectedHint(), (float) cantidad);
        Object[] row = new Object[3];
        row[0] = transaccion.getInsumo();
        row[1] = transaccion.getCantidad();
        switch (tipoOperacion) {
            case ENTRADA:
                float c = (float) jSpinnerMonto.getValue();
                transaccion.setMonto((float) c);

                row[2] = transaccion.getMonto();
                break;
            case SALIDA:
                transaccion.setcDestino((Cocina) jComboBoxAlmacenExistencias.getSelectedItem());
                row[2] = transaccion.getcDestino();
                break;
            case REBAJA:
                transaccion.setCausa(jTextFieldCausa.getText());
                row[2] = transaccion.getCausa();
                break;
            case TRASPASO:
                transaccion.setaDestino((Almacen) jComboBoxAlmacenExistencias.getSelectedItem());
                row[2] = transaccion.getaDestino();
                break;
            default:
                throw new UnExpectedErrorException(this, "Tipo de operacion no soportada");
        }
        transacciones.add(transaccion);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(row);

    }

    private void aceptarOperacion() {
        controller.crearOperacion(this.transacciones, tipoOperacion, jDateChooser1.getDate(), jTextFieldRecibo.getText());
        dispose();
    }

    private void limpiarFormulario() {
        jTextFieldInsumo.setText("");
        jTextFieldCausa.setText("'");
        jSpinnerMonto.setValue(0);
        jSpinnerCantidad.setValue(0);
    }

    private void lockTipoOp(boolean enabled) {
        for (Component c : jPaneloperaciones.getComponents()) {
            c.setEnabled(enabled);
        }
    }

    private void calcularValorEntrada(InsumoAlmacen selectedHint) {
        if (selectedHint.getValorMonetario() != 0) {
            jSpinnerMonto.setValue(((float) jSpinnerCantidad.getValue()) * utils.setDosLugaresDecimalesFloat(selectedHint.getValorMonetario() / selectedHint.getCantidad()));

        }
    }

}
