/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.main;

import com.jobits.pos.cordinator.DisplayType;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.MainMenuView;
import com.jobits.pos.ui.RootView;
import com.jobits.pos.ui.login.LogInView;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.ui.components.swing.containers.MaterialFrame;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Jorge
 */
public class MainWindow extends MaterialFrame {

    /**
     * Creates new form MainWindow
     */
    private CardLayout cards = new CardLayout();
    private RootView rootView;
    private LogInView loginView;

    public MainWindow() {
        super();
        initComponents();
        getContentPane().setLayout(new BorderLayout());
        setBackground(DefaultValues.PRIMARY_COLOR);
        setLayout(cards);
        loginView = LogInView.getInstance();
        add(loginView, LogInView.VIEW_NAME);
        repaint();
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize());
    }

    @Override
    public Dimension getMinimumSize() {
        return new Dimension(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds().getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void setWelcomeHeader(boolean b) {

    }

    public boolean showView(String viewUIDName, AbstractViewPresenter presenter, DisplayType displayType) {
        boolean ret = false;
        if (ret = viewUIDName.equals(LogInView.VIEW_NAME)) {
            cards.show(getContentPane(), viewUIDName);
        } else if (viewUIDName.equals(MainMenuView.VIEW_NAME)) {
            rootView = RootView.getInstance();
            add(rootView, RootView.VIEW_NAME);
            cards.show(getContentPane(), RootView.VIEW_NAME);
        } else if (rootView != null) {
            ret = rootView.showView(viewUIDName, presenter, displayType);
        }

        return ret;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
