/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.cartas;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.domain.models.Carta;
import com.jobits.pos.domain.models.Seccion;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.areaventa.presenter.AreaVentaViewPresenter;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.ui.components.MaterialComponentsFactory;
import static com.jobits.pos.ui.cartas.presenter.CartasSeccionViewModel.*;
import com.jobits.pos.ui.cartas.presenter.CartasSeccionViewPresenter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Jorge
 */
public class CartasSeccionView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Cartas";

    public CartasSeccionView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelAreas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMenus = MaterialComponentsFactory.Displayers.getList();
        jPanel4 = new javax.swing.JPanel();
        jButtonEliminarMenu = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAgregarMenu = MaterialComponentsFactory.Buttons.getMaterialButton();
        jPanelMesas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSecciones = MaterialComponentsFactory.Displayers.getList();
        jPanel3 = new javax.swing.JPanel();
        jButtonEliminarSeccion = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonEditarSeccion = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAgregarSeccion = MaterialComponentsFactory.Buttons.getMaterialButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 5));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jLabel3.setText(bundle.getString("label_gestion_carta")); // NOI18N
        jPanel5.add(jLabel3, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jPanelAreas.setMinimumSize(new java.awt.Dimension(150, 102));
        jPanelAreas.setOpaque(false);
        jPanelAreas.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("label_Cartas")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAreas.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jListMenus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListMenus.setPreferredSize(new java.awt.Dimension(100, 85));
        jScrollPane2.setViewportView(jListMenus);

        jPanelAreas.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonEliminarMenu.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEliminarMenu.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel4.add(jButtonEliminarMenu);

        jButtonAgregarMenu.setText(bundle.getString("label_agregar")); // NOI18N
        jButtonAgregarMenu.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel4.add(jButtonAgregarMenu);

        jPanelAreas.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanelAreas);

        jPanelMesas.setMinimumSize(new java.awt.Dimension(150, 102));
        jPanelMesas.setOpaque(false);
        jPanelMesas.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("label_seccion")); // NOI18N
        jPanelMesas.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jListSecciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSecciones.setPreferredSize(new java.awt.Dimension(100, 85));
        jScrollPane1.setViewportView(jListSecciones);

        jPanelMesas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonEliminarSeccion.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEliminarSeccion.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel3.add(jButtonEliminarSeccion);

        jButtonEditarSeccion.setText(bundle.getString("label_eliminar")); // NOI18N
        jButtonEditarSeccion.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel3.add(jButtonEditarSeccion);

        jButtonAgregarSeccion.setText(bundle.getString("label_agregar")); // NOI18N
        jButtonAgregarSeccion.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel3.add(jButtonAgregarSeccion);

        jPanelMesas.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanelMesas);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMenu;
    private javax.swing.JButton jButtonAgregarSeccion;
    private javax.swing.JButton jButtonEditarSeccion;
    private javax.swing.JButton jButtonEliminarMenu;
    private javax.swing.JButton jButtonEliminarSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<Carta> jListMenus;
    private javax.swing.JList<Seccion> jListSecciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelAreas;
    private javax.swing.JPanel jPanelMesas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void wireUp() {
        Bindings.bind(jListMenus, new SelectionInList<Carta>(getPresenter().getModel(PROP_LISTA_MENU), getPresenter().getModel(PROP_MENU_SELECCIONADO)));
        Bindings.bind(jListSecciones, new SelectionInList<Carta>(getPresenter().getModel(PROP_LISTA_SECCIONES), getPresenter().getModel(PROP_SECCION_SELECCIONADA)));
        jListSecciones.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_EDITAR_SECCION).doAction();
                }
            }

        });
        jListSecciones.addKeyListener(new KeyListener() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DELETE) {
                    getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_ELIMINAR_SECCION).doAction();
                }
            }
            @Override
            public void keyTyped(KeyEvent e) {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        jButtonAgregarMenu.setAction(getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_AGREGAR_MENU));
        jButtonAgregarSeccion.setAction(getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_AGREGAR_SECCION));
        jButtonEditarSeccion.setAction(getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_EDITAR_SECCION));
        jButtonEliminarMenu.setAction(getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_ELIMINAR_MENU));
        jButtonEliminarSeccion.setAction(getPresenter().getOperation(CartasSeccionViewPresenter.ACTION_ELIMINAR_SECCION));
    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }
}
