/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.cartas;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import static com.jobits.pos.ui.cartas.presenter.SeccionDetailViewModel.*;
import static com.jobits.pos.ui.cartas.presenter.SeccionDetailViewPresenter.*;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.ui.components.MaterialComponentsFactory;

/**
 *
 * @author Jorge
 */
public class SeccionDetailView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Seccion Detail";

    /**
     * Creates new form SeccionEditView
     */
    public SeccionDetailView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public void wireUp() {
        Bindings.bind(jTextFieldNombre, getPresenter().getModel(PROP_NOMBRE_SECCION));
        Bindings.bind(jTextFieldNombre, "enabled", getPresenter().getModel(PROP_NOMBRE_HABILITADO));
        Bindings.bind(jButtonAceptar, "text", getPresenter().getModel(PROP_CREAR_EDITAR_BUTTON_TEXT));

        Bindings.bind(jComboBoxSecciones, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_SECCIONES),
                getPresenter().getModel(PROP_SECCION_SELECCIONADA)));
        Bindings.bind(jListSeccionesAgregadas, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_SECCIONES_AGREGADAS),
                getPresenter().getModel(PROP_SECCION_AGREGADA_SELECCIONADA)));

        jButtonAceptar.addActionListener(getPresenter().getOperation(ACTION_ACEPTAR));
        jButtonAgregar.addActionListener(getPresenter().getOperation(ACTION_AGREGAR));
        jButtonCancelar.addActionListener(getPresenter().getOperation(ACTION_CANCELAR));
        jButtonEliminar.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfo = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombre = MaterialComponentsFactory.Input.getTextField("", "Nombre");
        jPanelMenus = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBoxSecciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSeccionesAgregadas = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jPanelBotones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getMaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(DefaultValues.SECONDARY_COLOR, 2, true));
        setLayout(new java.awt.BorderLayout());

        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        jPanelInfo.setLayout(new javax.swing.BoxLayout(jPanelInfo, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 60));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel1.add(jTextFieldNombre);

        jPanelInfo.add(jPanel1);

        add(jPanelInfo, java.awt.BorderLayout.NORTH);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jPanelMenus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), bundle.getString("label_carta"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        jPanelMenus.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(jComboBoxSecciones, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(jListSeccionesAgregadas);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonEliminar.setIcon(MaterialIcons.DELETE);
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel6.add(jButtonEliminar);

        jButtonAgregar.setIcon(MaterialIcons.ADD);
        jButtonAgregar.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel6.add(jButtonAgregar);

        jPanel7.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanelMenus.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanelMenus, java.awt.BorderLayout.CENTER);

        jButtonCancelar.setText("Cancelar");
        jPanelBotones.add(jButtonCancelar);

        jButtonAceptar.setText("Aceptar");
        jPanelBotones.add(jButtonAceptar);

        add(jPanelBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxSecciones;
    private javax.swing.JList<String> jListSeccionesAgregadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMenus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
