/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.cartas;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.root101.swing.material.standards.MaterialIcons;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import static com.jobits.pos.ui.cartas.presenter.SeccionDetailViewModel.*;
import static com.jobits.pos.ui.cartas.presenter.SeccionDetailViewPresenter.*;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import com.jobits.ui.components.MaterialComponentsFactory;

/**
 *
 * @author Jorge
 */
public class SeccionDetailView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Seccion Detail";

    /**
     * Creates new form SeccionEditView
     */
    public SeccionDetailView(AbstractViewPresenter presenter) {
        super(presenter);
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

    @Override
    public void uiInit() {
        initComponents();
    }

    @Override
    public void wireUp() {
        Bindings.bind(jTextFieldNombre, getPresenter().getModel(PROP_NOMBRE_SECCION));
        Bindings.bind(jTextFieldNombre, "enabled", getPresenter().getModel(PROP_NOMBRE_HABILITADO));
        Bindings.bind(jButtonAceptar, "text", getPresenter().getModel(PROP_CREAR_EDITAR_BUTTON_TEXT));

        Bindings.bind(jComboBoxSecciones, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_SECCIONES),
                getPresenter().getModel(PROP_SECCION_SELECCIONADA)));
        Bindings.bind(jListSeccionesAgregadas, new SelectionInList<String>(
                getPresenter().getModel(PROP_LISTA_SECCIONES_AGREGADAS),
                getPresenter().getModel(PROP_SECCION_AGREGADA_SELECCIONADA)));

        jButtonAceptar.addActionListener(getPresenter().getOperation(ACTION_ACEPTAR));
        jButtonAgregar.addActionListener(getPresenter().getOperation(ACTION_AGREGAR));
        jButtonCancelar.addActionListener(getPresenter().getOperation(ACTION_CANCELAR));
        jButtonEliminar.addActionListener(getPresenter().getOperation(ACTION_ELIMINAR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanelInfo = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jTextFieldNombre = MaterialComponentsFactory.Input.getTextField("", "Nombre");
        jPanelMenus = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jComboBoxSecciones = MaterialComponentsFactory.Displayers.getComboBox("Secciones Agreagadas");
        jScrollPane1 = MaterialComponentsFactory.Containers.getScrollPane();
        jListSeccionesAgregadas = new javax.swing.JList<>();
        jPanel6 = MaterialComponentsFactory.Containers.getTransparentPanel();
        jButtonEliminar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonAgregar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelBotones = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getLinedButton();
        jButtonAceptar = MaterialComponentsFactory.Buttons.getMaterialButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(335, 500));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 24))); // NOI18N
        jPanelInfo.setLayout(new java.awt.GridBagLayout());

        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(250, 60));
        jPanelInfo.add(jTextFieldNombre, new java.awt.GridBagConstraints());

        jPanel2.add(jPanelInfo, java.awt.BorderLayout.NORTH);

        jPanelMenus.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanelMenus.setLayout(new java.awt.BorderLayout());

        jComboBoxSecciones.setPreferredSize(new java.awt.Dimension(33, 50));
        jPanelMenus.add(jComboBoxSecciones, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(jListSeccionesAgregadas);

        jPanelMenus.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonEliminar.setIcon(MaterialIcons.DELETE);
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel6.add(jButtonEliminar);

        jButtonAgregar.setIcon(MaterialIcons.ADD);
        jButtonAgregar.setPreferredSize(new java.awt.Dimension(40, 30));
        jPanel6.add(jButtonAgregar);

        jPanelMenus.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanelMenus, java.awt.BorderLayout.CENTER);

        jPanelBotones.setPreferredSize(new java.awt.Dimension(280, 50));
        jPanelBotones.setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelBotones.add(jButtonCancelar, new java.awt.GridBagConstraints());

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(140, 40));
        jPanelBotones.add(jButtonAceptar, new java.awt.GridBagConstraints());

        jPanel2.add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxSecciones;
    private javax.swing.JList<String> jListSeccionesAgregadas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMenus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
