/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.trabajadores;

import com.jobits.pos.ui.AbstractDetailView;
import GUI.Components.JTextField;
import com.jobits.pos.ui.utils.RestManagerInputVerifier;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Frame;
import java.util.Arrays;
import java.util.Date;
import javax.swing.border.LineBorder;
import com.jobits.pos.controller.AbstractDetailController;
import com.jobits.pos.controller.trabajadores.PersonalDetailController;
import com.jobits.pos.exceptions.DevelopingOperationException;
import com.jobits.pos.domain.models.Personal;
import com.jobits.pos.domain.models.PuestoTrabajo;
import com.jobits.pos.recursos.R;
import com.jobits.pos.recursos.RegularExpressions;
import com.jobits.pos.ui.utils.RestManagerComboBoxModel;
import com.jobits.ui.components.MaterialComponentsFactory;


/**
 *
 * @author Jorge
 */
public class PersonalDetailView extends AbstractDetailView<Personal> {

    public PersonalDetailView(Personal instance, AbstractDetailController controller, Frame owner, boolean modal) {
        super(instance, DialogType.LIST, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();
    }

    public PersonalDetailView(Personal instance, AbstractDetailController controller, Dialog owner, boolean modal) {
        super(instance, DialogType.LIST, controller, owner, modal);
        initComponents();
        fetchComponentData();
        updateView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel8 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jTextFieldNombre = MaterialComponentsFactory.Input.getTextField(" ", "Nombre*");
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jTextFieldApellidos = MaterialComponentsFactory.Input.getTextField(" ", "Apellidos*");
        jPanel2 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jLabel9 = MaterialComponentsFactory.Displayers.getLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jComboBoxPuestoTrabajo = new javax.swing.JComboBox<>();
        jPanel3 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel1 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jTextFieldUsuario = MaterialComponentsFactory.Input.getTextField(" ", "Usuario*");
        jPanel5 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPasswordFieldPassAntigua = MaterialComponentsFactory.Input.getPasswordField("", "Contraseña antigua");
        jToggleButtonMostrarPass = new javax.swing.JToggleButton();
        jPasswordFieldPassNueva = MaterialComponentsFactory.Input.getPasswordField("", "Contraseña nueva");
        jPasswordFieldPassRepetir = MaterialComponentsFactory.Input.getPasswordField("", "Repetir contraseña antigua");
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jPanel4 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jPanel14 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel13 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldMovil = MaterialComponentsFactory.Input.getFormattedTextField("", "");
        jPanel9 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldFijo = MaterialComponentsFactory.Input.getFormattedTextField("", "");
        jPanel12 = MaterialComponentsFactory.Containers.getSecondaryPanel();
        jButtonCancelar = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jButtonCrear = MaterialComponentsFactory.Buttons.getMaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Planilla Trabajador");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(334, 700));
        setUndecorated(true);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Trabajador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPanel7.setMinimumSize(new java.awt.Dimension(334, 700));
        jPanel7.setPreferredSize(new java.awt.Dimension(334, 700));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jTextFieldNombre.setToolTipText("El nombre no debe exceder de 30 caracteres");
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setMaximumSize(new java.awt.Dimension(100, 50));
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(100, 50));
        jTextFieldNombre.setName(""); // NOI18N
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel8.add(jTextFieldNombre);
        jTextFieldNombre.getAccessibleContext().setAccessibleName("");

        jPanel8.add(filler1);

        jTextFieldApellidos.setBorder(null);
        jTextFieldApellidos.setMaximumSize(new java.awt.Dimension(150, 50));
        jTextFieldApellidos.setMinimumSize(new java.awt.Dimension(150, 50));
        jTextFieldApellidos.setPreferredSize(new java.awt.Dimension(170, 50));
        jPanel8.add(jTextFieldApellidos);

        jPanel7.add(jPanel8);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Puesto de Trabajo");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel2.add(jLabel9);
        jPanel2.add(filler2);

        jComboBoxPuestoTrabajo.setBackground(getBackground());
        jComboBoxPuestoTrabajo.setMaximumSize(new java.awt.Dimension(200, 27));
        jComboBoxPuestoTrabajo.setMinimumSize(new java.awt.Dimension(100, 27));
        jComboBoxPuestoTrabajo.setPreferredSize(new java.awt.Dimension(150, 26));
        jComboBoxPuestoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuestoTrabajoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxPuestoTrabajo);

        jPanel7.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seguridad"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 220));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jTextFieldUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldUsuario.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel1.add(jTextFieldUsuario);

        jPanel5.setMaximumSize(new java.awt.Dimension(150, 50));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPasswordFieldPassAntigua.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordFieldPassAntigua.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel5.add(jPasswordFieldPassAntigua, java.awt.BorderLayout.CENTER);

        jToggleButtonMostrarPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/images/visualizar.PNG"))); // NOI18N
        jToggleButtonMostrarPass.setBorderPainted(false);
        jToggleButtonMostrarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMostrarPassActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButtonMostrarPass, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5);

        jPasswordFieldPassNueva.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordFieldPassNueva.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel1.add(jPasswordFieldPassNueva);

        jPasswordFieldPassRepetir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordFieldPassRepetir.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel1.add(jPasswordFieldPassRepetir);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sexo");
        jPanel4.add(jLabel4, java.awt.BorderLayout.CENTER);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        jComboBoxSexo.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel4.add(jComboBoxSexo, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel4);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha Nacimiento");
        jPanel14.add(jLabel8, java.awt.BorderLayout.CENTER);

        jDateChooser1.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel14.add(jDateChooser1, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel14);

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefono Móvil");
        jPanel13.add(jLabel6, java.awt.BorderLayout.CENTER);

        jFormattedTextFieldMovil.setBorder(null);
        try {
            jFormattedTextFieldMovil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldMovil.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel13.add(jFormattedTextFieldMovil, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel13);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono Fijo");
        jPanel9.add(jLabel7, java.awt.BorderLayout.CENTER);

        jFormattedTextFieldFijo.setBorder(null);
        try {
            jFormattedTextFieldFijo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFijo.setText("");
        jFormattedTextFieldFijo.setToolTipText("");
        jFormattedTextFieldFijo.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel9.add(jFormattedTextFieldFijo, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel9);

        jPanel10.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel10);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(107, 50));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonCancelar);

        jButtonCrear.setText("Crear");
        jButtonCrear.setPreferredSize(new java.awt.Dimension(107, 50));
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonCrear);

        jPanel7.add(jPanel12);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPuestoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuestoTrabajoActionPerformed
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_jComboBoxPuestoTrabajoActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        getController().createUpdateInstance();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jToggleButtonMostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarPassActionPerformed
        jPasswordFieldPassAntigua.setEchoChar(!jToggleButtonMostrarPass.isSelected() ? '*' : (char) 0);
    }//GEN-LAST:event_jToggleButtonMostrarPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<PuestoTrabajo> jComboBoxPuestoTrabajo;
    private javax.swing.JComboBox jComboBoxSexo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextFieldFijo;
    private javax.swing.JFormattedTextField jFormattedTextFieldMovil;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordFieldPassAntigua;
    private javax.swing.JPasswordField jPasswordFieldPassNueva;
    private javax.swing.JPasswordField jPasswordFieldPassRepetir;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JToggleButton jToggleButtonMostrarPass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
        if (instance.getDatosPersonales() != null) {
            jTextFieldNombre.setText(instance.getDatosPersonales().getNombre());
            jTextFieldApellidos.setText(instance.getDatosPersonales().getApellidos());
            jDateChooser1.setDate(instance.getDatosPersonales().getFechaNacimineto());
            jFormattedTextFieldMovil.setText("" + instance.getDatosPersonales().getTelefonoMovil());
            jFormattedTextFieldFijo.setText("" + instance.getDatosPersonales().getTelefonoFijo());
            jTextFieldUsuario.setText(instance.getUsuario());
            jPasswordFieldPassAntigua.setText(instance.getContrasenna());
            if (instance.getDatosPersonales().getSexo() != null) {
                if (instance.getDatosPersonales().getSexo() == 'M') {
                    jComboBoxSexo.setSelectedIndex(0);
                } else {
                    jComboBoxSexo.setSelectedIndex(1);
                }
            }
            jComboBoxPuestoTrabajo.setSelectedItem(instance.getPuestoTrabajonombrePuesto());
        }
    }

    @Override
    public void fetchComponentData() {
        jComboBoxPuestoTrabajo.setModel(new RestManagerComboBoxModel<>(((PersonalDetailController) getController()).getPuestoTrabajoList()));
        jTextFieldUsuario.setInputVerifier(new RestManagerInputVerifier(RegularExpressions.USER_NAME));

    }

    @Override
    public void setEditingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_editar"));
    }

    @Override
    public void setCreatingMode() {
        jButtonCrear.setText(R.RESOURCE_BUNDLE.getString("label_crear"));
    }

    @Override
    public boolean validateData() {
        if (jPasswordFieldPassNueva.getPassword().length > 0) {
            if (!Arrays.equals(jPasswordFieldPassNueva.getPassword(), (jPasswordFieldPassRepetir.getPassword()))) {
                jPasswordFieldPassRepetir.setBorder(new LineBorder(Color.red));
                return false;
            } else {
                jPasswordFieldPassRepetir.setBorder(null);
                instance.setContrasenna(jPasswordFieldPassNueva.getText());
            }

        }
        instance.getDatosPersonales().setNombre(jTextFieldNombre.getText());
        instance.getDatosPersonales().setApellidos(jTextFieldApellidos.getText());
        instance.getDatosPersonales().setFechaNacimineto(jDateChooser1.getDate());
        if (jFormattedTextFieldMovil.getValue() == null) {
            instance.getDatosPersonales().setTelefonoMovil(null);
        } else {
            instance.getDatosPersonales().setTelefonoMovil(Integer.parseInt((String) jFormattedTextFieldMovil.getValue()));
        }
        if (jFormattedTextFieldFijo.getValue() == null) {
            instance.getDatosPersonales().setTelefonoFijo(null);
        } else {
            instance.getDatosPersonales().setTelefonoFijo(Integer.parseInt((String) jFormattedTextFieldFijo.getValue()));

        }
        instance.setUsuario(jTextFieldUsuario.getText());
        instance.getDatosPersonales().setPersonalusuario(instance.getUsuario());
        if (jComboBoxSexo.getSelectedIndex() == 0) {
            instance.getDatosPersonales().setSexo('M');
        } else {
            instance.getDatosPersonales().setSexo('F');
        }
        instance.setUltimodiaPago(new Date());
        instance.setPagoPendiente((float) 0);
        instance.setPuestoTrabajonombrePuesto((PuestoTrabajo) jComboBoxPuestoTrabajo.getSelectedItem());
        instance.setOnline(false);
        return true;
    }

}
