/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.login;

import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.list.SelectionInList;
import com.jobits.pos.domain.UbicacionConexionModel;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.utils.ComponentMover;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import static com.jobits.pos.ui.login.presenter.LoginViewModel.*;
import static com.jobits.pos.ui.login.presenter.LoginViewPresenter.*;
import com.jobits.ui.components.MaterialComponentsFactory;
import javax.swing.JButton;
import util.materials.MaterialColors;
import util.materials.MaterialIcons;

/**
 *
 * @author Jorge
 */
public class LogInView extends AbstractViewPanel {
    
    public static final String VIEW_NAME = "Autenticación";

    /**
     * Creates new form LogInView
     *
     * @param presenter
     */
    public LogInView(AbstractViewPresenter presenter) {
        super(presenter, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = MaterialComponentsFactory.Containers.getPrimaryPanel();
        jXLabelUser1 = new org.jdesktop.swingx.JXLabel();
        jPanelConn = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonEdit = MaterialComponentsFactory.Buttons.getEditButton();
        jLabelEstadoConexion = new javax.swing.JLabel();
        jButtonAutenticar = MaterialComponentsFactory.Buttons.getMaterialButton();
        jTextFieldUsuario = MaterialComponentsFactory.Input.getTextField("Usuario","Introduzca el nombre de usuario");
        jPasswordField = MaterialComponentsFactory.Input.getPasswordField("Contraseña", "Introduzca la contraseña");

        setMinimumSize(new java.awt.Dimension(483, 285));
        setName("main"); // NOI18N
        setOpaque(false);

        jPanel3.setBackground(MaterialColors.BLUEGREY_100);
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 600));

        jXLabelUser1.setBackground(new java.awt.Color(153, 255, 255));
        jXLabelUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/logo/banner.png"))); // NOI18N
        jXLabelUser1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N

        jPanelConn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Ubicacion"));
        jPanelConn.setMaximumSize(new java.awt.Dimension(405, 23));
        jPanelConn.setOpaque(false);
        jPanelConn.setLayout(new java.awt.BorderLayout());

        jComboBox1.setMinimumSize(new java.awt.Dimension(52, 48));
        jComboBox1.setPreferredSize(new java.awt.Dimension(52, 48));
        jPanelConn.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jButtonEdit.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonEdit.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonEdit.setSize(new java.awt.Dimension(40, 40));
        jPanelConn.add(jButtonEdit, java.awt.BorderLayout.EAST);

        jLabelEstadoConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstadoConexion.setPreferredSize(new java.awt.Dimension(45, 30));
        jLabelEstadoConexion.setSize(new java.awt.Dimension(45, 30));
        jPanelConn.add(jLabelEstadoConexion, java.awt.BorderLayout.PAGE_END);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonAutenticar.setText(bundle.getString("label_autenticar")); // NOI18N
        jButtonAutenticar.setEnabled(false);
        jButtonAutenticar.setPreferredSize(new java.awt.Dimension(180, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButtonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelConn, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jPasswordField)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jXLabelUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jXLabelUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelConn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAutenticar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAutenticar;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<UbicacionConexionModel> jComboBox1;
    private javax.swing.JLabel jLabelEstadoConexion;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelConn;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    private org.jdesktop.swingx.JXLabel jXLabelUser1;
    // End of variables declaration//GEN-END:variables

    @Override
    public AbstractViewPresenter getPresenter() {
        return presenter;
    }
    
    @Override
    public void wireUp() {
        Bindings.bind(jLabelEstadoConexion, getPresenter().getModel(PROP_ESTADOCONEXION));
        Bindings.bind(jTextFieldUsuario, getPresenter().getModel(PROP_NOMBREUSUARIO));
        Bindings.bind(jPasswordField, getPresenter().getModel(PROP_CONTRASENA));
        Bindings.bind(jComboBox1, new SelectionInList<UbicacionConexionModel>(
                getPresenter().getModel(PROP_LISTAUBICACIONES),
                getPresenter().getModel(PROP_UBICACIONSELECCIONADA)));
        Bindings.bind(jButtonAutenticar, "enabled", getPresenter().getModel(PROP_BOTON_AUTENTICAR_HABILITADO));
        Bindings.bind(jLabelEstadoConexion, "foreground", getPresenter().getModel(PROP_COLORLABELCONEXION));
        
        jPasswordField.setAction(getPresenter().getOperation(ACTION_AUTENTICAR));
        jButtonAutenticar.setAction(getPresenter().getOperation(ACTION_AUTENTICAR));
        jButtonEdit.setAction(getPresenter().getOperation(ACTION_EDITAR_UBICACION));
        jButtonEdit.setText("");
        jButtonEdit.setIcon(MaterialIcons.EDIT);
    }
    
    @Override
    public void uiInit() {
        initComponents();
        ComponentMover cr = new ComponentMover(this, this.getComponents());
        jPanel3 = MaterialComponentsFactory.Containers.getPrimaryPanel();
        
    }
    
    @Override
    public String getViewName() {
        return VIEW_NAME;
    }
    
}
