/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobits.pos.ui.login;

import com.jgoodies.binding.adapter.Bindings;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jobits.pos.controller.login.impl.LogInController;
import com.jobits.pos.ui.AbstractViewPanel;
import com.jobits.pos.ui.DefaultValues;
import com.jobits.pos.ui.autorizo.AuthorizerImpl;
import com.jobits.pos.ui.utils.ComponentMover;
import com.jobits.pos.ui.presenters.AbstractViewPresenter;
import static com.jobits.pos.ui.login.presenter.LoginViewModel.*;
import com.jobits.pos.ui.login.presenter.LoginViewPresenter;
import static com.jobits.pos.ui.login.presenter.LoginViewPresenter.*;
import com.jobits.ui.components.MaterialComponentsFactory;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author Jorge
 */
public class LogInView extends AbstractViewPanel {

    public static final String VIEW_NAME = "Autenticación";

    public static LogInView getInstance() {
        return new LogInView(new LoginViewPresenter(new LogInController(new AuthorizerImpl())));
    }

    /**
     * Creates new form LogInView
     *
     * @param presenter
     */
    private LogInView(LoginViewPresenter presenter) {
        super(presenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelLogo = new javax.swing.JPanel();
        jXLabelUser1 = new org.jdesktop.swingx.JXLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelInput = new javax.swing.JPanel();
        jTextFieldUsuario = MaterialComponentsFactory.Input.getTextField("Introduzca el nombre de usuario","Usuario");
        jPasswordField = MaterialComponentsFactory.Input.getPasswordField(java.util.ResourceBundle.getBundle("Strings").getString("label_introduzca_contrasena"), java.util.ResourceBundle.getBundle("Strings").getString("label_contrasena"));
        jPanelAutenticar = new javax.swing.JPanel();
        jButtonAutenticar = MaterialComponentsFactory.Buttons.getAcceptButton();
        jButtonEdit = MaterialComponentsFactory.Buttons.getOutlinedButton();
        jPanelConn = new javax.swing.JPanel();
        jLabelEstadoConexion = new javax.swing.JLabel();
        jLabelUbicacionSeleccionada = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(DefaultValues.SECONDARY_COLOR_LIGHT));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setName("main"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new java.awt.GridBagLayout());

        jPanel2.setAlignmentX(Component.CENTER_ALIGNMENT);
        jPanel2.setAlignmentY(Component.CENTER_ALIGNMENT);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 10, 40));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(270, 300));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        jPanelLogo.setBackground(DefaultValues.SECONDARY_COLOR_LIGHT);
        jPanelLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelLogo.setOpaque(false);
        jPanelLogo.setPreferredSize(new java.awt.Dimension(220, 96));
        jPanelLogo.setLayout(new java.awt.BorderLayout());

        jXLabelUser1.setBackground(new java.awt.Color(153, 255, 255));
        jXLabelUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXLabelUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/logo/banner.png"))); // NOI18N
        jXLabelUser1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jPanelLogo.add(jXLabelUser1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelLogo);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/usuario_indigo.png"))); // NOI18N
        jPanel4.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restManager/resources/icons pack/password_indigo.png"))); // NOI18N
        jPanel4.add(jLabel2);

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanelInput.setBackground(DefaultValues.SECONDARY_COLOR_LIGHT);
        jPanelInput.setMaximumSize(new java.awt.Dimension(220, 32767));
        jPanelInput.setOpaque(false);
        jPanelInput.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jTextFieldUsuario.setMaximumSize(new java.awt.Dimension(220, 2147483647));
        jPanelInput.add(jTextFieldUsuario);

        jPasswordField.setMaximumSize(new java.awt.Dimension(220, 2147483647));
        jPanelInput.add(jPasswordField);

        jPanel3.add(jPanelInput, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanelAutenticar.setBackground(DefaultValues.SECONDARY_COLOR_LIGHT);
        jPanelAutenticar.setOpaque(false);
        jPanelAutenticar.setPreferredSize(new java.awt.Dimension(235, 50));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Strings"); // NOI18N
        jButtonAutenticar.setText(bundle.getString("label_autenticar")); // NOI18N
        jButtonAutenticar.setEnabled(false);
        jButtonAutenticar.setPreferredSize(new java.awt.Dimension(180, 60));
        jPanelAutenticar.add(jButtonAutenticar);

        jButtonEdit.setIcon(MaterialIcons.LOCATION_ON);
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setMaximumSize(new java.awt.Dimension(40, 40));
        jButtonEdit.setMinimumSize(new java.awt.Dimension(40, 40));
        jButtonEdit.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanelAutenticar.add(jButtonEdit);

        jPanel1.add(jPanelAutenticar);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelConn.setMaximumSize(new java.awt.Dimension(405, 23));
        jPanelConn.setOpaque(false);
        jPanelConn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabelEstadoConexion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEstadoConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstadoConexion.setText(bundle.getString("label_circle_conecction")); // NOI18N
        jLabelEstadoConexion.setToolTipText("");
        jLabelEstadoConexion.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabelEstadoConexion.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabelEstadoConexion.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanelConn.add(jLabelEstadoConexion);

        jLabelUbicacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelUbicacionSeleccionada.setText("Ubicacion");
        jPanelConn.add(jLabelUbicacionSeleccionada);

        jPanel2.add(jPanelConn, java.awt.BorderLayout.SOUTH);

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAutenticar;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEstadoConexion;
    private javax.swing.JLabel jLabelUbicacionSeleccionada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAutenticar;
    private javax.swing.JPanel jPanelConn;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    private org.jdesktop.swingx.JXLabel jXLabelUser1;
    // End of variables declaration//GEN-END:variables

    @Override
    public LoginViewPresenter getPresenter() {
        return (LoginViewPresenter) presenter;
    }

    @Override
    public void wireUp() {
        Bindings.bind(jTextFieldUsuario, getPresenter().getModel(PROP_NOMBREUSUARIO));
        Bindings.bind(jPasswordField, getPresenter().getModel(PROP_CONTRASENA));
        Bindings.bind(jButtonAutenticar, "enabled", getPresenter().getModel(PROP_BOTON_AUTENTICAR_HABILITADO));

        Bindings.bind(jLabelEstadoConexion, "foreground", getPresenter().getModel(PROP_COLORLABELCONEXION));
        Bindings.bind(jLabelUbicacionSeleccionada, getPresenter().getModel(PROP_ESTADOCONEXION));

        jPasswordField.setAction(getPresenter().getOperation(ACTION_AUTENTICAR));
        jButtonAutenticar.setAction(getPresenter().getOperation(ACTION_AUTENTICAR));
        jButtonEdit.setAction(getPresenter().getOperation(ACTION_EDITAR_UBICACION));
        jButtonEdit.setText("");//TODO mal manejo de los actions que hay que poner aqui las cosas manuales
        jButtonEdit.setIcon(MaterialIcons.LOCATION_ON);

    }

    @Override
    public void uiInit() {
        initComponents();
        ComponentMover cr = new ComponentMover(this, this.getComponents());
        jTextFieldUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                getPresenter().setUbicacionSeleccionada();
            }

            @Override
            public void focusLost(FocusEvent e) {
            }
        });
        jTextFieldUsuario.requestFocusInWindow();
    }

    @Override
    public String getViewName() {
        return VIEW_NAME;
    }

}
